### ISSUE TITLE
Need to pass defines to library cpp files during sketch compile

### ISSUE THREAD

**Issue by wandrson** [arduino/Arduino#2015] opened 2014-04-15 15:39 UTC
I am attempting to modify my Entropy library to allow the user to decide if they want to include floating point functions for the library.  I placed conditional defines around the relavent code; however, it wouldn't link.  I determined that the source level #define was not being passed to the libraries cpp compile, though it was passed to the libraries header file.

My current solution is to require the user to comment/uncomment the header file for the library, but this is cumbersome, and problematic.  It would be nice if the compilation for library code included the defines made by the Arduino sketch.

**Comment by ricardojlrufino** [comment] 2015-02-22 03:49
I have a tip:
What do you think of working on convention where settings (#define) would be placed in the config.h inside sketch folder?

**Comment by cmaglie** [comment] 2015-05-19 13:55
Closing as duplicate of #1734 #1808

**Closed by cmaglie** 2015-05-19 13:55 UTC
Labels: Type: Duplicate
