### ISSUE TITLE
Switch/Case and If Statements Limit

### ISSUE THREAD

**Issue by peasoup49** [arduino/Arduino#10993] opened 2020-11-23 17:42 UTC
Please fix the limit of 'if' and/or 'switch/case' total in the compiler.  It strongly appears to be a memory allocation or limit that is set in the compiler and affects both 'if' and 'switch/case' statements alike.  Originally I had 2 different switches with 155 cases total throughout my program (each with 1 line command per case).  When I commented out 6 (bringing the total to 149) the program compiles and runs as expected.  Anything over that, the compiler will compile and upload, but the program will not run.  Any attempt to add more conditions per case, causes the same issue of the program not running if even more case statements are not commented out.  I went as far as re-writing approximately 25% of my program to replace all the 'switch/case' statements with 'if' statements.  Physical memory on the board is not a problem as this is where I'm currently at on my atMega2560:

Sketch uses 120778 bytes (47%) of program storage space. Maximum is 253952 bytes.
Global variables use 3034 bytes (37%) of dynamic memory, leaving 5158 bytes for local variables. Maximum is 8192 bytes.

**Comment by matthijskooijman** [comment] 2020-11-23 17:53
Interesting problem. Given we're using the standard gcc compiler, I would be somewhat surprised if there would be some maximum on the number of if statements (usually, problems like this end up being problems in the code someone has written), but we've seen weird compiler bugs, so it's not unthinkable. If it is a compiler problem, then I'd expect it's not so much the number of ifs that is limited somehow, but some other particularity of the code you've written that trips up the compiler.

To properly look into this, we'll need a complete example of code that ends up being broken, along with a clear description of what the code should do and actually does, so we can reproduce the problem and investigate this. Ideally, this is a minimal example that can show the problem (i.e. a sketch with just the ifs and and maybe some prints or so to show the problem). If that doesn't work (maybe a minimal example ends up being not broken, happens a lot), then you can try to strip down your original problem, removing parts one by one and leaving the ones that make the problem go away.

Also, please state the Arduino IDE version, exact board and core/platform version you are using (verbose compilation output should contain most of this info).

**Comment by peasoup49** [comment] 2020-11-23 18:23
I'm using the latest version of the IDE, 1.8.13 and the exact board is a Sundowner Mega 2560, their Ethernet Shield, and their RS232/485 Shield.
I assume it's this you're looking for??
Using library SPI at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SPI 
Using library SD at version 1.2.4 in folder: C:\Program Files (x86)\Arduino\libraries\SD 
Using library Ethernet at version 2.0.0 in folder: C:\Program Files (x86)\Arduino\libraries\Ethernet 
Using library TextFinder-master in folder: C:\Users\Mystery User\Documents\Arduino\libraries\TextFinder-master (legacy)

Here is the first switch/case with the last 6 cases commented out (valu) is an integer, (finder is the TextFinder Library):
`switch (valu)
              {
                case 1:
                  Code0x01(client);
                  break;

                case 2:
                  Code0x02(client);
                  break;

                case 3:
                  Code0x03(client);
                  break;

                case 4:
                  Code0x04(client);
                  break;

                case 5:
                  Code0x05(client);
                  break;

                case 6:
                  Code0x06(client);
                  break;

                case 7:
                  Code0x07(client);
                  break;

                case 8:
                  Code0x0A(client);
                  break;

                case 9:
                  Code0x0B(client);
                  break;

                case 10:
                  Code0x0F(client);
                  break;

                case 11:
                  Code0x10(client);
                  break;

                case 12:
                  Code0x11(client);
                  break;

                case 13:
                  Code0x12(client);
                  break;

                case 14:
                  Code0x13(client);
                  break;

                case 15:
                  Code0x14(client);
                  break;

                case 16:
                  Code0x15(client);
                  break;

                case 17:
                  Code0x16(client);
                  break;

                case 18:
                  Code0x17(client);
                  break;

                case 19:
                  Code0x18(client);
                  break;

                case 20:
                  Code0x19(client);
                  break;

                case 21:
                  Code0x1A(client);
                  break;

                case 22:
                  Code0x1C(client);
                  break;

                case 23:
                  Code0x1E(client);
                  break;

                case 24:
                  Code0x1F(client);
                  break;

                case 25:
                  Code0x20(client);
                  break;

                case 26:
                  Code0x09(client, finder);
                  break;

                case 27:
                  Code0x2A(client);
                  break;

                case 28:
                  Code0x2B(client);
                  break;

                case 29:
                  Code0x2C(client);
                  break;

                case 30:
                  Code0x2D(client, finder);
                  break;

                case 32:
                  Code0x31(client);
                  break;

                case 33:
                  Code0x32(client);
                  break;

                case 34:
                  Code0x33(client);
                  break;

                case 35:
                  Code0x34(client);
                  break;

                case 36:
                  Code0x35(client);
                  break;

                case 37:
                  Code0x36(client);
                  break;

                case 38:
                  Code0x37(client);
                  break;

                case 39:
                  Code0x46(client);
                  break;

                case 40:
                  Code0x47(client);
                  break;

                case 41:
                  Code0x48(client);
                  break;

                case 42:
                  Code0x49(client);
                  break;

                case 43:
                  Code0x4A(client);
                  break;

                case 45:
                  Code0x4F(client);
                  break;

                case 46:
                  Code0x50(client, finder);
                  break;

                case 47:
                  Code0x51(client);
                  break;

                case 48:
                  Code0x52(client, finder);
                  break;

                case 49:
                  Code0x53(client, finder);
                  break;

                case 50:
                  Code0x54(client);
                  break;

                case 51:
                  Code0x55(client);
                  break;

                case 52:
                  Code0x56(client);
                  break;

                case 56:
                  Code0x7D(client, finder);
                  break;

                case 58:
                  Code0x7F(client, finder);
                  break;

                case 60:
                  Code0x83(client, finder);
                  break;

                case 61:
                  Code0x84(client);
                  break;

                case 65:
                  Code0x90(client);
                  break;

                case 66:
                  Code0x94(client);
                  break;

                case 67:
                  Code0x9A(client, finder);
                  break;

                case 68:
                  Code0xA0(client, finder);
                  break;

                case 69:
                  Code0xA4(client, finder);
                  break;

                case 70:
                  Code0xA8(client, finder);
                  break;

                case 72:
                  Code0xAA(client, finder);
                  break;

                /*                case 75: 
                                  Code0xB0(client, finder);
                                  break;

                                case 76:  
                                  Code0xB1(client);
                                  break;

                                case 77:  
                                  Code0xB2(client);
                                  break;

                                case 78:  
                                  Code0xB3(client);
                                  break;

                                case 80:  
                                  Code0xB5(client, finder);
                                  break;

                                case 82:  
                                  Code0x8A(client, finder);
                                  break;
                */
                default:
                  break;
              }`

Here's is the second switch/case, I put the multiple lines in yesterday hoping I would've have to edit the code again and gotten an answer from the email I sent to Arduino.cc that would resolve this, (when it was just one line per case, everything worked fine as long as I didn't have over 149 cases throughout the whole code):
`
{
  EthernetClient client = server.available();
  switch (StatusInt[0])
  {
    case 17:
      client.print(F("<script>btn1.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 18:
      client.print(F("<script>btn1.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 19:
      client.print(F("<script>btn2.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 20:
      client.print(F("<script>btn2.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 21:
      client.print(F("<script>btn3.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 22:
      client.print(F("<script>btn3.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 24:
      client.print(F("<script>btn4.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 23:
      client.print(F("<script>btn4.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 25:
      client.print(F("<script>btn5.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 26:
      client.print(F("<script>btn5.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 27:
      client.print(F("<script>btn6.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 28:
      client.print(F("<script>btn6.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 29:
      client.print(F("<script>btn7.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 30:
      client.print(F("<script>btn7.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 32:
      client.print(F("<script>btn8.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 33:
      client.print(F("<script>btn9.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 34:
      client.print(F("<script>btn10.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 35:
      client.print(F("<script>btn11.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 36:
      client.print(F("<script>btn12.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 37:
      client.print(F("<script>btn13.style.backgroundColor='#FFFF00'\n"
                     "btn13.style.color='#000000'</script>\n"));
      break;

    case 39:
      client.print(F("<script>btn14.style.backgroundColor='#FFFF00'"
                     "btn14.style.color='#000000'</script>\n"));
      break;

    case 40:
      client.print(F("<script>btn15.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 41:
      client.print(F("<script>btn16.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 42:
      client.print(F("<script>btn17.style.backgroundColor='#FFFF00'"
                     "btn17.style.color='#000000'</script>\n"));
      break;

    case 43:
      client.print(F("<script>btn18.style.backgroundColor='#FFFF00'"
                     "btn18.style.color='#000000'</script>\n"));
      break;

    case 44:
      client.print(F("<script>btn19.style.backgroundColor='#FFFF00'"
                     "btn19.style.color='#000000'</script>\n"));
      break;

    case 45:
      client.print(F("<script>btn20.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 46:
      client.print(F("<script>btn21.style.backgroundColor='#FFFF00'"
                     "btn21.style.color='#000000'</script>\n"));
      break;

    case 49:
      client.print(F("<script>btn22.style.backgroundColor='#FFFF00'"
                     "btn22.style.color='#000000'</script>\n"));
      break;

    case 50:
      client.print(F("<script>btn23.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 51:
      client.print(F("<script>btn24.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 52:
      client.print(F("<script>btn25.style.backgroundColor='#FFFF00'"
                     "btn25.style.color='#000000'</script>\n"));
      break;

    case 53:
      client.print(F("<script>btn26.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 54:
      client.print(F("<script>btn27.style.backgroundColor='#FFFF00'"
                     "btn27.style.color='#000000'</script>\n"));
      break;

    case 55:
      client.print(F("<script>btn28.style.backgroundColor='#FFFF00'"
                     "btn28.style.color='#000000'</script>\n"));
      break;

    case 56:
      client.print(F("<script>btn29.style.backgroundColor='#FFFF00'"
                     "btn29.style.color='#000000'</script>\n"));
      break;

    case 57:
      client.print(F("<script>btn30.style.backgroundColor='#FFFF00'"
                     "btn30.style.color='#000000'</script>\n"));
      break;

    case 58:
      client.print(F("<script>btn31.style.backgroundColor='#FFFF00'"
                     "btn31.style.color='#000000'</script>\n"));
      break;

    case 59:
      client.print(F("<script>btn32.style.backgroundColor='#FFFF00'"
                     "btn32.style.color='#000000'</script>\n"));
      break;

    case 61:
      client.print(F("<script>btn33.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 62:
      client.print(F("<script>btn34.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 64:
      client.print(F("<script>btn35.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 65:
      client.print(F("<script>btn36.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 66:
      client.print(F("<script>btn37.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 67:
      client.print(F("<script>btn38.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 68:
      client.print(F("<script>btn39.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 69:
      client.print(F("<script>btn40.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 70:
      client.print(F("<script>btn41.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 71:
      client.print(F("<script>btn42.style.backgroundColor='#32CD32'\n"
                     "btn43.style.backgroundColor='#808080'\n"
                     "btn44.style.backgroundColor='#808080'\n"
                     "btn45.style.backgroundColor='#808080'\n"
                     "btn46.style.backgroundColor='#808080'\n"
                     "btn47.style.backgroundColor='#808080'\n"
                     "btn48.style.backgroundColor='#808080'</script>\n"));
      break;

    case 72:
      client.print(F("<script>btn43.style.backgroundColor='#32CD32'\n"
                     "btn42.style.backgroundColor='#808080'\n"
                     "btn44.style.backgroundColor='#808080'\n"
                     "btn45.style.backgroundColor='#808080'\n"
                     "btn46.style.backgroundColor='#808080'\n"
                     "btn47.style.backgroundColor='#808080'\n"
                     "btn48.style.backgroundColor='#808080'</script>\n"));
      break;

    case 73:
      client.print(F("<script>btn44.style.backgroundColor='#32CD32'\n"
                     "btn43.style.backgroundColor='#808080'\n"
                     "btn42.style.backgroundColor='#808080'\n"
                     "btn45.style.backgroundColor='#808080'\n"
                     "btn46.style.backgroundColor='#808080'\n"
                     "btn47.style.backgroundColor='#808080'\n"
                     "btn48.style.backgroundColor='#808080'</script>\n"));
      break;

    case 74:
      client.print(F("<script>btn45.style.backgroundColor='#32CD32'\n"
                     "btn43.style.backgroundColor='#808080'\n"
                     "btn44.style.backgroundColor='#808080'\n"
                     "btn42.style.backgroundColor='#808080'\n"
                     "btn46.style.backgroundColor='#808080'\n"
                     "btn47.style.backgroundColor='#808080'\n"
                     "btn48.style.backgroundColor='#808080'</script>\n"));
      break;

    case 75:
      client.print(F("<script>btn46.style.backgroundColor='#32CD32'\n"
                     "btn43.style.backgroundColor='#808080'\n"
                     "btn44.style.backgroundColor='#808080'\n"
                     "btn45.style.backgroundColor='#808080'\n"
                     "btn42.style.backgroundColor='#808080'\n"
                     "btn47.style.backgroundColor='#808080'\n"
                     "btn48.style.backgroundColor='#808080'</script>\n"));
      break;

    case 76:
      client.print(F("<script>btn47.style.backgroundColor='#32CD32'\n"
                     "btn43.style.backgroundColor='#808080'\n"
                     "btn44.style.backgroundColor='#808080'\n"
                     "btn45.style.backgroundColor='#808080'\n"
                     "btn46.style.backgroundColor='#808080'\n"
                     "btn42.style.backgroundColor='#808080'\n"
                     "btn48.style.backgroundColor='#808080'</script>\n"));
      break;

    case 77:
      client.print(F("<script>btn48.style.backgroundColor='#32CD32'\n"
                     "btn43.style.backgroundColor='#808080'\n"
                     "btn44.style.backgroundColor='#808080'\n"
                     "btn45.style.backgroundColor='#808080'\n"
                     "btn46.style.backgroundColor='#808080'\n"
                     "btn47.style.backgroundColor='#808080'\n"
                     "btn42.style.backgroundColor='#808080'</script>\n"));
      break;

    case 81:
      client.print(F("<script>btn49.style.backgroundColor='#FFFF00'"
                     "btn49.style.color='#000000'</script>\n"));
      break;

    case 82:
      client.print(F("<script>btn50.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 85:
      client.print(F("<script>btn51.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 87:
      client.print(F("<script>btn52.style.backgroundColor='#FFFF00'"
                     "btn52.style.color='#000000'</script>\n"));
      break;

    case 96:
      client.print(F("<script>btn53.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 97:
      client.print(F("<script>btn54.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 103:
      client.print(F("<script>btn56.style.backgroundColor='#FFFF00'\n"
                     "btn56.style.color='#000000'</script>\n"
                     "btn57.style.backgroundColor='#808080'\n"
                     "btn42.style.backgroundColor='#808080'\n"
                     "btn43.style.backgroundColor='#808080'\n"
                     "btn44.style.backgroundColor='#808080'\n"
                     "btn45.style.backgroundColor='#808080'\n"
                     "btn46.style.backgroundColor='#808080'\n"
                     "btn47.style.backgroundColor='#808080'\n"
                     "btn48.style.backgroundColor='#808080'\n"));
      break;

    case 104:
      client.print(F("<script>btn57.style.backgroundColor='#32CD32'\n"
                     "btn56.style.backgroundColor='#808080'\n"
                     "btn56.style.color='#FFFFFF'\n"
                     "btn42.style.backgroundColor='#808080'\n"
                     "btn43.style.backgroundColor='#808080'\n"
                     "btn44.style.backgroundColor='#808080'\n"
                     "btn45.style.backgroundColor='#808080'\n"
                     "btn46.style.backgroundColor='#808080'\n"
                     "btn47.style.backgroundColor='#808080'\n"
                     "btn48.style.backgroundColor='#808080'</script>\n"));
      break;

    case 112:
      client.print(F("<script>btn58.style.backgroundColor='#FFFF00'\n"
                     "btn58.style.color='#000000'</script>\n"));
      break;

    case 116:
      client.print(F("<script>btn60.style.backgroundColor='#FFFF00'"
                     "btn60.style.color='#000000'</script>\n"));
      break;

    case 117:
      client.print(F("<script>btn61.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 118:
      client.print(F("<script>btn61.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 119:
      client.print(F("<script>btn62.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 120:
      client.print(F("<script>btn63.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 121:
      client.print(F("<script>btn64.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 122:
      client.print(F("<script>btn65.style.backgroundColor='#FFFF00'"
                     "btn65.style.color='#000000'</script>\n"));
      break;

    case 123:
      client.print(F("<script>btn66.style.backgroundColor='#FFFF00'"
                     "btn66.style.color='#000000'</script>\n"));
      break;

    case 124:
      client.print(F("<script>btn67.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 128:
      client.print(F("<script>btn68.style.backgroundColor='#FFFF00'"
                     "btn68.style.color='#000000'</script>\n"));
      break;

    case 129:
      client.print(F("<script>btn69.style.backgroundColor='#FFFF00'"
                     "btn69.style.color='#000000'</script>\n"));
      break;

    case 130:
      client.print(F("<script>btn70.style.backgroundColor='#FFFF00'"
                     "btn70.style.color='#000000'</script>\n"));
      break;

    case 131:
      client.print(F("<script>btn70.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 132:
      client.print(F("<script>btn71.style.backgroundColor='#FFFF00'"
                     "btn71.style.color='#000000'</script>\n"));
      break;

    case 133:
      client.print(F("<script>btn71.style.backgroundColor='#32CD32'</script>\n"));
      break;

    case 134:
      client.print(F("<script>btn72.style.backgroundColor='#FF0000'</script>\n"));
      break;

    case 138:
      client.print(F("<script>btn73.style.backgroundColor='#FFFF00'"
                     "btn73.style.color='#000000'</script>\n"));
      break;

    case 152:
      client.print(F("<script>btn74.style.backgroundColor='#FFFF00'"
                     "btn74.style.color='#000000'</script>\n"));
      break;

    case 153:
      client.print(F("<script>btn75.style.backgroundColor='#FFFF00'"
                     "btn75.style.color='#000000'</script>\n"));
      break;

    case 154:
      client.print(F("<script>btn76.style.backgroundColor='#FFFF00'"
                     "btn76.style.color='#000000'</script>\n"));
      break;

    case 155:
      client.print(F("<script>btn77.style.backgroundColor='#FFFF00'"
                     "btn77.style.color='#000000'</script>\n"));
      break;

    default:
      break;

  }
}`

**Comment by matthijskooijman** [comment] 2020-11-23 21:26
Thanks for providing some more details. However, this shows the offending bit of code, which looks like it should work at first glance, but does not give me a *complete* example of something that is broken. With that I mean: A sketch that others can just copy-paste into the IDE and run on a board (e.g. an Arduino Mega2560, which is common enough for people to have it) to see the problem. Ideally this sketch can show the problem without additional hardware (i.e. without an Ethernet shield, which I and most people won't have...).

>  I assume it's this you're looking for??

There's also a bit at the start that says which core or platform (dunno which term is used there exactly) is used, with the version and directory that is helpful.

I've also edited your comment to fix the formatting a bit, you need to use triple backticks (`````````) instead of a single one for blocks of code.

**Comment by matthijskooijman** [comment] 2020-11-26 09:48
@peasoup49 sent me his sketch through private e-mail, since they didn't want to share it publicly yet. That's fine, but I want to keep discussion public, so I'm responding here.

@peasoup49, looking at the sketch you sent me, it still is your full sketch, not a minimal example like I asked for. In particular, it still relies on the Ethernet library and hardware, so I can't really test this locally to reproduce. You've also not clearly stated what the actual problem is ("It doesn't work" is too broad), so I can't really move forward here.

You also mention that you suspect that you might be running out of stack space. I can't be sure, but that would be a plausible explanation (when you run out of stack space, pretty much anything can happen, and removing random bits of code can help prevent the problem). With that, I now think that, as I originally suspected, this is just a bug in your code that causes some weirdness (possibly by running out of memory), rather than the compiler that actually produces incorrect results.

Since this issue tracker is for actual bugs in the IDE and compilation process, not for getting help with your own code, I'm going to close this issue. I also personally don't have time to help you find the issue, so you might want to seek assistance in other places, such as the forum or the IRC channel. Feel free to post followup comments here if you think there is a bug after all (we can always reopen) or maybe when you solve your issue (just for future reference).

**Closed by matthijskooijman** 2020-11-26 09:48 UTC
Labels: Component: Compilation, Type: Bug
