### ISSUE TITLE
Mouse.move positioning

### ISSUE THREAD

**Issue by Davonic** [arduino/Arduino#1417] opened 2013-05-16 02:54 UTC
I know the reason for the problem I'm having with multiple move Mouse.move  positioning being imprecise is due to Mouse Acceleration and/or Precise Pointer in Windows but my question is whether anyone has found a way to deal with this issue and get precise positioning. I don't consider this an Arduino hardware/software fault although it's possible a workaround could be added to it or even, unknown to me, already exist.

Example (test code section c/w commented actual results)
                                      // 60 40 mouse initial position by movement of physical mouse
Mouse.move(100,100,0);  // 160 140 for first movement which is correct
delay(10000);
Mouse.move(100,100,0) ; // 420 401 for second movement which is 260 & 261 (over 2 1/2 times)

Subsequent repeats of the command (w delay) continue to get over 2 1/2 times the desired movement. I've tried inserting other mouse commands including a Mouse.move(-1,-1,0) but none stop the acceleration.

I'm aware that I can adjust Mouse Acceleration & Precise Pointer to reduce the issue but then my regular mouse usage is less convenient.

My thought is that since the Leonardo mouse is a separate device from my regular mouse is that there might be a way, that someone is aware of, to remove Mouse Acceleration from it while leaving it in place for the hardware mouse. Possibly a Registry setting (that applies to Leo not hardware mouse) or some Arduino code that can be inserted before Mouse.move commands to trick Windows into thinking each move is the first (accurate one).

For Arduino hardware/software workarounds, an ability to set the speed that the mouse moves within each Mouse.move should reduce the problem significantly since the current near instant move from position to position is likely a major factor.

My temporary (reasonably successful) workaround is to assume a 2.6x acceleration on all but the first call and adjust the Mouse.move parameters to suit. Note to others who try this that the 2.6 value is for my PC & Windows settings and will probably be a different, though still consistant, value on yours.

Thanks in advance for any insights!

**Comment by facchinm** [comment] 2015-09-21 12:50
Closing with #1803

**Closed by facchinm** 2015-09-21 12:50 UTC
Labels: Component: Core

**Comment by laith7ussein** [comment] 2019-08-26 10:17
Hi, I'm working on a Robot project with Arduino and I'm using a mouse as a positioning system to get x and y, the Arduino reads dx and dy not x and y so I add these values in a new variable after each reading. The problem is when the robot moves faster dy or dx become larger, I mean the relative value is obviously depending on the speed of movement. 

Is there any way to read dx and dy without speed effect?
