### ISSUE TITLE
add Libraries in sub folder of Arduino libraries folder

### ISSUE THREAD

**Issue by mkeyno** [arduino/Arduino#8170] opened 2018-11-04 09:36 UTC
hi 
I intend to add my libraries in special folder in Arduino libraries folder like following temple
libraries/MyLibraries/lib1,lib2,lib3,.........
but according to this[ PR](https://github.com/arduino/Arduino/pull/1986) its not allowed yet , also I found that Arduino stop loading any folder content when it doesn't find any header file (*.h), so I was wondering, if it possible to create header file like "MyLibraries.h" in the MyLibraries folder and addressed new libs in it
TNX

**Comment by per1234** [comment] 2018-11-04 09:41
Closing as duplicate of https://github.com/arduino/Arduino/pull/1986.

**Closed by per1234** 2018-11-04 09:41 UTC
Labels: Type: Duplicate
