### ISSUE TITLE
MacOS 10.13.5 and IDE 1.8.5 window selector behaving differently

### ISSUE THREAD

**Issue by downunder54** [arduino/Arduino#7750] opened 2018-07-04 04:25 UTC
The latest version of the IDE doesn't seem to go through all the IDE windows anymore when using the Cmd-` shortcut. It only toggles between the current and last window.

Is that a new "feature" and if so, can the old behaviour be reactivated?

**Comment by facchinm** [comment] 2018-07-16 08:19
Hi @downunder54 ,
what do you mean with "old" and "new" versions? We didn't change any behaviour recently, could it be due to an OSX update?

**Comment by downunder54** [comment] 2018-07-16 08:41
Hello facchinm.

So by old I meant Arduino IDE 1.6.12 and new is 1.8.5.
Both on MacOS 10.13.5

I keep OSX on the latest version, so yes, there were quite a few updates. However, this is the only software I'm using that has changed its behaviour for the Cmd-backquote shortcut. Also, if I run the 1.6.12 IDE it's still showing the expected behaviour, which is cycling through all the Arduino windows that I have open, including the serial monitor.
Version 1.8.5 only changes between the active window and the previous active IDE window.
I'm a bit surprised no-one else is experiencing this on OSX...

**Comment by facchinm** [comment] 2018-07-16 09:04
Thanks for the info! I could try bisecting between that two versions but I doubt we changed something so specific. Another possible culprit is Java itself, since we update the bundled JRE regularly. Could you test latest hourly and check if it also happens there? Thanks a lot!

**Comment by downunder54** [comment] 2018-07-16 09:50
Sure. Just tried it with 1.8.6 hourly build 2018/07/11 and it shows the same, unusual behaviour.

This might be no big deal for many users, but some, like me, have 10 or more windows from all different applications open at the same time on the same  virtual desktop.
To change apps I always use Cmd-tab and then switch through the windows of one app with Cmd-backquote. 
If the latter only toggles between the last two windows I would have no way to get to IDE windows that are buried any deeper except for moving all the other windows to the side until I can find and click/focus on the one I need. That's because there is also no window selector option in the top ribbon command list, like you would find on software like BBedit, Skype or Firefox.

**Comment by facchinm** [comment] 2018-09-24 12:07
Hi @downunder54 ,
I was taking a look at various osx specific limitations and analyzed a bit more your report. 
In fact the problem is that new versions of macOS do not handle this for the application, but the app must reimplement the desired behaviour (see https://apple.stackexchange.com/a/337111).
Anyway, going backwards (with ```Cmd + Shift + ` ``` ) still scrolls all the windows :expressionless: 
Said that, I'd close the issue as wontfix; if anyone else is interested in bypassing this bug I'll be glad to reopen it.

**Closed by facchinm** 2018-09-24 12:07 UTC
Labels: OS: OSX

**Comment by downunder54** [comment] 2018-09-25 02:10
Thanks for looking into this again, facchinm! I didn't know about the Cmd-Shift-backtick shortcut. It's a bit too awkward for regular use as it requires three fingers. I'm now test driving the app Contexts, as mentioned in your link, which seems to help a lot with that.
