### ISSUE TITLE
Serial Monitor causes 100% cpu load after device is disconnected

### ISSUE THREAD

**Issue by bitluni** [arduino/Arduino#8783] opened 2019-04-13 18:10 UTC
Windows 10 Pro, XPS 13 Core i7
When the Serial Monitor is open and the device that was connected at the configured port is removed the Serial Monitor takes a core to 100% load. That is quite annoying on laptops especially when the moitor is somewhere in the background not being noticed.
I have this issue since ever on different versions. My current is 1.8.8

**Comment by per1234** [comment] 2019-04-13 22:57
Closing as duplicate of https://github.com/arduino/Arduino/issues/2333

This should be fixed by https://github.com/arduino/Arduino/pull/8046

Other reports:

- https://github.com/arduino/Arduino/issues/7505#issuecomment-421885841
- https://github.com/arduino/Arduino/issues/8009#issuecomment-424476441
- https://github.com/arduino/Arduino/issues/8009#issuecomment-440252164

Please test with the Beta Build of the Arduino IDE to see if https://github.com/arduino/Arduino/pull/8046 fixes the problem for you:
https://www.arduino.cc/en/Main/Software#beta

**Closed by per1234** 2019-04-13 22:57 UTC
Labels: Component: IDE Serial monitor, Type: Bug, Type: Duplicate
