### ISSUE TITLE
IDE freezes in Open File dialog upon option click to delete

### ISSUE THREAD

**Issue by TheAlexisProject** [arduino/Arduino#7538] opened 2018-05-01 13:00 UTC
Arduino rev 1.8.5, Windows 10 Pro Version 1709, Intel i7 64-bit, Date 1-May-2017

Steps to reproduce the bug.  Note this scenario is  something I wouldn't normally do, but I saw some old stuff I wanted to clean up and forgot I was in the open dialog when I tried to delete the files.  I suppose another user might do the same thing by accident.

1.  File->Open... dialog.
2. Open an Arduino sketch... dialog appears.
3.  Right click a sketch folder.
4.  Select Delete.
5.  Dialog prompts "Are you sure?"
6.  Click OK.
7. IDE locks up in the state pictured.  Used Task Manager to kill the IDE.

![capture](https://user-images.githubusercontent.com/13632521/39473568-185341ac-4d15-11e8-9348-73dff9c36dc3.png)

8. It appears the folder was actually deleted, so that part worked correctly.

**Comment by per1234** [comment] 2018-05-01 13:06
Closing as duplicate of https://github.com/arduino/Arduino/issues/5191.

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-05-01 13:06 UTC
