### ISSUE TITLE
Segmentation violation when sketch name starts with RCS

### ISSUE THREAD

**Issue by hardija** [arduino/Arduino#9569] opened 2019-12-29 15:16 UTC
Ok, here's a strange one. If I name a sketch starting with RCS (all caps), I get a seg fault when attempting to compile. If I change the name everything is fine. If it's not all caps everything is fine. 

### To reproduce:
1. Create a new sketch
2. Compile (Verify) => No issues
3. Save as "RCS"
4. Compile => SIGSEGV "invalid memory address or nil pointer dereference"

### Here is the error message dump:

Arduino: 1.8.10 (Mac OS X), TD: 1.48, Board: "Arduino Uno"

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1435c0e]

goroutine 1 [running]:
github.com/arduino/arduino-cli/legacy/builder.(*ContainerSetupHardwareToolsLibsSketchAndProps).Run(0x1bacff0, 0xc00012cc00, 0x1bacff0, 0x100c188)
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/container_setup.go:77 +0x45e
github.com/arduino/arduino-cli/legacy/builder.runCommands(0xc00012cc00, 0xc0004e7e00, 0x2, 0x2, 0x102aa01, 0xc000000008, 0xc0000b5df8)
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/builder.go:210 +0xdf
github.com/arduino/arduino-cli/legacy/builder.(*ParseHardwareAndDumpBuildProperties).Run(0xc0000b5e70, 0xc00012cc00, 0x1bacef0, 0xc00005c1f0)
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/builder.go:198 +0xcc
github.com/arduino/arduino-cli/legacy/builder.RunParseHardwareAndDumpBuildProperties(...)
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/builder.go:231
main.main()
	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-builder/main.go:388 +0x8ad
/Applications/Arduino v1.8.10.app/Contents/Java/arduino-builder returned 2

Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

I'm running Arduino 1.8.10 on Mac OS Mojave. Updated to the latest as of this post.

**Comment by per1234** [comment] 2019-12-29 15:19
Thanks for the report @hardija! This is actually a problem with arduino-cli, and we already have a report of it in that repository, so I'm going to close this as a duplicate of https://github.com/arduino/arduino-cli/issues/522

**Closed by per1234** 2019-12-29 15:20 UTC
