### ISSUE TITLE
Button stop compilation / upload

### ISSUE THREAD

**Issue by FernandoGarcia** [arduino/Arduino#3834] opened 2015-09-21 14:55 UTC
Hi!
I would like to ask to add this button again.
This button is very usefull when we are working with a big code.
The IDE spends 70 seconds to compile my code and more 60 to upload, so if I find some error during this time is needed remove the USB cable to stop the upload.
Best regards.

**Comment by ffissore** [comment] 2015-09-21 15:27
Duplicate of #3771

**Closed by ffissore** 2015-09-21 15:27 UTC

**Comment by lmihalkovic** [comment] 2015-12-04 09:32
[LMDONE]
