### ISSUE TITLE
Implement full screen mode on Mac OS X

### ISSUE THREAD

**Issue by cunidev** [arduino/Arduino#3749] opened 2015-08-31 18:24 UTC

**Comment by carlosperate** [comment] 2015-08-31 19:21
This feature was tested, but ultimately dropped: https://github.com/arduino/Arduino/pull/3243

**Comment by cunidev** [comment] 2015-09-01 07:18
Dropped definitely, or just waitiing for developers? #3256

**Comment by ffissore** [comment] 2015-09-01 07:46
Closing as duplicate of #3256. Indeed that code needs some mac expert. Feel free to fetch, use and adapt that code

**Closed by ffissore** 2015-09-01 07:46 UTC
