### ISSUE TITLE
Obsolete Reference files

### ISSUE THREAD

**Issue by 00alis** [arduino/Arduino#7778] opened 2018-07-11 10:22 UTC
- right click on a keyword in the code 
- select 'Find in Reference'
- an HTML page is opened, but the content and the layout are obsolete compered to what we have now on https://www.arduino.cc/reference/en/. All the content is now hosted on the repo https://github.com/arduino/reference-en

Current page
<img width="1429" alt="screenshot 2018-07-10 12 34 47" src="https://user-images.githubusercontent.com/6151328/42565877-fdf978e4-8504-11e8-9709-f18e92a8f281.png">

Desired page
[ReferanceIDEJava.pdf](https://github.com/arduino/Arduino/files/2184035/ReferanceIDEJava.pdf)

cc @smellai @cmaglie

**Comment by per1234** [comment] 2020-10-05 08:34
Closing as duplicate of https://github.com/arduino/Arduino/issues/8860. Even though this one was first (my bad), the other one has a little more information, so I'm giving that one preference.

**Closed by per1234** 2020-10-05 08:34 UTC
