### ISSUE TITLE
Issue with I2C lcd library in IDE 1.6.6 and 1.6.7

### ISSUE THREAD

**Issue by RoRut** [arduino/Arduino#4302] opened 2015-12-14 14:14 UTC
I am running Windows10 ( 64 bit). When trying to use the I2C lcd library in IDE 1.6.6 and 1.6.7 it only prints the first character of each line on the display.

If I load IDE 1.6.5 everything works fine.

Please advise ??

Best regards,
Roland Rutsaert

**Comment by facchinm** [comment] 2015-12-14 14:31
Hi @RoRut ,
the problem is not within the IDE itself but it's caused by a misbehaviour of LiquidCrystal_I2C library (read here for a fix https://github.com/arduino/Arduino/issues/4142#issuecomment-156690585)
In fact the latest Wire needs to know how many characters are written and the LiquidCrystal library was reporting 0, thus stopping after the first character.
In fact the fix was merged but the library was not released, so you need to apply the fix manually.

**Comment by cmaglie** [comment] 2015-12-14 14:33
@RoRut 
please comment also here https://github.com/arduino/Arduino/issues/4142#issuecomment-156690585 and ask the author of the library to make a new release.

**Closed by cmaglie** 2015-12-14 14:33 UTC

**Comment by cmaglie** [comment] 2015-12-14 14:37
ehm.. sorry I mean here: https://github.com/marcoschwartz/LiquidCrystal_I2C/pull/5

**Comment by RoRut** [comment] 2015-12-15 08:06
Did the mod  0 to 1.

 

Everything Works fine.

 

Thanks for the quick reaction.

 

Best regards,

 

Roland Rutsaert

 

Van: Cristian Maglie [mailto:notifications@github.com] 
Verzonden: maandag 14 december 2015 15:38
Aan: arduino/Arduino
CC: RoRut
Onderwerp: Re: [Arduino] Issue with I2C lcd library in IDE 1.6.6 and 1.6.7 (#4302)

 

ehm.. sorry I mean here: marcoschwartz/LiquidCrystal_I2C#5 <https://github.com/marcoschwartz/LiquidCrystal_I2C/pull/5>
