### ISSUE TITLE
Hacking/WiFiShieldFirmwareUpgrading points to a bad firmware download link on github

### ISSUE THREAD

**Issue by solarfly73** [arduino/Arduino#3132] opened 2015-05-14 08:35 UTC
http://www.arduino.cc/en/Hacking/WiFiShieldFirmwareUpgrading

Under "Download Updated Firmware for the 32UC3A1256" the link is:
https://github.com/arduino/Arduino/tree/master/hardware/arduino/firmwares

This link 404s.

**Comment by agdl** [comment] 2015-05-21 07:58
I'm closing this because is a duplicate of https://github.com/arduino/Arduino/issues/3133

**Closed by agdl** 2015-05-21 07:58 UTC
Labels: Component: Documentation, Type: Duplicate
