### ISSUE TITLE
OSX 10.13.4 doesn't open Arduino

### ISSUE THREAD

**Issue by Edizgoldeli** [arduino/Arduino#7527] opened 2018-04-28 22:13 UTC
macOS High Sierra 10.13.4 doesn't open 32-bit Arduino application. I install latest Java which Version 8 update 171 (build 1.8.0_171-b11)

(Note: It says "Unable to load java runtime environment)

**Comment by per1234** [comment] 2018-04-29 06:57
Which version of the Arduino IDE are you using?

Possible duplicate of https://github.com/arduino/Arduino/issues/7213

Similar past issues:
- https://github.com/arduino/Arduino/issues/7068
- https://github.com/arduino/Arduino/issues/2384
- https://github.com/arduino/Arduino/issues/2178

**Comment by Edizgoldeli** [comment] 2018-04-29 08:26
version 1.8.5

**Comment by facchinm** [comment] 2018-05-02 16:13
Hi @Edizgoldeli,
the hourly version of the IDE is now embedding jre 1.8.0_171.
Thanks for reporting!

**Comment by gvarisco** [comment] 2018-12-11 13:46
This should be fixed. @Edizgoldeli, I'm going ahead and mark this ticket as 'closed', but feel free to re-open it in case you encounter further problems with the newer, stable version released.

**Closed by gvarisco** 2018-12-11 13:46 UTC
Labels: Component: IDE, OS: OSX

**Comment by Edizgoldeli** [comment] 2018-12-11 14:05
After many tries I realise that my usb converter is fake (I bought it from aliexpress) so I think there isn’t any problem. Sorry for this mistake. Best regards.

iPhone’umdan gönderildi

Gianluca Varisco <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (11 Ara 2018 ÖS 4:47):


This should be fixed. @Edizgoldeli<https://github.com/Edizgoldeli>, I'm going ahead and mark this ticket as 'closed', but feel free to re-open it in case you encounter further problems with the newer, stable version released.
