### ISSUE TITLE
pin not an interrupt

### ISSUE THREAD

**Issue by ruggb** [arduino/Arduino#9371] opened 2019-10-29 13:38 UTC
I am using Marlin on a 3D printer. I have interrupts enabled. That defines pins as interrupts.
Previous builds of Marlin compiled with 1.8.10. The latest build produces this error:
```
In file included from C:\Users\Bill\AppData\Local\Temp\arduino_build_809038\sketch\src\module\endstops.cpp:36:0:

c:\users\bill\appdata\local\temp\arduino_build_809038\sketch\src\hal\hal_avr\endstop_interrupts.h: In function 'void setup_endstop_interrupts()':

c:\users\bill\appdata\local\temp\arduino_build_809038\sketch\src\hal\hal_avr\endstop_interrupts.h:135:7: error: non-constant condition for static assertion

       static_assert(digitalPinToPCICR(Y_MIN_PIN), "Y_MIN_PIN is not interrupt-capable");

       ^~~~~~~~~~~~~

c:\users\bill\appdata\local\temp\arduino_build_809038\sketch\src\hal\hal_avr\endstop_interrupts.h:57:57: error: reinterpret_cast from integer to pointer

                                     WITHIN(p, 62, 69) ? &PCICR : nullptr )

                                                         ^

c:\users\bill\appdata\local\temp\arduino_build_809038\sketch\src\hal\hal_avr\endstop_interrupts.h:135:21: note: in expansion of macro 'digitalPinToPCICR'

       static_assert(digitalPinToPCICR(Y_MIN_PIN), "Y_MIN_PIN is not interrupt-capable");

                     ^~~~~~~~~~~~~~~~~
```
the interrupt pins are X_MIN=3, Y_MIN=14, & Z_MIN=18 - there may be others
I do not know what the change was in Marlin that is now causing this error, but it is reported to compile OK with PlatformIO.

What happened to pin 14?

**Comment by matthijskooijman** [comment] 2019-10-29 14:23
In 1.8.10, the compiler (gcc) version was upgraded. The new version is a lot more strict (that is, more standards-compliant) regarding what can be used as a constant expression (i.e. in a `static_assert` statement). Apparently the Marlin firmware uses an expression that is not a valid constant expression. Looking at the code, this is something that should be fixed either in Marlin (by changing the assert to use something that is constant), or the library that exposes `digitalPinToPCICR` (which I think is not the Arduino IDE or core itself).

In any case, this is not something that the Arduino IDE can fix - the problem is in code that has always been illegal, it's just that in older versions gcc did not produce an error and made it work but no longer does so.

Thus I'm closing this issue, I would suggest you report this at the Marlin firmware (pointing to this issue). They might want to take this up with the PCINT library used, but it is probably good to track this at Marlin too.

**Closed by matthijskooijman** 2019-10-29 14:23 UTC
