### ISSUE TITLE
1.6.10 won't compile my project, fails on normal #include

### ISSUE THREAD

**Issue by i-make-robots** [arduino/Arduino#5211] opened 2016-08-05 20:48 UTC
https://github.com/MarginallyClever/Makelangelo-firmware/tree/master/firmware_ams/firmware_ams.ino
calls

   #include "AFMotorDrawbot/AFMotorDrawbot.h"

which exists.  Tests on windows 10 and linux systems both fail on this line.
someone in irc #arduino said that gcc was compiling with -E and that seemed wierd to them.  IDK.

**Comment by matthijskooijman** [comment] 2016-08-05 21:44
I believe this is a duplicate of #5186, which got introduced in 1.6.10 and will be fixed in 1.6.11 in the coming days. Testing the release candidate would be appreciated: https://github.com/arduino/Arduino/pull/5208#issuecomment-237938156

**Closed by matthijskooijman** 2016-08-05 21:44 UTC
