### ISSUE TITLE
Compiller error

### ISSUE THREAD

**Issue by ZASto** [arduino/Arduino#8111] opened 2018-10-18 10:48 UTC
As of the moment JRE was updated, the compiller spits out error:
* IDE ver 1.8.7, OS Ubuntu 14.04 64 biit
* same IDE version on Win7 Ultimate, 64 bit

Linux:
`lto1: internal compiler error: in lto_output_varpool_node, at lto-cgraph.c:624

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper: fatal error: /home/zasto/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-gcc returned 1 exit status

compilation terminated.

/home/zasto/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld: error: lto-wrapper failed

collect2: error: ld returned 1 exit status

exit status 1

Error compiling for board Arduino Nano.`

Win7:
`lto1.exe: internal compiler error: in lto_output_varpool_node, at lto-cgraph.c:624

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Nano.`

**Comment by facchinm** [comment] 2018-10-18 12:19
Hi @ZASto ,
it's not about jre but about the new compiler. Closing as duplicate of https://github.com/arduino/Arduino/issues/7949 , let's continue debugging the issue there.

**Closed by facchinm** 2018-10-18 12:19 UTC

**Comment by per1234** [comment] 2018-10-18 16:03
I think this is actually a duplicate of https://github.com/arduino/ArduinoCore-avr/issues/39. Perhaps both issues are related.
