### ISSUE TITLE
Spelling error on arduino.cc

### ISSUE THREAD

**Issue by alextaujenis** [arduino/Arduino#4148] opened 2015-11-14 15:38 UTC
Go to this page: http://playground.arduino.cc/Main/Participate
The side-bar on the left has the word Partecipate when it should be spelled Participate.
![screen shot 2015-11-14 at 8 37 12 am](https://cloud.githubusercontent.com/assets/521443/11164342/0580774a-8aab-11e5-9feb-a14d5e487a32.png)

**Comment by per1234** [comment] 2015-11-14 22:42
I've been trying to get this fixed for 2 months now. See https://github.com/arduino/Arduino/issues/3506#issuecomment-138879685. I have a list of 24 different issues with the website but I don't see the point of taking the time to report them if I'm just going to be ignored.

**Comment by matthijskooijman** [comment] 2015-11-16 07:31
The playground is essentially a wiki, created and maintained by the community, so anyone should be able to register an account and change it. However, I'm not so sure how to edit the side bar on the playground, perhaps it's a page with a special name?

**Comment by per1234** [comment] 2015-11-16 07:45
As I state in my issue, the page is http://playground.arduino.cc/Site/SideBar and it has a different password from the rest of the playground so the community can't edit that page. @mastrolinux has the ability to edit it. In fact he made this spelling mistake while making some of the changes I recommended in #3506.

**Comment by matthijskooijman** [comment] 2015-11-16 07:54
@per1234, ah, I should have read your issue before commenting here. I'm closing this issue as a duplicate of #3506, since that also includes this same issue. @alextaujenis, thanks for reporting, though!

**Closed by matthijskooijman** 2015-11-16 07:54 UTC
Labels: Component: Documentation

**Comment by alextaujenis** [comment] 2015-11-16 17:34
Looks like @mastrolinux fixed it, thanks!
