### ISSUE TITLE
Arduino IDE 1.6.11 - Sketch in temp folder is not saved in UTF-8 charset

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#5376] opened 2016-09-16 02:59 UTC
If the save is canceled during "compile" or "upload", sketches are saved in a temp folder with the current Windows charset not UTF-8 charset not like the save command.

**Comment by per1234** [comment] 2017-07-05 07:14
Closing as duplicate of https://github.com/arduino/Arduino/issues/4231

**Closed by per1234** 2017-07-05 07:14 UTC
Labels: Component: IDE, Type: Duplicate
