### ISSUE TITLE
Port grey out after a minute Windows 10 IDE 1.8.8 or 1.6.11. Works initially.

### ISSUE THREAD

**Issue by jcflyer** [arduino/Arduino#8410] opened 2019-01-20 13:47 UTC
OTA for nodemcu only works with old ide versions. New version 1.8.8 from MS store does the same thing described below. Port greyed out after a minute.
 I have used Arduino IDE 1.6.11 on a wired desktop running XP SP2 to wirelessly program 4 Nodemcu devices without any problem for over a year.
I got a new laptop with Windows 10 and installed 1.6.11 and all the network ports show up and work immediately but then disappear and the port is greyed out in a minute or so.
I can only upload once or twice before the port is gone.
If I restart the laptop the ports show up and work again for a short time. Nothing I have tried has worked so far including allowing port 8266 or turning off the firewall.
Also compiling is very slow now.

**Comment by matthijskooijman** [comment] 2019-01-20 14:20
This is the third issue you open with pretty much the same text. Can you please *not* do that and comment to existing issues rather than creating new issues? What you're doing now is certainly not going to get anything fixed faster (on the contrary, it will annoy people instead...).

I'm closing this issue as a duplicate of #8408.

**Closed by matthijskooijman** 2019-01-20 14:20 UTC
