### ISSUE TITLE
Arduino IDE - Serial ports not working on El Capitan

### ISSUE THREAD

**Issue by HBRancher** [arduino/Arduino#4829] opened 2016-04-06 15:43 UTC
Arduino IDE causes EL Capitan OSX to lockup the bluetooth mouse and keyboard, and does not upload to Arduino UNO boards ??
Has anyone solved this problem yet???
Thanks

**Comment by facchinm** [comment] 2016-04-11 07:53
Closing as duplicate of #3928, let's try keeping all the conversation there

**Closed by facchinm** 2016-04-11 07:53 UTC
