### ISSUE TITLE
Please add XLR8SPI to the library manager

### ISSUE THREAD

**Issue by crakerbr-superiontech** [arduino/Arduino#5860] opened 2017-01-16 16:02 UTC
Fixed issues, library is here: https://github.com/AloriumTechnology/XLR8SPI

**Comment by per1234** [comment] 2017-01-17 01:05
The library was already added to Library Manager in https://github.com/arduino/Arduino/issues/5847. Library Manager automatically picks up new releases and your most recent release(0.0.4) is already available via Library Manager. There's no need to submit an issue every time you make a release to your libraries.

Duplicate of https://github.com/arduino/Arduino/issues/5847

**Closed** 2017-01-18 12:45 UTC
Labels: Component: Board/Lib Manager
