### ISSUE TITLE
"Multiple libraries found" message cut off if path name has a space.

### ISSUE THREAD

**Issue by i-make-robots** [arduino/Arduino#9734] opened 2020-02-07 20:18 UTC
Arduino 1.8.10, Windows 10.
Installed Adafruit_TFTLCD library.
Opened tftbmp example from said library and compiled.
Last error message reads:

Multiple libraries were found for "Adafruit_TFTLCD.h"
 Used: C:\Users\Dan\Documents\Arduino\libraries\Adafruit_TFTLCD_Library
Multiple libraries were found for "SD.h"
 Used: C:\Program

Appears to cut off if folder name has a space.

I tried to search for duplicate issue, apologies if it's already there.

Thank you!  Stay awesome!!

**Comment by per1234** [comment] 2020-02-07 21:52
Closing as duplicate of https://github.com/arduino/arduino-cli/issues/493 and https://github.com/arduino/Arduino/issues/9287

**Closed by per1234** 2020-02-07 21:52 UTC
Labels: Type: Bug, Type: Duplicate
