### ISSUE TITLE
wrong result for pow()

### ISSUE THREAD

**Issue by digimeas** [arduino/Arduino#7796] opened 2018-07-18 19:28 UTC
Hi!

When I use this code:

    {
    TCCR1B  = B00010000; 
      // snip
    TCCR1B |= B00000011;                         //  CS12:CS10 = 011 => clk/64.  Starts the clock.
      // snip
    uint16_t cs = (TCCR1B & B111);   Serial.print("\t cs = B");  Serial.print(cs,BIN);  // B11
                                     Serial.print(" = ");        Serial.print(cs,DEC);  //   3
    cs--;                            Serial.print(" => ");       Serial.print(cs,DEC);  //   2
    cs = (uint16_t)pow(8, cs);       Serial.print(" => ");       Serial.print(cs,DEC);  //  63
    }

it results in cs = 63.    <- BAD :-(

But when I follow (or preceed) it with this WTF code:

    {
    uint16_t cs = 3;                 Serial.print("\t cs = B");  Serial.print(cs,BIN);  // B11
                                     Serial.print(" = ");        Serial.print(cs,DEC);  //   3
    cs--;                            Serial.print(" => ");       Serial.print(cs,DEC);  //   2
    cs = (uint16_t)pow(8, cs);       Serial.print(" => ");       Serial.print(cs,DEC);  //  64
    }

it yields cs = 64.    <- Good :-)

Wrong results for TCCR1B |= B00000010, B00000011, or B00000100.

Doesn't matter if I "8L" or "8." or "(float)cs", etc., inside pow().

Arduino 1.8.5,  Linux Mint current-ish.

Target is Pololu A*Micro 32U4 (using Board: "Arduino Leonardo");

Enjoy! :-)
Doug

**Comment by cmaglie** [comment] 2018-07-26 08:48
Please post a **full** sketch that shows the problem, otherwise it's quite difficult not only to diagnose but also to reproduce...

**Comment by digimeas** [comment] 2018-07-26 16:41
Here you go

      #include <Arduino.h>
      
      void setup() 
      {
      
        Serial.begin(500000);
        while (!Serial) { ; }
        
        {
        TCCR1B  = B00010000;
        TCCR1B |= B00000011;                         //  CS12:CS10 = 011 => clk/64.  Starts the clock.
        uint16_t cs = (TCCR1B & B111);   Serial.print("\t cs = B");  Serial.print(cs,BIN);  // B11
                                         Serial.print(" = ");        Serial.print(cs,DEC);  //   3
        cs--;                            Serial.print(" => ");       Serial.print(cs,DEC);  //   2
        cs = (uint16_t)pow(8, cs);       Serial.print(" => ");       Serial.print(cs,DEC);  //  63
        Serial.print("\n");
        }
        
        {
        uint16_t cs = 3;                 Serial.print("\t cs = B");  Serial.print(cs,BIN);  // B11
                                         Serial.print(" = ");        Serial.print(cs,DEC);  //   3
        cs--;                            Serial.print(" => ");       Serial.print(cs,DEC);  //   2
        cs = (uint16_t)pow(8, cs);       Serial.print(" => ");       Serial.print(cs,DEC);  //  64
        Serial.print("\n");
        }
      
      }

      void loop() { ; }

**Comment by WestfW** [comment] 2018-11-19 00:33
> it results in cs = 63. <- BAD :-(

pow() is a floating point function that returns a floating point value.  If you want it to print correctly as an integer, you need to ROUND the result instead of counting on the assignment to an integer value to do the right thing.  (assignment will do truncation, so that 63.999987 (or whatever) becomes 63.

In general, pow() is a poor choice for doing small integer exponents.

**Comment by matthijskooijman** [comment] 2018-11-19 10:16
@WestfW, good call. However, it's suprising that `pow()` behaves differently in both cases, depending on the source of the integer 3...

@digimeas, it would be interesting to do proper rounding, and print the unrounded value. E.g.

```
Serial.println(pow(8, cs));
```
and
```
cs = (uint16_t)(pow(8, cs) + 0.5);
```

**Comment by PaulStoffregen** [comment] 2018-11-19 14:20
I'm pretty sure the 2nd case is being computed at compile time.  The pow() function isn't even run on your AVR chip.  The compiler "knows" the answer to pow(8, cs) because "cs" is a constant known at compile time.  It's applying very crafty high-level optimization to replace pretty much all your code in the 2nd case with pre-computed constants.

To see the difference, try changing the definition of cs to use volatile, like this:

    volatile uint16_t cs = 3;         Serial.print("\t cs = B");  Serial.print(cs,BIN);  // B11

When using volatile, the compiler will force using real memory and the value can't be known at compile time.  Then you'll see both cases actually run on your AVR chip and both outputs should be identical.


Technically, this might be considered an avr-gcc bug.  Maybe?  The "pow" implementation avr-gcc "knows" is probably a double precision implementation that matches your PC's "pow" function, rather than an implementation of "pow" that faithfully implements the actual math performed on AVR.  The gcc toolchain is built using a library called GMP, which (as I understand anyway) is supposed to allow gcc as a cross compiler to faithfully perform arithmetic in the target system's way, even when compiling on a host which does it differently.  But it seems for AVR, this isn't done, or isn't done well.

**Comment by matthijskooijman** [comment] 2018-11-19 17:47
> I'm pretty sure the 2nd case is being computed at compile time.

Ah, that would explain the difference indeed. And that also means that the compiler is behaving as specified, and @digimeas should apply proper rounding to make things behave as expected. Since I believe there is no bug (at best a documentation bug), shall we close this issue?

**Comment by sandeepmistry** [comment] 2019-09-16 16:35
Closing as @matthijskooijman suggested above.

**Closed by sandeepmistry** 2019-09-16 16:35 UTC
