### ISSUE TITLE
Arduino IDE with multi screens  in MacOs

### ISSUE THREAD

**Issue by kako21** [arduino/Arduino#10029] opened 2020-04-11 13:30 UTC
Arduino IDE crashes when moving a window to another screen or when I close my MacBook with another screen on.
IDE 1.8.12  MacOS X Catalina 10.15.4
[Arduino crash.pdf](https://github.com/arduino/Arduino/files/4464670/Arduino.crash.pdf)

**Comment by per1234** [comment] 2020-04-11 13:57
Closing as duplicate of https://github.com/arduino/Arduino/issues/9764

The workaround is to use Arduino IDE 1.8.10, which you can download from this page:
https://www.arduino.cc/en/Main/OldSoftwareReleases#1.5.x

**Closed by per1234** 2020-04-11 13:57 UTC

**Comment by dirkx-reno-2020** [comment] 2020-04-30 12:16
Another work around is selecting the option 'Displays have separate Spaces' in System Preferences -> Mission Control.
