### ISSUE TITLE
IDE crashes because of negative font size

### ISSUE THREAD

**Issue by DarkPatrick** [arduino/Arduino#6798] opened 2017-10-05 08:20 UTC
Hi.

On Windows in Arduino IDE you can change font size by pressing control and scrolling up/down mouse wheel.
But if you accidentally set it too small, console will show a Java error message and IDE will never start again.

Debug log in cmd shows this:

java.lang.IllegalArgumentException: Font size must be > 0
        at org.fife.ui.rtextarea.RTextAreaBase.setFont(RTextAreaBase.java:986)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.setFont(RSyntaxTextArea.java:2510)
        at processing.app.EditorTab.applyPreferences(EditorTab.java:322)
        at processing.app.EditorTab.<init>(EditorTab.java:110)
        at processing.app.Editor.addTab(Editor.java:1672)
        at processing.app.Editor.createTabs(Editor.java:1645)
        at processing.app.Editor.handleOpenInternal(Editor.java:1944)
        at processing.app.Editor.<init>(Editor.java:340)
        at processing.app.Base.handleOpen(Base.java:833)
        at processing.app.Base.restoreSketches(Base.java:518)
        at processing.app.Base.<init>(Base.java:456)
        at processing.app.Base.main(Base.java:140)

**Comment by facchinm** [comment] 2017-10-05 08:22
The issue was already solved and IDE 1.8.5 (released) includes the fix. Closing as duplicate of https://github.com/arduino/Arduino/issues/6689

**Closed by facchinm** 2017-10-05 08:22 UTC
