### ISSUE TITLE
Arduino Micro - just plain keyboard

### ISSUE THREAD

**Issue by bitboy85** [arduino/Arduino#10463] opened 2020-07-03 15:09 UTC
I'm trying to use an arduino micro as a macro keyboard in use with a kvm switch. Sadly, my device is not detected as keyboard at all. I've tried the internal keyboard.h and files from HID-project.
Using it within windows it works fine.
My guess is that the reason is the extra com-port which is created by the arduino.
I found this similar issue https://github.com/arduino/Arduino/issues/6387
and i have three questions about this:
1. What excactly is the CDC for? Does it just reboot the device for uploading a new program? Because this could be done manually with the reset button. Or do you need an ISP to reprogram the micro if CDC is turned off?
2. Is the way described to turn CDC off still working? I'm using IDE version 1.8.11
3. Would another device work better?

**Comment by per1234** [comment] 2020-10-01 01:24
Closing as duplicate of https://github.com/arduino/Arduino/issues/6387. You're welcome to post on the [Arduino Forum](https://forum.arduino.cc/) for any further assistance with your project.

**Closed by per1234** 2020-10-01 01:24 UTC
Labels: Component: USB Device, Type: Duplicate, USB: CDC serial
