### ISSUE TITLE
Prevent negative font size

### ISSUE THREAD

**Issue by abundi** [arduino/Arduino#6786] opened 2017-10-02 12:19 UTC
Hi,

i accidentally zoomed out pretty far in the arduinoIDE (1.8.4 on Windows 10).
When i closed the IDE it saved the settings in the 
C:\Users\Andreas\AppData\Local\Arduino15\preferences.txt as 
```
editor.font=Monospaced,plain,-204
```
When i tried to start the IDE the next time ist just quit after the splash screen without any notice.
Starting the arduino_debug.exe showed me the following exception:
```
java.lang.IllegalArgumentException: Font size must be > 0
        at org.fife.ui.rtextarea.RTextAreaBase.setFont(RTextAreaBase.java:986)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.setFont(RSyntaxTextArea.java:2510)
        at processing.app.EditorTab.applyPreferences(EditorTab.java:322)
        at processing.app.EditorTab.<init>(EditorTab.java:110)
        at processing.app.Editor.addTab(Editor.java:1672)
        at processing.app.Editor.createTabs(Editor.java:1645)
        at processing.app.Editor.handleOpenInternal(Editor.java:1944)
        at processing.app.Editor.<init>(Editor.java:340)
        at processing.app.Base.handleOpen(Base.java:833)
        at processing.app.Base.restoreSketches(Base.java:518)
        at processing.app.Base.<init>(Base.java:456)
        at processing.app.Base.main(Base.java:140)
```

When I changed the font size in the preferences to a positive value the IDE started normally.

Please prevent the IDE from writing negative font sizes into the preferences or run a sanity check on startup to prevent the IDE from crashing. Maybe just use a default font size instead of throwing an exception.

**Comment by facchinm** [comment] 2017-10-02 12:23
The issue was already solved and IDE 1.8.5 (released today) includes the fix. Closing as duplicate of https://github.com/arduino/Arduino/issues/6689

**Closed by facchinm** 2017-10-02 12:23 UTC
