### ISSUE TITLE
Arduino 1.8.13 Java crash, Exception in thread "Thread-45"

### ISSUE THREAD

**Issue by trlafleur** [arduino/Arduino#10737] opened 2020-09-08 14:09 UTC
Getting this from time to time, closing IDE, and restarting fixes it for a short time... 

Mac OSX 10.14.6
Arduino 1.8.13

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

~~~
Exception in thread "Thread-45" java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1701)
	at java.security.Provider$Service.newInstance(Provider.java:1659)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:99)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.net.URL.openConnection(URL.java:1050)
	at cc.arduino.utils.network.HttpConnectionManager.makeConnection(HttpConnectionManager.java:130)
	at cc.arduino.utils.network.HttpConnectionManager.makeConnection(HttpConnectionManager.java:112)
	at processing.app.helpers.BoardCloudResolver.getBoardBy(BoardCloudResolver.java:61)
	at cc.arduino.packages.discoverers.serial.SerialDiscovery.forceRefresh(SerialDiscovery.java:183)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:171)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2055)
	at java.lang.Thread.run(Thread.java:748)` report.
~~~

**Comment by facchinm** [comment] 2020-09-21 07:53
Duplicate of #10685, fixed by #10747

**Closed by facchinm** 2020-09-21 07:53 UTC
