### ISSUE TITLE
Can't abort and restart an upload

### ISSUE THREAD

**Issue by teo1978** [arduino/Arduino#8044] opened 2018-09-30 16:20 UTC
Steps to reproduce:
- click the Upload Sketch button
- click it again

Expected:
When you click the upload button the first time, and it starts uploading, the upload button should switch to a "abort upload" button (suggested icon: an X). So by clicking it a second time, it should abort the upload, the button would revert to an upload button, and you could restart the upload by clicking a third time.
As a second-best option, it could be almost acceptable that there's no such thing as an "abort upload" button, but when you click the upload again while a sketch is already uploading, the current upload should be aborted before a new compile-upload cycle starts.

Observed:
When you click the upload button the second time, a new compile-and-upload cycle starts, while the previous upload still goes on (!!!!), leading to all sorts of pathetic errors and unpredictable, disastrous behavior.

**Comment by per1234** [comment] 2018-09-30 22:57
Closing as duplicate of https://github.com/arduino/Arduino/issues/5928

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-09-30 22:57 UTC
Labels: Type: Duplicate
