### ISSUE TITLE
Verbose don't work in Arduino CLI.

### ISSUE THREAD

**Issue by patrickelectric** [arduino/Arduino#5985] opened 2017-02-14 11:48 UTC
```
 $ arduino --board esp8266:esp8266:nodemcuv2:CpuFrequency=160 --verify --verbose smartmeter.ino        
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
$ echo $?
1
```

**Comment by facchinm** [comment] 2017-02-14 11:58
It works if the specified sketch exists. The issue is triggered by relative paths and was solved by https://github.com/arduino/Arduino/commit/61cccc01514f28c7c13e0d24d0842a4b75348c49 , available in nightly ATM

**Comment by patrickelectric** [comment] 2017-02-14 12:08
ty @facchinm, $PWD/smartmeter.ino solve the problem.

**Comment by facchinm** [comment] 2017-02-14 12:18
Closing as solved

**Closed by facchinm** 2017-02-14 12:18 UTC
