### ISSUE TITLE
Provide code completion inside editor

### ISSUE THREAD

**Issue by lmihalkovic** [arduino/Arduino#4089] opened 2015-11-05 13:13 UTC
The IDE currently does not provide any form of CTRL-SPACE code completion. The feature is sorely missing, especially for newbies like me. The feature should cover the following

* basic completion based on KWxxx and LITyyy available in the sketch libraries
* specific completion for different file types (keywords.txt, dependencies.txt, library.properties)
* a clean framework for future file types, ....

extended feature would cover more 'smartness' inside c/c++/h/hpp files, WITHOUT writing a full-blown parser

**Comment by lmihalkovic** [comment] 2015-11-05 13:16
Initial implementation working for keywords.properties

<img width="732" alt="arduino-2015-11-05 at 2 00 57 pm" src="https://cloud.githubusercontent.com/assets/1318077/10969281/8aa9aae4-83c7-11e5-8b1b-8ac19323709b.png">

<img width="588" alt="arduino-2015-11-05 at 2 01 16 pm" src="https://cloud.githubusercontent.com/assets/1318077/10969284/92c55f84-83c7-11e5-92b5-dd7d9a0d51ad.png">

<img width="481" alt="arduino-2015-11-05 at 2 01 37 pm" src="https://cloud.githubusercontent.com/assets/1318077/10969287/984aa8f6-83c7-11e5-8556-ddf9a068fd64.png">

At the moment I am not sure what LITERALXXX are for so the name strings are all wrong. The implementation is also missing the typical explanation window that opens when a keyword has been selected.

**Comment by lmihalkovic** [comment] 2015-11-05 13:40
Current completion for library's library.properties

<img width="794" alt="arduino-2015-11-05 at 2 38 31 pm" src="https://cloud.githubusercontent.com/assets/1318077/10969858/29392bf0-83cb-11e5-84bf-b57f4ff78f47.png">

**Comment by ffissore** [comment] 2015-11-05 13:56
Duplicate of #849 and #3484
@lmihalkovic it seems like you have running code already. Mind to show it? The smaller the PR, the easier it gets merged

**Comment by lmihalkovic** [comment] 2015-11-05 14:02
I seemed to have missed an episode... where can I find a keywords.txt for the code platform code?

**Closed** 2015-11-05 16:04 UTC
Labels: Type: Duplicate

**Comment by lmihalkovic** [comment] 2015-11-05 16:38
@ffissore I read #3484... quite the PR. IMHO integrating it into the core code as it is basicaly equates giving up on a lot things that are currently easy to do and signing up for a lot of maintenance headaches. The fact that I think it is does not make it so, but the fact that this PR requires so many changes to editor and textarea should itself be a smell if poor API design. 

I just find truly unfortunate that a lot of good existing design might be sacrificed.

**Comment by lmihalkovic** [comment] 2016-04-27 23:40
Interestingly enough, the weird highlighting in the screenshots was caused by some of the issues I was alluding to in my last comment (code in the _wrong_ place).
