### ISSUE TITLE
IDE Serial Monitor does not process "\r"

### ISSUE THREAD

**Issue by dg3al** [arduino/Arduino#3739] opened 2015-08-27 19:55 UTC
When I send an CR ("\r") at the end of a line to overwrite the existing line, the serial monitor ignores the CR and continues writing. For many applications an overwrite can be usefull.

**Comment by Chris--A** [comment] 2015-08-28 02:04
This is a duplicate of a '**wont fix**' issue.

Check here for more info: https://github.com/arduino/Arduino/issues/3654

BTW, a great no-install serial monitor is called HTerm. It is by far the best way to do complex things with serial. http://www.der-hammer.info/terminal/

**Closed** 2015-08-28 06:40 UTC
Labels: Type: Wontfix
