### ISSUE TITLE
Change board type and com port while compiling - did i bricked my devie?

### ISSUE THREAD

**Issue by bithost** [arduino/Arduino#7472] opened 2018-04-15 11:15 UTC
Hello, 
  I just got my first Arduino Pro micro. Downloaded Arduino IDE. Opened it and forgot to change board type and com port to match my device. 
 I pressed upload to test default code, when it started compiling, i noticed what board type and com port is wrong, so i changed to match my board. Finished compiling and uploaded code. And now only green light is on.
   So the first question:
1. Is my Arduino pro micro bricked?:)
2. Why Arduino IDE allowed me to change board type and com port when it was compiling?

Thanks, 
  Tadas

**Comment by per1234** [comment] 2018-04-15 11:36
>Is my Arduino pro micro bricked?:)

Only temporarily. Do this:

1. Connect a jumper wire to the "RST" pin on your Pro Micro.
2. File > Preferences > Show verbose output during: > upload (check) > OK
3. Sketch > Upload
4. Watch the black console window at the bottom of the Arduino IDE window. As soon as you start seeing something like: `PORTS {COM1, COM3, COM4, } / {COM1, COM3, COM4, } => {}` momentarily connect the "RST" pin to the "GND" pin.

The upload should finish successfully and you should be able to upload normally from then on.

>Why Arduino IDE allowed me to change board type and com port when it was compiling?

Regarding board type, it's a very good question and I'd like to see this fixed. In fact a proposal for a fix has already been made but not merged: https://github.com/arduino/Arduino/pull/6106. However, there is already an issue report for this (https://github.com/arduino/Arduino/issues/6035) so I'm closing this issue as duplicate.

Regarding port change, I find that to be very useful since I often forget to update the Port menu selection but am able to get it set correctly before the compilation finishes and I don't see any possible problems that could be caused by this.

**Closed by per1234** 2018-04-15 11:36 UTC
