### ISSUE TITLE
option to reload /dev/tty* entries

### ISSUE THREAD

**Issue by petaflot** [arduino/Arduino#11328] opened 2021-03-05 17:15 UTC
in certain conditions the available "Serial port" entries are out-of date ; it is therefore required to completely quit and restart the IDE so that the list is up-to-date

suggestion : add a "reload available serial ports" entry to to the "Tools > Port" submenu.

**Comment by per1234** [comment] 2021-03-05 18:09
Hi @petaflot. Thanks for your report. Have you tried Arduino IDE 2.0.0-beta.3 to see if this issue still occurs? If not, please try it out and then let us know what you found. You can download it here:
https://www.arduino.cc/en/software#experimental-software

**Comment by petaflot** [comment] 2021-03-05 21:05
nope, haven't tried it yet. have you tried making a dev-embedded/arduino-9999 ebuild (gentoo)?

**Comment by matthijskooijman** [comment] 2021-03-06 18:56
> in certain conditions the available "Serial port" entries are out-of date ; it is therefore required to completely quit and restart the IDE so that the list is up-to-date

That actually surprises me, since AFAIR the IDE 1.8.x code reloads the serial port list every time the tools (or ports, don't remember exactly) menu is reloaded.

You suggest you are using the Gentoo-build, I wonder if they changes something in this area. In addition to trying this with 2.x, you could also try downloading the 1.8.x zipfile and try that (no installation required), to check if this is maybe a problem in the Gentoo version only.

**Comment by petaflot** [comment] 2021-03-06 20:45
only a single patch is applied:

-    loadLib(new File(Base.getContentFile("lib"), System.mapLibraryName("astylej")));
+    System.loadLibrary("astylej");

in arduino-core/src/processing/app/Platform.java and app/src/cc/arduino/packages/formatter/AStyleInterface.java

comment in ebuild mentions:
# We need to load system astyle/listserialportsc instead of bundled ones.

**Comment by per1234** [comment] 2021-03-27 15:43
Closing as off topic for this repository. Arduino only supports the official builds of the Arduino IDE. If you are able to reproduce the issue with the official Arduino IDE then please comment here and I'll reopen.

**Closed by per1234** 2021-03-27 15:43 UTC
Labels: Component: IDE, Waiting for feedback, feature request, libListSerial
