### ISSUE TITLE
Add examples for hardware folders

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3857] opened 2015-09-24 14:41 UTC
It would be nice it hardware folders also could contain example folder which are recognized by the IDE. This would also get rid of the warning errors:
`[exec] Could not find boards.txt in /Arduino/sketchbook/hardware/HoodLoader2/examples. Is it pre-1.5?`

**Comment by ffissore** [comment] 2015-09-24 14:59
That warning is about an invalid folder structure, indeed pre 1.5. It should be hardare/Hoodloader2/avr

**Comment by NicoHood** [comment] 2015-09-24 15:09
But where to put the examples? Inside avr?

**Comment by ffissore** [comment] 2015-09-25 08:56
ATM you can't deliver examples for cores. You can only add them to libraries, whether they are bundled with a core or not

**Comment by NicoHood** [comment] 2015-09-25 11:08
Exactly. And I want to add core examples, since my HoodLoader2 has some extra features/explanation/examples to show what is different.
It would be nice to at least avoid the warning first and then add a proper IDE menu when you have time for this.

**Comment by ffissore** [comment] 2015-09-25 12:33
In order to avoid the warning, move that examples folder away. It won't be the right place anyway, since at that level you specify the arch

**Comment by NicoHood** [comment] 2015-09-28 14:52
A behavior like this would be appreciated (without workaround via library):
https://github.com/NicoHood/HoodLoader2/pull/23

**Comment by sandeepmistry** [comment] 2016-03-09 18:03
Marking this a duplicate of #3297.

**Closed by sandeepmistry** 2016-03-09 18:03 UTC
Labels: Component: IDE, Component: IDE user interface, Type: Duplicate, Type: Improvement
