### ISSUE TITLE
Arduino IDE does not take into account Windows desktop DPI settings.

### ISSUE THREAD

**Issue by juj** [arduino/Arduino#3030] opened 2015-04-24 13:05 UTC
On Windows when running on a display with desktop DPI scaling enabled, i.e. Control Panel\Appearance and Personalization\Display set to something larger than 100%, Arduino IDE doesn't notice this but renders font in unchanged pixel sizes, and the text is very small as a result.

See a screenshot below as an example of where e.g. Notepad scales font size according to DPI settings, but Arduino IDE text is very small in comparison.

![arduino_ide_dpi](https://cloud.githubusercontent.com/assets/225351/7319087/45d6c3d6-ea9b-11e4-93a1-8d340036f16a.png)

The toolbar at the top (File, Edit, Sketch, Tools, Help) is correctly scaled according to DPI settings, but the code text and the bottom status bar "Arduino Uno on COM1" is not.

To resolve this, it would be nice if the IDE would scale all the rendered UI components according to the DPI settings that have been set to Windows desktop. Additionally, it would be cool to have a custom zoom in/out option specifically for the text in the IDE, e.g. for classroom presentation purposes. (or perhaps this already exists, but I did not find?)

Tested on a Macbook Pro with Retina 2880x1800 display running in Windows 8.1 in Bootcamp.

**Comment by ffissore** [comment] 2015-04-24 13:11
Duplicate of #2532. A proposed fix is available at #2776
Please test IDE downloadable from #2776 and your feedback

**Closed by ffissore** 2015-04-24 13:11 UTC
