### ISSUE TITLE
IDE 1.6.5 improperly sets Arduino/libraries file to read-only on Windows

### ISSUE THREAD

**Issue by logos-electromechanical** [arduino/Arduino#3628] opened 2015-08-05 00:02 UTC
IDE version: 1.6.5 r2
OS: Windows 8.1

I have a test directory inside a library I am working on inside the Arduino/libraries folder, and it contains a sketch used for testing the library. Every time I open up the sketch with the IDE, the IDE sets the entire Arduino/libraries directory to read-only, and I have to save it to the sketchbook. This interrupts my source control workflow and is generally a pain.

**Comment by per1234** [comment] 2015-08-05 02:39
You might be interested in adding your input on the proposals for solving this issue discussed in #3512.

**Comment by ffissore** [comment] 2015-08-05 06:46
Closing as duplicate of #3512

**Closed by ffissore** 2015-08-05 06:46 UTC
