### ISSUE TITLE
[Library Manager]Please add Grove Ultrasonic Ranger v1.0.1 to Library Manager.               

### ISSUE THREAD

**Issue by linux-downey** [arduino/Arduino#7445] opened 2018-04-09 11:44 UTC
Github:https://github.com/Seeed-Studio/Grove_Ultrasonic_Ranger
Release:https://github.com/Seeed-Studio/Grove_Ultrasonic_Ranger/releases/tag/v1.0.1
Thank you very much！！

**Comment by per1234** [comment] 2018-04-09 11:53
It's not necessary to create a new issue for each release. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. After that the Library Manager indexer job will automatically pick up all new releases you create in the library so no further action will be required.

Closing as duplicate of https://github.com/arduino/Arduino/issues/7441

**Closed by per1234** 2018-04-09 11:53 UTC
