### ISSUE TITLE
Arduino fails to launch on a Mac OS 10.15

### ISSUE THREAD

**Issue by PJOssenbruggen** [arduino/Arduino#9460] opened 2019-11-24 13:01 UTC
I found a post that states an _Arduino will successfully open by right clicking_. In my case, it initializes, starts and immediately closes. 

I am suspicious. The Arduino app did not load properly. I got the following message. I found that in System Prefences Security & Preference would not open. I fixed this "malicious software" problem by removing a cache associated with Security & Preference and rebooting my Mac in a safe mode. Pressing the shift key when booting. After doing this, I was sort of able to open Arduino. See paragraph one above.

Apparently, I need to do something more than this.

Help will be appreciated.

![Screen Shot 2019-11-24 at 6 54 24 AM](https://user-images.githubusercontent.com/11671044/69494883-bdc26500-0e8e-11ea-8737-4cfb0bda74f6.png)

**Comment by EvgenV** [comment] 2019-11-24 19:30
Hi. 
I have had  the same issue. Try to open System Preferences -> Security and Privacy and press button Open Anyway. It helped me
<img width="678" alt="Screenshot 2019-11-24 at 21 28 21" src="https://user-images.githubusercontent.com/582826/69500189-a4a6cc00-0f01-11ea-9605-d507c279eb5c.png">

**Comment by per1234** [comment] 2019-11-24 20:21
Closing as duplicate of https://github.com/arduino/Arduino/issues/9314

**Closed by per1234** 2019-11-24 20:21 UTC

**Comment by PJOssenbruggen** [comment] 2019-11-25 17:33
Can Arduino run on Mac OSX 10.15 Catalina?
