### ISSUE TITLE
LTC®2633 miniDAC library

### ISSUE THREAD

**Issue by SandeepanSengupta** [arduino/Arduino#7070] opened 2018-01-01 19:38 UTC
[**LTC®2633 miniDAC Library**](https://github.com/TamojitSaha/LTC2633) is designed to operate [**Arduino miniDAC Module**](https://github.com/SandeepanSengupta/miniDAC), a unipolar digital to analog converter module built arround [LTC®2633](http://www.linear.com/product/LTC2633).
**LTC®2633** is a family of dual 12-, 10-, and 8-bit voltage-output DACs with an integrated, high accuracy, low drift reference in an 8-lead TSOT-23 package.

**Comment by per1234** [comment] 2018-01-01 21:58
Closing as either invalid or duplicate of #7063.

**Closed by per1234** 2018-01-01 21:58 UTC
