### ISSUE TITLE
IDE State Not Saved

### ISSUE THREAD

**Issue by OldSkiBum** [arduino/Arduino#8598] opened 2019-03-03 20:36 UTC
Past releases of the IDE used to save the current sketch name and window position/size when closed via the "X" in the upper right corner.
Version 1.8.8 now does NOT.  I have to drop down the "File" menu and click "Quit" to do this.

**Comment by per1234** [comment] 2019-03-03 22:35
Closing as duplicate of https://github.com/arduino/Arduino/issues/8337

**Closed by per1234** 2019-03-03 22:35 UTC
Labels: Type: Duplicate
