### ISSUE TITLE
Assigning a board to a sketch

### ISSUE THREAD

**Issue by Avamander** [arduino/Arduino#3228] opened 2015-05-25 11:13 UTC
Could someone please make it so that Arduino IDE automatically changes the board (and board model) based on the sketch that's opened. 

Having three-four different boards + board models, it is kinda tedious to select the board every time I open the sketch so something like "//BOARD=mega" that is added to the sketch and IDE automatically changes the board type would be really nice.

**Comment by dmjlambert** [comment] 2015-06-12 19:39
I love this idea.  During saving of the sketch, if the IDE remembered the board, processor, port, and any other boards.txt menu selections the user made on the Tools menu when working on the sketch, and then re-loaded those selections when opening the sketch, that would be fantastic.  I imagine this may be a bit difficult to code since you can have multiple sketches open at one time.  The code would have to take into consideration which window is in the foreground and active.  Your idea of line in the sketch to indicate the board is kind of an IDE directive and interesting.

**Comment by Chris--A** [comment] 2015-06-13 09:09
This is a good idea, but shouldn't be limited to just the board/port/etc

I personally would like a platform.txt style approach for each sketch (optional file). Comments in the code can be removed by unknowing users.

Sometimes I want to test with C++11 instead of C++98 or use some of the many other compiler/linker options, which cannot be changed without hard restarting the IDE.

**Comment by ffissore** [comment] 2015-09-17 14:11
Duplicate of #1481. Wontfix. Arduino Create will provide a similar feature

**Closed by ffissore** 2015-09-17 14:11 UTC
Labels: Component: IDE user interface, Type: Improvement

**Comment by Avamander** [comment] 2016-03-13 19:08
Would it be possible that this would be reconsidered at least partially?

**Comment by romandubrov** [comment] 2017-04-12 17:56
Bump!
I'd also like to have per-project settings in Arduino IDE because I'm completely tired with switching between my 4 boards. I like the online idea of Create but I need this feature locally because I store my projects and libs on Bitbucket. 
If you guys feel uncomfortable with storing settings in project.ino file - may be you'll like an idea of having separate optional file like project.settings?

**Comment by JesseBusman** [comment] 2019-10-22 20:50
To help anyone with this problem: If you start two arduino processes (by double-clicking your arduino icon twice) instead of two windows (by opening another file from an existing window) you can select different boards in the two different windows. (only if they run under separate procesess!)

It would still be awesome to not need this workaround and have the board selection saved in the .ino :)

**Comment by dsyleixa** [comment] 2020-05-09 13:52
IMO the most simple way would be to hardcode-config the targeted board type by configuration in Sketch (e.g. #pragma config...) such as
#pragma config board="Nano"
#pragma config board="NODE_MCU 1.0"
#pragma config board="Adafruit Feather ESP32"
