### ISSUE TITLE
feature request: hardcode-config board type by configuration in Sketch (e.g. #pragma config...)

### ISSUE THREAD

**Issue by dsyleixa** [arduino/Arduino#10175] opened 2020-05-09 09:11 UTC
feature request: 
as some programs are designed just for special arbitrary boards (e.g., Nano,  SAMD, ESP) it would be helpful to hardcode-config the targeted board type  by configuration in Sketch (e.g. #pragma config...) such as
#pragma config board="Nano"
#pragma config board="NODE_MCU 1.0"
#pragma config board="Adafruit Feather ESP32"

**Comment by per1234** [comment] 2020-05-09 12:07
Closing as duplicate of https://github.com/arduino/Arduino/issues/1481

**Closed by per1234** 2020-05-09 12:07 UTC
