### ISSUE TITLE
Please add Multiple serial port debugging window

### ISSUE THREAD

**Issue by CHN-STUDENT** [arduino/Arduino#8981] opened 2019-06-15 12:23 UTC
I open two example code window and select two device, but i still can only open a serial port debugging window. I hope it can open two program instead of a program with multi thread.
See here:https://github.com/arduino/Arduino/issues/6490
It may be useful for our programmer! Thanks!

**Comment by per1234** [comment] 2019-06-15 22:04
Closing as duplicate of https://github.com/arduino/Arduino/issues/6490.

@CHN-STUDENT we only need one issue report per topic. Having multiple issues only clutters up the issue tracker and may make it more difficult to find all the relevant information on the issue. If you want to express your support for a proposal, you can click the smiley face icon at the top right corner and give it a "thumbs up".

**Closed by per1234** 2019-06-15 22:04 UTC
Labels: Type: Duplicate
