### ISSUE TITLE
Library to allow Arduino to communicate with J1850-PWM encoding

### ISSUE THREAD

**Issue by VittorioEsposito** [arduino/Arduino#6511] opened 2017-07-16 05:19 UTC
Arduino library which allow to communicate on J1850-PWM mode: https://github.com/VittorioEsposito/J1850-Arduino-Transceiver-Library

**Comment by per1234** [comment] 2017-07-16 05:33
Duplicate of https://github.com/arduino/Arduino/issues/6488

Please stop posting your library over and over again. You only need to do it once. The Arduino team will get it added to the Library Manager index as soon as possible. Until that time please be patient and don't post any more duplicate issues.

**Closed by per1234** 2017-07-16 05:33 UTC
Labels: Type: Duplicate
