### ISSUE TITLE
figures are not loading on doc web page

### ISSUE THREAD

**Issue by ArtNumerique** [arduino/Arduino#8708] opened 2019-03-27 11:11 UTC
this page is no longer loading the figures:
https://www.arduino.cc/en/Tutorial/ArduinoToBreadboard
the links appear to be broken.
best regards

**Comment by per1234** [comment] 2019-03-27 11:13
Closing as duplicate of https://github.com/arduino/Arduino/issues/8706

**Closed by per1234** 2019-03-27 11:13 UTC
Labels: Type: Duplicate
