### ISSUE TITLE
Scaling issue on high DPI displays (4k)

### ISSUE THREAD

**Issue by Double-E** [arduino/Arduino#3813] opened 2015-09-17 18:27 UTC
While trying to use arduino software on a 4k 15.6" laptop screen, the buttons across the top (verify, upload, new, etc.) are ridiculously small. Any chance that they can be made larger so that they are easier to click on and actually possible to read on a 4k display? Changing the resolution of my screen to 1080p does not solve the issue either.

**Comment by PaulStoffregen** [comment] 2015-09-17 18:39
duplicate of #2776

**Closed** 2015-09-18 06:54 UTC
Labels: Type: Duplicate

**Comment by Juju89** [comment] 2015-12-21 22:59
:+1:  gsynek, i have the same problem. Other people have the same problem : https://forum.arduino.cc/index.php?topic=263838.0
