### ISSUE TITLE
1.6.3 Explicit use of RJMP/RCALL can cause "relocation truncated to fit: R_AVR_13_PCREL" linker error

### ISSUE THREAD

**Issue by ryanneve** [arduino/Arduino#2895] opened 2015-04-03 17:31 UTC
Details and patch are here:
https://savannah.nongnu.org/bugs/?33698#cc
I have two projects which will not compile due to this issue.

**Comment by cmaglie** [comment] 2015-04-07 18:30
Closing as duplicate of #2752. Please do not open multiple issues for the same problem.

**Closed by cmaglie** 2015-04-07 18:30 UTC
