### ISSUE TITLE
software Programming  bug

### ISSUE THREAD

**Issue by cwalger** [arduino/Arduino#3698] opened 2015-08-18 18:20 UTC
I am programming blank atmega328p's.

If i use the IDE and a programmer to burn a sketch, the code runs at 1/16th the speed it should. 

If i push 'burn bootloader' in the IDE, then program the sketch with an FTDI, the code runs at the right speed. 

If the then go back and use the IDE/programmer to burn the sketch, the code runs at the right speed.

**Comment by matthijskooijman** [comment] 2015-08-18 18:33
The problem is that the fuse settings are not yet configured. Upload using programmer does not do this, but burn bootloader does set the fuses.

This is essentially a duplicate of #1514, so I'm closing it as such.

**Closed** 2015-08-19 08:31 UTC
Labels: Type: Duplicate
