### ISSUE TITLE
PROGMEM Reference documentation needs updating due to GCC changes

### ISSUE THREAD

**Issue by pfeerick** [arduino/Arduino#2647] opened 2015-02-16 03:17 UTC
Was just putting together a new project, and the demo code used PROGMEM to save some SRAM space. It declared an array in memory for a image for the OLED display with the following initialiser...

    prog_uchar welcomeimage[] PROGMEM = {

However, that doesn't work with 1.6.0 when compiled for a Arduino Pro Mini /w Atmega328, and I would get the following error:

    GraphicLCDAdapaterDemo.ino:15:1: error: 'prog_uchar' does not name a type

After some prodding around, either of the following lines do work correctly:

    const PROGMEM uint8_t welcomeimage[] = {
    const uint8_t welcomeimage[] PROGMEM = {

I saw a reference in the changelog at 1.5.7 Beta to "* avr: Fixed PROGMEM statements to be compatible with newer avr gcc (Scott Howard)"  - and after finding the commit 33b1e7c546dabfc014d7e3c6cb86c2bd60479459 I realised it was fixing the symptoms not the problem. 

Can somebody update the reference page @ http://arduino.cc/en/Reference/PROGMEM (and thus also the bundled documentation!)  as it now clear that the prog_char and prog_uchar (and probably none of the other) variables no longer work. And variables now need to be declared const also. 

Just using `#define  __PROG_TYPES_COMPAT__`  as suggested in `<avr/pgmspace.h>` will not work without also adding the const parameter. Plus this not really a fix as these typedefs are all deprecated.

**Comment by cmaglie** [comment] 2015-02-17 13:49
Duplicate of #1536

**Closed by cmaglie** 2015-02-17 13:49 UTC
Labels: Component: Documentation, Type: Duplicate
