### ISSUE TITLE
Button example won't compile

### ISSUE THREAD

**Issue by Hansgur** [arduino/Arduino#3090] opened 2015-05-06 13:23 UTC
The provided example > digital > Button; won't compile, yet if one inserts just "Serial.begin(9600);" in setup it works fine. (as in "DigitalInputPullup").

What could the reason be? Bug?

**Comment by mschlenker** [comment] 2015-05-06 13:31
I tried under Linux/x64 with "Arduino AVR boards" in version 1.6.3, 1.6.5 and 1.6.6. Compiles everywhere. Which version do you use? Which platform?

**Comment by matthijskooijman** [comment] 2015-05-06 13:31
Compiles fine here as well. What error are you getting? What board do you have selected?

**Comment by Hansgur** [comment] 2015-05-06 13:35
Hi. Arduino Uno R3. 

>>Arduino: 1.7.2 (Windows XP), Board: "Arduino Uno"

collect2.exe: error: ld returned 5 exit status

Error compiling.
<<
  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by mschlenker** [comment] 2015-05-06 13:39
Oh. Arduino 1.7.2 is over there: https://github.com/arduino-org/Arduino/issues

A long story:
http://blog.arduino.cc/2015/03/20/dear-arduino-community/
http://hackaday.com/2015/03/12/arduino-v-arduino-part-ii/

**Comment by Hansgur** [comment] 2015-05-06 13:41
Thanks I'll have a look what they say.

**Comment by mschlenker** [comment] 2015-05-06 14:01
Please take a look at the issue #2989 - this probably might happen with the .cc version 1.6.3 as well. XP is deprecated since more than one year now, so please do not expect anyone to be very eager to fix this.

**Comment by Hansgur** [comment] 2015-05-06 14:10
Hehe point taken  (XP)

**Comment by mschlenker** [comment] 2015-05-07 21:01
@ffissore Please merge and close #2989 and #3090

**Comment by ffissore** [comment] 2015-05-08 07:16
Sorry @mschlenker I'm not sure I caught that: what should I merge?

**Comment by cmaglie** [comment] 2015-05-26 15:31
Duplicate of #2989

**Closed by cmaglie** 2015-05-26 15:31 UTC
Labels: OS: Windows, Type: Duplicate
