### ISSUE TITLE
Add an option to unlink IDE's windows from each other

### ISSUE THREAD

**Issue by Avamander** [arduino/Arduino#3499] opened 2015-07-10 11:09 UTC
I would really like if every sketch had a "Unlink" button so that when the sketchs are unlinked they have their own prgrammer, board and port settings.

**Comment by ffissore** [comment] 2015-07-10 12:02
Duplicate of #3228

**Closed by ffissore** 2015-07-10 12:02 UTC

**Comment by Avamander** [comment] 2016-03-13 19:01
@ffissore
