### ISSUE TITLE
IDE doesn't start on Windows 7 Home Premium 64bit [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1048] opened 2012-11-15 19:03 UTC
This is [Issue 1048](http://code.google.com/p/arduino/issues/detail?id=1048) moved from a Google Code project.
Added by 2012-09-23T19:55:31.000Z by [vkn...@gmail.com](http://code.google.com/u/102710172685908038264/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1.After start the IDE the splash screen apear. After one minute (the pc is very slow) apears the Error "An error occured while starting the appliction" "Lauch4j"
**2.**
**3.**

**What is the expected output? What do you see instead?**

What version of the Arduino software are you using? 1.0.1
On what operating system ? Windows 7 64bit Home Premium
Which Arduino board are you using? Mini pro (working with xp)

**Please provide any additional information below.**

**Comment by ffissore** [comment] 2015-05-26 14:30
Closing because I can't reproduce the issue with current 1.6.4

**Closed by ffissore** 2015-05-26 14:30 UTC
Labels: Component: IDE, OS: Windows
