### ISSUE TITLE
Deleted header files remain includable

### ISSUE THREAD

**Issue by fredrikeldh** [arduino/Arduino#2072] opened 2014-05-13 10:33 UTC
Tested with 1.0.5 on Windows.

To reproduce:
- Have a sketch.
- Create a file, let's call it "foo.h", in the sketch's directory.
- Add `#include "foo.h"` to the sketch.
- Compile the sketch.
- Delete the file "foo.h".
- Compile the sketch again. If the bug is present, there is no error message despite the header file being deleted.

This happens because the Arduino IDE copies all source files to a temporary directory, reuses that directory and does not clear it of files that shouldn't be there.

On Windows 7, the temporary directory may be called something like "c:\Users<yourName>\AppData\Local\Temp\build4632717550972951918.tmp\".

**Comment by per1234** [comment] 2017-07-03 08:58
I find that if I use the Arduino IDE 1.8.3 to delete the tab via the tab menu it works correctly. This may not have been the case at the time of the issue report as indicated by https://github.com/arduino/Arduino/issues/4233 and https://github.com/arduino/Arduino/issues/1161). It is only if you delete the tab from outside the IDE that this issue occurs now and that's not really unexpected behavior since the tab is still shown in the Arduino IDE even though the file was deleted from the disk.

Where I find more problematic behavior is this issue as it occurs when an included file is deleted from a subfolder of the sketch folder (e.g. `#include "src/foo/foo.h"). In this case there is no mechanism to delete the file from within the IDE so there is no alternative to deleting files from outside the IDE. I suppose that is more appropriate to discuss in the [arduino-builder repository](https://github.com/arduino/arduino-builder) now.

**Comment by per1234** [comment] 2023-01-15 00:46
Closing as resolved. I can still reproduce the fault via the modified procedure described in [my previous reply](https://github.com/arduino/Arduino/issues/2072#issuecomment-312589501) when using Arduino IDE 1.8.3, but I cannot reproduce it via that procedure when using Arduino IDE 1.8.19 or Arduino IDE 2.x.

I didn't bisect the resolution so I don't know exactly where the bug was fixed.

**Closed by per1234** 2023-01-15 00:46 UTC
Labels: Type: Bug, Component: Compilation
