### ISSUE TITLE
Auto Complete Implimentation

### ISSUE THREAD

**Issue by kingofl337** [arduino/Arduino#3139] opened 2015-05-14 15:52 UTC
I'm just bringing this to attention again. What about adding auto complete to the IDE? It would be a huge improvement.

Someone had already done it, can't you roll it in?

https://www.youtube.com/watch?v=jSRuVy_fcVM

**Comment by ffissore** [comment] 2015-05-15 14:05
Please consider joining @ricardojlrufino in his effort to add autocomplete to the IDE. The new editor is ready and we can now use its autocomplete feature. Closing as duplicate of #849

**Closed by ffissore** 2015-05-15 14:05 UTC
Labels: Component: IDE, Type: Improvement
