### ISSUE TITLE
Port menu greyed out on Linux

### ISSUE THREAD

**Issue by Pitel** [arduino/Arduino#2853] opened 2015-03-30 20:45 UTC
Using latest nightly. It works ok in 1.6.1. Ubuntu 14.10 64bit.

**Comment by aveekbh** [comment] 2015-03-31 16:08
Hello Pitel

It worked for me after two steps:
1. Moved my ~/.arduino15 directory (to get the fix for #2849 to work).
2. Selected Yun as my board, then Uno again (the actual board that I tested this on). Then, the port menu showed up.

**Comment by Pitel** [comment] 2015-03-31 17:15
Just downloaded latest nightly, deleted `~/.arduino15`, and it works.

**Comment by Pitel** [comment] 2015-04-02 15:25
It still happens occasionaly, and it's pretty annoying. It starts to working after your workaround, but it's still just a workaround.

**Comment by ffissore** [comment] 2015-04-02 15:56
Can you list the ports you see when that happens? (in order to understand if it's a mix of serial and network or only one of the two)

**Comment by Pitel** [comment] 2015-04-02 18:38
Well, when it happens I don't see any because the whole *Ports* menu is greyed out. But it starts working, I see these items:
* `/dev/ttyACM0`
* `/dev/ttyS`

The `/dev/ttyACM0` is the one that works.

**Comment by facchinm** [comment] 2015-04-14 08:53
Probably a duplicate of #2892 , should be fixed in nightly builds.
Reopen if needed

**Closed by facchinm** 2015-04-14 08:53 UTC
