### ISSUE TITLE
Allow pinning the Find window inside the Arduino window

### ISSUE THREAD

**Issue by PickyBiker** [arduino/Arduino#4405] opened 2016-01-08 16:45 UTC
Whenever "Find" is used and the found data is modified, the Arduino window covers up the find window. 

Please allow the Find window to remain on top, or pinning the Find window inside the Arduino window.

This would allow multiple find/modify sequences to be far easier.

**Comment by lmihalkovic** [comment] 2016-01-27 10:40
ended up doing #4488. would that match your needs better?

**Comment by per1234** [comment] 2017-07-04 11:58
This is a duplicate of https://github.com/arduino/Arduino/issues/6408. Even though this one came first, the other is more informative so I'm closing this one.

**Closed by per1234** 2017-07-04 11:58 UTC
Labels: Component: IDE user interface, Type: Improvement
