### ISSUE TITLE
burning bootloader for 328PB

### ISSUE THREAD

**Issue by javicho21** [arduino/Arduino#6447] opened 2017-07-02 04:19 UTC
i'm jumping through hoops to burn the bootloader for my 328PB and still i'm unsuccessful. can we include the necessary files so that this is a recognized MCU and I don't have to hack avrdude?

**Comment by per1234** [comment] 2017-07-02 06:57
Duplicate of https://github.com/arduino/toolchain-avr/issues/36

In the future please [search for previous open and closed issues](https://github.com/arduino/Arduino/issues?&q=) before submitting an issue to avoid creating duplicate reports.

If you haven't done so already, feel free to post on the Arduino Forum and we'll see if we can help you get your ATmega328PB working over there.
https://forum.arduino.cc/index.php?board=67.0

**Closed by per1234** 2017-07-02 06:57 UTC
Labels: Type: Duplicate
