### ISSUE TITLE
serial.find stops serial.read() to work [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1044] opened 2012-11-15 19:02 UTC
This is [Issue 1044](http://code.google.com/p/arduino/issues/detail?id=1044) moved from a Google Code project.
Added by 2012-09-17T09:27:26.000Z by [x1angw...@gmail.com](http://code.google.com/u/101906961841219629081/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Core

### Original description

**What steps will reproduce the problem?**
1. Using serial.read() to store different inputs in a unsigned char array as soon as serial.available()>0 leads to misreads (elements in the array bigger than [0]  still filled with 0). As I found out it takes some time until all elements of the input are available (serial.available() returns 1 at the beginning, some Milliseconds later 3 ...). Therefore I would like to use serial.find to assure that all the elements of the input are stored in the buffer.

2.Define a while loop or if clause with serial.find(a char determing the end of the serial input) to avoid the misreads by waiting until all elements are in the buffer

3. In the while loop: unsigned char array array[8]=serial.read();

**What is the expected output? What do you see instead?**
Expected: array filled with the values send via HTerm
Instead:First element in the unsigned array is =255, every other is still 0

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

Using 1.01 on Windows 7 (32bit) and Arduino Uno

**Please provide any additional information below.**

Thank you in advance for your feedback!

**Comment by joseangeljimenez** [comment] 2015-12-10 16:35
Can, somebody, please, try to decipher this issue? I am not able to understand exactly what the problem is.

**Comment by PaulStoffregen** [comment] 2015-12-10 16:41
To have any realistic chance of someone investigating this problem, you really must provide a complete program that can be copied into Arduino and uploaded to a board to reproduce the problem.

The exact string to send from the serial monitor would also be needed, as well as any other steps.

Imagine if you're an Arduino developer.  Are you could to try to cobble together a test program from the imprecise description above?  And figure out the specific input?  Maybe.  But it's probably too much trouble and unlikely to work (recreate the problem).  Bug reports like this, which don't provide a ready-to-run test case almost never get investigated.

**Comment by joseangeljimenez** [comment] 2015-12-10 16:45
@PaulStoffregen I am not the original poster. I don't have the issue. I am reviewing old open issues.

My question is: does anybody understand the OP's description of the issue? If not, why is this issue still open after +3 years?

**Comment by PaulStoffregen** [comment] 2015-12-10 16:52
I don't understand the OP's description.  But admittedly, I don't put much effort into reading issues that describe code without providing that code.

**Comment by matthijskooijman** [comment] 2015-12-10 21:28
I went over it as well, and it actually looks a bit like a problem in the poster's code, or perhaps a very poorly worded feature request. In the original Google Code issue, David Mellis already wrote:

> This sounds like it might be a bug in your code rather than in Serial.find(). Can you post your whole sketch? I'd also suggest posting it in the Arduino forum as you might get more help there.

With no reply.

I'm closing this issue, @joseangeljimenez, thanks for pointing it out.

**Closed by matthijskooijman** 2015-12-10 21:28 UTC
