### ISSUE TITLE
Separate the console outputs

### ISSUE THREAD

**Issue by lmihalkovic** [arduino/Arduino#4216] opened 2015-11-25 10:33 UTC
When multiple sketches are open, the compilation results 'follow' the active editor around. Each editor should have its own outputs that do not get mixed with the ouput from all other open sketches.

**Comment by ffissore** [comment] 2015-11-25 10:59
Duplicate of #2680

**Closed by ffissore** 2015-11-25 10:59 UTC

**Comment by lmihalkovic** [comment] 2015-11-26 12:57
Done
