### ISSUE TITLE
Arduino IDE takes more time to startup each time

### ISSUE THREAD

**Issue by Richard-B** [arduino/Arduino#6664] opened 2017-08-29 06:31 UTC
I am using Arduino IDE version 1.8.4 in my laptop , with **windows 10**. It will take **more time** to **startup** the Arduino IDE **each time.**
Plz give the solution for this type of issues.

**Comment by Richard-B** [comment] 2017-08-29 13:31
I already have the title **Arduino** , it will take more time to startup for each time

**Comment by facchinm** [comment] 2017-09-04 16:28
Duplicate of https://github.com/arduino/Arduino/issues/6350

**Closed by facchinm** 2017-09-04 16:28 UTC
