### ISSUE TITLE
Request to add SparkFun Graphic LCD Backpack library to library package manager. 

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3152] opened 2015-05-15 19:14 UTC
Repo is here: https://github.com/sparkfun/SparkFun_Graphic_LCD_Serial_Backpack_Arduino_Library

Most recent tag: https://github.com/sparkfun/SparkFun_Graphic_LCD_Serial_Backpack_Arduino_Library/tree/V_1.0.1

Thank you!

**Comment by ffissore** [comment] 2015-05-18 09:38
Duplicate of #3044. Lib already listed

**Closed by ffissore** 2015-05-18 09:38 UTC
Labels: Component: Board/Lib Manager
