### ISSUE TITLE
Verbose output follows the window focus

### ISSUE THREAD

**Issue by mastrolinux** [arduino/Arduino#2711] opened 2015-02-27 08:33 UTC
When uploading a sketch or doing everything writing to the console inside the IDE, if someone changes window the output follow the focus. This make debugging almost impossible with part of the output split over multiple windows.

**Comment by wayoda** [comment] 2015-02-27 13:16
I can confirm that this bug exists, but   
> This make debugging almost impossible with part of the output split over multiple windows.

is a bit of an exaggeration I think.
A simple workaround is to wait until the operation finishes before switching to another window.

**Comment by mastrolinux** [comment] 2015-02-27 14:00
If your sketch takes a while to upload, especially on networking upload, that means you could wait up to 1  min before switching window. It is for sure not an high prio bug, still something good to have. It can confuse new users.

**Comment by ffissore** [comment] 2015-02-27 14:43
Duplicate of #2680

**Closed by ffissore** 2015-02-27 14:43 UTC
Labels: Component: IDE user interface, Type: Bug
