### ISSUE TITLE
[Windows] bug: libraries can not be directory junctions any more

### ISSUE THREAD

**Issue by niccokunzmann** [arduino/Arduino#4459] opened 2016-01-21 12:53 UTC
I updated to Arduino version 1.6.7 (used 1.6.1 before) and now, I face this error:

    Arduino: 1.6.7 (Windows 7), Board: "Arduino Nano, ATmega328"

    C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\username\Documents\Arduino\libraries" -fqbn=arduino:avr:nano:cpu=atmega328 -ide-version=10607 -build-path "C:\Users\username\AppData\Local\Temp\build252bb44f6f71c75ddcee77fafdc01d21.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "C:\Users\username\Documents\Arduino\libraries\ledtable\examples\transparency\transparency.ino"
    readlink C:\Users\username\Documents\Arduino\libraries\ledtable: The system cannot find the file specified.

    Error compiling.

This error occurs for all libraries that I created a directory junction for and into the folder using

    mlink /J C:\Users\...\Documents\Arduino\libraries\<library> <path to library>

When I remove the library it complains about, I complains about the next until there are no more libraries left linked by mklink.
I can not compile any program as it aborts with this error message.

**Comment by matthijskooijman** [comment] 2016-01-21 13:19
Thanks for reporting, but this is a duplicate of https://github.com/arduino/arduino-builder/issues/90 so I'm closing this issue.

**Closed by matthijskooijman** 2016-01-21 13:19 UTC
