### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by johbell** [arduino/Arduino#5189] opened 2016-07-31 12:27 UTC
After updating to 1.6.10 I can not communicate with my MKS Base 1.3 board. When I try to upload the firmware it just keeps saying uploading with no activity on the board. I went back to the 1.6.9 version and everything worked fine.

**Comment by meoudon** [comment] 2016-08-01 02:54
I have solved. It Avrdude's error. I copy worked avrdude from another version into /avr/bin and avrdude.conf. Everything done on 1.6.12.

**Comment by harryboo** [comment] 2016-08-03 21:25
Please test this [build](https://github.com/arduino/Arduino/pull/5202) !

**Comment by per1234** [comment] 2016-08-03 22:35
> Please test this build !

Unless there were changes in avrdude other than the avrdude.conf lock bits read mask that build should only affect issues related to **Tools > Burn Bootloader**.

**Comment by cmaglie** [comment] 2016-09-22 08:13
Should be fixed with #5374 and released in IDE 1.6.12.
Please reopen if the issue is not solved.

**Closed by cmaglie** 2016-09-22 08:13 UTC
Labels: Component: Avrdude 6.3
