### ISSUE TITLE
Leornardo Serial boolean flag should be set to false when serial port is closed. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1052] opened 2012-11-15 19:03 UTC
This is [Issue 1052](http://code.google.com/p/arduino/issues/detail?id=1052) moved from a Google Code project.
Added by 2012-09-26T23:57:49.000Z by [francois...@gmail.com](http://code.google.com/u/117531142841538656903/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-ATmega32U4

### Original description

**What change would like to see?**
On Arduino Leonardo, "if(Serial)" allows to know when Serial CDC is open for the FIRST time, but this parameter isn't updated when the serial closes / when shutting down hyperterminal on computer. So it is not possible to detect the next hyperterminal/serial opening.

**Why?**
To reproduce the same behavior as the Uno (setup welcome messages on every hyperterminal openings), it would be nice to update this parameter so that we can detect that the serial was closed.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
No

**Comment by NicoHood** [comment] 2016-03-09 15:26
Duplicate: https://github.com/arduino/Arduino/issues/1397

**Comment by sandeepmistry** [comment] 2016-03-09 16:27
@NicoHood thanks!

Closing and marking as duplicate of #1397.

**Closed by sandeepmistry** 2016-03-09 16:27 UTC
Labels: Type: Duplicate
