### ISSUE TITLE
Add stop button to build and upload process

### ISSUE THREAD

**Issue by mynameisbill2** [arduino/Arduino#10116] opened 2020-04-29 14:19 UTC
Please add stop button to build and upload process

**Comment by jpmeijers** [comment] 2020-05-02 12:07
This would definitely be a useful feature. I regularly have to run `killall bossac` or `killall avrdude` in a terminal to get things going again.

**Comment by per1234** [comment] 2020-05-06 08:41
Closing as duplicate of https://github.com/arduino/Arduino/issues/5928

**Closed by per1234** 2020-05-06 08:41 UTC
