### ISSUE TITLE
"ant start/run" does not work

### ISSUE THREAD

**Issue by Pieter12345** [arduino/Arduino#8653] opened 2019-03-14 15:35 UTC
After downloading the Arduino project, installing the required software to compile and running `ant dist`, the result is a passing and working `C:\Users\Pietje\Documents\Java Eclipse Workspace\Arduino\build\windows\arduino-1.8.9-windows.zip` build.
The problem, however, is that running `ant start` or `ant run` only results in a flash of the Arduino startup screen before it terminates. Running `Arduino/build/windows/work/arduino_debug.exe` from commandline results in the following exception:
```
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at com.sun.jna.platform.win32.Shell32.<clinit>(Shell32.java:32)
        at com.sun.jna.platform.win32.Shell32Util.getFolderPath(Shell32Util.java:44)
        at com.sun.jna.platform.win32.Shell32Util.getFolderPath(Shell32Util.java:61)
        at cc.arduino.os.windows.Win32KnownFolders.getLocalAppDataFolder(Win32KnownFolders.java:53)
        at processing.app.windows.Platform.recoverSettingsFolderPath(Platform.java:64)
        at processing.app.windows.Platform.init(Platform.java:54)
        at processing.app.Base.<init>(Base.java:208)
        at processing.app.Base.main(Base.java:151)
```
I have verified that the `Arduino/build/windows/work/lib` directory contains both `jna-4.2.2.jar` and `jna-platform-4.2.2.jar`. I do not understand why the first doesn't seem to be on the classpath whereas the latter is.

Additional information:
- `java -version`:
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) Client VM (build 25.202-b08, mixed mode, sharing)
Note that this is a 32 bits version of java and that both `JAVA_HOME` and `C:\Program Files (x86)\Common Files\Oracle\Java\javapath` point to this 32 bits installation.
- OS:
Windows 7 64 bits
- Ant commands were executed from a cygwin terminal.

Any help is appreciated.

**Comment by facchinm** [comment] 2019-03-15 08:21
Closing as duplicate of #8617 , will try to take a look early next week

**Closed by facchinm** 2019-03-15 08:21 UTC
