### ISSUE TITLE
The text in IDE is unreadable on High Resolution screens

### ISSUE THREAD

**Issue by punitganshani** [arduino/Arduino#2851] opened 2015-03-30 17:54 UTC
On high-resolution screens (3200x1800), the text in IDE is very small.  Even after reducing the resolution to 1920x1080, the text is too small to read.

![image](https://cloud.githubusercontent.com/assets/1032553/6902787/9f3a2a82-d748-11e4-9c05-72360e5d210e.png)

**Comment by PaulStoffregen** [comment] 2015-03-30 18:00
This is a duplicate of #2532

See pull request #2776 for a partial solution.  Please test #2776  (don't forget to edit theme.txt) on your computer+display and comment.  Maybe someday it will be merged into Arduino, but so far very few people with these highres screens have tested it.

**Comment by 00alis** [comment] 2015-04-03 15:12
Have you tried changing the font size in the Preferences? 
![screenshot 2015-04-03 17 08 02](https://cloud.githubusercontent.com/assets/6151328/6983952/02bad2b8-da24-11e4-93d9-17b02c7b34d3.png)

I am using a Mac retina display 15" and I can see the text pretty big with the font set at 22 pt
![screenshot 2015-04-03 17 10 01](https://cloud.githubusercontent.com/assets/6151328/6983979/4f3b7070-da24-11e4-9d04-3741157c453b.png) 

Of course this does not fix the UI and menu size problems, if you are referring only to that please discard this comment.

**Comment by neslekkim** [comment] 2015-04-21 17:10
Does it exist built versions with this fix to test?, on my 4k display the ide is rather unusable.

**Comment by PaulStoffregen** [comment] 2015-04-21 19:39
Yes, test versions exist on issue #2776.  About half way down that page are test copies from ArduinoBot.

You MUST edit theme.txt.  They don't (yet) scale automatically.  On a Mac, control-click on Arduino and select "Show Package Contents".  Then find "theme.txt" inside and edit to increase the scaling.  In that test version, the first line in theme.txt is the new scaling parameter.

Please comment on issue #2776.  This duplicate issue should be closed.

**Closed** 2015-04-22 07:02 UTC
Labels: Type: Duplicate
