### ISSUE TITLE
On OSX, program should not quit when last window is closed until user clicks away.

### ISSUE THREAD

**Issue by Segmented** [arduino/Arduino#5972] opened 2017-02-10 16:09 UTC
In order to keep the behaviour consistent with other programs on OSX, Arduino should not automatically close when the last window is closed, until the user clicks away. This allows the user the opportunity to open a new file, or change settings. Other programs such as QuickTime behave in this way.

**Comment by cmaglie** [comment] 2017-02-10 16:18
Duplicate of #936

**Closed by cmaglie** 2017-02-10 16:18 UTC

**Comment by Segmented** [comment] 2017-02-10 16:24
I'll add a note about how QuickTime behaves to the other issue, thanks.
