### ISSUE TITLE
Can't install Arduino program in Mac OS.

### ISSUE THREAD

**Issue by 720candy** [arduino/Arduino#6709] opened 2017-09-08 13:39 UTC
I can't install program pls help me....

install Arduino --> pop up screen --> disappear --> doesn't work anything.

code-----

java.lang.IllegalArgumentException: Font size must be > 0
	at org.fife.ui.rtextarea.RTextAreaBase.setFont(RTextAreaBase.java:986)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.setFont(RSyntaxTextArea.java:2510)
	at processing.app.EditorTab.applyPreferences(EditorTab.java:322)
	at processing.app.EditorTab.<init>(EditorTab.java:110)
	at processing.app.Editor.addTab(Editor.java:1672)
	at processing.app.Editor.createTabs(Editor.java:1645)
	at processing.app.Editor.handleOpenInternal(Editor.java:1944)
	at processing.app.Editor.<init>(Editor.java:340)
	at processing.app.Base.handleOpen(Base.java:833)
	at processing.app.Base.handleOpen(Base.java:819)
	at processing.app.Base.handleOpen(Base.java:815)
	at processing.app.Base.handleNew(Base.java:754)
	at processing.app.Base.<init>(Base.java:460)
	at processing.app.Base.main(Base.java:140)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by facchinm** [comment] 2017-09-08 15:57
closing as duplicate of #6708

**Closed by facchinm** 2017-09-08 15:57 UTC
