### ISSUE TITLE
No Such file or directory during Verify

### ISSUE THREAD

**Issue by Thomjohn21** [arduino/Arduino#1789] opened 2014-01-05 04:22 UTC
When I verify any program in the IDE; the following message appears:

"C:\Program Files (x86)\Arduino\hardware\tools\avr\bin\avr-ar: malloc.c.o: No such file or directory"

I have installed and uninstalled versions 1.0.5 and 1.5.5 several times. Also, I installed 1.0.5 in a different directory as the administrator with the same result:

"C:\Users\thom\Arduino\hardware\tools\avr\bin\avr-ar: malloc.c.o: No such file or directory"

I have verified my rights in those directories. I am not sure why the "malloc.c.o" file does not get created. I have taken notice a file called "malloc.c.d" does get created.

I am using a Windows 7 home premium SP1. I have disabled my firewall and antivirus to test. I got the same result. I am not sure if this a bug or user error. Any help would be appreciated.

**Comment by ffissore** [comment] 2015-05-26 14:18
Closing as user reported his issue was caused by an external program interfering with the IDE

**Closed by ffissore** 2015-05-26 14:18 UTC
Labels: Component: IDE
