### ISSUE TITLE
http://downloads.arduino.cc/CMSIS-4.5.0.tar.bz2 is missing/forbidden

### ISSUE THREAD

**Issue by Aerospacesmith** [arduino/Arduino#5781] opened 2016-12-29 20:43 UTC
Installing Arduino SAMD Boards 1.6.11 with Windows fails:
Error downloading http://downloads.arduino.cc/CMSIS-4.5.0.tar.bz2

Going to http://downloads.arduino.cc/CMSIS-4.5.0.tar.bz2 gives me a 403 Forbidden error.

Tried on Arduino 1.6.13 and 1.8.0. I'm able to Install other board packages like the SAM Boards just fine.

I can install SAMD 1.6.8, but none of the newer ones. It looks like version 1.6.8 used CMSIS 4.0 and the newer ones use CMSIS 4.5.

Arduino IDE Log:
```
	Error downloading http://downloads.arduino.cc/CMSIS-4.5.0.tar.bz2
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/CMSIS-4.5.0.tar.bz2
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:176)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/CMSIS-4.5.0.tar.bz2
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:131)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:69)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:110)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:173)
	... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 403
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:194)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:129)
	... 4 more
```

**Comment by facchinm** [comment] 2017-01-02 09:59
Probably there was some sort of network error, the link seems up now. Could you please try installing SAMD core again and close the issue if it works? Thanks

**Comment by NicoHood** [comment] 2017-01-02 10:02
I do not know why I see an http link, but it should be changed to https. Its possible in a boards json file.

**Comment by Aerospacesmith** [comment] 2017-01-03 19:44
Thanks NicoHood. Its because the link is a http and not a https.

https://downloads.arduino.cc/CMSIS-4.5.0.tar.bz2 does work. It appears the json file needs updated.

**Comment by facchinm** [comment] 2017-01-04 14:41
The file should be reachable from both http and https (and it IS reachable, I just checked directly and via a proxy). Would you mind testing now (from within the Board Manager) making sure that no warning appears in the Console? Thanks

@NicoHood , we'll also update that link to https but it can't be the root cause of this issue

**Comment by Aerospacesmith** [comment] 2017-01-04 16:51
I believe it has something to do with my work internet. 
I can not access http://downloads.arduino.cc/CMSIS-4.5.0.tar.bz2
But I can access https://downloads.arduino.cc/CMSIS-4.5.0.tar.bz2

**Comment by mastrolinux** [comment] 2017-01-12 10:12
I just tried from many clients referring to that specific server and I can confirm is not an issue on our end. I am going to close the issue but please let us know if the problem appears again. From what I see the 403 forbidden page is not provided by us but from some internal proxy. Please verify with your network administrator.

**Closed** 2017-01-12 10:12 UTC

**Comment by VladimirAkopyan** [comment] 2019-03-05 19:26
This happened again!

**Comment by per1234** [comment] 2019-03-05 20:36
@VladimirAkopyan I just tried downloading the file and had no error at all. It might have been a momentary outage or else you are behind a firewall that is preventing the download.
