### ISSUE TITLE
Commented code highlighted wrong

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3532] opened 2015-07-15 15:32 UTC
If you put a single, capital character at the start of a /**/ comment the underlaying paragraph is not grey anymore. Not all letters are affected, only a few, and only capital once.

Example:
```
/*
Test
A
Test
*/
```

**Comment by per1234** [comment] 2015-07-16 08:55
That example doesn't work for me, but I think I know why. I have noticed this happens when an unindented keyword is in a multi-line comment. I'm guessing Test is in one of your keywords.txt files and not mine. For example:
```
/*
this is gray
 void
this is still gray
void
this is not gray
*/
```
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/8719043/9d3da128-2b5d-11e5-8e99-36afc18a8d45.gif)

**Comment by NicoHood** [comment] 2015-07-16 09:19
Not talking about the "test", rather the "A" and other letters. But yes, that is the issue. This shouldnt happen.

**Comment by per1234** [comment] 2015-07-16 09:22
Is "A" a keyword in your installation?

**Comment by NicoHood** [comment] 2015-07-16 09:23
Yes. And other capital letters. Dont know why. Might be because of some libraries, but I will not search them now.

**Comment by lcafaro** [comment] 2015-07-19 20:27
This should help you find the culprit:
```find . -type f -name keywords.txt | xargs grep '^A '```

Anyway, I think this should be marked as not a bug.

![test](https://cloud.githubusercontent.com/assets/13108002/8767697/3135590c-2e65-11e5-9096-91ac5cc20311.png)

**Comment by carlosperate** [comment] 2015-07-19 20:33
If the code highlighting fails using default keywords as shown by per1234, then it is a bug.

**Comment by lcafaro** [comment] 2015-07-19 20:44
You're right, I missed that bit. Apparently this only happens with that style of commenting.
Looks like it's related to our implementation of ```rsyntaxtextarea.TokenMap``` (e.g. PdeKeywords.java) since I can't reproduce on a plain Java implementation of rsyntaxtextarea.

**Comment by ffissore** [comment] 2015-09-17 12:28
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Closed** 2015-09-17 12:28 UTC
Labels: Component: IDE user interface, Type: Bug
