### ISSUE TITLE
Missing native support for ATmega328PB

### ISSUE THREAD

**Issue by chaveiro** [arduino/Arduino#6040] opened 2017-03-05 01:22 UTC
New cpu will be used on many new boards in future so native support is a must.
It is missing in two places (as of 1.8.1):
 **gcc** - missing header files
 **avr-dude** -missing in config

See here how to add support:
 https://github.com/watterott/ATmega328PB-Testing
 http://forum.arduino.cc/index.php?topic=374642.585

**Comment by per1234** [comment] 2017-03-05 04:09
Duplicate of https://github.com/arduino/toolchain-avr/issues/36

**Comment by facchinm** [comment] 2017-03-06 08:28
Closing as duplicate, please continue the discussion about new chips integration in arduino/toolchain-avr#36 as @per1234 reported, thanks :wink:

**Closed by facchinm** 2017-03-06 08:28 UTC
