### ISSUE TITLE
Get download count of library 

### ISSUE THREAD

**Issue by AIS-DeviceInnovation** [arduino/Arduino#9774] opened 2020-02-17 04:02 UTC
How to get download count of the library?

**Comment by MisterAwesome23** [comment] 2020-04-10 22:31
Hey @AIS-DeviceInnovation 

Do you mean a download count of "AIS_NB_BC95" library in your case and want to know/log/display number of downloads?

Or is it something different altogether?

**Comment by per1234** [comment] 2020-10-05 02:26
Closing as duplicate of https://github.com/arduino/Arduino/issues/7265

**Closed by per1234** 2020-10-05 02:26 UTC
Labels: Component: Website, feature request
