### ISSUE TITLE
Add a Window drop down menu.

### ISSUE THREAD

**Issue by NateD4** [arduino/Arduino#1950] opened 2014-03-22 13:46 UTC
There is no 'Window' drop down menu on the menu bar.

Please add one that will show all open windows.

I frequently find I have multiple sketches open and switch between them. It would be nice to have a Window menu to more quickly access these.

**Comment by ffissore** [comment] 2015-09-17 13:25
Duplicate of #234

**Closed by ffissore** 2015-09-17 13:25 UTC
Labels: Component: IDE, Type: Improvement
