### ISSUE TITLE
documentation of Serial.readString() is ambiguous and misleading

### ISSUE THREAD

**Issue by tofrnr** [arduino/Arduino#6722] opened 2017-09-14 09:04 UTC
the Arduino documentation of Serial.readString() is ambiguous and misleading:
what does it return?
a  char*  or a cstring or a member of the String class ?
\0 terminated?
\n terminated?
\n\0 terminated?

Nonetheless it does not even provide example source codes where one would be able to check the usage!

this documentation is really a nightmare, tbh!
https://www.arduino.cc/en/Serial/ReadString

**Comment by per1234** [comment] 2017-09-14 09:09
Duplicate of https://github.com/arduino/Arduino/issues/6486

**Closed by per1234** 2017-09-14 09:09 UTC

**Comment by tofrnr** [comment] 2017-09-14 09:10
this is not a duplicate, my question is about the termination!
re-open it immediately!
