### ISSUE TITLE
--verify doesn't appear to work for 'release' executable

### ISSUE THREAD

**Issue by pfeerick** [arduino/Arduino#3460] opened 2015-07-04 11:21 UTC
After seeing the article on Travis CI for testing arduino libraries, I followed the steps in their article to have Travis CI verify my arduino library. No problems there. Then I thought I would make it run on an arduino sketch... and encountered a build lockup every time the arduino IDE starts. I've given up for the night, but thought I'd try to reproduce it on Windows (7 x64), to see if it was actually a bug in my code. If I run the below commands from the command line on Windows, the standard 'release' exe for arduino does nothing bar show the splash screen, and the 'debug' exe works fine. If It remove the --board and --verify parameters, the IDE opens with that sketch loaded, so there is no problem accessing it...

Shouldn't the release build also be echoing the verification details to the console?

```
D:\Open Source Programming\arduino-hourly>arduino --board arduino:avr:uno --verify "d:\Dropbox\Arduino\RF\nano_nrf_tester\nano_nrf_tester.ino"

[splash screen -> loading configuration, initialising packages, preparing boards, then nothing]
```

```
D:\Open Source Programming\arduino-hourly>arduino_debug --board arduino:avr:uno--verify "d:\Dropbox\Arduino\RF\nano_nrf_tester\nano_nrf_tester.ino"
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...

Sketch uses 14,110 bytes (43%) of program storage space. Maximum is 32,256 bytes.
Global variables use 696 bytes (33%) of dynamic memory, leaving 1,352 bytes for local variables. Maximum is 2,048 bytes.
```

**Comment by matthijskooijman** [comment] 2015-07-05 09:21
Closing this as a duplicate of #3461, which you just also reported. For future reference, you could have edited your first report or added comments, though I suspect you didn't realize you already reported it or something like that.

**Closed by matthijskooijman** 2015-07-05 09:21 UTC
