### ISSUE TITLE
per-project libraries

### ISSUE THREAD

**Issue by night-ghost** [arduino/Arduino#4356] opened 2015-12-28 08:15 UTC
sometimes big projects needs to make small (or not) modifications in libraries it uses. To prevent poison of another projects such libraries should be private for one project and be placed for example in (project)/include or (project)/libraries folder, so IDE should add such subfolder to list of library places

**Comment by lmihalkovic** [comment] 2015-12-28 08:41
I was asking for that too #4050

**Comment by matthijskooijman** [comment] 2015-12-28 10:55
Yup, so I'm closing this as a duplicate of #314 and #4050.

**Closed** 2015-12-28 10:55 UTC
Labels: Type: Duplicate
