### ISSUE TITLE
Arduino preprocessing stripping comments when creating .cpp file

### ISSUE THREAD

**Issue by WestfW** [arduino/Arduino#3598] opened 2015-07-29 08:53 UTC
Why has the IDE started stripping comments when preprocessing .ino files to .cpp files in the build directory?  This is liable to make disassembly and real debugging more difficult (for those few who do it), and violates the principal of doing as little pre-processing as possible, and I don't see any advantage to doing it...

**Comment by Chris--A** [comment] 2015-07-29 12:55
Yup very bad, it doesn't actually do it properly:

```arduino



//This is a valid comment. \
so is this, but not today!

void setup() {}
void loop() {}
```

http://stackoverflow.com/questions/7059549/c-multi-line-comments-using-backslash

**Comment by ffissore** [comment] 2015-08-05 08:30
Sorry, this issue belongs to a long list of issue tagged with https://github.com/arduino/Arduino/labels/Component%3A%20Preprocessor

**Comment by Chris--A** [comment] 2015-08-05 12:44
Ah, I had forgotten I had a PR for this too: https://github.com/arduino/Arduino/pull/3240

And this is a duplicate of #956

**Comment by ffissore** [comment] 2015-09-11 15:40
Fixed by #3779

**Closed by ffissore** 2015-09-11 15:40 UTC
Labels: Component: Preprocessor
