### ISSUE TITLE
Don't compile everytime it uploads the code

### ISSUE THREAD

**Issue by mgameiro** [arduino/Arduino#5819] opened 2017-01-07 17:10 UTC
Some projects have more than one arduino, both with the same code. It would save some time to just compile once, and just upload the compiled code for both. Arduino IDE has a button just to compile, be it would be useful to have one just for upload too.

In alternative, it could be implemented a system in witch the compiler doesn't compile again until the code changes, just like the one on makefiles on linux.

**Comment by cmaglie** [comment] 2017-01-08 19:32
This should be solved with the latest releases. Can you add some steps to reproduce?
Please add also verbose compile output.

**Comment by mgameiro** [comment] 2017-01-15 14:36
Sorry, the material in witch my project was done wasn't mine and I had to return it. I can't do the steps again. Sorry.

**Comment by matthijskooijman** [comment] 2017-01-15 22:10
The we'll assume the problem is indeed fixed, I'm closing this issue.

**Closed by matthijskooijman** 2017-01-15 22:10 UTC
