### ISSUE TITLE
Menu and Icons need to scale on higher resolution displays

### ISSUE THREAD

**Issue by jem-green** [arduino/Arduino#4418] opened 2016-01-13 14:13 UTC
Needs font / icon scaling as difficult to use on higher resolution displays. In the short term possibly add menu item to have large icons.  I have the font size set to 36 to make it readable.
![capture](https://cloud.githubusercontent.com/assets/8076147/12296481/d231093e-b9ff-11e5-8993-4af8a239c087.PNG)

**Comment by cmaglie** [comment] 2016-01-13 14:40
Duplicate of #4376.

Please try the test build on #4376 (you can find it at the bottom of the discussion) and report back if it works for you.

**Closed by cmaglie** 2016-01-13 14:40 UTC
