### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by ShmulikKraus** [arduino/Arduino#8728] opened 2019-03-29 12:02 UTC
I'm not nearly experienced enough to differentiate a bug from a user error, but I did ask in the Arduino forums and did not get an answer.
Everything is summed up nicely in [post  #7 of my thread](https://forum.arduino.cc/index.php?PHPSESSID=h2p6i6m95l1l7ggbui2e6j2255&topic=605409.msg4110550#msg4110550) on the Arduino forums but to reiterate:
A code block that is not executed is still affecting the output of a program:

```
#include <Arduino.h>

#define REVERSE 1
#define ALIGNRIGHT 2

//Functions
void reverseheb(unsigned char *string);
void printheb(uint8_t xpos, uint8_t y, char ch[], uint8_t flags);

void setup(void) {
  Serial.begin(57600);
}

void loop(void) {
  printheb(0, 20, "This is just a simple test.", REVERSE | ALIGNRIGHT);
  delay(5000);
}


void reverseheb(unsigned char *string)
{
    int i,j;
    char *temp;
    //
    j = strlen(string);
    temp = (char*)malloc(j+1);
    temp[j] = 0;
    for(i=0 ; string[i] ; i++)
    {
      if(string[i] == 0xD7)
      {
        temp[j-i-1] = string[i+1];
        temp[j-i-2] = 0xD7;
        i++;
      }
      else
      {
        if((string[i] < '0' || string[i] > '9') && (string[i] < 'A' || string[i] > 'Z') && (string[i] < 'a' || string[i] > 'z')) temp[j-i-1] = string[i];
        else
        {
          int m,k;
          k = i;
          while((string[i] >= '0' && string[i] <= '9') || (string[i] >= 'A' && string[i] <= 'Z') || (string[i] >= 'a' && string[i] <= 'z'))
          {
            i++;
          }
          i--;
          for(m=0 ; m<(i-k+1) ; m++)
          {
            temp[j-(k+m)-1] = string[i-m];
          }
        }
      }
    }
    strcpy(string,temp);
    free(temp);
}

void printheb(uint8_t xpos, uint8_t y, char ch[], uint8_t flags)
{
   int i,j,k;
   char tmp;
   char *temp;
   //
   if(!flags) // if not REVERSE and not ALIGNRIGHT
   {
     Serial.println(ch);
     return;
   }
   if(((flags & 1) == 1) && ((flags & 2) == 0) ) // (Line 70) if REVERSE but not ALIGNRIGHT
   //if(flags  == 1) // (Line 71)
   {
     temp = (char *)malloc(strlen(ch) + 1);
     strcpy(temp, ch);
     reverseheb(temp); // (Line 75)
     Serial.println("This is never executed.");
   }
   if((flags & 2) == 0) return;
   k = 0;
   for(i=0,j=0 ; ch[i] ;)
   {
     j++;
     if(ch[i] == (char)0xD7) i+=2;
       else i++;
     if(j == (  (  (128 - xpos)/6)  )  || !ch[i])
     {
       tmp = ch[i];
       ch[i] = 0;
       temp = (char *)malloc(strlen(&ch[k]) + 1);
       strcpy(temp, &ch[k]);
       if((flags & 1) == 1) // if REVERSE
       {
         reverseheb(temp);
       }
       Serial.println(temp);
       free(temp);
       y+=13;
       ch[i] = tmp;
       if(ch[i] == 0) break;
       k = i;
       j = 0;
     }
   }
}
```

The mentioned code block is between lines 70 and 77.

Some info that may or may not be relevant:
Board: Pro mini clone (ATmega328p, 16Mhz, 5V).
OS: Windows 10.
IDE Version: 1.8.8

**Comment by PaulStoffregen** [comment] 2019-03-30 13:01
Not a bug with Arduino.  Your code is terrible!

I answered on the forum.  Closing this.

**Closed by PaulStoffregen** 2019-03-30 13:01 UTC
