### ISSUE TITLE
Theme colors issue since 1.6.5  by LITERAL1

### ISSUE THREAD

**Issue by MarkusLange** [arduino/Arduino#4572] opened 2016-02-13 18:09 UTC
In IDE 1.6.7 the Color of the LITERAL1 tagged Constants from the keywords.txt are shown orange not blue.

Since IDE 1.6.4 (I looked back from 1.6.7 the LITERAL1 is shown orange not blue) is the color from LITERAL1 not correct inside the editor.

**Comment by facchinm** [comment] 2016-02-15 08:45
@00alis

**Comment by PaulStoffregen** [comment] 2016-02-15 11:56
I've noticed this too, in several libraries I maintain which use LITERAL1.

**Comment by 00alis** [comment] 2016-02-16 16:19
You are right! Thank you for reporting this!
We are going through a review of the Arduino pigmentation in the next few days and we will add this bugfix. @agdl

**Comment by MarkusLange** [comment] 2016-02-16 17:01
Thanks

**Comment by agdl** [comment] 2016-02-19 09:43
it should be ok now with https://github.com/arduino/Arduino/commit/88650b65a699dcddbe0ac58bbabd9b19cf882c1e

**Comment by MarkusLange** [comment] 2016-02-19 20:46
Changed the files to 88650b6 in 1.6.7 but no luck

**Comment by agdl** [comment] 2016-02-22 09:13
Try now please this time should be really ok with https://github.com/arduino/Arduino/commit/8035f244989f92830bd5a72f5a7d8d9f3aa7f6c8

If so close the issue please

**Comment by MarkusLange** [comment] 2016-02-22 22:12
May I did something wrong but it doesn't help, sorry.

**Comment by PaulStoffregen** [comment] 2016-02-27 05:50
I can confirm the problem is NOT FIXED in the latest nightly build.

**Comment by PaulStoffregen** [comment] 2016-02-27 05:53
As you can see, a library using LITERAL1 isn't getting the proper blue color.

To reproduce the problem, install the Encoder library, and then add "#define ENCODER_USE_INTERRUPTS".

**Comment by agdl** [comment] 2016-02-27 18:20
@PaulStoffregen yes I know. I understood where the problem is. On Monday i will fix it

**Comment by agdl** [comment] 2016-02-27 18:23
If you switch to the branch I created and referenced in this issue. Looking at the files I modified you can easily see that working on that it is possible to highlight many different keywords. It will be very useful for future developments.

**Comment by PaulStoffregen** [comment] 2016-02-28 01:02
I just tried the themeKeywords branch, compiling from source on Ubuntu 14.04 (64 bit).

The colors do not seem to be correct....

**Comment by agdl** [comment] 2016-02-28 11:13
@PaulStoffregen yes it is a work in progress we have to decide colors with @00alis

**Closed** 2016-02-29 08:27 UTC
Labels: Component: IDE user interface, Type: Bug
