### ISSUE TITLE
Arduino IDE freeze

### ISSUE THREAD

**Issue by Jomelo** [arduino/Arduino#8161] opened 2018-11-01 20:47 UTC
Hello, 
i can reproduce an error which i can freeze the arduino ide.
Tested on Windows 10 Pro 64bit, latest Update, 

1. Press "File"
2. Press "Save as"
3. delete a displayed folder in the "save as" window. -> the ide is freezing. 

Only the Task-Manager can help.

**Comment by per1234** [comment] 2018-11-01 20:56
Closing as duplicate of 
https://github.com/arduino/Arduino/issues/5191
We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-11-01 20:56 UTC
Labels: Type: Duplicate
