### ISSUE TITLE
Arduino Editor: jerking lines for mouse mark/ drag and moving marked blocks

### ISSUE THREAD

**Issue by VogonJeltz** [arduino/Arduino#3726] opened 2015-08-25 18:27 UTC
when putting the cursor in one of the upper or lower lines in the editor window e.g. for marking a code block (keeping left mouse button pressed, then drag the mouse)  the lines jerk and jump up and down, this makes handling of draging very complicated.

Additionally, if a code block (e.g., a few lines) is already marked, moving this block by draging the mouse (keeping left button pressed)  to another position is not possible.

Fixing these issues would be appreciated!

**Comment by ffissore** [comment] 2015-08-26 12:11
Can you screencast a video? I can't reproduce both the issues: selection works fine, moving a selected code block using the mouse works fine

**Comment by VogonJeltz** [comment] 2015-08-26 15:43
no, sorry, I cant make a video unfortunately.
I'm using IDE 1.6.3 for Windows XP32.

about moving a marked block:
when I drag the mouse with pushed-down left btn, I can mark.
But when I then put the mouse pointer on the marked area, the markes area dissapears.so I can't move it.
With MS Word it works.

About the jerking:
Put the mose pointer on the 2nd line from above => the lines jerk down.
On the bottom it's vice versa, it jerks up.

**Comment by ffissore** [comment] 2015-08-27 09:18
Not even a screenshot? As I said, I cannot reproduce those issues

**Comment by VogonJeltz** [comment] 2015-08-27 09:43
a screenshot of a disappearing selection:
1) clicking into the line 10:
![jerkdn001](https://cloud.githubusercontent.com/assets/11213519/9517422/2e85aff4-4cb0-11e5-85b7-facf7abacac8.jpg)
2) holding the mouse pressed the lines jerk down and everything is going to be unintentional selected until up to line 1:
![jerk002](https://cloud.githubusercontent.com/assets/11213519/9517447/57bb462c-4cb0-11e5-8502-77b9356b2aee.jpg)

about mark/select and the try to move the highlighted block:
1) select a block:
![Uploading mark001.jpg…]()
2) now trying to click into the selected heighlighted area in order to move it  
=> selection disappears at once, no moving/draging possibe!
![mark002](https://cloud.githubusercontent.com/assets/11213519/9517515/d3b18b42-4cb0-11e5-8d9d-7dc13428b4b4.jpg)

**Comment by Chris--A** [comment] 2015-08-27 09:55
You'll have to update your IDE to see if this still exists.

The editor was replaced with RSyntaxTextArea in 1.6.5, your screenshots are using 1.6.3

**Comment by ffissore** [comment] 2015-08-27 09:58
@Chris--A good catch!! Sorry @VogonJeltz, you also wrote that in your first reply, but somehow I missed it. Closing as worksforme then. @VogonJeltz upgrade to 1.6.5 and reopen if your issues are still valid with the latest version

**Closed by ffissore** 2015-08-27 09:58 UTC
Labels: Component: IDE user interface, Waiting for feedback

**Comment by VogonJeltz** [comment] 2015-08-27 10:00
yes, I already wrote that I'm using 1.6.3.
If the issue has been fixed meanwhile then it's fine of course.

I wouldn't update to 1.6.5 though because the boards and the library manager is too weird, I can't update all my installed boards, all my existing libs and all my lib.c float patches without huge issues then.
