### ISSUE TITLE
1.8.8 Segmentation fault

### ISSUE THREAD

**Issue by Ixby** [arduino/Arduino#8508] opened 2019-02-07 01:35 UTC
Using 1.8.8 of ide - 1.6.23 of the board package. Installed the keypad library 3.1.

Following message on compile: Keypad/Keypad.h:87:73: internal compiler error: Segmentation fault

Changed the boards version to 1.6.22 and recompiled and it worked.

**Comment by per1234** [comment] 2019-02-07 01:40
Closing as duplicate of https://github.com/arduino/Arduino/issues/7949

Note that it's likely rolling back to Arduino AVR Boards 1.6.22 only coincidentally made the error go away and you may see it reappear again. The sure workaround is to roll back to Arduino AVR Boards 1.6.21, or try the beta test version of Arduino AVR Boards 1.6.20x:
https://github.com/arduino/Arduino/issues/7949#issuecomment-442969335

**Closed by per1234** 2019-02-07 01:40 UTC
Labels: Type: Duplicate
