### ISSUE TITLE
tone() for Due

### ISSUE THREAD

**Issue by chrisrichards01** [arduino/Arduino#3937] opened 2015-10-08 14:50 UTC
Please add to documentation that tone() does not currently work with the Due.

**Comment by VogonJeltz** [comment] 2015-10-08 15:26
... and then please add a lib that would work with the Due...

**Comment by q2dg** [comment] 2015-10-08 18:54
...and what about Zero? I'm in Europe and I can't try it.

**Comment by aethaniel** [comment] 2015-10-10 22:16
@q2dg tone has been implemented for the Zero a while ago ;-)
https://github.com/arduino/ArduinoCore-samd/commits/master/cores/arduino/Tone.cpp

**Comment by VogonJeltz** [comment] 2015-10-11 08:12
but not for the Due (which is far longer on the market) ?

**Comment by cmaglie** [comment] 2015-10-20 22:50
Duplicate of #2362

**Closed by cmaglie** 2015-10-20 22:50 UTC
Labels: Architecture: SAM, Component: Core

**Comment by VogonJeltz** [comment] 2015-10-21 07:37
I don't see how it now should work for the Due - can you provide a example source code please?

**Comment by cmaglie** [comment] 2015-10-21 08:16
The tone function is not implemented on the Due, and the code posted by @aethaniel is for the Zero board and cannot be used for the Due. That's why #2362 is still open.

**Comment by VogonJeltz** [comment] 2015-10-21 08:43
ok, thank you, I didn't understand this.
is there a timeline about when it will be available?

**Comment by VogonJeltz** [comment] 2015-12-06 11:24
https://github.com/arduino/Arduino/issues/2362

why hadn't this been fixed yet?!?
