### ISSUE TITLE
Why does Serial.print ("\n\n\nAborted !!!\n\n\n"); that the Sketch can not always be uploaded?

### ISSUE THREAD

**Issue by bgma** [arduino/Arduino#10731] opened 2020-09-06 15:20 UTC
Hi,
Why does `Serial.print ("\n\n\nAborted !!! \n\n\n");` that the Sketch can not always be uploaded? But it works sometimes!
I have seen this several times. Now it has happened again.
When it does not work, it is enough to remove 1 of the 3 !!!.
It is always possible to compile but not to upload.
After a long time, the error message "An error occurred while uploading the sketch"

/With kind regards
 Bengt-Görana

[sketch_sep06a.txt](https://github.com/arduino/Arduino/files/5179855/sketch_sep06a.txt)

![Namnlös1](https://user-images.githubusercontent.com/10388645/92328943-85c69000-f064-11ea-8153-7e9475c59fe2.png)

**Comment by per1234** [comment] 2020-09-06 15:27
Closing as duplicate of https://github.com/arduino/Arduino/issues/392

Please see that issue for an explanation of the cause. You can check Google to find a lot of information about how to burn a modern bootloader to your Mega to make this not happen.

**Closed by per1234** 2020-09-06 15:27 UTC

**Comment by bgma** [comment] 2020-09-06 17:37
Tankyou!
