### ISSUE TITLE
BUILD FAILED IDE on RaspberryPi

### ISSUE THREAD

**Issue by NervenCid** [arduino/Arduino#8361] opened 2019-01-05 02:19 UTC
Hello i tried to build and install from source in raspberrypi using these instructions:

https://www.instructables.com/id/Build-Arduino-From-GIT-Sources-on-Ubuntu-1604/

https://github.com/arduino/Arduino/wiki/Building-Arduino

I installed openjfx as shown there:

But i got this error:

build:
      [jar] Building jar: /home/pi/Downloads/Arduino/arduino-core/arduino-core.jar

compile:
    [javac] Compiling 87 source files to /home/pi/Downloads/Arduino/app/bin
    [javac] /home/pi/Downloads/Arduino/app/src/processing/app/EditorToolbar.java:159: error: cannot access Window
    [javac]             touchBar.show(editor); 
    [javac]                     ^
    [javac]   class file for javafx.stage.Window not found
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
/home/pi/Downloads/Arduino/build/build.xml:141: The following error occurred while executing this line:
/home/pi/Downloads/Arduino/build/build.xml:118: The following error occurred while executing this line:
/home/pi/Downloads/Arduino/build/build.xml:166: The following error occurred while executing this line:
/home/pi/Downloads/Arduino/app/build.xml:82: Compile failed; see the compiler error output for details.

Total time: 20 seconds

Any suggestion?

Thank you

**Comment by facchinm** [comment] 2019-01-07 08:50
Closing as duplicate of https://github.com/arduino/Arduino/issues/8255 ; the issue is that adding the touchBar library (for OSX) added an unwanted dependency on JavaFX (not included by default in openJDK distribution normally found on Linux).
The only way right now it to compile using Oracle JDK; we are trying to find a solution but it's not yet landed in master, sorry for that.

**Closed by facchinm** 2019-01-07 08:50 UTC
