### ISSUE TITLE
Arduino 101 not detected on iMac running Win 10

### ISSUE THREAD

**Issue by PickyBiker** [arduino/Arduino#8916] opened 2019-05-25 16:44 UTC
The Arduino Genuino 101 board has the same problem being detected on an iMac running Win 10 as the Arduino WiFi Rev2 that is reported in issue [https://github.com/arduino/Arduino/issues/8881](url)

The attached images show how this board is detected both with and without the driver installed. 
The problem is that in both cases, no COMn port is attached. 

All testing results on this board are the same as with the WiFi Rev2 board issue.  Multiple cables tried and everything works as expected if the iMac is booted in the iMac OS. This is only a problem when booting in Win 10.

![device without](https://user-images.githubusercontent.com/16281039/58372376-d2bf3b00-7ee1-11e9-99a1-b65ad084de8b.JPG)
![Device](https://user-images.githubusercontent.com/16281039/58372378-d652c200-7ee1-11e9-9817-2475309628b1.JPG)

Update Saturday 5/25/2019 Same problem with WeMos D1R2
The only board I can get to work is the UNO.

**Comment by facchinm** [comment] 2019-05-28 16:28
Hi @PickyBiker , I'd close this in as duplicate of #8881 . At this point, I think the issue can be your PC (USB controller/drivers) or your Windows installation

**Closed by facchinm** 2019-05-28 16:28 UTC
