### ISSUE TITLE
1.6.8 IIC 1602 error can display all codes

### ISSUE THREAD

**Issue by wwwusr** [arduino/Arduino#4838] opened 2016-04-08 22:14 UTC
hello guys,
Sth wrong with me,need help!
Use Arduino 1.6.8 in win7 64,when I run the code from Lib LiquidCrystal_I2C-HelloWorld,I can only get a "H" at the first of the 1602,lose other words.
But when run the code in Arduino 1.0.5 in win7 64,I can get the right result.......
I feel confuse about that .

**Comment by wwwusr** [comment] 2016-04-10 02:04
Version 1.5.8 is OK,tested

**Comment by facchinm** [comment] 2016-04-11 07:37
Duplicate of https://github.com/arduino/Arduino/issues/4302, simply update the LiquidCrystal_I2C library and it should work correctly again!

**Closed by facchinm** 2016-04-11 07:37 UTC

**Comment by wwwusr** [comment] 2016-04-11 11:12
Thanks!I'll try like that
