### ISSUE TITLE
[Switch Case] Default bug

### ISSUE THREAD

**Issue by Talabo** [arduino/Arduino#9070] opened 2019-07-16 18:21 UTC
From the Image it's illustrated the code for the Switch Case. It's done with arduino 1.8.9 (Windows Store 1.8.21.0).

The default statement is always runned, even if the given character 'R', 'G', 'B' er sent as command.

![switch_bug](https://user-images.githubusercontent.com/6014776/61319235-16aa2e80-a807-11e9-8074-77fd5c0ef708.png)

**Comment by matthijskooijman** [comment] 2019-07-16 19:28
I suspect the problem is that you are receiving newline characters in addition to your letters, which are handled as invalid commands.

Note that this is not the place to get help with your own projects, but to report bugs in the IDE itself (which this could arguably have been, though). For that reason, I'm closing this as invalid.

**Closed by matthijskooijman** 2019-07-16 19:28 UTC
