### ISSUE TITLE
Arduino Software Crashing When Opened nano v3 (Mac)

### ISSUE THREAD

**Issue by USER8282** [arduino/Arduino#8338] opened 2018-12-28 17:40 UTC

**Comment by per1234** [comment] 2018-12-28 22:12
Due to lack of information, I'll have to guess this is a duplicate of https://github.com/arduino/Arduino/issues/8274

Please test with the [hourly build of the Arduino IDE](https://www.arduino.cc/en/Main/Software#hourly) to see if the problem is resolved. If not, come back here with a thorough description of the problem and I'll reopen the issue.

**Closed by per1234** 2018-12-28 22:12 UTC
Labels: Type: Duplicate
