### ISSUE TITLE
Blurry icons on retina display

### ISSUE THREAD

**Issue by neauoire** [arduino/Arduino#8713] opened 2019-03-28 08:32 UTC
<img width="855" alt="Screen Shot 2019-03-28 at 5 29 47 PM" src="https://user-images.githubusercontent.com/1455726/55142089-27169a80-517f-11e9-8d4c-331f6943a34a.png">

The icons are blurry, and there seems to be a dashed lined under the magnifying glass?

**Comment by per1234** [comment] 2019-03-28 21:24
Closing as duplicate of https://github.com/arduino/Arduino/issues/5850

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2019-03-28 21:24 UTC
Labels: Type: Duplicate
