### ISSUE TITLE
Arduino IDE crashes when trying to save or load

### ISSUE THREAD

**Issue by jakkubu** [arduino/Arduino#3046] opened 2015-04-28 11:31 UTC
In Ubuntu 15.04 with java jre 7 or higher 64 bit. The workaround is to user java jre 6. 

Error: 

    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGSEGV (0xb) at pc=0x00007fb905c3cec7, pid=20916, tid=140431511389952
    #
    # JRE version: OpenJDK Runtime Environment (7.0_79-b14) (build 1.7.0_79-b14)
    # Java VM: OpenJDK 64-Bit Server VM (24.79-b02 mixed mode linux-amd64 compressed oops)
    # Derivative: IcedTea 2.5.5
    # Distribution: Ubuntu Vivid Vervet (development branch), package 7u79-2.5.5-0ubuntu1
    # Problematic frame:
    # C  [libjavagtk.so+0x8ec7]
    #
    # Core dump written. Default location: /opt/arduino-1.6.3/core or core.20916
    #
    # An error report file with more information is saved as:
    # /opt/arduino-1.6.3/hs_err_pid20916.log
    #
    # If you would like to submit a bug report, please include
    # instructions on how to reproduce the bug and visit:
    #   http://icedtea.classpath.org/bugzilla
    #
    ./arduino: line 29: 20916 Aborted                 (core dumped) java -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel $SPLASH processing.app.Base --curdir $CURDIR "$@"

Similar issue in Energia: https://github.com/energia/Energia/issues/466 

hs_err file: http://pastebin.com/E2005Yut

**Comment by ffissore** [comment] 2015-04-28 11:35
Duplicate of #3024
Ubuntu inject jayatana everytime a java app is run, even when executing a simple `java -version` from the command line.
Although nice, we don't support jayatana at the moment.
Try uninstalling jayatana

**Closed by ffissore** 2015-04-28 11:35 UTC
