### ISSUE TITLE
After W10 FALL CREATOR Project store in Onedrive => Error message ( The specific file was not found )

### ISSUE THREAD

**Issue by llist** [arduino/Arduino#6891] opened 2017-11-05 17:25 UTC
Error message: The specific file was not found .
If I move  the directory project in my Hard drive => it's ok
This project compile in OneDrive before Fall Creator update.

Thk

**Comment by per1234** [comment] 2017-11-05 19:40
Closing as duplicate of https://github.com/arduino/Arduino/issues/6867

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2017-11-05 19:40 UTC
