### ISSUE TITLE
Error opening file .ino

### ISSUE THREAD

**Issue by lestofante** [arduino/Arduino#1350] opened 2013-04-05 14:07 UTC
Hi,
if you open a file .ino downloaded, the first time you are prompted about missing folder. 
If you click yes, the folder is created and sketch opened, if no the IDE will exit.

This SEEMS ok BUT: the folder is created into system "temp". So you close the IDE and try to open the file again, you get an error "folder already exist".
Also the request for creating the folder SEEMS to save the skecth into sketchbook.

Proposed fix:
don't ask to create folder but to "import into sketcbook".
If user say yes, create the folder with the INO into sketchbook (if it does not exist)
if user say no, REPLACE the folder in the temp with the current folder + sketch

Or just don't ask nothing and CREATE/REPLACE the folder in temp.

**Comment by ffissore** [comment] 2015-06-05 12:49
I guess this was fixed with #2980 because I can't reproduce it
Fix is available with latest hourly build http://www.arduino.cc/en/Main/Software#hourly

**Closed by ffissore** 2015-06-05 12:49 UTC
Labels: Component: IDE
