### ISSUE TITLE
Mac Full Screen Support

### ISSUE THREAD

**Issue by soumilkanwal80** [arduino/Arduino#7893] opened 2018-08-16 07:38 UTC
Please add support for full screen on mac osx

**Comment by per1234** [comment] 2018-08-16 10:07
It looks like this is a duplicate of https://github.com/arduino/Arduino/issues/1246, which was worked on in https://github.com/arduino/Arduino/pull/3243 but the final decision was to not add the feature.

**Closed by per1234** 2018-08-16 10:07 UTC
Labels: OS: OSX, Type: Duplicate
