### ISSUE TITLE
LiquidCrystal.print() not documented accurately

### ISSUE THREAD

**Issue by rawtaz** [arduino/Arduino#4324] opened 2015-12-21 11:30 UTC
The second argument to LiquidCrystal.print() can be used to specify the number of decimals that should be printed when giving a float as the first argument. But this is not described or mentioned in https://www.arduino.cc/en/Reference/LiquidCrystalPrint, it probably should be.

**Comment by per1234** [comment] 2015-12-22 03:25
@agdl maybe you could just create reference pages for the Print functions and then link to those pages from the relevant reference pages of each library that uses the Print class. The library specific reference pages would contain a description of what the function does in that library and the link to the Print function reference page provides usage details.

**Comment by q2dg** [comment] 2015-12-26 10:10
I'd extent @perl1234 idea to Stream functions too.

**Comment by per1234** [comment] 2017-07-06 11:11
Even though this one came first, I'm closing it as a duplicate of https://github.com/arduino/Arduino/issues/5588 because that issue has slightly more information. I am also transferring the assignment of agdl to #5588, which is currently unassigned.

**Closed by per1234** 2017-07-06 11:11 UTC
Labels: Component: Documentation, Type: Duplicate
