### ISSUE TITLE
Copying text in the Serial Monitor window

### ISSUE THREAD

**Issue by johnsondavies** [arduino/Arduino#4984] opened 2016-05-24 18:13 UTC
If you select text in the Serial Monitor window and copy it to the clipboard, the last selected character gets omitted.

Tested on Arduino 1.6.8 on MacOS.

**Comment by pierreverbakel** [comment] 2017-11-09 14:40
I would realy (really!) like to have a Button below in the Serial Monitor window 'Copy to Clipboard'.  When having like 10.000 lines of continuous output it is nice look for specific moments of the run time, to see what my sketch did, measured, or decided. I really do not understand how this can be version 1.84 and not having such a Windows 1.0 function to be honest. Piece of cake to implement, loads of rewards.

**Comment by oldmanegan** [comment] 2017-11-09 14:55
On a Mac I do Cmd+A to select All then Cmd+C to copy to clipboard. There must be a windows analogue of this. Really need a button?

**Comment by facchinm** [comment] 2017-11-09 16:41
I just tested it on IDE 1.8.5 on OSX Sierra and it works correctly. Closing as solved, please reopen if the issue is still there on your configuration.

**Closed by facchinm** 2017-11-09 16:41 UTC
Labels: Component: IDE Serial monitor
