### ISSUE TITLE
ATmega8U2 usb-serial firmware doesn't work at 300 (UBBR overflows) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#542] opened 2012-11-15 18:38 UTC
This is [Issue 542](http://code.google.com/p/arduino/issues/detail?id=542) moved from a Google Code project.
Added by 2011-05-14T16:29:29.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Build
### Original description

The ATmega8U2 firmware overflows UBBR at 300 baud because it sets the U2X bit, yielding a setting that overflows the 12-bits.  This was masked previously because the Arduino core contained the same bug: (issue #522).  I'm fixing that bug, though, so we should fix the firmware too.

**Comment by per1234** [comment] 2017-07-04 18:37
Closing as duplicate of https://github.com/arduino/Arduino/issues/4714 because that issue has more information.

**Closed by per1234** 2017-07-04 18:37 UTC
Labels: Type: Bug, Type: Duplicate
