### ISSUE TITLE
No menu to list currently opened sketches in MacOS X

### ISSUE THREAD

**Issue by nesdnuma** [arduino/Arduino#5256] opened 2016-08-16 16:19 UTC
With several sketches opened simultaneously, it's a real pain to navigate between them whenever any of them is hidden. Adding a "sketches" menu listing all the currently open sketches would help a lot.

**Comment by oldmanegan** [comment] 2016-08-16 18:09
Of course, there is Command + ~ to rotate through open sketches currently, which is barely acceptable. And it seems to not follow a predefined order, instead it moves forward through the list of open sketches until you work on a sketch, then the next time it moves backward through the list. Would be nice to have the menu of open sketches along the bottom bar, as well as the open hardware configs, to make it easy on users with different sketches using different HW configs open.
Regards,

John
johnvegan@gmail.com

**Comment by nesdnuma** [comment] 2016-08-16 18:33
By the way, there's no dedicated ~ key on French azerty keyboards, so the mentioned shortcut is not even possible for me. However one can install [this little app](url=http://manytricks.com/witch/).

**Comment by lmihalkovic** [comment] 2016-08-24 02:51
See #234 
Seems it was first requested in 2010...

**Comment by per1234** [comment] 2017-07-05 20:58
Thanks for pointing that out @lmihalkovic!

Closing as duplicate of https://github.com/arduino/Arduino/issues/234

**Closed by per1234** 2017-07-05 20:58 UTC
Labels: Type: Duplicate
