### ISSUE TITLE
Missing page behind links in documentation Playground

### ISSUE THREAD

**Issue by BraveTea** [arduino/Arduino#5907] opened 2017-01-24 09:14 UTC
I am not entirely sure I am supposed to report Playground documentation issues here, but I couldn't find information to that regard.

on page:
http://playground.arduino.cc/Learning/AtmegaStandalone

under heading <i>Is it Simple?</i> there are two links to external websites. Both links are faulty and redirect to no longer existing pages.

I then proceeded to quickly go through some of the other links, but most of them are no longer valid. 
To be honest I have not taken the time to list all of them here, because the list seems to be quite lengthy. Apologies.

**Comment by per1234** [comment] 2017-01-24 11:05
Duplicate of https://github.com/arduino/Arduino/issues/4836 and https://github.com/arduino/Arduino/issues/4028. Please do a search at:
https://github.com/arduino/Arduino/issues?&q=
before submitting issue reports to make sure they haven't already been reported.

The Arduino Playground is a publicly editable wiki. Maintaining the content is the responsibility of the Arduino community. You are free to improve that page if you like. If you can't find an update for the dead links you can often find the content in the [Wayback Machine](https://archive.org/web/) and update the dead links to point to the archived pages.

I looked over that page after one of the previous issue reports and deciding it wasn't worth the time to fix it up since https://www.arduino.cc/en/Tutorial/ArduinoToBreadboard and https://www.arduino.cc/en/Main/Standalone pretty much cover all the same information. I have added a note to the top of the playground page with a link to those tutorial pages.

**Closed** 2017-01-25 10:09 UTC
Labels: Type: Duplicate
