### ISSUE TITLE
bump: ANSI-compatible sprintf() feat. "%f" even for AVRs

### ISSUE THREAD

**Issue by shiftleftplusone** [arduino/Arduino#3588] opened 2015-07-26 09:21 UTC
as my former bug report has been closed and not reactivated, I now try it other way round, explaining the problem from another point of view:

sprintf currently does not support the formatter "%f" for AVR by default 
(for the Due it works by default nevertheless.)
Installing a lib.c float patch overwriting all lib.c one can also make "%f" work for AVR:
http://www.mindstormsforum.de/viewtopic.php?f=70&t=8624&p=67238#p67238
http://www.mindstormsforum.de/download/file.php?id=810

The point is:
"%f" is a legal formatter to ANSI C sprintf, so it should be also the default for AVR.
If one don't want the "%f" overhead for very small AVRs one must be able to exclude it from being linked, and should use a different downstripped "sprintf_min()" version.

OR:
please enable a compiler switch or anything to switch between 
"sprintf WITH %f" 
versus 
"sprintf WITHOUT %f" 

But anyway, as sprintf() WITH the "%f"  feature is ANSI standard it should always be the Arduino AVR standard by default.
Who ever does not want this standard feature (e.g., for memory reasons) should be able to exclude it and get rid of it -
OR
one should be able to #include < stdio.h> feat. all stdio "%f" features,
and who ever does not want sprintf and either stdio.h features simply can choose 
NOT to #include < stdio.h> -

and this is what I actually want to be implemented.

**Comment by per1234** [comment] 2017-07-03 20:06
Closing as duplicate of https://github.com/arduino/Arduino/issues/5033, where this was discussed in great detail.

**Closed by per1234** 2017-07-03 20:06 UTC
Labels: Type: Duplicate
