### ISSUE TITLE
Possibility to specify compilation flags to arduino-builder from the IDE

### ISSUE THREAD

**Issue by clasqui** [arduino/Arduino#11108] opened 2020-12-28 16:22 UTC
## Description
Add a space on the Arduino IDE to specify compilation settings, specifically flags to be passed to arduino-builder and the avr toolchain, like definitions.

## Justification
It would be very useful to be able to define some constants at compile time, for example when there is a secret value that you don't want to put in your code (maybe because you open source your project). Therefore, you could tell the IDE to use the -D flag with your value when compiling, and then the preprocessor would add that value to the program.

**Comment by per1234** [comment] 2020-12-28 16:26
Closing as duplicate of https://github.com/arduino/Arduino/issues/421

**Closed by per1234** 2020-12-28 16:26 UTC
