### ISSUE TITLE
Persistent Board Setting

### ISSUE THREAD

**Issue by BADnetwork** [arduino/Arduino#4950] opened 2016-05-14 19:09 UTC
A great feature to add would be for each sketch to remember the board it was compiled for, if a write a sketch for a uno, it would add a file to the sketch folder with '328p, 16MHz, Bootloader' etc So when I open it next time, It auto chooses the correct 'tools' setting.

**Comment by jsotola** [comment] 2016-05-24 00:17
maybe it would be better if the settings were in the sketch itself in a form of a comment on first line,
or a #pragma line
that way the settings would be applied to a sketch that was copied from the internet

**Comment by per1234** [comment] 2017-03-21 01:20
Duplicate of #1481

**Closed** 2017-07-01 11:43 UTC
Labels: Type: Duplicate
