### ISSUE TITLE
Ctrl+"-" decreases font size, but Ctrl+"+" does nothing

### ISSUE THREAD

**Issue by teo1978** [arduino/Arduino#8091] opened 2018-10-12 18:26 UTC
I accidentally hit Ctrl+Minus and unintentionally decreased font size.
So I obviously thought Ctrl+Plus would revert that, but it doesn't.

Now I notice this, almost surely related:
![image](https://user-images.githubusercontent.com/542107/46887061-e9d28080-ce5c-11e8-83d9-2056bbc60d45.png)

I guess this has to do with the fact that I use a Spanish keyboard.

Note that EVERY other software that has Ctrl+Plus/Minus shortcuts for increasing/decreasing stuff (e.g. Chrome for zooming in/out) work fine on the same keyboard.

**Comment by per1234** [comment] 2018-10-12 21:28
Closing as duplicate of https://github.com/arduino/Arduino/issues/6806, which was fixed 2 months ago by https://github.com/arduino/Arduino/pull/7888.

Please always test with the hourly build of the Arduino IDE before reporting a bug to be sure it hasn't already been fixed:
https://www.arduino.cc/en/Main/Software#hourly

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-10-12 21:28 UTC
Labels: Type: Duplicate

**Comment by per1234** [comment] 2018-10-12 21:48
>Decent bug trackers automatically search for similar issues based on the title and/or description and show results when submitting. When they do, I do take the time to check if any of them is the issue I'm reporting.

Well GitHub doesn't have this feature. If you won't make the effort to search, I have to do it for you. I'm a volunteer so I don't get paid to do that. Why is my time worth less than yours? Even after duplicates are closed, they continue to clog up the search results forevermore, making it even more difficult for people to search for existing issues. They also result in spam to the 957 people who watch this repository and get an email for every issue that's opened, closed, or commented on.
