### ISSUE TITLE
Error in Eagle schematic for Nano?

### ISSUE THREAD

**Issue by ehJayGee** [arduino/Arduino#9206] opened 2019-09-10 02:52 UTC
Re: https://content.arduino.cc/assets/Nano-reference.zip

I am using Eagle 9.5.0.  Opening the NanoV3.3.sch gives the following:

Error:

line 177, column 25: Unexpected ''.

Is there a fix or workaround?

Many thanks.

**Comment by per1234** [comment] 2019-09-10 03:08
Closing as duplicate of https://github.com/arduino/Arduino/issues/6039

Note the comment in that thread:
>we use eagle version 7 sorry for this. We are not planning to support eagle 8 at the moment

With Eagle 7.x the files open fine. I recommend using the latest release of the 7 series: 7.7.0. This was the last version of Eagle before Autodesk took over and required an Autodesk account to use Eagle.

There are also fixes described in https://github.com/arduino/Arduino/issues/6039.

**Closed by per1234** 2019-09-10 03:08 UTC
