### ISSUE TITLE
Serial Monitor Fails to Respont to <CR> (\r)

### ISSUE THREAD

**Issue by randym52** [arduino/Arduino#3729] opened 2015-08-26 05:03 UTC
The Serial monitor on ver 1.6.5 does not respond to carriage return. 
CR or \r. It should return to the beginning of line. At this time it does nothing.

**Comment by matthijskooijman** [comment] 2015-08-26 07:40
This is a duplicate of #3654, which is closed as wontfix. Please refer to that issue for details.

**Closed by matthijskooijman** 2015-08-26 07:40 UTC
Labels: Type: Duplicate

**Comment by VogonJeltz** [comment] 2015-08-26 07:45
I also would appreciate Carriage-Return (without Linefeed) plus Backspace.
