### ISSUE TITLE
[ macOS issue ] Inputed twice during copy function ( control + c , control + v )

### ISSUE THREAD

**Issue by dndi0489** [arduino/Arduino#7963] opened 2018-09-02 12:46 UTC
Sometimes, when you copy and paste a specific command, 
you encounter problems that are entered twice.

There are times when this problem happens and times when it doesn't, but it usually happens. 
The same is true of version 1.8.6.

**Comment by per1234** [comment] 2018-09-02 12:48
Closing as duplicate of https://github.com/arduino/Arduino/issues/7061

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-09-02 12:48 UTC
Labels: Type: Duplicate
