### ISSUE TITLE
LiquidCrystal::begin() documentation update request

### ISSUE THREAD

**Issue by wolfman1138** [arduino/Arduino#5563] opened 2016-11-05 08:41 UTC
Hi Folks,

I ran across an interesting 1 line LCD display that had 5x10 characters instead of the normal 5x8. 

I searched google a bunch and found the source table for the 32 extended characters (http://lcd-linux.sourceforge.net/pdfdocs/hd44780.pdf; Table 4) but could not find anywhere how to get them to display properly using my Arduino and the LiquidCrystal library.

I tried a number of things to to get it to display the extended characters with no success.  But when I dug into the library source code I found that there was a [hidden option in lcd.begin()](https://github.com/arduino-libraries/LiquidCrystal/blob/1.0.4/src/LiquidCrystal.h#L62) that allowed me to define the extended 5x10 font support. (yeah!)

If the documentation (https://www.arduino.cc/en/Reference/LiquidCrystalBegin) could be updated to something along the lines of this, that would be great.

`lcd.begin(cols, rows [, dotsize])`

Optional Parameters:

dotsize: enable 5x10 extended fonts on compatible one line displays (1 = Enable 5x10, 0 = Enable 5x8)

The third optional parameter dotsize is set to a 1 to enable drop fonts for displays with 5x10 characters.  This allows for printing characters like g,j,p,q and y that extend below the virtual line.  These extending characters can be found in the lcd character map between xE0 and xFF.
If set to a 0, the extended characters are truncated to 5x8.

**Comment by buddywhitman** [comment] 2021-12-26 17:03
hey @kengdahl are you working on this issue... if not, i can try to fix the docs by the next weekend (:

**Comment by kengdahl** [comment] 2022-02-09 09:27
@buddywhitman Please make a pull request with the changes you want :)

**Comment by igmtz** [comment] 2023-04-04 18:07
Hey @kengdahl ! I'm looking for my first issue in the open-source world. I would like to contribute with this, is someone currently working on the documentation?

**Comment by buddywhitman** [comment] 2023-05-09 07:51
> @buddywhitman Please make a pull request with the changes you want and me and @per1234 will look at the suggestions :)

<img width="960" alt="image" src="https://user-images.githubusercontent.com/39520468/237030430-91c6714c-e490-4cf4-b244-686871291a2c.png">
I figured it out and will make a pull request now. Kindly approve!

**Comment by per1234** [comment] 2023-05-11 05:50
Thanks so much for your pull request @buddywhitman, and for your attention to this issue!

As you pointed out, we now have a dedicated repository for the LiquidCrystal library so the issue is off topic for this repository. Since we have your pull request, we can close this issue without risking forgetting about the task so I'll do that now.

**Closed by per1234** 2023-05-11 05:50 UTC
Labels: Component: Documentation, Type: Bug, Library: LiquidCrystal

**Comment by buddywhitman** [comment] 2023-05-11 05:53
Thanks @per1234 could you also remind the users with write access on the LiquidCrystal repository to merge the pull request after review. I noticed they haven't been active for over a year.
