### ISSUE TITLE
Character modifying key combinations do not work

### ISSUE THREAD

**Issue by stolendata** [arduino/Arduino#2864] opened 2015-03-31 21:01 UTC
Character modifying key combinations such as tilde (alt-gr + ~), umlaut (¨) and other accents do not work in the IDE. The modifying keystroke is accepted, but the following keystroke never outputs a character.

The problem is in both 1.5.8 and 1.6.1, and I have only tested this on Linux Mint 16 and 17.1 32-bit.

**Comment by stolendata** [comment] 2015-04-15 11:30
Fix: https://github.com/arduino-org/Arduino/commit/5d429fa62f7e2907bfc568a3abc06a2ffad14a12

**Comment by ffissore** [comment] 2015-04-22 07:33
Closing as duplicate of #2620. A fix is on its way

**Closed by ffissore** 2015-04-22 07:33 UTC

**Comment by ffissore** [comment] 2015-04-23 16:17
Issue is being fixed with a brand new editor. See #3019

**Comment by ffissore** [comment] 2015-05-07 15:41
#3019 merged. Next hourly build and IDE 1.6.5 will contain the fix
