### ISSUE TITLE
Autoformat trashes fancy comments...

### ISSUE THREAD

**Issue by WestfW** [arduino/Arduino#8187] opened 2018-11-10 01:51 UTC
If I start with a nice (and relatively standard) command block like:

```
/****************************************************
 *  Test program for digitalWriteFast()             *
 *  November 2018, by Bill Westfield.               *
 *  This test sketch is in the Public Domain        *
 ****************************************************
 *                                                  *
 * This sketch isn't really meant to be run.        *
 *  Rather, you compile it and look at the code     *
 *  that has been created to confirm that it has    *
 *  the appropriate minimal instruction sequences.  *
 *                                                  *
 *  Test matrix:                                    *
 *                                                  *
 *     Arduino Core  Boards:                        *
 *                                                  *
 *      Uno (xx8)                                   *
 *      Micro (32u4)                                *
 *      Mega                                        *
 *                                                  *
```
And then use "autoformat", it deletes all of my carefully added "asterisk blocks" and leaves only:
```

/****************************************************
    Test program for digitalWriteFast()
    November 2018, by Bill Westfield.
    This test sketch is in the Public Domain
 ****************************************************
 *                                                  *
   This sketch isn't really meant to be run.
    Rather, you compile it and look at the code
    that has been created to confirm that it has
    the appropriate minimal instruction sequences.
 *                                                  *
    Test matrix:
 *                                                  *
       Arduino Core  Boards:
 *                                                  *
        Uno (xx8)
        Micro (32u4)
        Mega
 *                                                  */
```

**Comment by per1234** [comment] 2018-11-10 03:43
This is caused by the [`remove-comment-prefix` Artistic Style option](http://astyle.sourceforge.net/astyle.html#_remove-comment-prefix):
https://github.com/arduino/Arduino/blob/799879e8ae9f0cb76c7a76f4e945347b92d6352d/build/shared/lib/formatter.conf#L31

Related issue: https://github.com/arduino/Arduino/issues/3941

**Comment by WestfW** [comment] 2018-11-11 01:50
I would prefer that autoformat not touch comments, perhaps with the exception of indenting already indented comments to match the code indentation...

**Comment by per1234** [comment] 2021-04-05 06:33
Closing as wontfix because the current Artistic Style configuration is now thoroughly established and each user can configure it to their preference.

The new [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html)-based auto formatter of Arduino IDE 2.x does not mess with the fanciness of block comments at all, so the future looks bright.

**Closed by per1234** 2021-04-05 06:33 UTC
Labels: Component: IDE, feature request
