### ISSUE TITLE
MacOS X High Sierra - Menu missing

### ISSUE THREAD

**Issue by GermanSheepDog** [arduino/Arduino#6747] opened 2017-09-21 12:36 UTC
At version Mac OS X High Sierra 10.13 Beta (17A362a) and Arduino 1.8.4 (and 1.8.3) there is no completely menu  at the mac. Only the top menu line "Arduino" is visible, nothing more!

<img width="297" alt="macosx" src="https://user-images.githubusercontent.com/15141568/30695785-b6cf469a-9ed9-11e7-8b85-a4213fbb18d5.png">

At previous version of Mac OS X High Sierra Beta (=10.12) and Arduino 1.8.3 everything was okay.

**Comment by per1234** [comment] 2017-09-21 13:09
Closing as duplicate of https://github.com/arduino/Arduino/issues/6548

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2017-09-21 13:09 UTC
