### ISSUE TITLE
Arduino IDE can not open ！Something must be wrong ！

### ISSUE THREAD

**Issue by xp187oo** [arduino/Arduino#10341] opened 2020-06-10 06:51 UTC
java.lang.NullPointerException
        at cc.arduino.contributions.packages.ContributionsIndexer.parseIndex(ContributionsIndexer.java:134)
        at processing.app.BaseNoGui.initPackages(BaseNoGui.java:483)
        at processing.app.Base.<init>(Base.java:273)
        at processing.app.Base.main(Base.java:150)

**Comment by AkhilGKrishnan** [comment] 2020-06-10 07:03
@xp187oo  I am facing the same issue. when i open board manager

**Comment by hmeijdam** [comment] 2020-06-10 07:09
If you look at the forum  https://forum.arduino.cc/index.php?board=2.0  you will see that everyone has this problem. One of the files that the "boards manager" is downloading must cause a data corruption. I have it in the older IDE versions also, so not just 1.8.12

**Comment by jandrassy** [comment] 2020-06-10 07:19
it looks like Arduino's package_index.json is the corrupted one. no way around

**Comment by imrehorvath** [comment] 2020-06-10 07:29
Duplicate of https://github.com/arduino/Arduino/issues/10340

**Comment by jandrassy** [comment] 2020-06-10 07:34
problem is a new section `arduino-beta` for Portenta H7

**Comment by cmaglie** [comment] 2020-06-10 08:29
We had a problem on our package_index.json that caused the error and prevented the IDE to start.
Now the package_index has been fixed, but to recover a working installation you must delete once again the package_index.json with the cache folder and restart the IDE as usual.

Windows:
* remove file C:\Users\YourUsername\AppData\Local\Arduino15\package_index.json
* remove folder C:\Users\YourUsername\AppData\Local\Arduino15\cache

Mac:
* remove file /Users/YourUsername/Library/Arduino15/package_index.json
* remove folder /Users/YourUsername/Library/Arduino15/cache

Linux:
* remove file /home/YourUsername/.arduino15/package_index.json
* remove folder /home/YourUsername/.arduino15/cache

Please note that the problem that prevents the IDE to start has already been fixed and it's ready for the next release, that's the reason why the Nightly/Beta Builds are not affected, and also the reason why we did not detect this problem earlier, sorry about that!

**Closed by cmaglie** 2020-06-10 08:29 UTC

**Comment by Hamid11300** [comment] 2020-06-16 06:25
> We had a problem on our package_index.json that caused the error and prevented the IDE to start.
> Now the package_index has been fixed, but to recover a working installation you must delete once again the package_index.json with the cache folder and restart the IDE as usual.
> 
> Windows:
> 
> * remove file C:\Users\YourUsername\AppData\Local\Arduino15\package_index.json
> * remove folder C:\Users\YourUsername\AppData\Local\Arduino15\cache
> 
> Mac:
> 
> * remove file /Users/YourUsername/Library/Arduino15/package_index.json
> * remove folder /Users/YourUsername/Library/Arduino15/cache
> 
> Linux:
> 
> * remove file /home/YourUsername/.arduino15/package_index.json
> * remove folder /home/YourUsername/.arduino15/cache
> 
> Please note that the problem that prevents the IDE to start has already been fixed and it's ready for the next release, that's the reason why the Nightly/Beta Builds are not affected, and also the reason why we did not detect this problem earlier, sorry about that!

Big Like

**Comment by xp187oo** [comment] 2020-06-16 06:30
Thank you for replay，man.&nbsp; &nbsp;I had empty&nbsp;C:\Users\YourUsername\AppData\Local\Arduino15\&nbsp; &nbsp;and&nbsp; it works .&nbsp; &nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hamid11300"<notifications@github.com&gt;; 
发送时间: 2020年6月16日(星期二) 下午2:25
收件人: "arduino/Arduino"<Arduino@noreply.github.com&gt;; 
抄送: "呵呵"<1392206007@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [arduino/Arduino] Arduino IDE can not open ！Something must be wrong ！ (#10341)





  
We had a problem on our package_index.json that caused the error and prevented the IDE to start.
 Now the package_index has been fixed, but to recover a working installation you must delete once again the package_index.json with the cache folder and restart the IDE as usual.
 
Windows:
  
remove file C:\Users\YourUsername\AppData\Local\Arduino15\package_index.json
 
remove folder C:\Users\YourUsername\AppData\Local\Arduino15\cache
  
Mac:
  
remove file /Users/YourUsername/Library/Arduino15/package_index.json
 
remove folder /Users/YourUsername/Library/Arduino15/cache
  
Linux:
  
remove file /home/YourUsername/.arduino15/package_index.json
 
remove folder /home/YourUsername/.arduino15/cache
  
Please note that the problem that prevents the IDE to start has already been fixed and it's ready for the next release, that's the reason why the Nightly/Beta Builds are not affected, and also the reason why we did not detect this problem earlier, sorry about that!
  
Big Like
