### ISSUE TITLE
Slave example for Wire master reader tutorial incorrect

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/Arduino#10134] opened 2020-05-02 17:30 UTC
The slave example in the masterreader tutorial is the same as in the masterwriter tutorial.

This used to be correct in the past.

PS
Please move if needed.

**Comment by per1234** [comment] 2020-05-02 20:45
Closing as duplicate of https://github.com/arduino/Arduino/issues/9740

**Closed by per1234** 2020-05-02 20:45 UTC
