### ISSUE TITLE
ADK link to Arduino documentation error

### ISSUE THREAD

**Issue by jgrina** [arduino/Arduino#2410] opened 2014-11-04 01:57 UTC
-------- Arduino's ADK documentation.  ------

Reference   Language | Libraries | Comparison | Changes

The page "Reference/AndroidAccessory" doesn't exist.

Reference Home

Corrections, suggestions, and new documentation should be posted to the Forum.

The text of the Arduino reference is licensed under a Creative Commons Attribution-ShareAlike 3.0 License. Code samples in the reference are released into the public domain.

**Comment by nickgammon** [comment] 2015-02-28 20:43
Confirmed. On page: http://arduino.cc/en/Main/ArduinoBoardMegaADK

Link to "Arduino's ADK documentation." which is http://arduino.cc/en/Reference/AndroidAccessory

Gives this error: "The page "Reference/AndroidAccessory" doesn't exist. ".

Can this be fixed?

Reported here: http://forum.arduino.cc/index.php?topic=304300

**Comment by agdl** [comment] 2015-04-03 10:25
@nickgammon @jgrina  all the ADK documentation created by Arduino will be online soon!

**Comment by Lauszus** [comment] 2015-04-03 14:47
@agdl my name is spelled wrong on this page: http://arduino.cc/en/Main/ArduinoBoardMegaADK. It's "Lauszus" not "Lauzus" ;)

Also it is missing some of the other developers. Please see this page: http://arduino.cc/en/Main/ArduinoUSBHostShield which list them all correctly.

**Comment by agdl** [comment] 2015-04-03 15:04
@Lauszus done sorry about the typo and the missing people

**Comment by Lauszus** [comment] 2015-04-03 15:06
@agdl thanks :)

**Comment by agdl** [comment] 2016-01-04 10:34
Sorry about this, but I'm closing this, since the ADK hardware is marked as retired and the documentation will not be online any more :(

**Closed by agdl** 2016-01-04 10:34 UTC
Labels: Component: Documentation, Type: Bug
