### ISSUE TITLE
[Manual] Can't find reference/Guide_Windows.html and reference/Guide_MacOSX.html in README.md

### ISSUE THREAD

**Issue by HirotakaTakayama** [arduino/Arduino#3509] opened 2015-07-12 04:52 UTC
README.md needs to be updated. 
Because I can't find reference/Guide_MacOSX.html file on README.md. 
Is the installation page "https://github.com/arduino/Arduino/wiki/Building-Arduino"?

This text should be changed:

    Detailed instructions are in reference/Guide_Windows.html and reference/Guide_MacOSX.html. 
    For Linux, see the Arduino playground: http://www.arduino.cc/playground/Learning/Linux

I recommend replacing it with this:

    Detailed instructions are in https://github.com/arduino/Arduino/wiki/Building-Arduino

**Comment by agdl** [comment] 2015-09-01 12:27
this is a duplicate of https://github.com/arduino/Arduino/issues/2596

**Closed by agdl** 2015-09-01 12:27 UTC
Labels: Component: Documentation, Type: Duplicate

**Comment by sinisterrook** [comment] 2015-11-22 23:31
Seems to be still relevant
