### ISSUE TITLE
Arduino fails to compile a sketch with tabs on ubuntu if path contains accent

### ISSUE THREAD

**Issue by Vincent14** [arduino/Arduino#5463] opened 2016-10-06 16:49 UTC
Tested on Ubuntu with Arduino 1.6.12 taken from arduino.cc website.

**Comment by facchinm** [comment] 2016-10-07 07:28
Hi @Vincent14 , the bug is not confirmed (I could not reproduce on my systems). Could you post the complete verbose compilation output and a minimal multitab sketch triggering the issue?

**Comment by Vincent14** [comment] 2016-10-07 16:31
You're right, the problem is not the space but the accent "à". Have a try with [this project](http://dl.free.fr/grhM2Llve). Here is the full trace:

> /media/Stockage/Bureau/à/cubeled_v1.2/cubeled_v1.2.ino: In function 'void setup()':
> cubeled_v1.2:28: error: 'cubeBegin' was not declared in this scope
>    cubeBegin();
>              ^
> cubeled_v1.2:29: error: 'initLeds' was not declared in this scope
>    initLeds();
>             ^
> cubeled_v1.2:30: error: 'loadParams' was not declared in this scope
>    loadParams();
>               ^
> /media/Stockage/Bureau/à/cubeled_v1.2/cubeled_v1.2.ino: In function 'void loop()':
> cubeled_v1.2:39: error: 'refreshFrame' was not declared in this scope
>    if (refresh && changed) refreshFrame();
>                                         ^
> cubeled_v1.2:44: error: 'drawLeds' was not declared in this scope
>        drawLeds();
>                 ^
> cubeled_v1.2:48: error: 'drawLeds' was not declared in this scope
>    else drawLeds();
>                  ^
> /media/Stockage/Bureau/à/cubeled_v1.2/cubeled_v1.2.ino: In function 'void serialEvent()':
> cubeled_v1.2:58: error: 'parse' was not declared in this scope
>      parse(input);
>                 ^
> /media/Stockage/Bureau/à/cubeled_v1.2/config.ino: In function 'void refreshFrame()':
> config:73: error: 'copyFrame' was not declared in this scope
>    copyFrame(bufferFrame, actualFrame);
>                                      ^
> /media/Stockage/Bureau/à/cubeled_v1.2/parser.ino: In function 'void parse(byte)':
> parser:54: error: 'execute' was not declared in this scope
>          if (input == EOP) execute();
>                                    ^
> /media/Stockage/Bureau/à/cubeled_v1.2/parser.ino: In function 'void execute()':
> parser:265: error: 'MOVE' was not declared in this scope
>          MOVE(buffer[0], 1, false);
>                                  ^
> parser:269: error: 'MOVE' was not declared in this scope
>          MOVE(buffer[0], buffer[1], false);
>                                          ^
> parser:276: error: 'MOVE' was not declared in this scope
>          MOVE(buffer[0], 1, true);
>                                 ^
> parser:280: error: 'MOVE' was not declared in this scope
>          MOVE(buffer[0], buffer[1], true);
>                                         ^
> exit status 1
> 'cubeBegin' was not declared in this scope

**Comment by oqibidipo** [comment] 2016-10-08 00:33
This looks like #5216 and #5277.

**Comment by Vincent14** [comment] 2016-10-08 08:23
Yes, you're right

**Comment by dlabun** [comment] 2016-10-13 21:22
Any non-ASCII character will give you problems... There an open PR for Arduino builder that should fix the issue. [https://github.com/arduino/arduino-builder/pull/178]

**Comment by facchinm** [comment] 2016-10-20 12:27
Closing as duplicate of #5216

**Closed by facchinm** 2016-10-20 12:27 UTC
Labels: Waiting for feedback
