### ISSUE TITLE
code compiles if we write anything after header line #include "pins_arduino.h"cccsdsdasd

### ISSUE THREAD

**Issue by ashwanisihag** [arduino/Arduino#6653] opened 2017-08-25 18:20 UTC
code complied even we write anything after header line 
#include <avr/wdt.h>cccsdsdasd

**Comment by per1234** [comment] 2017-08-25 20:43
I can't reproduce this with Arduino IDE 1.8.4:
```
C:\Users\per\AppData\Local\Temp\arduino_modified_sketch_482279\sketch_aug25a.ino:1:31: fatal error: e:\arduinoide\arduino-1.8.4\hardware\tools\avr\avr\include\avr\wdt.h>cccsdsdas: Invalid argument
 #include <avr/wdt.h>cccsdsdasd
                               ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Uno.
```
Which version of the Arduino IDE are you using? Which board are you compiling for?

**Comment by feikname** [comment] 2017-08-25 23:33
I can't reproduce it here either unless I explicitly do `#define cccsdsdasd` before.

However, if I add an space (i.e. `#include <avr/wdt.h> cccsdsdasd` it compiles without problems and produces the following warning:
```text
/tmp/arduino_modified_sketch_261955/sketch_aug25a.ino:1:22: warning: extra tokens at end of #include directive
 #include <avr/wdt.h> cccsdsdasd
```

Which, in my opinion, is the best behavior.

**Comment by cmaglie** [comment] 2017-09-01 13:05
@ashwanisihag I'm closing this as invalid, feel free to comment further if you have any other information to provide.

**Closed by cmaglie** 2017-09-01 13:05 UTC
