### ISSUE TITLE
Arduino Due freezes just after declaring a Rtc_Pcf8563 type object in 1.8.1 IDE.

### ISSUE THREAD

**Issue by linzym** [arduino/Arduino#5992] opened 2017-02-16 07:39 UTC
I think that the wire library is a standard library for all arduino boards. But when I use the wire library on an arduino due board, I find it doesn't work, even if I use an example code and comment out any other statements related with the instance rtc.

I use the code below just for a test:

#include <Wire.h>
#include <DueRtcPcf8563.h>

//init the real time clock
Rtc_Pcf8563 rtc;

void setup()
{
  //clear out the registers
  //rtc.initClock();
  //set a time to start with.
  //day, weekday, month, century(1=1900, 0=2000), year(0-99)
 // rtc.setDate(14, 6, 3, 1, 10);
  //hr, min, sec
 // rtc.setTime(1, 15, 0);
  Serial.begin(9600);
}

void loop()
{
  //both format functions call the internal getTime() so that the 
  //formatted strings are at the current time/date.
  //Serial.print(rtc.formatTime());
  Serial.print("\r\n");
 // Serial.print(rtc.formatDate());
  Serial.print("\r\n");
  delay(1000);

  //debug
  Serial.write(0x5A);
}

What's the problem with the wire or twi library running on an Arduino Due board?

**Comment by facchinm** [comment] 2017-02-16 08:51
Duplicate of #5993

**Closed by facchinm** 2017-02-16 08:51 UTC
