### ISSUE TITLE
[Boards-Menue: Upload Speed]: Problem when Switching between different platforms

### ISSUE THREAD

**Issue by hasenradball** [arduino/Arduino#8837] opened 2019-05-01 08:42 UTC
Hello Guys I found some Issue, can any one Help me to detect the root cause?

The issue is:
if I switch back from ESP32 -> ESP8266 Hardware I recognized that the The UploadSpeed is not corectly filled with Values.
I had to restart the Arduino IDE that the upload meue behaves correctly.
I found some diferences in the Menue definition in the Boards.txt files.
Maybe the menues regarding the Upload speed have different names, could that be the issue?

![ESP8266](https://user-images.githubusercontent.com/26808969/57010561-90b21a80-6bfd-11e9-99ea-09b451b49584.JPG)

![ESP32](https://user-images.githubusercontent.com/26808969/57010568-9d367300-6bfd-11e9-9bca-b3ed952214c5.JPG)

**Comment by per1234** [comment] 2019-05-04 09:37
Closing as duplicate of https://github.com/arduino/Arduino/issues/5260

**Closed by per1234** 2019-05-04 09:37 UTC
Labels: Type: Duplicate
