### ISSUE TITLE
Taskbar icon in arduino installer and application

### ISSUE THREAD

**Issue by shloma** [arduino/Arduino#3587] opened 2015-07-26 04:39 UTC
Taskbar icon in arduino installer look is very nice, but in arduino application (ide) look very dirty (look likw jpeg low quality) (my os is windows 7 sp1)

https://onedrive.live.com/redir?resid=66F6F4A579CB43B0!4129&authkey=!AHyNxF5NGxgSSrM&v=3&ithint=photo%2cjpg
please fix this...

**Comment by carlosperate** [comment] 2015-07-26 04:43
This is a duplicate of https://github.com/arduino/Arduino/issues/3473

**Comment by matthijskooijman** [comment] 2015-07-26 09:49
Thanks for pointing that out, closing as duplicate.

**Closed by matthijskooijman** 2015-07-26 09:49 UTC
Labels: Type: Duplicate
