### ISSUE TITLE
Feature request: Option to overwrite library examples

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#2619] opened 2015-02-10 16:42 UTC
Library examples are protected. Since I am developing them it would be nice to set add a checkbox to the settings which allows to edit the files. Or maybe a special "dev/advanced" section for that stuff in settings would be nice. Then we could also add other stuff people suggested but not bother beginners too much.

**Comment by ffissore** [comment] 2015-08-05 06:45
Closing as duplicate of #3512. Despite this being older, #3512 raised more attention

**Closed by ffissore** 2015-08-05 06:45 UTC

**Comment by ffissore** [comment] 2015-08-05 15:09
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly. See #3512 for how to make it work
