### ISSUE TITLE
Arduino Nano wrong Optiboot bootloader size 

### ISSUE THREAD

**Issue by PiotrC1** [arduino/Arduino#7341] opened 2018-03-18 13:21 UTC
In file
`AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.21\boards.txt
`
 there are wrong parameters for Arduino Nano new bootloader (Optiboot):

There is:
`
nano.menu.cpu.atmega328.upload.maximum_size=30720
...
nano.menu.cpu.atmega328.bootloader.high_fuses=0xDA
`

And it should be (same as for Uno):
`
nano.menu.cpu.atmega328.upload.maximum_size=32256
...
nano.menu.cpu.atmega328.bootloader.high_fuses=0xDE
`

as Optiboot bootloader is 512 byte long and not 2014 bytes as old one.

**Comment by per1234** [comment] 2018-03-18 13:24
Closing as duplicate of https://github.com/arduino/ArduinoCore-avr/issues/10

**Closed by per1234** 2018-03-18 13:24 UTC
