### ISSUE TITLE
Documentation: Hacking/WiFiShieldFirmwareUpgrading points to a bad firmware download link on github

### ISSUE THREAD

**Issue by solarfly73** [arduino/Arduino#3133] opened 2015-05-14 08:36 UTC
http://www.arduino.cc/en/Hacking/WiFiShieldFirmwareUpgrading

Under "Download Updated Firmware for the 32UC3A1256" the link is:
https://github.com/arduino/Arduino/tree/master/hardware/arduino/firmwares

This link 404s.

**Comment by ajaafar88** [comment] 2015-05-19 14:44
I am having the same issue here , please update this asap. I am blocked because of this.

**Comment by agdl** [comment] 2015-05-21 08:02
I'm closing this because is a duplicate of https://github.com/arduino/Arduino/issues/2896

**Closed by agdl** 2015-05-21 08:02 UTC
Labels: Component: Documentation
