### ISSUE TITLE
Don't exit when last window (sketch) is closed (on Mac OS X). [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#936] opened 2012-11-15 18:57 UTC
This is [Issue 936](http://code.google.com/p/arduino/issues/detail?id=936) moved from a Google Code project.
Added by 2012-06-01T02:38:55.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-IDE, OpSys-OSX
### Original description

**What change would like to see?**

The Arduino application shouldn't exit when the last window is closed (on Mac OS X).

**Why?**

That's how other Mac applications work.  The latest versions of Processing have made this change, I believe.

**Comment by Segmented** [comment] 2017-02-10 16:24
I think it would be best if it closed when the user clicks away, if there are no windows open. This is how QuickTime and other programs work.

**Comment by charliewilliams** [comment] 2018-08-08 09:36
@Segmented The QuickTime Player app doesn't quit when I close the last window (macOS 10.13.6). I don't see any reason why the Arduino app should either.

The workflow that I run into with this is:
1. Launch Arduino
2. Arduino auto-opens the last sketches I was working on. I'm not doing anything with those sketches right now, so I close them
3. Drat, Arduino has quit.
4. Relaunch Arduino

**Comment by per1234** [comment] 2018-09-21 16:51
Closing as duplicate of https://github.com/arduino/Arduino/issues/8021

Even though this one came first and has more information, https://github.com/arduino/Arduino/issues/8021 has signs of progress so I guess it takes precedent.

**Comment by facchinm** [comment] 2018-09-24 08:29
@per1234 I couldn't find this issue to set #8021 as duplicate, doing it now :wink:  Thanks for your incredible effort!

**Comment by facchinm** [comment] 2018-11-23 11:41
Fixed by merging #8023

**Closed by facchinm** 2018-11-23 11:41 UTC
Labels: Component: IDE, OS: OSX
