### ISSUE TITLE
IDE crash when a SAMD21 board is connected. JSON file or platform.txt parse bug?

### ISSUE THREAD

**Issue by RabidPrototypes** [arduino/Arduino#5473] opened 2016-10-12 11:39 UTC
I've designed a custom Zero compatible board with a ATSAMD21E17A and created a board definition to go along with it.  This definition doesn't differ much from the Arduino Zero's, yet half my users report that after installing the board files the IDE (1.6.8, 1.6.12, or any version in between) will crash if they load it while the board is connected, or if they connect the board after the IDE has been loaded.  

The only thing these users have in common is they are using Windows.  Some Windows 7, some Windows 10. I am using 10, and I do not experience the crash, so I have no way to diagnose the issue. 

I suspect there may be some sort of JSON parsing bug at play. Perhaps a buffer overrun. I think this because I don't know what other files in the board definition the IDE would be accessing when one simply connects the PCB. 

The JSON link to install my board files is here:
http://rabidprototypes.com/arduino/package_rabidprototypes_index.json

If I knew what files the IDE was accessing when a board is plugged in, I might have a better chance of diagnosing the issue. but aside from the JSON file, the only files I might expect it to access would be platform.txt.

**Comment by RabidPrototypes** [comment] 2016-10-12 11:44
One thing I have noticed and which occurred to me just now is that "Rabid Prototypes SAMD Boards (32bit ARM Cortex-M0+)" gets cut off on the boards menu.  Is it possible someone used a fixed-length array to store the board names, and this name being too long is causing a buffer overrun?

The only other thing I suspect at the moment is my use of "Tau / Firecricket" in the JSON file, but as far as I can tell a forward slash is allowed.

**Comment by RabidPrototypes** [comment] 2016-10-15 09:47
It appears this crash may actually occur regardless of whether the JSON files for my project are installed.  In other words, simply plugging in an ATSAMD21E17A board causes the latest IDE to crash.

**Comment by PaulStoffregen** [comment] 2016-10-15 10:14
Are you aware of arduino_debug.exe?  It lets you see the Java stack trace when the IDE crashes.  On Linux you get this automatically if running the IDE from a terminal.  But on Windows, you have to run the debug version.

**Comment by RabidPrototypes** [comment] 2016-10-15 10:25
Thanks for reminding me! 

While I can't replicate the problem myself and record a log of it, a customer sent me this log the other day.  I can't make heads or tails of it as I don't know Java, but maybe it will be obvious to someone who does what the problem is:

> Every time I plug either of my my Taus into my PC Running Arduino IDE version 1.6.12 (and 1.6.11)  (Win 7 64bit) It crashes with:

A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x617493cd, pid=4576, tid=0x000015b4

JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
Java VM: Java HotSpot(TM) Client VM (25.92-b14 mixed mode windows-x86 )
Problematic frame:
C  [listSerialsj.dll+0x93cd]

Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x06054800):  JavaThread "cc.arduino.packages.discoverers.serial.SerialBoardsLister" [_thread_in_native, id=5556, stack(0x07720000,0x07770000)]

siginfo: ExceptionCode=0xc0000005, writing address 0x00000000

Registers:
EAX=0x00000000, EBX=0x0000072c, ECX=0x00000000, EDX=0x00000001
ESP=0x0776eed0, EBP=0x0776f328, ESI=0x00000002, EDI=0x00611908
EIP=0x617493cd, EFLAGS=0x00010246

Top of Stack: (sp=0x0776eed0)
0x0776eed0:   007a26c8 0000002e 00000002 00000000
0x0776eee0:   00000003 00000000 00000000 02c8a31d
0x0776eef0:   128d0590 00000009 0000006c 763b27bd
0x0776ef00:   05bd0960 00000009 00611820 00003c18
0x0776ef10:   128d05a0 00000000 000018a8 00000200
0x0776ef20:   00000001 0000006c 00001438 00000001
0x0776ef30:   00000000 128d05a0 314d4f43 00ef0032
0x0776ef40:   00425355 04006d65 00000000 04ef01d8 

Instructions: (pc=0x617493cd)
0x617493ad:   8b 45 08 8b 90 94 00 00 00 85 d2 74 16 8b 40 2c
0x617493bd:   c7 44 24 04 2e 00 00 00 89 04 24 e8 73 14 00 00
0x617493cd:   c6 00 00 8d 85 04 fc ff ff 89 44 24 18 8d 85 0a
0x617493dd:   fc ff ff 89 44 24 10 a1 e4 01 75 61 c7 85 04 fc 


Register to memory mapping:

EAX=0x00000000 is an unknown value
EBX=0x0000072c is an unknown value
ECX=0x00000000 is an unknown value
EDX=0x00000001 is an unknown value
ESP=0x0776eed0 is pointing into the stack for thread: 0x06054800
EBP=0x0776f328 is pointing into the stack for thread: 0x06054800
ESI=0x00000002 is an unknown value
EDI=0x00611908 is an unknown value


Stack: [0x07720000,0x07770000],  sp=0x0776eed0,  free space=315k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [listSerialsj.dll+0x93cd]
C  [listSerialsj.dll+0x2211]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  processing.app.Platform.listSerialsNative()[Ljava/lang/String;+0
j  processing.app.Platform.listSerials()Ljava/util/List;+5
j  cc.arduino.packages.discoverers.serial.SerialBoardsLister.retriggerDiscovery(Z)V+22
j  cc.arduino.packages.discoverers.serial.SerialBoardsLister.run()V+9
j  java.util.TimerThread.mainLoop()V+221
j  java.util.TimerThread.run()V+1
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x06290800 JavaThread "DestroyJavaVM" [_thread_blocked, id=376, stack(0x00370000,0x003c0000)]
  0x06290000 JavaThread "Timer-0" [_thread_blocked, id=7348, stack(0x0a5e0000,0x0a630000)]
  0x0628ec00 JavaThread "AWT-EventQueue-0" [_thread_in_Java, id=7316, stack(0x09700000,0x09750000)]
  0x0628e800 JavaThread "AWT-Shutdown" [_thread_blocked, id=7372, stack(0x08040000,0x08090000)]
  0x0628e000 JavaThread "TimerQueue" daemon [_thread_blocked, id=7240, stack(0x09420000,0x09470000)]
  0x0628d000 JavaThread "Batik CleanerThread" daemon [_thread_blocked, id=8028, stack(0x08fd0000,0x09020000)]
  0x0628c000 JavaThread "JmDNS(Ric-xymmetrix-local.local.).Timer" daemon [_thread_blocked, id=1216, stack(0x08090000,0x080e0000)]
  0x06281400 JavaThread "JmDNS(Ric-xymmetrix-local.local.).State.Timer" [_thread_blocked, id=5492, stack(0x08210000,0x08260000)]
  0x0627f000 JavaThread "JmDNS(Ric-xymmetrix-local.local.).Timer" daemon [_thread_blocked, id=7528, stack(0x08150000,0x081a0000)]
  0x0626e000 JavaThread "SocketListener(Ric-xymmetrix-local.local.)" daemon [_thread_in_native, id=2752, stack(0x07d50000,0x07da0000)]
  0x0607a800 JavaThread "cc.arduino.packages.discoverers.network.BoardReachabilityFilter" [_thread_blocked, id=7276, stack(0x07880000,0x078d0000)]
  0x0603ec00 JavaThread "cc.arduino.packages.discoverers.network.NetworkChecker" [_thread_blocked, id=6228, stack(0x07790000,0x077e0000)]
=>0x06054800 JavaThread "cc.arduino.packages.discoverers.serial.SerialBoardsLister" [_thread_in_native, id=5556, stack(0x07720000,0x07770000)]
  0x06034000 JavaThread "AWT-Windows" daemon [_thread_in_native, id=5564, stack(0x064b0000,0x06500000)]
  0x06030c00 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=7308, stack(0x06510000,0x06560000)]
  0x052c1000 JavaThread "Service Thread" daemon [_thread_blocked, id=5828, stack(0x05d50000,0x05da0000)]
  0x052be800 JavaThread "C1 CompilerThread0" daemon [_thread_blocked, id=5140, stack(0x05e90000,0x05ee0000)]
  0x052bd400 JavaThread "Attach Listener" daemon [_thread_blocked, id=6200, stack(0x05da0000,0x05df0000)]
  0x052ba400 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=7368, stack(0x05df0000,0x05e40000)]
  0x05299c00 JavaThread "Finalizer" daemon [_thread_blocked, id=6428, stack(0x05900000,0x05950000)]
  0x05273400 JavaThread "Reference Handler" daemon [_thread_blocked, id=4336, stack(0x05ab0000,0x05b00000)]

Other Threads:
  0x0526d800 VMThread [stack: 0x05950000,0x059a0000] [id=4180]
  0x052c4000 WatcherThread [stack: 0x05a10000,0x05a60000] [id=6552]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 def new generation   total 39424K, used 32196K [0x10200000, 0x12cc0000, 0x1aca0000)
  eden space 35072K,  91% used [0x10200000, 0x12171130, 0x12440000)
  from space 4352K,   0% used [0x12440000, 0x12440000, 0x12880000)
  to   space 4352K,   0% used [0x12880000, 0x12880000, 0x12cc0000)
 tenured generation   total 87424K, used 9269K [0x1aca0000, 0x20200000, 0x30200000)
   the space 87424K,  10% used [0x1aca0000, 0x1b5ad730, 0x1b5ad800, 0x20200000)
 Metaspace       used 17140K, capacity 17452K, committed 17536K, reserved 17792K

Card table byte_map: [0x04ba0000,0x04cb0000] byte_map_base: 0x04b1f000

Polling page: 0x001c0000

CodeCache: size=32768Kb used=2139Kb max_used=2139Kb free=30628Kb
 bounds [0x02ba0000, 0x02db8000, 0x04ba0000]
 total_blobs=1321 nmethods=1054 adapters=198
 compilation: enabled

Compilation events (10 events):
Event: 14.685 Thread 0x052be800 1074             sun.font.FontDesignMetrics::getLatinCharWidth (29 bytes)
Event: 14.686 Thread 0x052be800 nmethod 1074 0x02c6f9c8 code [0x02c6faf0, 0x02c6fbfc]
Event: 14.688 Thread 0x052be800 1075             java.beans.PropertyChangeSupport::addPropertyChangeListener (45 bytes)
Event: 14.688 Thread 0x052be800 nmethod 1075 0x02c6f588 code [0x02c6f6d0, 0x02c6f890]
Event: 14.688 Thread 0x052be800 1076             java.util.ArrayList$Itr::next (66 bytes)
Event: 14.689 Thread 0x052be800 nmethod 1076 0x02c6f048 code [0x02c6f180, 0x02c6f374]
Event: 14.692 Thread 0x052be800 1077             java.awt.Component::isLightweight (8 bytes)
Event: 14.692 Thread 0x052be800 nmethod 1077 0x02c6ee48 code [0x02c6ef40, 0x02c6f010]
Event: 14.695 Thread 0x052be800 1078             sun.awt.SunHints$Value::hashCode (5 bytes)
Event: 14.695 Thread 0x052be800 nmethod 1078 0x02c6ec48 code [0x02c6ed40, 0x02c6edcc]

GC Heap History (4 events):
Event: 1.679 GC heap before
{Heap before GC invocations=0 (full 0):
 def new generation   total 39296K, used 34944K [0x10200000, 0x12ca0000, 0x1aca0000)
  eden space 34944K, 100% used [0x10200000, 0x12420000, 0x12420000)
  from space 4352K,   0% used [0x12420000, 0x12420000, 0x12860000)
  to   space 4352K,   0% used [0x12860000, 0x12860000, 0x12ca0000)
 tenured generation   total 87424K, used 0K [0x1aca0000, 0x20200000, 0x30200000)
   the space 87424K,   0% used [0x1aca0000, 0x1aca0000, 0x1aca0200, 0x20200000)
 Metaspace       used 9949K, capacity 10124K, committed 10240K, reserved 10624K
Event: 1.699 GC heap after
Heap after GC invocations=1 (full 0):
 def new generation   total 39296K, used 4352K [0x10200000, 0x12ca0000, 0x1aca0000)
  eden space 34944K,   0% used [0x10200000, 0x10200000, 0x12420000)
  from space 4352K, 100% used [0x12860000, 0x12ca0000, 0x12ca0000)
  to   space 4352K,   0% used [0x12420000, 0x12420000, 0x12860000)
 tenured generation   total 87424K, used 2597K [0x1aca0000, 0x20200000, 0x30200000)
   the space 87424K,   2% used [0x1aca0000, 0x1af294a0, 0x1af29600, 0x20200000)
 Metaspace       used 9949K, capacity 10124K, committed 10240K, reserved 10624K
}
Event: 3.992 GC heap before
{Heap before GC invocations=1 (full 0):
 def new generation   total 39296K, used 38705K [0x10200000, 0x12ca0000, 0x1aca0000)
  eden space 34944K,  98% used [0x10200000, 0x1238c5a8, 0x12420000)
  from space 4352K, 100% used [0x12860000, 0x12ca0000, 0x12ca0000)
  to   space 4352K,   0% used [0x12420000, 0x12420000, 0x12860000)
 tenured generation   total 87424K, used 2597K [0x1aca0000, 0x20200000, 0x30200000)
   the space 87424K,   2% used [0x1aca0000, 0x1af294a0, 0x1af29600, 0x20200000)
 Metaspace       used 11983K, capacity 12281K, committed 12288K, reserved 12672K
Event: 4.074 GC heap after
Heap after GC invocations=2 (full 1):
 def new generation   total 39424K, used 0K [0x10200000, 0x12cc0000, 0x1aca0000)
  eden space 35072K,   0% used [0x10200000, 0x10200000, 0x12440000)
  from space 4352K,   0% used [0x12440000, 0x12440000, 0x12880000)
  to   space 4352K,   0% used [0x12880000, 0x12880000, 0x12cc0000)
 tenured generation   total 87424K, used 9269K [0x1aca0000, 0x20200000, 0x30200000)
   the space 87424K,  10% used [0x1aca0000, 0x1b5ad730, 0x1b5ad800, 0x20200000)
 Metaspace       used 11983K, capacity 12281K, committed 12288K, reserved 12672K
}

Deoptimization events (0 events):
No events

Internal exceptions (10 events):
Event: 2.289 Thread 0x0239e000 Exception <a 'sun/nio/fs/WindowsException'> (0x11143530) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 2.289 Thread 0x0239e000 Exception <a 'sun/nio/fs/WindowsException'> (0x11143ad8) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 2.291 Thread 0x0239e000 Exception <a 'sun/nio/fs/WindowsException'> (0x1114d728) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 2.291 Thread 0x0239e000 Exception <a 'sun/nio/fs/WindowsException'> (0x1114dd20) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 2.293 Thread 0x0239e000 Exception <a 'java/io/IOException'> (0x11152210) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 2.293 Thread 0x0239e000 Exception <a 'java/io/IOException'> (0x11152488) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 2.293 Thread 0x0239e000 Exception <a 'java/io/IOException'> (0x111526d0) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 2.294 Thread 0x0239e000 Exception <a 'sun/nio/fs/WindowsException'> (0x1115b270) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 2.294 Thread 0x0239e000 Exception <a 'sun/nio/fs/WindowsException'> (0x1115b7b0) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 2.800 Thread 0x0239e000 Exception <a 'java/lang/NoSuchMethodError': java.lang.Object.lambda$negate$1(Ljava/lang/Object;)Z> (0x1178e1e8) thrown at [C:\workspace\8-2-build-windows-i586-cygwin\jdk8u92\6642\hotspot\src\share\vm\interpreter\linkResolver.cpp, line 582]

Events (10 events):
Event: 14.682 loading class javax/swing/PopupFactory
Event: 14.682 loading class javax/swing/PopupFactory done
Event: 14.686 loading class javax/swing/Popup$HeavyWeightWindow
Event: 14.686 loading class sun/awt/ModalExclude
Event: 14.686 loading class sun/awt/ModalExclude done
Event: 14.686 loading class javax/swing/JWindow
Event: 14.687 loading class javax/swing/JWindow done
Event: 14.687 loading class javax/swing/Popup$HeavyWeightWindow done
Event: 14.687 loading class javax/swing/PopupFactory$HeavyWeightPopup
Event: 14.687 loading class javax/swing/PopupFactory$HeavyWeightPopup done


Dynamic libraries:
0x003e0000 - 0x00413000 	C:\Program Files (x86)\Arduino\java\bin\javaw.exe
0x775c0000 - 0x77740000 	C:\Windows\SysWOW64\ntdll.dll
0x75d10000 - 0x75e20000 	C:\Windows\syswow64\kernel32.dll
0x758b0000 - 0x758f7000 	C:\Windows\syswow64\KERNELBASE.dll
0x76190000 - 0x76231000 	C:\Windows\syswow64\ADVAPI32.dll
0x751c0000 - 0x7526c000 	C:\Windows\syswow64\msvcrt.dll
0x75e20000 - 0x75e39000 	C:\Windows\SysWOW64\sechost.dll
0x75900000 - 0x759f0000 	C:\Windows\syswow64\RPCRT4.dll
0x74eb0000 - 0x74f10000 	C:\Windows\syswow64\SspiCli.dll
0x74ea0000 - 0x74eac000 	C:\Windows\syswow64\CRYPTBASE.dll
0x74f10000 - 0x75010000 	C:\Windows\syswow64\USER32.dll
0x76250000 - 0x762e0000 	C:\Windows\syswow64\GDI32.dll
0x751b0000 - 0x751ba000 	C:\Windows\syswow64\LPK.dll
0x75c70000 - 0x75d0d000 	C:\Windows\syswow64\USP10.dll
0x6b030000 - 0x6b1ce000 	C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_41e855142bd5705d\COMCTL32.dll
0x76090000 - 0x760e7000 	C:\Windows\syswow64\SHLWAPI.dll
0x75e60000 - 0x75ec0000 	C:\Windows\system32\IMM32.DLL
0x75580000 - 0x7564c000 	C:\Windows\syswow64\MSCTF.dll
0x553d0000 - 0x5548f000 	C:\Program Files (x86)\Arduino\java\bin\msvcr100.dll
0x55000000 - 0x553cb000 	C:\Program Files (x86)\Arduino\java\bin\client\jvm.dll
0x712c0000 - 0x712c7000 	C:\Windows\system32\WSOCK32.dll
0x75bd0000 - 0x75c05000 	C:\Windows\syswow64\WS2_32.dll
0x760f0000 - 0x760f6000 	C:\Windows\syswow64\NSI.dll
0x727b0000 - 0x727e2000 	C:\Windows\system32\WINMM.dll
0x74dd0000 - 0x74dd9000 	C:\Windows\system32\VERSION.dll
0x75bc0000 - 0x75bc5000 	C:\Windows\syswow64\PSAPI.DLL
0x55510000 - 0x55541000 	C:\Program Files (x86)\Arduino\java\bin\splashscreen.dll
0x6ab60000 - 0x6abe0000 	C:\Windows\system32\uxtheme.dll
0x58570000 - 0x5857c000 	C:\Program Files (x86)\Arduino\java\bin\verify.dll
0x55a20000 - 0x55a41000 	C:\Program Files (x86)\Arduino\java\bin\java.dll
0x10000000 - 0x10184000 	C:\Program Files\NVIDIA Corporation\nview\nview.dll
0x76540000 - 0x7718c000 	C:\Windows\syswow64\SHELL32.dll
0x75010000 - 0x7516d000 	C:\Windows\syswow64\ole32.dll
0x76300000 - 0x76391000 	C:\Windows\syswow64\OLEAUT32.dll
0x74d40000 - 0x74d61000 	C:\Windows\system32\ntmarta.dll
0x75a00000 - 0x75a45000 	C:\Windows\syswow64\WLDAP32.dll
0x554f0000 - 0x55503000 	C:\Program Files (x86)\Arduino\java\bin\zip.dll
0x76100000 - 0x76183000 	C:\Windows\syswow64\CLBCatQ.DLL
0x751a0000 - 0x751ab000 	C:\Windows\syswow64\profapi.dll
0x54eb0000 - 0x54ff5000 	C:\Program Files (x86)\Arduino\java\bin\awt.dll
0x6ab40000 - 0x6ab53000 	C:\Windows\system32\dwmapi.dll
0x554d0000 - 0x554e6000 	C:\Program Files (x86)\Arduino\java\bin\net.dll
0x71200000 - 0x7123c000 	C:\Windows\system32\mswsock.dll
0x6d620000 - 0x6d626000 	C:\Windows\System32\wship6.dll
0x74380000 - 0x7439c000 	C:\Windows\system32\IPHLPAPI.DLL
0x74370000 - 0x74377000 	C:\Windows\system32\WINNSI.DLL
0x72e60000 - 0x72e72000 	C:\Windows\system32\dhcpcsvc.DLL
0x73280000 - 0x7328d000 	C:\Windows\system32\dhcpcsvc6.DLL
0x61740000 - 0x6176c000 	C:\Program Files (x86)\Arduino\lib\listSerialsj.dll
0x763a0000 - 0x7653d000 	C:\Windows\syswow64\SETUPAPI.dll
0x77190000 - 0x771b7000 	C:\Windows\syswow64\CFGMGR32.dll
0x75a50000 - 0x75a62000 	C:\Windows\syswow64\DEVOBJ.dll
0x6e5f0000 - 0x6e607000 	C:\Windows\system32\CRYPTSP.dll
0x6e5b0000 - 0x6e5eb000 	C:\Windows\system32\rsaenh.dll
0x75e40000 - 0x75e57000 	C:\Windows\syswow64\USERENV.dll
0x58580000 - 0x5858f000 	C:\Program Files (x86)\Arduino\java\bin\nio.dll
0x00520000 - 0x0055d000 	C:\Users\ric\AppData\Local\Temp\jna-112908\jna6072286323916535931.dll
0x6d590000 - 0x6d5d4000 	C:\Windows\system32\DNSAPI.dll
0x6d550000 - 0x6d571000 	C:\Program Files (x86)\Bonjour\mdnsNSP.dll
0x711f0000 - 0x711f5000 	C:\Windows\System32\wshtcpip.dll
0x69be0000 - 0x69be6000 	C:\Windows\system32\rasadhlp.dll
0x69ba0000 - 0x69bd8000 	C:\Windows\System32\fwpuclnt.dll
0x55490000 - 0x554c9000 	C:\Program Files (x86)\Arduino\java\bin\fontmanager.dll
0x54e70000 - 0x54ea2000 	C:\Program Files (x86)\Arduino\java\bin\t2k.dll
0x75550000 - 0x7557f000 	C:\Windows\syswow64\WINTRUST.dll
0x75f50000 - 0x76071000 	C:\Windows\syswow64\CRYPT32.dll
0x759f0000 - 0x759fc000 	C:\Windows\syswow64\MSASN1.dll
0x54e00000 - 0x54e69000 	C:\Program Files (x86)\Arduino\msvcp100.dll
0x54ce0000 - 0x54d9e000 	C:\Program Files (x86)\Arduino\msvcr100.dll
0x05e40000 - 0x05e72000 	C:\Program Files (x86)\Arduino\lib\AStylej.dll
0x54dd0000 - 0x54df4000 	C:\Program Files (x86)\Arduino\java\bin\dcpr.dll
0x5f890000 - 0x5f9c1000 	C:\Windows\system32\WindowsCodecs.dll
0x67030000 - 0x6707c000 	C:\Windows\system32\apphelp.dll
0x611e0000 - 0x61218000 	C:\Program Files (x86)\Dropbox\Client\DropboxExt.65536.dll
0x079d0000 - 0x079f7000 	C:\Windows\SysWOW64\CbFsMntNtf3.dll
0x712b0000 - 0x712bd000 	C:\Windows\SysWOW64\WTSAPI32.dll
0x07a00000 - 0x07a2a000 	C:\Windows\SysWOW64\cbfsMntNtf4.dll
0x65020000 - 0x65051000 	C:\Windows\system32\EhStorShell.dll
0x66ce0000 - 0x66dd5000 	C:\Windows\system32\PROPSYS.dll
0x5e6c0000 - 0x5e933000 	C:\Windows\system32\nvapi.dll
0x66de0000 - 0x66ecb000 	C:\Windows\system32\dbghelp.dll

VM Arguments:
jvm_args: -Dsun.java2d.d3d=false -Djna.nosys=true -DAPP_DIR=C:\Program Files (x86)\Arduino -Xms128M -Xmx512M 
java_command: processing.app.Base
java_class_path (initial): C:\Program Files (x86)\Arduino\lib\apple.jar;C:\Program Files (x86)\Arduino\lib\arduino-core.jar;C:\Program Files (x86)\Arduino\lib\batik-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-anim-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-awt-util-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-bridge-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-codec-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-css-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-dom-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-ext-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-gvt-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-parser-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-rasterizer-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-script-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-squiggle-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-svg-dom-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-svgpp-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-transcoder-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-util-1.8.jar;C:\Program Files (x86)\Arduino\lib\batik-xml-1.8.jar;C:\Program Files (x86)\Arduino\lib\bcpg-jdk15on-152.jar;C:\Program Files (x86)\Arduino\lib\bcprov-jdk15on-152.jar;C:\Program Files (x86)\Arduino\lib\commons-codec-1.7.jar;C:\Program Files (x86)\Arduino\lib\commons-compress-1.8.jar;C:\Program Files (x86)\Arduino\lib\commons-exec-1.1.jar;C:\Program Files (x86)\Arduino\lib\commons-httpclient-3.1.jar;C:\Program Files (x86)\Arduino\lib\commons-lang3-3.3.2.jar;C:\Program Files (x86)\Arduino\lib\commons-logging-1.0.4.jar;C:\Program Files (x86)\Arduino\lib\commons-net-3.3.jar;C:\Program Files (x86)\Arduino\lib\jackson-annotations-2.6.3.jar;C:\Program Files (x86)\Arduino\lib\jackson-core-2.6.3.jar;C:\Program Files (x86)\Arduino\lib\jackson-databind-2.6.3.jar;C:\Program Files (x86)\Arduino\lib\jackson-module-mrbean-2.6.3.jar;C:\Program Files (x86)\Arduino\lib\java-semver-0.8.0.jar;C:\Program Files (x86)\Arduino\lib\jmdns-3.4.1.j
Launcher Type: SUN_STANDARD

Environment Variables:
CLASSPATH=.;C:\Program Files (x86)\Java\jre7\lib\ext\QTJava.zip
PATH=C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;c:\Python27;C:\Program Files (x86)\Arduino\java\bin
USERNAME=ric
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 23 Stepping 6, GenuineIntel



---------------  S Y S T E M  ---------------

OS: Windows 7 , 64 bit Build 7601 (6.1.7601.23539)

CPU:total 2 (2 cores per cpu, 1 threads per core) family 6 model 23 stepping 6, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, tsc

Memory: 4k page, physical 8387960k(4805004k free), swap 16774060k(12698840k free)

vm_info: Java HotSpot(TM) Client VM (25.92-b14) for windows-x86 JRE (1.8.0_92-b14), built on Mar 31 2016 21:09:21 by "java_re" with MS VC++ 10.0 (VS2010)

time: Mon Oct 10 13:34:47 2016
elapsed time: 14 seconds (0d 0h 0m 14s)`

**Comment by RabidPrototypes** [comment] 2016-10-15 10:37
Of course, even not knowing Java, this line stands out to me like a sore thumb:
Current thread (0x06054800): JavaThread "cc.arduino.packages.discoverers.serial.SerialBoardsLister"

My first thought was that perhaps the name of my board in platforms.txt was too long and someone had shoved the names into a fixed length string. I noticed the name is too large to fit in the menu, but I hadn't had the chance to correct that and have someone test it when someone else reported that the crash happens regardless of whether the board files are installed.

It may be worth noting that I have the USB IDs set the same as those on the Zero (I chose to do this because I don't know how using a different one might affect the detection of the board by IDE with the included drivers on different versions of Windows), but I'm having a difficult time imagining why that would cause a crash, and I don't have any easy way of testing a different USB ID since I can't reproduce the crash myself.

**Comment by PaulStoffregen** [comment] 2016-10-15 19:59
Looks like a bug in listSerialPortsC.  Probably should open an issue here:

https://github.com/arduino/listSerialPortsC

While unrelated, you might also want to know about the CDC serial driver bug which exists in Windows 7 and all other versions before Windows 10.

https://www.youtube.com/watch?v=DRmvUsa2xuU

If another program has the COM port open during the disconnect event, when you later reconnect (as happens when reprogramming on these native USB ports) the COM port appears in the device manager, but can't be used.  It's a driver bug.  The only solution is to carefully avoid having the COM port open when uploading, which Arduino IDE does automatically, but other programs can't.  Or upgrade to Windows 10, or Mac or Linux.  All copies of Windows 7 have this annoying bug.  Still, the IDE (and listSerialPortsC) shouldn't crash.

**Comment by RabidPrototypes** [comment] 2016-10-15 22:28
That customer was using Windows 7, but the crash bug occurs in Windows 10 as well, so this issue is unrelated to the CDC driver bug.

**Comment by facchinm** [comment] 2016-10-20 12:53
Indeed, this problem is libSerialPort related. I'll try to reproduce it by flashing your board's bootloader into a Zero and see what happens on Win. Maybe the long name can be an hint, I'll investigate on that

**Comment by facchinm** [comment] 2016-10-24 12:19
@RabidPrototypes , I reproduced it on Win10 and fixed with https://github.com/arduino/Arduino/commit/de9bd89a01323d7358bfc1c20834e77a7642d3f4 . Could you please test latest nightly to confirm that it works now? Thanks

**Comment by RabidPrototypes** [comment] 2016-10-27 23:22
So far it seems to have fixed it! Thanks!

**Closed** 2016-10-28 07:38 UTC
Labels: libListSerial
