### ISSUE TITLE
IDE 1.8 Horrible font type

### ISSUE THREAD

**Issue by FernandoGarcia** [arduino/Arduino#5754] opened 2016-12-23 17:27 UTC
Hi!

New font type in IDE 1.8 is not comfortable to read, please make it as IDE 1.6.10.

See the difference:

![font type](https://cloud.githubusercontent.com/assets/2778501/21459246/c7e07b8e-c923-11e6-89c8-4add139dffdd.PNG)

The font seems blurred or in bold.

I'm using Windows 10.

Best regards.

**Comment by cmaglie** [comment] 2016-12-23 17:47
duplicate of #5750

**Closed by cmaglie** 2016-12-23 17:47 UTC
