### ISSUE TITLE
[Feature] Add CLS, CR, LF

### ISSUE THREAD

**Issue by teundool** [arduino/Arduino#9679] opened 2020-01-29 12:43 UTC
The source code of the "Serial Monitor" suggests that it might be easy to implement a CLS  (Clear Screen) command in the Serial Monitor. Additionally I think CR, LF (without CR) , and cursor positioning could be added relative easy. It would certainly help a huge number of people that have been looking for these features and are forced to revert to multiple println to clear the screen, ending at the bottom of the screen instead of at the top, and printing complete screens if you want to change a single number in a GUI. Of course can be done with a VT100 terminal like TeraTerm but that won't allow to reprogram e.g. a Teensy (without pressing the reset button, that is, not remotely).

**Comment by per1234** [comment] 2020-09-25 02:29
Closing as duplicate of https://github.com/arduino/Arduino/issues/346

**Closed by per1234** 2020-09-25 02:29 UTC
Labels: Component: IDE Serial monitor, feature request
