### ISSUE TITLE
Stop Mega bootloader going into debug mode on "!!!"

### ISSUE THREAD

**Issue by nickgammon** [arduino/Arduino#2477] opened 2014-11-30 22:21 UTC
Isn't it time to stop this nonsense? Who uses debug mode anyway? Day after day we get bug reports from people who try to upload code like this:

```
  Serial.println ("Activation fin de course X !!!");
```

The page for the Mega2560 ( http://arduino.cc/en/Main/ArduinoBoardMega2560 ) does not mention debug mode.

The troubleshooting page ( http://www.arduino.cc/en/Guide/Troubleshooting#upload ) does not mention debug mode.

I can't even find a page that mentions _how to use it_.

But was **does** happen is that people post code like the above, or this:

```
Serial.println ("Ready to work!!!");
```

Then they complain that they can't upload their code.

**Comment by cmaglie** [comment] 2015-01-27 20:14
hi @nickgammon 

this was fixed a long time ago now, here some references

original issue: https://github.com/arduino/Arduino/issues/392
fix: https://github.com/arduino/Arduino/pull/1183

AFAIK the new firmware has also been moved in production.
Maybe the guy has an Mega2560 with the old firmware?

**Comment by nickgammon** [comment] 2015-01-27 20:44
> Possibly, but we seem to get the issue often enough.

Reported here: http://forum.arduino.cc/index.php?topic=282504.0

That was in December 2014. He didn't say when he bought the boards, but it happened to three of them.

**Comment by PaulStoffregen** [comment] 2015-01-27 21:59
He also didn't say *where* he bought the 3 boards.

Asian clones probably still ship with the original bootloader.

**Comment by NicoHood** [comment] 2015-02-09 10:20
Paul is right. I had a guy with a 4kb Uno bootloader last time.

But you really should provide better information on how to update the bootloader or at least why this happens. Maybe then people start buying official products as well ;)

**Comment by per1234** [comment] 2017-07-01 10:00
Since this is no longer a common problem and when it does happen is more likely to be caused by clones or counterfeits I think the documentation of this issue is more suitable for the Arduino Playground. I have added a description of the fix to the Playground's [Troubleshooting](https://playground.arduino.cc/Main/Troubleshooting) page so I'm going to close this issue.

If anyone wants to make improvements to that Playground page (or any other), feel free to do so. It is a publicly editable wiki.

**Closed by per1234** 2017-07-01 10:00 UTC
Labels: Component: Bootloader, Type: Duplicate
