### ISSUE TITLE
macos 64bit version of ide

### ISSUE THREAD

**Issue by OverTheSea1** [arduino/Arduino#11652] opened 2021-08-22 12:11 UTC
When i try to upload my sketch to my digispark i get the error 
`bad CPU type in executable`
after some researches i think i discoverred it is a problem with 32bit Versions on macos but all the provided links are not working. 
So where may i download the 64bit Version of Arduino IDE ? 

Thanks

**Comment by per1234** [comment] 2021-08-22 13:10
Hi @OverTheSea1. Thanks for your interest in this open source project. You can always get the latest version of the Arduino IDE from the "Software" page on arduino.cc:
https://www.arduino.cc/en/software
The macOS version has been 64 bit ever since the 32 bit support was dropped some years ago. So as long as you are using a recent version of the Arduino IDE, it's sure to be compatible.

However, the entire compiling and uploading toolchain for the board you have selected also must be 64 bit. In the case of 3rd party boards platforms, Arduino has no responsibility or control over that toolchain. So it is the responsibility of the maintainers of that 3rd party boards platform. In the case of the traditional boards platform for the Digispark boards, it has not been updated, as reported here:
https://github.com/digistump/DigistumpArduino/issues/105
Be sure to check the issue above to discover a well maintained fork of the Digistump boards platform that has been updated.

Since this issue is not at all related to the Arduino IDE code hosted in this repository, I'll go ahead and close it as a duplicate of https://github.com/digistump/DigistumpArduino/issues/105.

**Closed by per1234** 2021-08-22 13:10 UTC
