### ISSUE TITLE
feature request: 'reset target' from serial terminal

### ISSUE THREAD

**Issue by lpdunwell** [arduino/Arduino#8148] opened 2018-10-31 06:19 UTC
a 'reset target' button in the serial terminal would be useful.
currently, changing the baud rate does it for boards like arduino uno and mega.
however, this does not work for all boards. example: esp32

**Comment by per1234** [comment] 2018-10-31 07:41
Closing as duplicate of https://github.com/arduino/Arduino/issues/4353
Also related: https://github.com/arduino/Arduino/issues/5866

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-10-31 07:41 UTC
Labels: Type: Duplicate
