### ISSUE TITLE
SD library

### ISSUE THREAD

**Issue by Matsarnts** [arduino/Arduino#7983] opened 2018-09-10 16:53 UTC
i instaled the library but it say i isent instaled so it cant read the sd but it is

prove:
![arduino help](https://user-images.githubusercontent.com/43147196/45311838-b6819680-b52a-11e8-9ecc-0f6884a64776.PNG)

**Comment by per1234** [comment] 2018-09-10 21:30
Closing as duplicate of https://github.com/arduino-libraries/TFT/issues/2

**Closed by per1234** 2018-09-10 21:30 UTC
Labels: Library: TFT, Type: Duplicate
