### ISSUE TITLE
IDE enhancement request: better search function: only find, find+replace, find only whole words  

### ISSUE THREAD

**Issue by tofrnr** [arduino/Arduino#6378] opened 2017-06-13 11:44 UTC
IDE enhancement request: 
please provide a better search function: 
only find, 
find+replace, 
extra option: find only whole words  
find next by F3 key stroke

(keyword search for 
find search replace whole words  
did not show any matches!)

**Comment by quequen** [comment] 2017-06-15 19:24
Buenas tardes:solicite bajar IDE Arduino l.8.3 para Win-hice la donacion solicitada y logro de ingresar ba la misma para bajar dicho archivo,(adjunto recibo-
Arduino, LLC recibo [# 1352-0594-

**Comment by tofrnr** [comment] 2017-06-16 12:52
what? please post in English!

**Comment by tofrnr** [comment] 2017-06-27 09:38
why has this not been tagged as " Component: IDE / Type: Improvement" meanwhile?

**Comment by per1234** [comment] 2017-07-06 16:49
Closing as duplicate of https://github.com/arduino/Arduino/issues/3727.

**Closed by per1234** 2017-07-06 16:49 UTC
Labels: Component: IDE, Component: IDE user interface, Type: Duplicate, Type: Improvement

**Comment by tofrnr** [comment] 2017-07-07 16:44
per1234: that's weird: a referenced post once opened at  25 Aug 2015, still unresolved, now you close my report/topic although it's still  unresolved  - why the heck do you close it then?? Instead of closing unresolved issue you'd better resolve them !!

**Comment by cmaglie** [comment] 2017-07-07 16:53
@tofrnr 
the issue has been closed as **duplicate** of #3727, it has no sense to have multiple issue about the same topic. Please note that #3727 is still open.

> Instead of spending time on searching so-called duplicates and closing unresolved issues you'd better use your time to resolve them

removing duplicates actually helps a lot to keep the issues tracker clean and to keep the all the informations into a single issue instead of having them scattered around many issues.

**Comment by tofrnr** [comment] 2017-12-14 09:13
is there meanwhile an update about the extra option "search whole words only" ?
without that option even the "replace all" button causes total mess!
