### ISSUE TITLE
Wrong operation of the preprocessor with the enum type.

### ISSUE THREAD

**Issue by allnick** [arduino/Arduino#10138] opened 2020-05-04 01:32 UTC
Hi.
Here are two seemingly equivalent versions of program code.

=============================================================

```
#define BOARD_MODE_NONE 0
#define BOARD_MODE_1    1
#define BOARD_MODE_2    2
#define BOARD_MODE_1_2  (BOARD_MODE_1 + BOARD_MODE_2)
#define BOARD_MODE_HARD 255

#define BOARD_MODE      BOARD_MODE_1_2

#if BOARD_MODE == BOARD_MODE_HARD // It's false. Block 2 is defined. It's OK.
  // Some block 1
#else
  // Some block 2
#endif
```

=============================================================

```
enum tBoardModes{
  BOARD_MODE_NONE = 0,
  BOARD_MODE_1    = 1,
  BOARD_MODE_2    = 2,
  BOARD_MODE_1_2  = (BOARD_MODE_1 + BOARD_MODE_2),
  BOARD_MODE_HARD = 255
};

#define BOARD_MODE  BOARD_MODE_1_2

#if BOARD_MODE == BOARD_MODE_HARD // It's true! Block 1 is defined! What a hell !!!
                                  // However, the values of all IDs remain correct !!!
  // Some block 1
#else
  // Some block 2
#endif
```

=============================================================

As it turned out, they are not so equivalent…
Bye.

**Comment by matthijskooijman** [comment] 2020-05-04 06:29
`#if` is a preprocessor directive, it only knows about preprocessor macros defined with `#define`. In your second example, `BOARD_MODE` is replaced by `BOARD_MODE_1_2`, but `BOARD_MODE_1_2` and `BOARD_MODE_HARD` are both unknown macros, which are treated as `0`, so they are equal. All of this works as designed.

So the problem is that you mix C-level values (enum) with a preprocessor `#if (note that the reverse is ok, using preprocessor macros in C-level code, since the preprocessor always runs first).

To fix this, you can also use a normal `if` here: `if (BOARD_MODE == BOARD_MODE_HARD) { ...code ... }`. Provided that the optimizer knows about the value of `BOARD_MODE` (which is pretty much guaranteed on the AVR core that uses link-time-optimization), the compiler will typically resolve the if at compile time and include only the needed block in the final code.

This does require that both blocks can be properly compiled (e.g. do not refer to variables that are not available). If you really need to do more invasive changes (e.g. change types, omit struct fields, etc. based on your selected `BOARD_MODE`), that you will have to resort to preprocessor values.

Since there's no bug here, I'm closing this.

**Closed by matthijskooijman** 2020-05-04 06:29 UTC
