### ISSUE TITLE
Impossible to use "CTRL+/" with French keyboard

### ISSUE THREAD

**Issue by BorisDess** [arduino/Arduino#8968] opened 2019-06-11 17:05 UTC
I have been googling this a bit, but it seems no French is complaining about that...
There's no way a French keyboard can do "CTRL+/". Therefore all frenchs have to manually type the comment sign "//" and then delete it.
With Spyder IDE, I'm used to quickly comment/uncomment, this is a must have.
It's a shave that the shortcuts can't be customised easily.

**Comment by matthijskooijman** [comment] 2019-06-11 18:01
This is a known problem, but IIRC the fix is fairly non-trivial due to the way that keycodes work in general and possibly in java in particular. See #5064 for a link to the rsyntaxtextarea bug report (which is where the actual problem is).

I'm closing this issue as a duplicate of #5064.

**Closed by matthijskooijman** 2019-06-11 18:01 UTC
