### ISSUE TITLE
Cannot Open Arduino

### ISSUE THREAD

**Issue by RockZombie123** [arduino/Arduino#11675] opened 2021-10-01 17:19 UTC
This is a reopening of: Cannot Open Arduino

`/home/pi/Downloads/arduino-nightly/arduino: line 35: /home/pi/Downloads/arduino-nightly/java/bin/java: cannot execute binary file: Exec format error
`

**Comment by per1234** [comment] 2021-10-01 17:36
Closing as duplicate of https://github.com/arduino/Arduino/issues/11673

@RockZombie123 you already have an issue for this subject. Please just use the one. If we determine that there is a valid bug report, that other issue will be reopened.

**Closed by per1234** 2021-10-01 17:36 UTC
