### ISSUE TITLE
Need to download Arduino 1.0.5-r2 for Mac OSx but I can't find it

### ISSUE THREAD

**Issue by mheimbinder** [arduino/Arduino#7057] opened 2017-12-28 15:28 UTC
Thanks so much for responding cmaglie.

Unfortunately, I'm not looking for 1.0.5 but 1.0.5-r2 for Mac OSx. I can find the release on the "Release Notes" page here, https://www.arduino.cc/en/Main/ReleaseNotes, but it is not present on the "Previous IDE Releases" page you linked to. Any idea where I might download 1.0.5-r2 for Mac OSx. Note that I have asked this same question in the Arduino Forums, see http://forum.arduino.cc/index.php?topic=519313.0

Apologies, for opening a new issue but I wasn't sure if a response inside a closed ticket would be responded to.  If I'm not following best practices please let me know.  I'm new to this repository so advice is appreciated.

Thanks in advance for your assistance.

**Comment by per1234** [comment] 2017-12-28 15:51
Closing as duplicate of https://github.com/arduino/Arduino/issues/7056

**Closed by per1234** 2017-12-28 15:51 UTC

**Comment by matthijskooijman** [comment] 2017-12-28 15:59
@mheimbinder, just add more comments to your previous issue, rather than opening new issues and cluttering the list.

**Comment by mheimbinder** [comment] 2017-12-28 17:34
Thanks for the tip matthijskooijman.  Will do.
