### ISSUE TITLE
Window menu is missing on the Mac

### ISSUE THREAD

**Issue by probonopd** [arduino/Arduino#3557] opened 2015-07-20 16:59 UTC
On the Mac, (almost) every application has a "Window" menu, where you can see and switch between all open windows of that application.

![mac-osx-window-zoom](https://cloud.githubusercontent.com/assets/2480569/8781783/6cf330e8-2f11-11e5-8c8a-2d2dacc53723.jpg)

It would be nice if Arduino cold have this menu, too.

**Comment by ffissore** [comment] 2015-08-04 15:29
Duplicate of #234

**Closed by ffissore** 2015-08-04 15:29 UTC
Labels: Component: IDE user interface, OS: OSX

**Comment by lmihalkovic** [comment] 2015-11-26 09:43
simple first step

<img width="418" alt="screen shot 2015-11-26 at 10 35 43 am" src="https://cloud.githubusercontent.com/assets/1318077/11419866/8ba8a9c2-942a-11e5-8876-2bcb5bc69f75.png">

**Comment by probonopd** [comment] 2015-11-27 12:25
Great @lmihalkovic - did you send a pull request?
