### ISSUE TITLE
ctags pattern is missing on openSUSE 42.3

### ISSUE THREAD

**Issue by AEtherC0r3** [arduino/Arduino#6965] opened 2017-11-25 18:06 UTC
I've installed the Arduino IDE using the guide https://playground.arduino.cc/Linux/OpenSUSE
But, when I'm trying to compile a sketch e.g. the Blink example, it throws the following error
```
ctags pattern is missing

Error compiling for board Arduino/Genuino Uno.
```

The binaries from https://www.arduino.cc/en/Main/Software work as expected

**Comment by PaulStoffregen** [comment] 2017-11-25 23:45
You need to report this problem to OpenSUSE.

Closing this issue would be appropriate, since it has nothing to do with upstream Arduino which you've already confirmed works.

**Closed** 2017-11-27 08:22 UTC

**Comment by thild** [comment] 2020-04-28 22:40
> You need to report this problem to OpenSUSE.
> 
> Closing this issue would be appropriate, since it has nothing to do with upstream Arduino which you've already confirmed works.

See https://build.opensuse.org/package/show/CrossToolchain:avr/Arduino#comment-1131218

**Comment by thild** [comment] 2020-04-28 22:41
> I've installed the Arduino IDE using the guide https://playground.arduino.cc/Linux/OpenSUSE
> But, when I'm trying to compile a sketch e.g. the Blink example, it throws the following error
> 
> ```
> ctags pattern is missing
> 
> Error compiling for board Arduino/Genuino Uno.
> ```
> 
> The binaries from https://www.arduino.cc/en/Main/Software work as expected

See https://build.opensuse.org/package/show/CrossToolchain:avr/Arduino#comment-1131218
