### ISSUE TITLE
We need a "project file"

### ISSUE THREAD

**Issue by dotto59** [arduino/Arduino#10462] opened 2020-07-03 14:17 UTC
Currently, when creating projects for different board types (e.g. UNO, Mega, Nano, AtTiny, WeMos, etc.) the IDE just "remembers" the last settings about board type, port, speed etc, but this is a pain when working with more than one project for more than one board, because you always need to manually set the IDE board configuration every time you change platform. It's pretty boring if you open a project, edit it, compile ad upload just to get errors due to any setting not suitable for that project (board, upload speed, COM port, etc), or even open the serial monitor and find it is set to 115200 baud instead of the 9600 for that project.

For this reason, I think it would be a great fix (or improvement, and absolutely an essential thing to make an even better IDE), to define a "project" file with the same dir and name of the main *.ino file but with a different extension (e.g. something like ".aproj" as "Arduino PROJect file") as a plain INI-style text file where the IDE could save any project-specific setting like board, COM port, upload speed, programmer, position and size of the window, baud rate position and size of the serial monitor, and any specific setting. The default value for any missing setting on *.aproj file will be the same as current one, either from preferences or the last IDE execution. The file will be automatically created when a new project is saved, and updated each time the project is successfully saved.
I don't think it's a hard thing to implement,

**Comment by per1234** [comment] 2020-08-01 22:39
Closing as duplicate of https://github.com/arduino/Arduino/issues/1481

Note that this capability is already provided by [Arduino CLI](https://arduino.github.io/arduino-cli/latest/commands/arduino-cli_board_attach/) and [Arduino Web Editor](https://create.arduino.cc/editor).

**Closed by per1234** 2020-08-01 22:39 UTC
