### ISSUE TITLE
Unable to delete "Tab" File until project saved

### ISSUE THREAD

**Issue by wholder** [arduino/Arduino#7331] opened 2018-03-15 22:03 UTC
This is a minor issue, but it seems odd that if I use "New Tab" to create a file, I can't use "Delete" to remove the tab until I first save the project.  I'm guessing that this is just a  special case someone didn't consider.

Wayne

**Comment by per1234** [comment] 2018-03-16 01:56
Closing as duplicate of 
https://github.com/arduino/Arduino/issues/6453
We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-03-16 01:56 UTC
Labels: Type: Duplicate
