### ISSUE TITLE
Matched brace disappears in some cases

### ISSUE THREAD

**Issue by ut2uz** [arduino/Arduino#4337] opened 2015-12-23 19:00 UTC
Try to put the cursor before last brace in the following simple example and move cursor forward:

void loop() 
{
}

The upper brace disappears.

If one of matched braces is not in the same column, then OK:
void loop() 
_ {
}

The same problem exists for any kind of matched brackets/braces

**Comment by sandeepmistry** [comment] 2015-12-23 19:04
@ut2uz which version of the IDE and OS are you using?

With 1.6.7 on OS X 10.11 I get a white box on the first bracket. Is this what you are seeing?

<img width="512" alt="screen shot 2015-12-23 at 2 02 40 pm" src="https://cloud.githubusercontent.com/assets/1163840/11983003/14d7cf3a-a97e-11e5-9f77-042ae1ae44d8.png">
<img width="512" alt="screen shot 2015-12-23 at 2 02 44 pm" src="https://cloud.githubusercontent.com/assets/1163840/11983004/14ea7388-a97e-11e5-910f-869e4aaa6dfd.png">

**Comment by ut2uz** [comment] 2015-12-23 20:22
@sandeepmistry , I think this problem exists since 1.6.5, the last is arduino-nightly 1.6.8. The OS is W10. Loop() looks like at your second picture.

**Comment by per1234** [comment] 2015-12-24 00:16
It doesn't only happen when the braces are in the same column. Arduino IDE 1.6.8 2015/12/21 03:51 with Windows 7 64 bit:
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/11987220/03cfb1aa-a990-11e5-9c3e-26cbc6eb4a81.gif)
![clipboard02](https://cloud.githubusercontent.com/assets/8572152/11987229/4ab1a902-a990-11e5-8621-76d160a70e9e.gif)
![clipboard03](https://cloud.githubusercontent.com/assets/8572152/11987230/4b67d16e-a990-11e5-97e2-4a822b200e0a.gif)

**Comment by VaclavSal** [comment] 2016-01-06 19:40
I would be interested looking into this at the source code. 
Since this would be my first attempt I have no clue how / where to find the source code.
Any help in  just locating the source code would be sufficient for now.

**Comment by matthijskooijman** [comment] 2016-01-06 19:52
@VaclavSal, I think that the matching of braces is taken  care of by the RSyntaxTextArea library / component we use. It is built here: https://github.com/arduino/Arduino/blob/master/app/src/processing/app/Editor.java#L1034-L1070 and some related bits of code are here: https://github.com/arduino/Arduino/tree/master/app/src/processing/app/syntax

The rsyntaxtextarea source code itself can be found at https://github.com/bobbylight/RSyntaxTextArea though in Arduino we currently use a slightly modified version (source is here: https://github.com/arduino/RSyntaxTextArea). In the Arduino source tree, RSTA is included as a .jar file (compiled java code) here: https://github.com/arduino/Arduino/blob/master/app/lib/rsyntaxtextarea-2.5.8.1%2Barduino.jar

I hope this helps you find your way around, though it might be a bit tricky as your first introduction, because the code is split between two projects somewhat.

**Comment by VaclavSal** [comment] 2016-01-06 21:26
Thanks, I'll give it a try.

**Comment by nickgammon** [comment] 2016-01-17 04:02
I also have this problem in Ubuntu, IDE version 1.6.7. See screenshot.

![screenshot from 2016-01-17 14 56 42](https://cloud.githubusercontent.com/assets/185088/12375874/f42c740a-bd2a-11e5-9eae-8d00a81d1e60.png)

It is annoying to have the brace disappear in this way, particularly as it is the "important brace" in this case.

In my tests, if the opening brace is in a different column you can see it:

![screenshot from 2016-01-17 15 00 59](https://cloud.githubusercontent.com/assets/185088/12375881/2d2ea52a-bd2b-11e5-9db1-31cd5957cba8.png)

**Comment by VaclavSal** [comment] 2016-01-17 19:30
I hope I can use this as an supporting argument for early fix. 
I use AutoFormat and if the leading brace is NOT in first column ( tested on loop ())  , AutoFormat will move it there. 

I am sorry, too busy coding and not having time to get my feet wet in Java.

**Comment by per1234** [comment] 2017-07-04 08:46
I can reproduce the issue in Arduino IDE 1.8.1. The issue does not occur in Arduino IDE 1.8.2 (or 1.8.3). This leads me to believe the issue was fixed by https://github.com/arduino/Arduino/pull/6022.

**Closed by per1234** 2017-07-04 08:46 UTC
Labels: Component: IDE user interface, Type: Bug
