### ISSUE TITLE
Store board information beside sketch

### ISSUE THREAD

**Issue by tobiasschuerg** [arduino/Arduino#7746] opened 2018-07-01 10:27 UTC
It would be nice if arduino would create a *project* file in the sketch directory so that I don't need to manually change board setup each time I switch projects.

**Comment by per1234** [comment] 2018-07-01 10:34
Closing as duplicate of #1481, and many others.

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-07-01 10:34 UTC

**Comment by tobiasschuerg** [comment] 2018-07-01 19:09
I actually used the search, but "Autoselection of device" is nothing close to what I searched for. But thanks for linking.

**Comment by mike-s123** [comment] 2019-03-17 00:37
> Closing as duplicate of #1481, and many others.
> 
> We welcome bug reports and feature requests but in the future please take the time to search

I've been searching, and only find MANY closed issues, often pointing to each other, but all referencing the same root issue. Simply closing them as duplicates is NOT HELPFUL without also pointing to an issue which tracks this problem and is current and active.

**Comment by dsyleixa** [comment] 2020-05-09 13:53
IMO the most simple way would be to hardcode-config the targeted board type by configuration in Sketch (e.g. #pragma config...) such as
#pragma config board="Nano"
#pragma config board="NODE_MCU 1.0"
#pragma config board="Adafruit Feather ESP32"
