### ISSUE TITLE
[Feature request] periodically check if open files were touched from outside

### ISSUE THREAD

**Issue by i-make-robots** [arduino/Arduino#9169] opened 2019-08-23 17:10 UTC
In Windows 10, most IDEs and text editors will notice that a file was changed by some other application.  Arduino is a notable exception.

Test case:
- use ide to load file from disk
- touch the file from some other application.

What's expected: 
- "Warning: File has changed on disk.  Reload ? [yes]/[no]"
- if yes, reload file without losing other files (unsaved work in other tabs)

What happens: 
- nothing.

Possible method:
- repeating 5s timer that watches file last touched time.

Thank you, stay awesome!

**Comment by per1234** [comment] 2019-08-23 18:21
I'm going to close this as a duplicate of https://github.com/arduino/Arduino/issues/4551

Note that there is an existing pull request that will do what you are requesting, except without the prompt:
https://github.com/arduino/Arduino/pull/6074

Also note that the Arduino IDE does already update according to outside edits if you have **File > Preferences > Use External Editor** checked. The only limitation is this makes the Arduino IDE's editor window read-only, so you can't edit the sketch using both the external editor and the Arduino IDE.

**Closed by per1234** 2019-08-23 18:21 UTC
