### ISSUE TITLE
Status messages sent to wrong window

### ISSUE THREAD

**Issue by deisterhold** [arduino/Arduino#4099] opened 2015-11-06 17:39 UTC
Arduino Version: 1.6.6
OS: OS X 10.10.5

If you have two sketch windows open and start compiling a sketch in the first window then immediately switch to the second window, the status and debug messages go to the active window. I believe the correct behavior would be that the output from the compiler should go to the window that called it.

**Comment by ffissore** [comment] 2015-11-11 07:45
Duplicate of #2680

**Closed by ffissore** 2015-11-11 07:45 UTC
