### ISSUE TITLE
SerialEvent tutorial omission

### ISSUE THREAD

**Issue by EffC00k** [arduino/Arduino#7669] opened 2018-06-05 18:25 UTC
This tutorial:
https://www.arduino.cc/en/Tutorial/SerialEvent
for SerialEvent()
is missing a call to SerialEvent()
in the loop() function.  The code is never called.

**Comment by per1234** [comment] 2018-06-05 22:29
The tutorial's code is correct. SerialEvent is called from the `main()` function (which is hidden in the core library):

- https://github.com/arduino/ArduinoCore-avr/blob/b7c607663fecc232e598f2c0acf419ceb0b7078c/cores/arduino/main.cpp#L47
- https://github.com/arduino/ArduinoCore-avr/blob/b7c607663fecc232e598f2c0acf419ceb0b7078c/cores/arduino/HardwareSerial.cpp#L64-L68

So even though there is no call in `loop()`, `SerialEvent()` will indeed be called when there is data available.

What is not correct is this statement on that page:
>This function is called inside the loop().

I believe that is the cause of the confusion, and should be fixed.

----
#### My suggested edit to the page:
Change:
>This example demonstrates use of the SerialEvent() function. This function is called inside the loop(). If there is serial data in the buffer each character found is added to a string until a newline is found.

To:
>This example demonstrates use of the **`SerialEvent()`** function. This function is called **when there is Serial data available**. **Each received character** is added to a string until a newline is found.

**Comment by tofrnr** [comment] 2018-06-12 12:40
my suggestion:
Change:... To:

This example demonstrates use of the SerialEvent() function. 
Once having been initialized by an arbitrary function 
void serialEvent() { ... }
this function is called then automatically in the background when there is Serial data available. Notice that there is no need to call this function then repeatedly in the loop() function.
Each received character is added to a string until a newline is found.

**Closed** 2020-09-29 14:24 UTC
Labels: Component: Documentation, Type: Bug
