### ISSUE TITLE
Compiler Segmentation fault when using Serial

### ISSUE THREAD

**Issue by Antares95** [arduino/Arduino#9194] opened 2019-09-04 08:30 UTC
Compiler Logs:

> Arduino:1.8.9 (Windows Store 1.8.21.0) (Windows 10), 开发板："Arduino/Genuino Uno"
> 
> C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino\HardwareSerial.cpp: In member function 'availableForWrite':
> 
> C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino\HardwareSerial.cpp:203:1: internal compiler error: Segmentation fault
> 
>  }
> 
>  ^
> 
> Please submit a full bug report,
> 
> with preprocessed source if appropriate.
> 
> See <http://gcc.gnu.org/bugs.html> for instructions.
> 
> lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status
> 
> compilation terminated.
> 
> c:/program files/windowsapps/arduinollc.arduinoide_1.8.21.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed
> 
> collect2.exe: error: ld returned 1 exit status
> 
> exit status 1
> 为开发板 Arduino/Genuino Uno 编译时出错。
> 
> 在文件 -> 首选项开启
> “编译过程中显示详细输出”选项
> 这份报告会包含更多信息。

How to reproduce:
Compile this code
> 
> void setup() {
>   Serial.begin(9600);
> }
> 
> float i = 0;
> unsigned long t0 = 0;
> void loop() {
>   i += 1.0;
> 
>   if (millis() - t0 > 1000) {
>     Serial.println(i);
>     t0 = millis();
>   }
> }

Arduino IDE version: 1.8.9(Windows Store 1.8.21.0)

**Comment by per1234** [comment] 2019-09-04 14:24
Closing as duplicate of https://github.com/arduino/Arduino/issues/7949

This bug is specific to the 5.4.0-atmel3.6.1-arduino2 version of avr-gcc used by Arduino AVR Boards 1.6.22 and newer. 

#### Here's the traditional workaround:
1. Tools > Board > Boards Manager
1. Wait for downloads to finish.
1. When you move the mouse pointer over "Arduino AVR Boards", you will see a "Select version" dropdown menu appear. Select "1.6.21".
1. Click "Install".
1. Wait for installation to finish.
1. Click "Close".

If you have **File > Preferences > Check for updates on startup** checked, the Arduino IDE may occasionally notify you that a new version of Arduino AVR Boards is available, you'll need to refrain from updating back to the new Arduino AVR Boards version, otherwise you'll be back to seeing the segmentation fault error again.

**Closed by per1234** 2019-09-04 14:24 UTC
