### ISSUE TITLE
Compile not working for onedrive files, 1.8.5, windows version 1709 build 16299.371

### ISSUE THREAD

**Issue by rustyplate** [arduino/Arduino#7487] opened 2018-04-19 01:15 UTC
If i copy files to the desktop no problem, was working before latest windows update.  Error just says unable to find the ino file that is currently open and i am trying to compile.

**Comment by per1234** [comment] 2018-04-19 02:02
Closing as duplicate of https://github.com/arduino/arduino-builder/issues/254.

One solution is simply to not put files that you will be using with the Arduino IDE under OneDrive.

If you do want to continue using OneDrive, the problem has been resolved in the beta build of the Arduino IDE:
https://www.arduino.cc/en/Main/Software#beta
you should be aware that the beta build is primarily intended for beta testing and you will be more likely to encounter bugs than you would using a stable release of the Arduino IDE.

For more information and other workarounds for the problem see:
https://github.com/arduino/arduino-builder/issues/254

**Closed by per1234** 2018-04-19 02:02 UTC
