### ISSUE TITLE
Can't compile with "arduino nano every"

### ISSUE THREAD

**Issue by dvince38** [arduino/Arduino#9652] opened 2020-01-22 07:02 UTC
OS version: Windows 10 build 1903
Arduino IDE version: 1.8.10
Arduino device: Nano Every

Hello,
the code below compiles well with an "arduino nano" but not with an "arduino nano every" :
```c++
const __FlashStringHelper *test()
{
  return F("Hello");
}
void setup() {}
void loop() {}
```

The result is :
```
In file included from sketch\bug.ino.cpp:1:0:

C:\Users\yo\Desktop\bug\bug.ino: In function 'const __FlashStringHelper* test()':

C:\Users\yo\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.5\cores\arduino/Arduino.h:30:20: error: cannot convert 'const char*' to 'const __FlashStringHelper*' in return

 #define F(str) (str)

                    ^

C:\Users\yo\Desktop\bug\bug.ino:4:10: note: in expansion of macro 'F'

   return F("Hello,");

          ^

exit status 1
Erreur de compilation pour la carte Arduino Nano Every
```

**Comment by per1234** [comment] 2020-01-22 07:05
Closing as duplicate of https://github.com/arduino/ArduinoCore-megaavr/issues/62

**Closed by per1234** 2020-01-22 07:05 UTC
Labels: Type: Duplicate
