### ISSUE TITLE
IF content is done in half. It should not at all.

### ISSUE THREAD

**Issue by lunter2** [arduino/Arduino#6492] opened 2017-07-15 12:39 UTC
a is not uninitialized local variable because first Serial.println(a) prints 0 and second 1.

```
void setup() {
  Serial.begin(9600);

  byte pin = 7;

  pinMode(pin, INPUT_PULLUP);

  byte a;
  byte b = 0;
  Serial.println(a); // 0
  Serial.println(b); // 0

  a++;
  b++;
  Serial.println(a); // 1
  Serial.println(b); // 1

  if (digitalRead(pin) == LOW) { // condition always false (no GND on pin)
   a = 123;
   b = 234;
  }

  Serial.println(a); // 123 (should be 1)
  Serial.println(b); // 1
}

void loop() {

}
```

**Comment by per1234** [comment] 2017-07-15 12:50
Duplicate of https://github.com/arduino/Arduino/issues/6491

**Closed by per1234** 2017-07-15 12:50 UTC
Labels: Type: Duplicate, Type: Invalid
