### ISSUE TITLE
Clipboard cleaned when IDE exits

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3674] opened 2015-08-14 17:12 UTC
Not sure if this is a general linux issue (using linux) but if you select the whole sketch, copy it (ctrl c) and then close the IDE the clipboard is empty. I normally use this very often and maybe the new editor inside the IDE changed this. Not sure if it also exists on windows.

**Comment by per1234** [comment] 2015-08-15 16:59
The clipboard is not cleared on exit from IDE with 1.6.6 2015/08/14 02:42 under Windows 7 64 bit.

**Comment by ffissore** [comment] 2015-08-17 06:42
Duplicate of #2332

**Closed by ffissore** 2015-08-17 06:42 UTC
