### ISSUE TITLE
Bug: Arduino IDE 1.8.5 Linux is not working with the Arduino Micro

### ISSUE THREAD

**Issue by jtdaling** [arduino/Arduino#7690] opened 2018-06-13 14:26 UTC
Hello, I would like to report a bug.
I installed Arduino IDE (version 1.8.5) on a Manjaro Linux distro.
When I tried to upload a sketch I received the warning:
avrdude: Expected signature for ATmega32U4 is 1E 95 87

I was sure to have selected the right arduino board, port and I had sufficient rights to use the port.
I installed the same version (1.8.5) on a windows computer and uploaded the same script with the same settings and on Windows it worked.

I tried out some different versions of Arduino IDE and discovered that version 1.6.2 was the latest version that was able to upload sketches under Linux

**Comment by per1234** [comment] 2018-06-13 14:51
Please do this:
1. File > Preferences > Show verbose output during: > compilation (uncheck) > upload (check) > OK
1. Sketch > Upload
1. After the upload fails you'll see a button on the right side of the orange bar "Copy error messages". Click that button.
1. Paste the error messages in a reply here [using code fencing](https://guides.github.com/features/mastering-markdown/).

**Comment by jtdaling** [comment] 2018-06-13 15:07
Her is the error message:

Arduino: 1.8.5 (Linux), Board: "Arduino/Genuino Micro"

Sketch uses 4130 bytes (14%) of program storage space. Maximum is 28672 bytes.
Global variables use 149 bytes (5%) of dynamic memory, leaving 2411 bytes for local variables. Maximum is 2560 bytes.
Forcing reset using 1200bps open/close on port /dev/ttyACM1
PORTS {/dev/ttyACM1, } / {} => {}
PORTS {} / {} => {}
PORTS {} / {/dev/ttyACM1, } => {/dev/ttyACM1, }
Found upload port: /dev/ttyACM1
/home/jantinus/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino9/bin/avrdude -C/home/jantinus/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino9/etc/avrdude.conf -v -patmega32u4 -cavr109 -P/dev/ttyACM1 -b57600 -D -Uflash:w:/tmp/arduino_build_93539/Blink.ino.hex:i 

avrdude: Version 6.3, compiled on Jan 17 2017 at 11:00:16
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/home/jantinus/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino9/etc/avrdude.conf"
         User configuration file is "/home/jantinus/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/ttyACM1
         Using Programmer              : avr109
         Overriding Baud Rate          : 57600
         AVR Part                      : ATmega32U4
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  9000  9000 0x00 0x00
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0x00 0x00
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : butterfly
         Description     : Atmel AppNote AVR109 Boot Loader

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude: devcode selected: 0x44
avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.19s

avrdude: Device signature = 0x433f0d
avrdude: Expected signature for ATmega32U4 is 1E 95 87
         Double check chip, or use -F to override this check.
avrdude: error: programmer did not respond to command: leave prog mode
avrdude: error: programmer did not respond to command: exit bootloader

avrdude done.  Thank you.

the selected serial port 
 does not exist or your board is not connected
Invalid library found in /home/jantinus/Arduino/libraries/sketch_jun13a: /home/jantinus/Arduino/libraries/sketch_jun13a
Invalid library found in /home/jantinus/Arduino/libraries/sketch_jun13a: /home/jantinus/Arduino/libraries/sketch_jun13a

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by nseidle** [comment] 2018-06-14 19:19
This may or may not be related but in the last ~20 hours we've seen micro support break in Windows and Mac (reported but not confirmed).

We can't tell if it's a windows update (not likely since Linux and Mac are reporting similar issue), Java update (we've reverted all the way back to 7 without fix), or something with Arduino (we've tried back to v1.6.x). We are currently dumbfounded, but are starting to hear from customers.

Turning on verbose, the port is correctly found, but Arduino just hangs at the port. 

![image](https://user-images.githubusercontent.com/117102/41433140-3b4a1478-6fd5-11e8-9bd9-6a9b3143e916.png)

If I replicate the avrdude command at CLI it works flawlessly (once I force the Pro Micro into bootloader mode by double-tapping the reset).

May be related: I am seeing the Tools->Ports menu lag behind Windows Device Manager by 20 to 30 seconds. It seems the Arduino IDE can't see the port but avrdude and Windows can.

**Comment by PaulStoffregen** [comment] 2018-06-14 19:29
Is this Linux?  I see lots of talk of COM ports...

**Comment by nseidle** [comment] 2018-06-14 19:32
Sorry if I'm conflating issues but it seems related: We have multiple windows users and a Mac user reporting the same behavior (failed/timeout at point of avrdude call) as jtdaling (serial port does not exist).

**Comment by gdsports** [comment] 2018-06-14 21:40
I noticed the IDE accesses api-builder.arduino.cc on startup (thank you wireshark) so I blocked access to this host. I added an entry to /etc/hosts like this to blacklist the host.

`127.0.0.1       api-builder.arduino.cc`

Now the IDE starts up with the serial ports listed immediately without having to disconnect the network cable.

Perhaps something has changed on api-builder.arduino.cc.

Lots of discussion at forum.arduino.cc. JP2222 at the forum discovered disconnecting the network cable makes the serial problem go away.

[https://forum.arduino.cc/index.php?topic=553078.0](https://forum.arduino.cc/index.php?topic=553078.0)

**Comment by NPoole** [comment] 2018-06-14 22:35
As suggested by gdsports above, adding "127.0.0.1 api-builder.arduino.cc" to your Windows\System32\drivers\etc\hosts file will prevent anything on your machine from talking to that particular domain and it's a good fix for now. (I'm running 1.8.5 on Win10)

An "Application Rule" for Windows Defender Firewall may also work to block the IDE from calling the web. I haven't tested though.

**Comment by jtdaling** [comment] 2018-06-15 08:27
I can confirm that the solution that rmadsen61 suggested, also works for Linux (Arch).
I switched my wireless adapter off and was able to upload scripts without any problems and without having to force the micro into bootloader mode.
After the upload the connection over the serial port was immediately established and  started to receive data send by the Arduino.

**Comment by kshestov** [comment] 2018-09-30 20:07
I have this problem with IDE 1.8.5 on Arch too

**Comment by l0ud** [comment] 2019-05-07 21:35
I know the issue is pretty old, but it still happens on Arch and possibly other linux distros.
For me the problem was ModemManager, which was talking to ttyACM0 device (arduino) thinking it's some sort of USB modem. The simplest solution is to remove "modemmanager" from distro package manager.

**Comment by bjett80** [comment] 2019-06-08 14:02
10ud .... you just brought 2 days of frustration to an end !
Changing udev rules didn't seem to work on Ubuntu 18.10 but removing modemmanager fixed all my problems.  My Pro Micro is now uploading sketches without issue.
Thanks !

**Comment by matthijskooijman** [comment] 2019-06-08 21:22
Note that some issues with modemmanager might have recently (in the last two years) surfaced or resurfaced by changes in modemmanager's probe policy. For a fix in the Arduino side for this, see https://github.com/arduino/ArduinoCore-avr/pull/92.

**Comment by jonmacd** [comment] 2019-06-12 19:01
> I know the issue is pretty old, but it still happens on Arch and possibly other linux distros.
> For me the problem was ModemManager, which was talking to ttyACM0 device (arduino) thinking it's some sort of USB modem. The simplest solution is to remove "modemmanager" from distro package manager.

Thank you. This solved it for me as well running Manjaro.
did `sudo pacman -R modemmanager`
Code is uploading like normal now.

**Comment by JazzTp** [comment] 2019-06-16 06:54
> I know the issue is pretty old, but it still happens on Arch and possibly other linux distros.
> For me the problem was ModemManager, which was talking to ttyACM0 device (arduino) thinking it's some sort of USB modem. The simplest solution is to remove "modemmanager" from distro package manager.

**THANKS!** That solved the same problem with Arduino IDE 1.8.9 on Ubuntu 18.04.2 (with Arduino Leonardo R3).

**Comment by facchinm** [comment] 2019-09-20 10:26
Should be fixed now, please reopen if needed

**Closed by facchinm** 2019-09-20 10:26 UTC
Labels: Component: Avrdude 6.3, Component: Uploading, Waiting for feedback

**Comment by leobel96** [comment] 2019-10-20 14:59
Same issue with actual version of Arduino Web Editor. Removing modemmanager resolved the problem.

> Should be fixed now, please reopen if needed

**Comment by AshiqMehmood** [comment] 2019-11-04 07:07
@l0ud Thanks for suggesting this method !! i am using debian10 and had the same problem of uploading the sketch to Pro-micro.
i used this command  " sudo apt-get purge modemmanager "

**Comment by andreiva** [comment] 2019-11-10 22:27
Holy ******! This saved me a lot of frustration. 
After uploading any sketch to a pro micro (Leonardo) the board would become unresponsive, and the only way to bring it back is to burn the bootloader.

After removing modemmanager, all works fine like before :)
Arduino IDE 1.8.10
Linux Mint 19.2

**Comment by erikjber** [comment] 2020-02-25 19:37
> 10ud .... you just brought 2 days of frustration to an end !
> Changing udev rules didn't seem to work on Ubuntu 18.10 but removing modemmanager fixed all my problems. My Pro Micro is now uploading sketches without issue.
> Thanks !

Awesome! Uninstalling modemmanager from Xubuntu 19.10 solved the issue for me as well. Thank you.

**Comment by andymanning** [comment] 2020-06-03 07:29
I was struggling with getting it all to work on Linux (PopOS) but I found that In the latest version of the Linux download package (1.8.12), there's a script called **arduino-linux-setup.sh** . I ran that and it automatically set up the system and the IDE then just worked!

**Comment by delphir-com** [comment] 2020-11-27 16:48
`sudo apt remove modemmanager` helped on Ubuntu 18.04
