### ISSUE TITLE
Arduino / ARDUBLOCK

### ISSUE THREAD

**Issue by Piet52** [arduino/Arduino#5896] opened 2017-01-21 20:40 UTC
The new version 1.8.1 does not work with Ardublock, why! I can access Ardublock as a tool and create programs in Ardublock, but I can not transfer these programs to the Arduino editor! At the moment I use the Arduino version 1.6.11 and so it works very well!

Piet

**Comment by per1234** [comment] 2017-01-22 00:48
Duplicate of https://github.com/arduino/Arduino/issues/5454

Please do a search at https://github.com/arduino/Arduino/issues?&q= before you submit issues to make sure they have not already been reported.

**Closed** 2017-01-22 11:46 UTC

**Comment by Piet52** [comment] 2017-01-22 11:48
please refer: IDE 1.6.12 for Ardublock #5454
