### ISSUE TITLE
(Bug) avrdude: ser_open(): can't open device "\\.\COM1": The system cannot find the file specified.

### ISSUE THREAD

**Issue by Nic12345** [arduino/Arduino#5371] opened 2016-09-14 22:22 UTC
Please help, every single program I try to upload spits out this message at me:

Arduino: 1.6.11 (Windows 10), Board: "Arduino/Genuino Uno"

Sketch uses 10,578 bytes (32%) of program storage space. Maximum is 32,256 bytes.
Global variables use 387 bytes (18%) of dynamic memory, leaving 1,661 bytes for local variables. Maximum is 2,048 bytes.
avrdude: ser_open(): can't open device "\\.\COM1": The system cannot find the file specified.

Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

**Comment by facchinm** [comment] 2016-09-15 07:38
Duplicate of #5370

**Closed by facchinm** 2016-09-15 07:38 UTC
