### ISSUE TITLE
Arduino ide not opening problem

### ISSUE THREAD

**Issue by miracorhan** [arduino/Arduino#6252] opened 2017-05-02 15:50 UTC
Arduino does not open in the first click, while in the second click opens the problem; If a multi-screen computer was used before, the second screen is trying to open it. The solution is to change the "reflection" screen to "just this computer". It has been observed that the problem is resolved.

**Comment by facchinm** [comment] 2017-05-03 07:34
Duplicate of https://github.com/arduino/Arduino/issues/5581

**Closed by facchinm** 2017-05-03 07:34 UTC
