### ISSUE TITLE
1.6.12 CLI upload issue

### ISSUE THREAD

**Issue by noelpaz** [arduino/Arduino#5476] opened 2016-10-13 01:36 UTC
When using the command line interface on upload I get this error

java.lang.NullPointerException
        at processing.app.BaseNoGui.selectSerialPort(BaseNoGui.java:1088)
        at processing.app.helpers.CommandlineParser.parseArgumentsPhase1(CommandlineParser.java:143)
        at processing.app.Base.<init>(Base.java:273)
        at processing.app.Base.guardedMain(Base.java:219)
        at processing.app.Base.main(Base.java:132)

In my case since I am running headless as part of Jenkins CI I am using xfvb-run

xfvb-run - a arduino --upload --port /dev/ttyACM0 --pref sketchbook.path=/var/jenkins/workspace/215.BAT_Loopback_TT/Bat/../Arduino /var/jenkins/workspace/215.BAT_Loopback_TT/Bat/../Arduino/libraries/IntelTestV2_2/examples/LoopbackTests/LoopbackTests.ino

When I go back to 1.6.11 it works as intended.

EDIT?ADD:
Compiling / verify and other operations just work fine. However when the --port argument is in place you get an error

 xvfb-run -a ~/arduino-1.6.12/arduino --verify --port /dev/ttyACM0 --pref sketchbook.path=Arduino Arduino/libraries/IntelTestV2_2/examples/LoopbackTests/LoopbackTests.in

Loading configuration...
java.lang.NullPointerException
        at processing.app.BaseNoGui.selectSerialPort(BaseNoGui.java:1088)
        at processing.app.helpers.CommandlineParser.parseArgumentsPhase1(CommandlineParser.java:143)
        at processing.app.Base.<init>(Base.java:273)
        at processing.app.Base.guardedMain(Base.java:219)
        at processing.app.Base.main(Base.java:132)

But if you omit the --port it is fine

**Comment by per1234** [comment] 2016-10-13 03:40
Duplicate of https://github.com/arduino/Arduino/issues/5413, which has already been fixed in the hourly build.

**Closed** 2016-10-14 11:08 UTC
Labels: Type: Duplicate
