### ISSUE TITLE
[LibraryManager] Duplicate category Robotic & Robotics

### ISSUE THREAD

**Issue by rlogiacco** [arduino/Arduino#4774] opened 2016-03-28 18:45 UTC
Apparently there has been a typo somewhere ending up in two distinct categories, one called `Robotic` containing solely library `Svante`, one called `Robotics` containing two libraries, `IBot` and `WebServer`.

Please merge into one single category.

**Comment by per1234** [comment] 2016-03-28 22:15
All three of those libraries have had their category changed to a valid value already but the old releases still have the invalid values. IBot and WebServer are actually the same library but the first IBot release had the wrong name value. I wonder if it would be best to request that the library owner remove that release?

**Comment by cmaglie** [comment] 2016-04-04 14:40
(Sort of) duplicate of #4802, please continue the discussion there.

**Closed by cmaglie** 2016-04-04 14:40 UTC
