### ISSUE TITLE
feature request: Serial.print() easy concatenation

### ISSUE THREAD

**Issue by robzach** [arduino/Arduino#8070] opened 2018-10-08 15:57 UTC
Instead of having to write `Serial.print("val = " + String(val))` it would be preferable for `Serial.print` to cast all arguments to strings, i.e. `Serial.print("val = " + val)`.

(Note that the latter *will* compile in 1.8.7, but will produce a torrent of garbage output when viewed with the serial monitor.)

**Comment by per1234** [comment] 2018-10-09 04:18
Closing as duplicate of https://github.com/arduino/Arduino/issues/3546

**Closed by per1234** 2018-10-09 04:18 UTC

**Comment by matthijskooijman** [comment] 2018-10-09 05:01
Note that the request in this issue is different from the proposal in that issue (this requests addition of strings, that allows multiple arguments to print), but since the result is the same (and addition of strings will likely not be easy to implement), marking this as a duplicate makes sense.
