### ISSUE TITLE
Problem running 1.8.8 on OSX 10.11.6 

### ISSUE THREAD

**Issue by jnovec** [arduino/Arduino#8445] opened 2019-01-27 09:02 UTC
Hello,
when i try to run Arduino IDE 1.8.8 on my Mac it ends with crash.
Can you please help ?

Thank you in advance

Jan
[arduino_ide_trace.pdf](https://github.com/arduino/Arduino/files/2799887/arduino_ide_trace.pdf)

**Comment by per1234** [comment] 2019-01-27 10:37
Closing as duplicate of https://github.com/arduino/Arduino/issues/8274

This bug is specific to Arduino IDE 1.8.8. It has already been fixed but there has not been a production release of the Arduino IDE since that time so the fix is only available in the [Hourly Build](https://www.arduino.cc/en/Main/Software#hourly).

The recommended workaround is to use Arduino IDE 1.8.7 instead of Arduino IDE 1.8.8. You can download 1.8.7 here:
https://www.arduino.cc/en/Main/OldSoftwareReleases#previous

**Closed by per1234** 2019-01-27 10:37 UTC
Labels: OS: OSX, Type: Duplicate
