### ISSUE TITLE
Avrdude 6.1

### ISSUE THREAD

**Issue by PaoloP74** [arduino/Arduino#2150] opened 2014-06-30 09:56 UTC
I have seen in the next release 1.5.7 will be added to the IDE avrdude 6.0.1. 
I note that the version 6.1 is available.
--> http://download.savannah.gnu.org/releases/avrdude/

**Comment by ffissore** [comment] 2015-05-20 08:48
Duplicate of https://github.com/arduino/toolchain-avr/issues/17

**Closed by ffissore** 2015-05-20 08:48 UTC
Labels: Component: Toolchain
