### ISSUE TITLE
Inconsistent line ending style created by Arduino IDE on Windows 7

### ISSUE THREAD

**Issue by prjemian** [arduino/Arduino#1552] opened 2013-08-24 18:32 UTC
Using the Arduino IDE 1.0.5 to edit sketches, I find that the editor, when saving a sketch to disk, mixes the line-ending styles.  This is observed on a Windows 7 machine, when editing code that is managed by subversion with the property::

```
svn propset eol:style native mysketch.ino
```

The problem is described when trying to commit changes back to subversion, the commit fails with a report of::

```
Commit failed (details follow):
While preparing
'C:\Users\Me\Documents\Arduino\mysketch\mysketch.ino'
for commit
Inconsistent line ending style
```

I regularly fix this situation by going to a tool that will make all the end-of-line characters consistent for my OS and then try committing again.

The Arduino IDE requires a fix since it is the generator of the inconsistent line endings.  This is easy to demonstrate on a sketch that has several blank lines.  
1. Check that sketch out of subversion
2. open the .ino file with the Arduino IDE
3. delete one blank line
4. save the file
5. check back in to subversion

Step 5 here consistently produces this error for me when using Tortoise SVN as my subversion client.

Note that the same 5-step procedure on Linux Mint 15 and Arduino IDE 1.0.3 with the same project did not produce an error at step 5.

**Comment by ffissore** [comment] 2015-06-08 13:11
Sorry for the late reply. No, we are not going to fix it. Using a uniform line ending makes it easier to share the sketches

**Comment by tico-tico** [comment] 2015-08-26 18:09
Sorry for touching a won't fix bug. Just to make sure you understand the problem, for now IDE's line endings are kinda consistent except for one last CRLF. Editing such files in other editors is PITA coz many of them like uniformity. Not-so-pretty picture for you:

![ardedi](https://cloud.githubusercontent.com/assets/10702026/9501861/89b81198-4c36-11e5-8058-18af27a6cf85.png)

**Comment by prjemian** [comment] 2015-08-26 18:15
understand your position, thanks for the update

**Comment by matthijskooijman** [comment] 2015-08-27 07:24
Reopening this, as *mixing* LF and CRLF inside the same file would indeed be a bug to me (and I think me and @ffissore didn't realize this was the case before).

@tico-tico what OS are you running that on? Did you just open up the IDE and save the empty sketch somewhere? I just tried this on Linux, which just uses LF everywhere.

**Comment by tico-tico** [comment] 2015-08-27 07:46
> what OS are you running that on?

Win 7 x64 SP1 Home Premium.

> Did you just open up the IDE and save the empty sketch somewhere?

i guess i pressed Enter once)) here is screenshot of the unchanged empty sketch. Yes, I just saved it .

![ardued2](https://cloud.githubusercontent.com/assets/10702026/9515111/da7b9282-4ca7-11e5-8ffc-045f3bd7a6f4.png)

The same result, actually.

I don't know if it matters, anyway, screenshot of the cpp file:

![ardued3](https://cloud.githubusercontent.com/assets/10702026/9515214/9870a994-4ca8-11e5-9489-df05236894aa.png)

**Comment by matthijskooijman** [comment] 2015-08-27 12:16
Interesting that some `#line` directives also get inserted with  CRLF apparently, but not others...

**Comment by tico-tico** [comment] 2015-08-27 16:41
Another piece of information. I just realize that there is NO new line at the end of the code if I use Arduino IDE, addition new line (CRLF) appears only in the SAVED file. I mean

__number_of_lines_in_IDE__ == __number_of_lines_in_file__ - 1

Some uses println() for saving :smile: A joke and a hint.))

**Comment by per1234** [comment] 2018-03-19 07:02
Closing as duplicate of https://github.com/arduino/Arduino/issues/6736, due to that one having received better attention.

This should be fixed in the [beta build](https://www.arduino.cc/en/Main/Software#beta).

**Closed by per1234** 2018-03-19 07:02 UTC
Labels: Component: IDE, Type: Bug
