### ISSUE TITLE
[Arduino Create Plugin] installing on debian

### ISSUE THREAD

**Issue by lostsh** [arduino/Arduino#9639] opened 2020-01-18 21:41 UTC
# Instalation of Arduino Create Agent on Debian 10

Installation of the plugin does not seem to work, however, it can be noted that the process proceeds without apparent problems, and that no error messages are returned, however the plugin does not work.

Source code : [here](https://github.com/arduino/arduino-create-agent/)

**Comment by per1234** [comment] 2020-01-22 04:16
Closing as duplicate of https://github.com/arduino/arduino-create-agent/issues/515

**Closed by per1234** 2020-01-22 04:16 UTC
Labels: Type: Duplicate
