### ISSUE TITLE
"Link status" missing

### ISSUE THREAD

**Issue by ibantxo** [arduino/Arduino#3993] opened 2015-10-18 07:10 UTC
Arduino/libraries/Ethernet (W5100 chip)

In the Ethernet Shield there are some status leds: PWR, LINK, 100M...

How could I get the "LINK" status from my code?

**Comment by ibantxo** [comment] 2015-10-19 13:26
I have found the ISSUE number 855: Ethernet library should doesn't notice if the physical layer is disconnected (https://code.google.com/p/arduino/issues/detail?id=855&can=1&q=w5100%20link)

That is my problem!!

As they say, reading the W5100 datasheet v1.2.2 there is no register corresponding to the link status. But there is a led for it!!!

**Comment by ibantxo** [comment] 2015-10-19 14:00
Maybe reading one W5100 internal register via SPI from arduino...

**Comment by NicoHood** [comment] 2015-10-20 15:53
Maybe you should get the ethernet shield schematic and look where the led is conencted to. It must be connected to the W5100. And if your datasheets says there is no register to read the data, only the pin lets you know the state. So you can solder a wire to the led or just... give up. (I never read the datasheet, just answered based on the given information)

**Comment by cmaglie** [comment] 2015-10-20 22:23
Duplicate of #855.

Unfortunately it's not possible, the W5100 has no registers that reports the status.

**Closed by cmaglie** 2015-10-20 22:23 UTC
