### ISSUE TITLE
Unable to startup Arduino IDE

### ISSUE THREAD

**Issue by LovelyA72** [arduino/Arduino#7984] opened 2018-09-11 05:06 UTC
Expected: Arduino startup normally

Actual: The splash screen display then disappear.

Error: 

> Error parsing library.index:Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (FileInputStream); line: 1, column: 2]
正在准备开发板...
java.lang.NullPointerException
        at cc.arduino.contributions.libraries.LibrariesIndexer.rescanLibraries(LibrariesIndexer.java:140)
        at cc.arduino.contributions.libraries.LibrariesIndexer.setLibrariesFolders(LibrariesIndexer.java:109)
        at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:677)
        at processing.app.Base.onBoardOrPortChange(Base.java:1313)
        at processing.app.Base$11.actionPerformed(Base.java:1514)
        at processing.app.Base.rebuildBoardsMenu(Base.java:1490)
        at processing.app.Base.<init>(Base.java:267)
        at processing.app.Base.main(Base.java:145)

OS: Windows 10 1803
Arduino IDE: 1.8.6
JAVA: 

> java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

System language: English US
Display language: Chinese Simplified

**Comment by per1234** [comment] 2018-09-11 05:11
Closing as duplicate of https://github.com/arduino/Arduino/issues/7937

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

This bug has already been fixed in the hourly build and the upcoming Arduino IDE 1.8.7. You will also find the Arduino IDE 1.8.6 workaround in the linked forum thread.

**Closed by per1234** 2018-09-11 05:11 UTC
Labels: Type: Duplicate
