### ISSUE TITLE
unable to find a register to spill in class 'POINTER_REGS' error

### ISSUE THREAD

**Issue by Y-forest** [arduino/Arduino#7918] opened 2018-08-24 09:10 UTC
I'm implementing 'trainable neural network' (a code by Giorgi Butbaia ) in my ATTINY85 chip and can't fix this error :

Trainable_Neural_Net:160: error: unable to find a register to spill in class 'POINTER_REGS'

 }

 ^

Trainable_Neural_Net:160: error: this is the insn:

(insn 269 268 271 5 (set (reg/v:SF 109 [ t_n ])

        (mem:SF (post_inc:HI (reg:HI 150 [ ivtmp.129 ])) [2 MEM[base: _228, offset: 0B]+0 S4 A8])) C:\Users\user\Desktop\Trainable_Neural_Net\Trainable_Neural_Net.ino:110 100 {*movsf}

     (expr_list:REG_INC (reg:HI 150 [ ivtmp.129 ])

        (nil)))

**Comment by per1234** [comment] 2018-08-24 09:14
Closing as duplicate of https://github.com/arduino/Arduino/issues/3972

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

If you're only looking for help with your project then the [Arduino Forum](http://forum.arduino.cc/) is the appropriate place, not here.

**Closed by per1234** 2018-08-24 09:14 UTC
Labels: Type: Duplicate
