### ISSUE TITLE
Wrong recognition of nested comments /**/ in the IDE

### ISSUE THREAD

**Issue by Gianluca755** [arduino/Arduino#4954] opened 2016-05-15 18:23 UTC
The /* */ don't work if they are nested.
example:

/*
not executable code
   /*
comments
   */
executable code 
*/

**Comment by matthijskooijman** [comment] 2016-05-15 22:01
This is how block comments work in C/C++ (which is the language that your sketch is actually written in). This is not something Arduino can/should change. Instead, you could use the `#if 0` trick, see also http://stackoverflow.com/a/6797546/740048.

I'm closing this, as this isn't actual a bug but by design (even though it is annoying).

**Closed by matthijskooijman** 2016-05-15 22:01 UTC
