### ISSUE TITLE
Arduino IDE crashes if Mac lid closed and connected to ext. monitor

### ISSUE THREAD

**Issue by mdelag** [arduino/Arduino#9778] opened 2020-02-17 21:06 UTC
As the title says, IDE crash occurs when shifting from open lid to closed lid and connected to external monitor and viceversa.

MacOS Catalina 10.15.3
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

**Comment by per1234** [comment] 2020-02-18 00:10
@mdelag is it the same error reported here: https://github.com/arduino/Arduino/issues/9764?

**Comment by mdelag** [comment] 2020-02-18 00:12
@per1234 looks like it's a similar setup.

**Comment by per1234** [comment] 2020-03-02 04:42
Closing as duplicate of https://github.com/arduino/Arduino/issues/9764

**Closed by per1234** 2020-03-02 04:42 UTC
Labels: Component: IDE, Type: Bug
