### ISSUE TITLE
[Library Manager] Please add libedge 1.1 to Library Manager

### ISSUE THREAD

**Issue by onekick** [arduino/Arduino#7355] opened 2018-03-21 08:17 UTC
URL: https://github.com/EdgeiLAB/libedge.git

Release : libedge 1.1

Description: previous version 1.0 has trivial problem and updated 1.1 version.

thank you!

**Comment by per1234** [comment] 2018-03-21 08:25
It's not necessary to submit a request for every release of the library so I'll close this as a duplicate of https://github.com/arduino/Arduino/issues/7354. Once your library is added to the Library Manager index, the job will regularly check your repository new releases and those will automatically be made available for installation via Library Manager.

There is a problem with your latest release though. You should always update the `version` field in library.properties before making a release because it is that property which Library Manager uses for versioning of your library. So currently you have two releases with a 1.0 version. The Library Manager indexer will only pick up one of the two. IIRC that will be the first one released.

**Closed by per1234** 2018-03-21 08:25 UTC
