### ISSUE TITLE
The download version of Arduino does not work with newest macOS update 

### ISSUE THREAD

**Issue by hanne-louise** [arduino/Arduino#9407] opened 2019-11-07 16:26 UTC
I don't know if it is a bug but with macOS Catalina 10.15 I can not open the download version of Arduino

**Comment by gvarisco** [comment] 2019-11-11 20:59
Hi @hanne-louise, could you please tell us what is the errors that gets displayed and/or attach a screenshot?

**Comment by aurman** [comment] 2019-11-16 21:02
“Arduino” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

<img width="420" alt="Screen Shot 2019-11-16 at 21 02 19" src="https://user-images.githubusercontent.com/1455805/68999160-6fbcc880-08b4-11ea-9055-804d4f7d8150.png">

**Comment by per1234** [comment] 2019-11-18 09:07
Closing as duplicate of https://github.com/arduino/Arduino/issues/9314

**Closed by per1234** 2019-11-18 09:07 UTC
Labels: Component: IDE, OS: OSX, Type: Bug, Type: Duplicate
