### ISSUE TITLE
Arduino freezes when deleting active project folder

### ISSUE THREAD

**Issue by ulfstottmeister** [arduino/Arduino#7260] opened 2018-02-26 03:32 UTC
Steps to reproduce the error:
(Warning: make a backup of the project in question first!)

1. Open a project in Arduino.
2. Click "Save As.."
3. In the Dialog, browse to the project folder of the current project
4. Delete the folder within the "Save As.." Dialog.

This makes Arduino hang everytime.
Tested on Windows, Arduino 1.8.4

**Comment by per1234** [comment] 2018-02-26 03:52
Closing as duplicate of 
https://github.com/arduino/Arduino/issues/5191
We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-02-26 03:52 UTC
