### ISSUE TITLE
Make the STK_500 error more friendly.

### ISSUE THREAD

**Issue by tigoe** [arduino/Arduino#1996] opened 2014-04-07 16:40 UTC
One of the most common errors beginners get is the STK_500 getsync() error:

avrdude: stk500_getsync(): not in sync: resp=0x00

(see http://forum.arduino.cc/index.php?topic=28223.00)

It would be good to put a wrapper around that makes it more helpful to beginners. Though it could be because of several reasons, a simple response would be "Your Arduino board is not responding to the upload request. There are several possible reasons. Check XXX for more info."

XXX could point to the forum or any of the many web pages that address it, including:  
http://www.ladyada.net/learn/arduino/lesson1.html

**Comment by per1234** [comment] 2017-07-03 06:33
Closing as duplicate of https://github.com/arduino/Arduino/issues/868

**Closed by per1234** 2017-07-03 06:33 UTC
Labels: Type: Duplicate
