### ISSUE TITLE
Print statements influence output of variable values 

### ISSUE THREAD

**Issue by carlcrott** [arduino/Arduino#5387] opened 2016-09-19 18:26 UTC
http://pastebin.com/raw/ZBqu75dQ

The above arduino code will output two different values for: 
`Serial.println(ODSeeRaw_on);`

Depending whether the *print* statements on ln52/53  are active or commented out:
`Serial.print("all_on: ");`
`Serial.println(all_on);`

Fixing the way the variables on lines 
`int ODSeeRaw_on, ODSeeRaw_off = 0;`
`int all_on, all_off = 0;`

to: 

`int ODSeeRaw_on = 0 , ODSeeRaw_off = 0;`
`int all_on = 0, all_off = 0;`
...fixed this issue ... but its still weird that the print statements caused this behavior.

Correct output, with print statements active:
> 565
> 564
> 562
> 561
> 559
> 558
> 557
> 555
> 554
> 552
> 551
> 550
> 578
> 576
> 574
> 572
> 570
> 569
> 567
> 566
> all_on: 11275
> ODsee = 48,563
> 570
> 569
> 567
> 566
> 564
> 562
> 561
> 560
> 558
> 557
> 555
> 555
> 552
> 551
> 550
> 564
> 576
> 574
> 572
> 571
> all_on: 11269
> ODsee = 48,563
> 576
> 574
> 572
> 570
> 569
> 568
> 566
> 565
> 563
> 562
> 560
> 559
> 558
> 556
> 555
> 554
> 552
> 551
> 550
> 578
> all_on: 11273
> ODsee = 48,563

Inorrect output, with print statements active:
> 564
> 576
> 574
> 572
> 571
> 569
> 568
> 566
> 565
> 563
> 562
> 560
> 559
> 557
> 556
> 555
> 553
> 552
> 550
> 549
> ODsee = 48,766
> 561
> 560
> 558
> 557
> 556
> 555
> 553
> 551
> 550
> 565
> 576
> 574
> 572
> 571
> 569
> 568
> 566
> 565
> 563
> 562
> ODsee = 48,767
> 564
> 576
> 574
> 572
> 571
> 569
> 568
> 566
> 564
> 563
> 561
> 560
> 559
> 558
> 556
> 555
> 554
> 552
> 551
> 549
> ODsee = 47,766

**Comment by matthijskooijman** [comment] 2016-09-19 20:44
int ODSeeRaw_on, ODSeeRaw_off = 0;

This line declares two variables, initializes the second one to 0 and *leaves the first one unitialized*. That variable can have any value, depending on what is in the registers or on the stack, so other statements can affect it.

The code is behaving as intended, so I'm closing this issue. If you can point out a place in the Arduino documentation that could have been better to prevent this confusion on your side, let us know and we can see if we can fix that.

**Closed by matthijskooijman** 2016-09-19 20:44 UTC
