### ISSUE TITLE
analogWrite in loop() seems to interfere with digitalWrite in serialEvent() [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1091] opened 2012-11-15 19:04 UTC
This is [Issue 1091](http://code.google.com/p/arduino/issues/detail?id=1091) moved from a Google Code project.
Added by 2012-11-01T02:46:10.000Z by [bmi...@gmail.com](http://code.google.com/u/105963512006120788592/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description
```
/* serial_pin_control_with_breathing - take commands from serial and light or extinguish leds based on it

Demonstration of taking serial commands while doing something else.

*/



int max_led=7;
int min_led=2;
int state=0;
int position=0;

// the setup routine runs once when you press reset:
void setup() {                
  // initialize the digital pin as an output.
  for (int pin=min_led;pin<=max_led;pin++) 
  {
    pinMode(pin, OUTPUT);     
    digitalWrite(pin,LOW);
  }
  Serial.begin(115200);
  pinMode(11, OUTPUT);
}

void loop(){
  // breathing effect from http://sean.voisen.org/blog/2011/10/breathing-led-with-arduino/ to test using serialEvent to 
  // "multitask".
  float val = (exp(sin(millis()/2000.0*PI)) - 0.36787944)*108.0;
  analogWrite(11, val);
  delay(1); // needed so that the digitalWrites in serialEvent() go through.  I do not know why this is needed!
}

void serialEvent() {

 Serial.println(state);
 switch(state) {
   case 0: {
     char inChar = (char)Serial.read();
     if (inChar!='\n') { // ignore newlines
       position=atoi(&inChar);
       state++;
     }
     break;
   }
   case 1: {
     char inChar = (char)Serial.read();

     if (inChar=='+') {
       digitalWrite(min_led+position,HIGH);
     } else if (inChar=='-') {
       digitalWrite(min_led+position,LOW);
     }
   state=0;
   Serial.println("command done");
   break;
   }
  
  }

}
```
If I remove delay(1) from the loop, the serial routine works, but the LEDs do not go on or off.  If I remove both delay(1) and analogWrite(11, val) then the LEDs work.  The LEDs also work if loop() is blank.

**Comment by tadam777** [comment] 2015-12-28 09:56
This is maybe related to a previous bug with digitalWrite : if digitalWrite is used in the main loop and at the exact same time in an interrupt, there was an issue.

This seems to be the case in your code, as serialEvent is interrupt driven.

This was apparently solved a long time ago, but maybe not completely :

https://code.google.com/p/arduino/issues/detail?id=146

About the 1ms delay, it just makes it much more unlikely to happen, as the mail loop will then make a digitalWrite only +-0.1% of the time rather than +-90% of the time.

**Comment by NicoHood** [comment] 2015-12-28 09:57
Serialevent is not interrupt driven. One more reason to remove it.
https://github.com/arduino/Arduino/issues/4328

**Comment by matthijskooijman** [comment] 2015-12-28 10:54
I just tried this code with a recent build from git, and it works just fine, even when I remove the delay. I suspect that there was either a bug that has been fixed already, or the problem was in the original reporters test setup. In any case, I'm closing this bug. If someone can reproduce it after all, just leave a comment and we can reopen.

**Closed by matthijskooijman** 2015-12-28 10:54 UTC
