### ISSUE TITLE
Arduino IDE UI not high-DPI aware on Windows

### ISSUE THREAD

**Issue by noeldev** [arduino/Arduino#4042] opened 2015-10-29 11:18 UTC
Apart from the menus that are handled by the system itself, the different texts of the IDE are too small by default on screens with size of text set to 150% or more in Display settings, and only the text in the editor can be enlarged.

**Comment by PaulStoffregen** [comment] 2015-10-29 11:41
duplicate of #2776

**Closed** 2015-10-29 11:53 UTC
Labels: Type: Duplicate
