### ISSUE TITLE
[Library Manager]  Please update for TridentTD_Linenotify V3.0.2 (fix library.properties to 3.0.2) 

### ISSUE THREAD

**Issue by TridentTD** [arduino/Arduino#11507] opened 2021-05-10 04:24 UTC
Hi,

Could you please update TridentTD_Linenotify V3.0.1 to the latest V3.0.2 version in library manager?
( Already fixed version in library.properties  3.0.2)

https://github.com/TridentTD/TridentTD_LineNotify/releases/tag/3.0.2

Thank you very much.

**Comment by per1234** [comment] 2021-05-10 06:23
Duplicate of https://github.com/arduino/Arduino/issues/11499

**Closed by per1234** 2021-05-10 06:23 UTC
