### ISSUE TITLE
Input Method to compose complex characters

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#2430] opened 2014-11-09 03:27 UTC
There are 2 bugs to use Korean characters:
1. If any ASCII character such as white space, comma, dot, or number is typed in during composing the Korean character, the currently composed Korean character is disappeared as like deleted in the screen of the Edit and the Serial Monitor windows. 
2. Korean characters are commonly consisted of 3 components: 1) beginning consonant, 2) vowel, and 3) final consonant. Sometimes the final consonant of the previous composed character becomes the beginning consonant of the following composed character. If the previous final consonant becomes the beginning consonant of the next composed character, then the previous composed Korean character should be redrawed with the final completely composed Korean character, but it is still displayed with the final consonant which becomes the beginning consonant of the next Korean character.
- Same in 1.5.x

**Comment by ffissore** [comment] 2015-05-12 08:12
This should be fixed with the new editor, available with the latest hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by Myriads** [comment] 2015-05-12 10:48
It works great. Thanks a lot. 

But still there is a bug in the Serial monitor. 

![ide-1 6 5 01](https://cloud.githubusercontent.com/assets/9634845/7585490/1411e9a0-f8df-11e4-819e-329e87f6f5db.png)
This sketch directly prints out the Korean characters "한글" to serial monitor and after that displays the inputString received from the serial monitor.

![ide-1 6 5 02](https://cloud.githubusercontent.com/assets/9634845/7585496/18561892-f8df-11e4-8560-f350f6995531.png)
The inputString is displayed well but the directly printed Korean characters "한글" are broken. Korean characters are displayed as like as the following attached picture.


![ide-1 6 5 03](https://cloud.githubusercontent.com/assets/9634845/7585502/1df1afb4-f8df-11e4-9655-1f0c28296080.png)

**Comment by cmaglie** [comment] 2015-05-12 11:13
May you cut&paste your sketch here?

**Comment by cmaglie** [comment] 2015-05-12 13:00
Nevermind, I reproduced (more or less) the issue with this sketch on an Arduino Due:

```C++
void setup() {  Serial.begin(9600); }

void loop() {  Serial.println("한글");  delay(1000); }
```

Before giving false expectations let me say that the strings functions in Arduino are designed to work with plain ASCII characters, so if you try to use UTF8 characters it may work in simple cases but you may encounter random faulty behaviours on more complex sketches for example if you try to concatenate two strings or extract a substring from a bigger one.

Said that, it happens that the above sketch works if I connect to the serial port with an external terminal program like Putty but it prints random garbage with the serial monitor of the Arduino IDE. So my conclusion is that something weird is happening on the Arduino Serial Monitor.

My guess is that the issue is in how the incoming chars are buffered here:
https://github.com/arduino/Arduino/blob/master/arduino-core/src/processing/app/Serial.java#L156

```java
        byte[] buf = port.readBytes(serialEvent.getEventValue());
        if (buf.length > 0) {
          String msg = new String(buf);
          char[] chars = msg.toCharArray();
          message(chars, chars.length);
        }
```

an UTF8 char may be composed of many bytes, and the String object can extract the correct UTF8 char only if a complete UTF8 char is received in one single read. If the a multi-byte UTF8 char is fragmented the two consecutive calls to String constructor are not able to build the correct character.

This is a tricky issue, because JSSC doesn't implement the InputStream interface but, instead, has this weird readBytes() method that returns an array of bytes. See https://github.com/scream3r/java-simple-serial-connector/issues/17

The best fix would be to implement an InputStream interface in JSSC and feed the InputStream into an InputStreamReader or a BufferedReader that will do all the correct buffering and decoding.

An alternative is to write an anonymous-InputStream wrappen around the JSSC's Serial object to obtain the same result.

**Comment by Myriads** [comment] 2015-05-12 15:35
Here is the sketch:

<div style="display:inline-block; background-color:#FFFFFF; "><table style="font-family:'Consolas';font-size:12px; white-space:nowrap !important;" border="0" cellpadding="0" cellspacing="0" width="743"><tbody><tr style="margin:0; padding:0;"><td style="color:#888888; width:12px; margin:0; padding:0 3px; text-align:right; border-right:1px solid #e0e0e0"><div>1</div><div>2</div><div>3</div><div>4</div><div>5</div><div>6</div><div>7</div><div>8</div><div>9</div><div>10</div><div>11</div><div>12</div><div>13</div><div>14</div><div>15</div><div>16</div><div>17</div><div>18</div><div>19</div><div>20</div><div>21</div><div>22</div><div>23</div><div>24</div><div>25</div><div>26</div><div>27</div><div>28</div><div>29</div><div>30</div><div>31</div><div>32</div><div>33</div><div>34</div><div>35</div><div>36</div><div>37</div><div>38</div><div>39</div><div>40</div><div>41</div><div>42</div><div>43</div><div>44</div><div>45</div><div>46</div><div>47</div><div>48</div><div>49</div><div>50</div><div>51</div><div>52</div><div>53</div><div>54</div><div>55</div><div>56</div><div>57</div><div>58</div><div>59</div><div>60</div></td><td style="padding: 0 0 0 3px"><div style="background-color:#F7F7F7;"><font color="#434F54">/*</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;&nbsp;Serial&nbsp;Event&nbsp;example</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;When&nbsp;new&nbsp;serial&nbsp;data&nbsp;arrives,&nbsp;this&nbsp;sketch&nbsp;adds&nbsp;it&nbsp;to&nbsp;a&nbsp;String.</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;When&nbsp;a&nbsp;newline&nbsp;is&nbsp;received,&nbsp;the&nbsp;loop&nbsp;prints&nbsp;the&nbsp;string&nbsp;and&nbsp;</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;clears&nbsp;it.</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;A&nbsp;good&nbsp;test&nbsp;for&nbsp;this&nbsp;is&nbsp;to&nbsp;try&nbsp;it&nbsp;with&nbsp;a&nbsp;GPS&nbsp;receiver&nbsp;</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;that&nbsp;sends&nbsp;out&nbsp;NMEA&nbsp;0183&nbsp;sentences.&nbsp;</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;Created&nbsp;9&nbsp;May&nbsp;2011</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;by&nbsp;Tom&nbsp;Igoe</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;This&nbsp;example&nbsp;code&nbsp;is&nbsp;in&nbsp;the&nbsp;public&nbsp;domain.</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;http://www.arduino.cc/en/Tutorial/SerialEvent</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;*/</font>&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#00979C">String</font>&nbsp;inputString&nbsp;=&nbsp;<font color="#006699">""</font>;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#434F54">//&nbsp;a&nbsp;string&nbsp;to&nbsp;hold&nbsp;incoming&nbsp;data</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#00979C">boolean</font>&nbsp;stringComplete&nbsp;=&nbsp;<font color="#00979C">false</font>;&nbsp;&nbsp;<font color="#434F54">//&nbsp;whether&nbsp;the&nbsp;string&nbsp;is&nbsp;complete</font>&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#00979C">void</font>&nbsp;<font color="#5E6D03">setup</font>()&nbsp;{&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;<font color="#434F54">//&nbsp;initialize&nbsp;serial:</font>&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;<font color="#D35400"><b>Serial</b></font>.<font color="#D35400">begin</font>(115200);&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;<font color="#434F54">//&nbsp;reserve&nbsp;200&nbsp;bytes&nbsp;for&nbsp;the&nbsp;inputString:</font>&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;inputString.reserve(200);&nbsp;</div><div style="background-color:#FFFFFF;">}&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#00979C">void</font>&nbsp;<font color="#5E6D03">loop</font>()&nbsp;{&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;<font color="#434F54">//&nbsp;print&nbsp;the&nbsp;string&nbsp;when&nbsp;a&nbsp;newline&nbsp;arrives:</font>&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;<font color="#5E6D03">if</font>&nbsp;(stringComplete)&nbsp;{&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;&nbsp;&nbsp;<font color="#D35400"><b>Serial</b></font>.<font color="#D35400">print</font>(<font color="#006699">"한글:"</font>);&nbsp;&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;&nbsp;&nbsp;<font color="#D35400"><b>Serial</b></font>.<font color="#D35400">print</font>(inputString);&nbsp;&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;&nbsp;&nbsp;<font color="#434F54">//&nbsp;clear&nbsp;the&nbsp;string:</font>&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;&nbsp;&nbsp;inputString&nbsp;=&nbsp;<font color="#006699">""</font>;&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;&nbsp;&nbsp;stringComplete&nbsp;=&nbsp;<font color="#00979C">false</font>;&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;}&nbsp;</div><div style="background-color:#F7F7F7;">}&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">/*</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;&nbsp;SerialEvent&nbsp;occurs&nbsp;whenever&nbsp;a&nbsp;new&nbsp;data&nbsp;comes&nbsp;in&nbsp;the</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;hardware&nbsp;serial&nbsp;RX.&nbsp;&nbsp;This&nbsp;routine&nbsp;is&nbsp;run&nbsp;between&nbsp;each</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;time&nbsp;loop()&nbsp;runs,&nbsp;so&nbsp;using&nbsp;delay&nbsp;inside&nbsp;loop&nbsp;can&nbsp;delay</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#434F54">&nbsp;response.&nbsp;&nbsp;Multiple&nbsp;bytes&nbsp;of&nbsp;data&nbsp;may&nbsp;be&nbsp;available.</font>&nbsp;</div><div style="background-color:#FFFFFF;"><font color="#434F54">&nbsp;*/</font>&nbsp;</div><div style="background-color:#F7F7F7;"><font color="#00979C">void</font>&nbsp;serialEvent()&nbsp;{&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;<font color="#5E6D03">while</font>&nbsp;(<font color="#D35400"><b>Serial</b></font>.<font color="#D35400">available</font>())&nbsp;{&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;&nbsp;&nbsp;<font color="#434F54">//&nbsp;get&nbsp;the&nbsp;new&nbsp;byte:</font>&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;&nbsp;&nbsp;<font color="#00979C">char</font>&nbsp;inChar&nbsp;=&nbsp;(<font color="#00979C">char</font>)<font color="#D35400"><b>Serial</b></font>.<font color="#D35400">read</font>();&nbsp;&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;&nbsp;&nbsp;<font color="#434F54">//&nbsp;add&nbsp;it&nbsp;to&nbsp;the&nbsp;inputString:</font>&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;&nbsp;&nbsp;inputString&nbsp;+=&nbsp;inChar;&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;&nbsp;&nbsp;<font color="#434F54">//&nbsp;if&nbsp;the&nbsp;incoming&nbsp;character&nbsp;is&nbsp;a&nbsp;newline,&nbsp;set&nbsp;a&nbsp;flag</font>&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;&nbsp;&nbsp;<font color="#434F54">//&nbsp;so&nbsp;the&nbsp;main&nbsp;loop&nbsp;can&nbsp;do&nbsp;something&nbsp;about&nbsp;it:</font>&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;&nbsp;&nbsp;<font color="#5E6D03">if</font>&nbsp;(inChar&nbsp;==&nbsp;<font color="#006699">'\n'</font>)&nbsp;{&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stringComplete&nbsp;=&nbsp;<font color="#00979C">true</font>;&nbsp;</div><div style="background-color:#F7F7F7;">&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;&nbsp;}&nbsp;</div><div style="background-color:#F7F7F7;">}&nbsp;</div><div style="background-color:#FFFFFF;">&nbsp;</div></tr><tr><td colspan="2"><div style="text-align:right;">Colored by <font color="#5E6D03"><b>WayFarer&#8482</b></font></div></td></tr></tbody></table></div>

**Comment by cousteaulecommandant** [comment] 2016-04-29 13:44
> If the multi-byte UTF8 char is fragmented the two consecutive calls to String constructor are not able to build the correct character.

With UTF-8 it is possible to detect whether a "chunk" of bytes ends in a single-byte (ASCII) character or a multi-byte sequence, and it is relatively easy to manually check whether this multi-byte sequence is complete or not (also the number of bytes that are in this chunk and the number of bytes that are missing).  Therefore if a chunk ends in an incomplete multi-byte sequence, this sequence could be stripped and "saved for later", either "pushed back" with something like C's `ungetc()` if available, or by just saving it in an internal variable that will be prepended to the next chunk.

This involves the serial monitor being a bit smart though; plus the fix I'm mentioning is specific to UTF-8.  If the InputStream solution is easy to implement and already takes care of this, it's probably a better solution.

**Comment by PaulMurrayCbr** [comment] 2016-05-12 06:54
Yeah - the issue is a design one. The serial monitor uses this "message" interface that works with strings, because when sending stuff via the monitor you type something and then hit return. But this doesn't work for receiving bytes. The "message" model is inappropriate for the serial monitor altogether.

**Comment by aknrdureegaesr** [comment] 2017-02-05 18:14
As noted over at [4452](https://github.com/arduino/Arduino/issues/4452#issuecomment-277534907):

The String-constructor documentation advises to use a `CharsetDecoder` instead, if better control is needed.

I think that's good advice. This would give control over the encoding used, which is the point of #4452 .

Clean UTF-8 decoding even in the split character case is also a feature included in `CharsetDecoder`. It has the appropriate buffer that holds back the few bytes that belong to a not-yet completed character. See its [documentation](http://docs.oracle.com/javase/8/docs/api/java/nio/charset/CharsetDecoder.html).

So using this would be an easy fix, with no need to completely redo the "message" model. I think it's not that bad a choice, actually.

**Closed** 2017-02-20 16:11 UTC
Labels: Component: IDE user interface
