### ISSUE TITLE
I2C Master Reader/Slave Sender

### ISSUE THREAD

**Issue by Baptistou38** [arduino/Arduino#9933] opened 2020-03-27 09:07 UTC
Hello, in the Wire library documentation, page https://www.arduino.cc/en/Tutorial/MasterReader
the code example for the second arduino is for the slave as reader and not the slave sender. Would anyone update this ?
Baptistou

**Comment by per1234** [comment] 2020-03-27 09:09
Closing as duplicate of https://github.com/arduino/Arduino/issues/9740

**Closed by per1234** 2020-03-27 09:09 UTC
