### ISSUE TITLE
Release 1.9.x Library Manager unpacking error to folder portable

### ISSUE THREAD

**Issue by ANMay-ru** [arduino/Arduino#8794] opened 2019-04-15 08:45 UTC
If the Portable folder is created in the Arduino folder, when installing or updating libraries, the archive is unpacked into the Arduino root folder (.\arduino-PR-beta1.9-BUILD-105\sketchbook\libraries\..), but must be in (.\arduino-PR-beta1.9-BUILD-105\portable\sketchbook\libraries\..)

**Comment by per1234** [comment] 2021-04-04 08:40
Thanks so much for reporting this bug @ANMay-ru. I'm not able to reproduce this issue with the latest beta build (119), so I'm going to guess this was since fixed and close it as such.

If you are still able to reproduce the issue with the latest version of the beta IDE, please comment here with any additional information (which operating system you're using, exact set of steps we can follow to reproduce the bug) and I'll be sure to reopen this.

**Closed by per1234** 2021-04-04 08:40 UTC
Labels: IDE 1.9.x Beta, Type: Bug
