### ISSUE TITLE
Pro Mini baud rate error

### ISSUE THREAD

**Issue by Parms01** [arduino/Arduino#8392] opened 2019-01-14 23:20 UTC
IDE 1.8.8 ... Serial.begin(115200) actually establishes serial comms at 57600.

**Comment by per1234** [comment] 2019-01-15 00:48
This issue is caused by you having one of the 16 MHz options selected from the **Tools > Processor** menu when your Pro Mini is actually running at 8 MHz. It can be resolved by choosing the correct **Tools > Processor** menu selection and then uploading the sketch to your Pro Mini again.

**Closed by per1234** 2019-01-15 00:48 UTC
Labels: Type: Invalid

**Comment by Parms01** [comment] 2019-01-15 00:54
Oops! ... Thanks.

Paul Armstrong

Cell: +  1    973-908-1925

Disclaimer and Confidentiality Note. This e-mail, its attachments and any
rights attaching hereto are, unless explicitly indicated otherwise, are the
property of the sender. The content of this e-mail is confidential, private
and intended for the addressee only. If you are not the addressee and have
received this e-mail, kindly notify the sender, delete this e-mail
immediately and do not disclose or use the same in any manner whatsoever.
The sender accepts no liability whatsoever for any loss or damages
whatsoever and howsoever incurred, or suffered, resulting, or arising, from
the use of this email or its attachments. The sender does not warrant the
integrity of this e-mail nor that it is free of errors, viruses,
interception or interference.
