### ISSUE TITLE
Arduino IDE 1.8.9 Compilation Error

### ISSUE THREAD

**Issue by yaronze** [arduino/Arduino#8821] opened 2019-04-25 18:17 UTC
Hi,
in IDE version 1.8.8 and 1.8.9 i am getting an unpredictable compilation error while trying to upload sketch to the Arduino Uno board.
I found out that i check the last lines as remark and compile - the error is gone' than i Unchecked the lines and they are back in the code - compile successfully.
The odd error are not consistent.

any suggestions?

the Error log looks like that:

In function 'global constructors keyed to 65535_0_Pulse_Counter_MQTT_Proto_v001.ino.cpp.o':

lto1.exe: internal compiler error: Segmentation fault

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: D:\Arduino\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

d:/arduino/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by per1234** [comment] 2019-04-26 01:33
Closing as duplicate of https://github.com/arduino/Arduino/issues/7949

**Closed by per1234** 2019-04-26 01:33 UTC
Labels: Type: Duplicate
