### ISSUE TITLE
Document board/pin configuration and capabilities macros.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#4918] opened 2016-05-02 23:27 UTC
Do we have documentation of the various macros in the pins_arduino.h files that live in the variants/ folders (e.g. analogInputToDigitalPin(), NUM_DIGITAL_PINS, NUM_ANALOG_INPUTS, digitalPinHasPWM, SERIAL_PORT_MONITOR, SERIAL_PORT_HARDWARE)? These are / should be somewhat of a standard by now, so it seems like it would be good to document them. For instance on the 3rd party hardware specifications page (https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification) or something linked from it.

**Comment by per1234** [comment] 2017-07-03 20:51
Closing as duplicate of https://github.com/arduino/Arduino/issues/4141

**Closed by per1234** 2017-07-03 20:51 UTC
Labels: Component: Documentation, Type: Duplicate
