### ISSUE TITLE
Provide keywords.txt with a hardware library

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#2617] opened 2015-02-10 10:34 UTC
Lets pretend you want to create a custom Arduino core which adds new functions. Then you also want to provide keyword highlighting to this core. But since it is no library, it wont be accepted.

I suggest that the IDE accepts keywords.txt files inside the hardware sektchbook folder or in the avr/cores subfolder.

**Comment by ffissore** [comment] 2015-08-06 13:37
Duplicate of #755

**Closed by ffissore** 2015-08-06 13:37 UTC
