### ISSUE TITLE
version 1.8.10 clears serial monitor

### ISSUE THREAD

**Issue by jwgera** [arduino/Arduino#9410] opened 2019-11-08 03:24 UTC
The new version clears the serial monitor on disconnecting the controller. Version 1.8 9 did not. This is annoying because I would want to look the monitor over after stopping the program but can't now.  

Please do not clear the serial monitor when disconnecting the board. That is what the clear button on the serial monitor is for.

Thanks.
John

**Comment by facchinm** [comment] 2019-11-08 08:40
Closing as duplicate of https://github.com/arduino/Arduino/issues/9234, following the thread there.

**Closed by facchinm** 2019-11-08 08:40 UTC
