### ISSUE TITLE
User libraries not picked up from --pref sketchbook.path=...

### ISSUE THREAD

**Issue by kzyapkov** [arduino/Arduino#3295] opened 2015-06-05 22:11 UTC
When used on the command line, `arduino` fails to pick up libraries installed in `sketchbook.path`/libraries. Creating a `custom-preferences.txt` file which contains the correct `sketchbook.path` inside it and adding `--preferences-file custom-preferences.txt` fixes this. 

However, only supplying `--pref sketchbook.path` doesn't work: libraries installed in the customized sketchbook path are not picked up.

I've reproduced with 1.6.4 and the current master branch.

**Comment by matthijskooijman** [comment] 2015-06-06 07:46
This is a duplicate of #3261, which was just fixed. Could you see if the latest hourly build still has this problem? Thanks!

**Closed by matthijskooijman** 2015-06-06 07:46 UTC
