### ISSUE TITLE
Close a Tab

### ISSUE THREAD

**Issue by bkelly13** [arduino/Arduino#9253] opened 2019-09-23 00:59 UTC
IDE version 1.8.9
A search and several returns did not provide a method to close a tab in the IDE.  One result said that tabs cannot be closed, the file must be deleted.
I don't want to be obnoxious, but if the IDE works in said manner, this is a really bad way of doing things.  What should I do when I have a dozen older projects and do not want to delete them?  How can I get the IDE to open without any file active?  Then I can pick the one I want?

**Comment by per1234** [comment] 2019-09-23 01:16
Closing as duplicate of https://github.com/arduino/Arduino/issues/2883

**Closed by per1234** 2019-09-23 01:16 UTC
Labels: Type: Duplicate
