### ISSUE TITLE
Compiler error - java.lang.NullPointerException (arduino 1.6.12)

### ISSUE THREAD

**Issue by knefel** [arduino/Arduino#5487] opened 2016-10-15 13:03 UTC
I'm using the arduino compiler with the nxcEditor since nearly 1 year. Everything was good until I changed from arduino-1.6.6 to arduino-1.6.12. The following line is no problem with arduino-1.6.6, but with the new version there is a problem.

Tested inside a terminal window (by the way it's the example program Blink.ino):

/opt/arduino-1.6.12/arduino --board arduino:avr:uno --port /dev/ttyACM0 --upload Blink.ino

This is the command line output:

Picked up JAVA_TOOL_OPTIONS: 
Konfiguration wird geladen...
java.lang.NullPointerException
	at processing.app.BaseNoGui.selectSerialPort(BaseNoGui.java:1088)
	at processing.app.helpers.CommandlineParser.parseArgumentsPhase1(CommandlineParser.java:143)
	at processing.app.Base.<init>(Base.java:273)
	at processing.app.Base.guardedMain(Base.java:219)
	at processing.app.Base.main(Base.java:132)

I've tested with Ubuntu 12.04, Ubuntu 16.04 and Opensuse Leap 42.1 (32 bit and 64 bit).

**Comment by per1234** [comment] 2016-10-15 23:24
Duplicate of #5413, which has already been fixed in the hourly build. Please always test the hourly build before reporting an issue to check if the problem has already been solved and if not then search for issues/PRs to make sure the issue hasn't already been reported.

**Comment by facchinm** [comment] 2016-10-20 12:56
Thanks @per1234, closing as solved. Stable version containing this patch is on its way.

**Closed by facchinm** 2016-10-20 12:56 UTC
