### ISSUE TITLE
Invalid library found in

### ISSUE THREAD

**Issue by infusion** [arduino/Arduino#7597] opened 2018-05-13 18:10 UTC
Hello,

a user of my Nunchuk library ( https://github.com/infusion/Fritzing/tree/master/Wii-Nunchuk )  is reporting, he is getting an "Invaild library found in /Users/maddyr/Documents/Arduino/libaries/Nunchuk: /Users/maddyr/Documents/Arduino/libraries/Nunchuk" error. I can't reproduce this error and wanted to ask if certain checks are made to fail compilation with that error.

Thanks Robert

**Comment by per1234** [comment] 2018-05-13 23:57
No, the "Invalid library found" warning does not cause compilation to fail. It's a warning, not an error.

My experience is that when the Arduino IDE gives that warning it's because the library is invalid. I've never seen a report of a spurious warning. Likely the user did not properly install the library, which is more likely due to the structure of your repository (library not in the root of the repo). The fact their folder name is "Nunchuk" rather than "Wii-Nunchuk" shows they didn't just simply copy the Wii-Nunchuk folder to their libraries folder. I recommend you have the user provide you with a directory listing or screenshot of the folder contents. That will quickly make it clear why it's invalid.

I'm going to close this issue. If you do find the problem to be caused by a bug in the Arduino IDE then please comment here with details and I'll reopen.

**Closed by per1234** 2018-05-13 23:57 UTC
