### ISSUE TITLE
Wrong link to avrdude config on Raspberry Pi (debian) 1.6 rc2

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#2587] opened 2015-01-28 17:33 UTC
See this post for more information:
http://www.raspberrypi.org/forums/viewtopic.php?p=677255#p677255

I dont know if this also applies to other Linux distributions. It would also be nice to provide a raspberry pi version of 1.6 when its out without manual recompiling.

**Comment by ffissore** [comment] 2015-01-30 09:07
It looks like the issue is not related to the IDE but to how it has been packaged for raspian. Closing as invalid.

**Closed by ffissore** 2015-01-30 09:07 UTC
