### ISSUE TITLE
Some libraries versions don't appear in different platforms and arduino versions

### ISSUE THREAD

**Issue by MustafaFayez** [arduino/Arduino#4396] opened 2016-01-06 18:19 UTC
I tried to install OneSheeld library on arduino IDE on both Windows and macOS with different arduino versions, here is what I get:
1-On Windows 7-X64, with arduino version 1.6.5: all versions of OneSheeld lib appear normally as shown:
![1 6 5-win7](https://cloud.githubusercontent.com/assets/7977794/12150251/709595a8-b4b1-11e5-9edf-21eb7cc3b62a.png)

On Windows 7-X64, with arduino version 1.6.7: I can't get the last version of OneSheeld library by using manage libraries in arduino IDE, I only get OneSheeld versions 1.6.0 and 1.5.0 despite it have versions up to 1.7.0. Here are screen shots:

![1 6 7-win7](https://cloud.githubusercontent.com/assets/7977794/12150261/7b811636-b4b1-11e5-9664-32ebb724cdb2.png)

2- On Windows 10-X86, with both arduino versions 1.6.5 and 1.6.7: all versions of OneSheeld lib appear normally as shown:
![untitled](https://cloud.githubusercontent.com/assets/7977794/12150322/e1101fc4-b4b1-11e5-858f-b485d0ce8ca8.png)

![untitled 1](https://cloud.githubusercontent.com/assets/7977794/12150345/01121aac-b4b2-11e5-9717-ca77604eb60a.png)

3-On MacOS ElCapitan, with both arduino versions 1.6.5 and 1.6.7 all versions of OneSheeld lib appear normally as shown: 

![screen shot 2016-01-06 at 6 33 29 pm](https://cloud.githubusercontent.com/assets/7977794/12150369/1ae8d498-b4b2-11e5-9663-00de601761cb.png)

![screen shot 2016-01-06 at 6 48 33 pm](https://cloud.githubusercontent.com/assets/7977794/12150395/30d966be-b4b2-11e5-98af-61b7a769ec96.png)

note: the link of OneSheeld library:
https://github.com/Integreight/1Sheeld-Arduino-Library

**So, I need to use arduino 1.6.7 on windows 7 and include OneSheeld library ver 1.7.0**

**Comment by iSsO** [comment] 2016-01-07 10:42
Yes, I have the exact same problem. The versions of the libraries aren't consistent across different Arduino IDE versions / Platforms.

**Comment by cmaglie** [comment] 2016-01-07 16:12
I tried with a fresh install of 1.6.7 on windows 7 x64, and I see all the versions:

![sheeld](https://cloud.githubusercontent.com/assets/423515/12175051/5d58686c-b560-11e5-9137-01cd92c397c8.png)

it seems that your 1.6.7 is reading an outdated library index, maybe you're affected by this bug: 
https://github.com/arduino/Arduino/pull/4361

may you try the "Hourly build" and see if that solves your issue?

**Comment by MustafaFayez** [comment] 2016-01-11 17:34
yeah, it worked with the hourly build, thanks.

**Comment by alieslam** [comment] 2016-01-27 11:26
Hi @cmaglie, 
I am still having the issue and can't find the latest updated library of "1Sheeld 1.8.0" using "Manage libraries" although my friend has the same Arduino IDE version "1.6.7" but for MAC and the library version is updated. 
I have attached a screen shot bellow which shows that i have already installed the pre version 1.7.0 and the latest is not available on the list even there's a version 1.6.1 which is not included in the list.

![image](https://cloud.githubusercontent.com/assets/8179651/12611943/38121d12-c4f8-11e5-89ec-612e71acfe90.png)

**Comment by sandeepmistry** [comment] 2016-01-27 16:09
@alieslam can you please try the latest hourly build? https://www.arduino.cc/en/Main/Software

This has been resolved by https://github.com/arduino/Arduino/pull/4361, however this fix is not in the 1.6.7 release.

Alternatively, you can also workaround for now by deleting ```%LOCALAPPDATA%\Arduino15\library_index.json.tmp.gz``` and then restarting the IDE.

I'm closing this as it is a duplicate of #4272.

**Closed by sandeepmistry** 2016-01-27 16:09 UTC
Labels: Component: Board/Lib Manager
