### ISSUE TITLE
using 4 k monitors

### ISSUE THREAD

**Issue by ramigrafx** [arduino/Arduino#4510] opened 2016-02-01 00:48 UTC
I have just upgraded to a 4 k monitor. I have adjusted the font scaling in Windows and in the majority of my programs the fonts are scaled. However when I open up a sketch some of the text is extremely small and dificult to read. I have altered the editor font size to 30 so that I can read the sketch that I write and that  part is now ok. Is there a way of altering all of the fonts to the correct size for this monitor so that it looks like it did at the lower resolution?

**Comment by PaulStoffregen** [comment] 2016-02-01 01:17
duplicate of #4376

**Comment by agdl** [comment] 2016-02-01 08:16
I'm closing this since it has been referenced and it is a duplicate

**Closed by agdl** 2016-02-01 08:16 UTC
Labels: Type: Duplicate
