### ISSUE TITLE
Can not enter custom serial port name on Linux (to use virtual TTY)

### ISSUE THREAD

**Issue by anymouse404** [arduino/Arduino#10782] opened 2020-09-22 15:46 UTC
I've been attempting to test Arduino Uno simulator using Arduino IDE and virtual serial ports. I'm using tty0tty to create a virtual serial port /dev/tnt1.
There seems to be no way to select that serial port name instead of traditional /dev/ttyUSB* or /dev/ttyACM*.

Current hacky workaround is described at https://lcgamboa.github.io/picsimlab/Arduino_IDE_Integration_sim.html , but that only helps for that particular tty name pattern.
Simple ability to enter custom name would solve this. Almost every other linux software which uses serial ports does it this way.

**Comment by per1234** [comment] 2020-09-25 02:07
Hi @anymouse404. Thanks for taking the time to file this report.

If I understand correctly, this is a duplicate of https://github.com/arduino/Arduino/issues/5096 (make sure to read past the first post to https://github.com/arduino/Arduino/issues/5096#issuecomment-230305207). So I'm going to close this issue in favor of that one. If you have some additional input to provide beyond what is already in https://github.com/arduino/Arduino/issues/5096 you're welcome to comment there.

If I've misunderstood and this is different from https://github.com/arduino/Arduino/issues/5096, let me know and I'll investigate reopening.

**Closed by per1234** 2020-09-25 02:07 UTC
