### ISSUE TITLE
Arduino Nano Clone with CH340: uploading fails with AVR Boards 1.6.21

### ISSUE THREAD

**Issue by sburlot** [arduino/Arduino#7381] opened 2018-03-27 23:19 UTC
Uploading code using Arduino AVR Boards 1.6.21 with Arduino 1.85 on MacOS 10.13.3,
on an Arduino Nano clone with a CH340 chip fails:
`avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x42`
etc..
going back to Arduino AVR Boards 1.6.20 works.
Driver is v1.4 from [this page](http://www.wch.cn/download/CH341SER_MAC_ZIP.html)

**Comment by per1234** [comment] 2018-03-27 23:43
Closing as duplicate of 
https://github.com/arduino/Arduino/issues/7264
We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-03-27 23:43 UTC
