### ISSUE TITLE
Uploading asks for OTA password when using programmer

### ISSUE THREAD

**Issue by timkoers** [arduino/Arduino#7684] opened 2018-06-11 17:01 UTC
Arduino IDE 1.8.5
Windows 10 Pro 1709 x64

I am trying to upload my Arduino Nano code with the USBasp. I have 1 ESP8266 with ArduinoOTA capabilities and that is the only thing that is visible in my boards menu.

When trying to upload to the Arduino Nano with the USBasp, it asks for the ArduinoOTA password of the ESP8266.

The work around is to attach a Serial device to your computer and select that as the upload target. Then programming via a programmer will work.

**Comment by facchinm** [comment] 2018-06-12 07:06
Hi @timkoers ,
thanks for noticing, there is surely a bug in the "serial" selection code (since USBasp doesn't need a serial port to be selected it's useless to evaluate it).

**Comment by per1234** [comment] 2021-04-05 13:27
Closing as duplicate of https://github.com/arduino/Arduino/issues/8513

**Closed by per1234** 2021-04-05 13:27 UTC
Labels: Component: Uploading, Type: Bug
