### ISSUE TITLE
please fix VERY ANNOYING BUG giving Idiotic Error Message "contains unrecognized characters"

### ISSUE THREAD

**Issue by ftlpilot** [arduino/Arduino#11700] opened 2021-11-14 08:40 UTC
I'm getting really DUMB (Idiotic even) error messages that an .ino file "contains unrecognized characters. If this code was created with an older version of Arduino, you may need to use Tools -> Fix Encoding & Reload to update"

This is completely idiotic - I have a degree symbol IN A COMMENT - DUMB DUMB DUMB

the offending line is :-
```cpp
const char  degreeChar[1+1] = {0xBA} ; //{char(176)} or 186;° 
```

**Comment by per1234** [comment] 2021-11-14 15:34
The fact that it is in a comment is irrelevant. As explained by the error message, the classic Arduino IDE only supports UTF-8 character encoding. This is not a bug. This is the IDE working exactly as intended.

It is true that it is not a great user experience, but it is also something that only a tiny percentage of users ever encounter. For that reason, and since Arduino IDE 2.x already supports various character encodings (though UTF-8 is always recommended), I don't think there is any point in working on this so I'll go ahead and close it.

In the future, I'd appreciate it if you would take a more calm and civil tone when submitting issue reports to Arduino's repositories. This is a place for the Arduino community to efficiently collaborate on these free open source projects in a professional manner. It is not a place to vent.

**Closed by per1234** 2021-11-14 15:34 UTC
