### ISSUE TITLE
Pick up changes in .cpp files when compiling

### ISSUE THREAD

**Issue by probonopd** [arduino/Arduino#3440] opened 2015-06-30 11:07 UTC
I have a sketch which includes a cpp file in the same directory as the .ino file. When I make a change to the .cpp file, save, and compile, then the change in the .cpp file is not picked up. I have to restart the Arduino IDE each time to have it recognize the change in the .cpp file.

It would be nice if the restart wasn't necessary. (This might apply to other file types different from .cpp as well).

**Comment by matthijskooijman** [comment] 2015-06-30 11:17
Hm, weird. In any case, there have been some recent changes in how these files are handled. Could you try running the hourly build and see if the problem still exists there?

**Comment by probonopd** [comment] 2015-06-30 11:23
I am running 
![bildschirmfoto 2015-06-30 um 13 23 49](https://cloud.githubusercontent.com/assets/2480569/8429792/3b1e8cde-1f2b-11e5-8450-09b2cbb3f7ca.png)

**Comment by matthijskooijman** [comment] 2015-06-30 11:27
Hm, I was talking about #3435, which was merged only four hours ago. You might want to upgrade to the latest hourly, just in case.

@ffissore, might be good to also list the git revision of the latest hourly on the site and in the IDE itself?

**Comment by ffissore** [comment] 2015-06-30 13:08
Ouch, confirmed. Working on it

**Comment by ffissore** [comment] 2015-06-30 13:36
Fixed. Sorry about that. Available since next hourly http://www.arduino.cc/en/Main/Software#hourly

**Closed** 2015-06-30 13:35 UTC
Labels: Component: Compilation, Component: IDE

**Comment by probonopd** [comment] 2015-06-30 19:07
Thanks ffissore. I can confirm it is fixed.
