### ISSUE TITLE
LCD hello world

### ISSUE THREAD

**Issue by noisegate** [arduino/Arduino#3806] opened 2015-09-16 15:58 UTC
In this tutorial https://www.arduino.cc/en/Tutorial/HelloWorld, it says in the code comment to connect LCD module pin r/w (5) to GND. In the (Fritzing) schematics it is connected to +5V. I think the former is correct (pin r/w (5) on the LCD module should be connected to GND). 
could you look into this please, thx in advance
code:
```c
/*
  LiquidCrystal Library - Hello World

 Demonstrates the use a 16x2 LCD display.  The LiquidCrystal
 library works with all LCD displays that are compatible with the
 Hitachi HD44780 driver. There are many of them out there, and you
 can usually tell them by the 16-pin interface.

 This sketch prints "Hello World!" to the LCD
 and shows the time.

  The circuit:
 * LCD RS pin to digital pin 12
 * LCD Enable pin to digital pin 11
 * LCD D4 pin to digital pin 5
 * LCD D5 pin to digital pin 4
 * LCD D6 pin to digital pin 3
 * LCD D7 pin to digital pin 2
 * LCD R/W pin to ground
 * LCD VSS pin to ground
 * LCD VCC pin to 5V
 * 10K resistor:
 * ends to +5V and ground
 * wiper to LCD VO pin (pin 3)

 Library originally added 18 Apr 2008
 by David A. Mellis
 library modified 5 Jul 2009
 by Limor Fried (http://www.ladyada.net)
 example added 9 Jul 2009
 by Tom Igoe
 modified 22 Nov 2010
 by Tom Igoe

 This example code is in the public domain.

 http://www.arduino.cc/en/Tutorial/LiquidCrystal
 */

```

![](https://www.arduino.cc/en/uploads/Tutorial/LCD_Base_bb_Schem.png)

**Comment by agdl** [comment] 2015-09-17 05:59
Duplicate of#3810

**Closed by agdl** 2015-09-17 05:59 UTC
Labels: Component: Documentation, Type: Duplicate

**Comment by noisegate** [comment] 2015-09-17 23:05
yeah 3806 > 3810? Thanks for looking into it though..
