### ISSUE TITLE
portModeRegister not implemented for Arduino Uno WiFi Rev 2

### ISSUE THREAD

**Issue by Guerillah** [arduino/Arduino#8454] opened 2019-01-28 00:03 UTC
Found out while trying to use some Uno compatible libraries such as SoftwareWire . Please see https://github.com/Testato/SoftwareWire/issues/17#issuecomment-457957741 for more information, it appears to be a bug with Arduino.h / variant.h .

**Comment by per1234** [comment] 2019-01-28 02:20
The correct place to report issues specific to the Uno WiFi Rev2 is here:
https://github.com/arduino/ArduinoCore-megaavr

@Guerillah please do me a favor and open an issue in that repository.

**Comment by Guerillah** [comment] 2019-01-28 02:40
Done, apologies

**Comment by per1234** [comment] 2019-01-28 03:01
No worries.

Closing as duplicate of https://github.com/arduino/ArduinoCore-megaavr/issues/14

**Closed by per1234** 2019-01-28 03:01 UTC
Labels: Type: Duplicate
