### ISSUE TITLE
v1.9b upload fails, must close serial monitor first

### ISSUE THREAD

**Issue by danbates2** [arduino/Arduino#8518] opened 2019-02-09 02:03 UTC
Seems that the serial monitor isn't closing when the upload button is pressed, causing uploads to fail as the serial monitor tried to butt in.

1.9.0-beta
I'm on 10.11.6 El Capitan.

**Comment by facchinm** [comment] 2019-02-11 09:44
Hi @danbates2 ,
I cannot reproduce on Linux. May you attach a screencast so I can try to understand where the "pause" control is failing? Thanks!

**Comment by danbates2** [comment] 2019-02-11 11:51
Hi, I don't have a screencast program. But it isn't any more complex than I describe. I must close the serial monitor to have successful uploads.
The error in the IDE (black window at bottom of sketch) is the typical upload error in red text returned when the serial port is busy and unavailable.

**Comment by facchinm** [comment] 2019-02-11 13:14
Ok, the issue was surely in beta some weeks ago (and the outcome was : press upload -> monitor was greyed out during compilation -> small reopen glitch and greyout again -> upload error), then it was patched. This is why I asked for a screenscast, but don't worry. Could you test the latest beta and report if the problem is still there?

**Comment by danbates2** [comment] 2019-02-11 13:24
Sure, where can I download or how do I compile for mac?

**Comment by danbates2** [comment] 2019-02-11 13:24
BTW, this v1.9 is a big improvement generally ;)

**Comment by per1234** [comment] 2019-02-11 22:41
@danbates2 you can download the latest beta build of the Arduino IDE here:
https://www.arduino.cc/en/Main/Software#beta
The beta build is regularly updated to reflect the ongoing development work on the IDE. It's helpful to mention the build number of the beta you're using when submitting bug reports.

For a free, open source, lightweight screencast program, I like this one:
https://www.cockos.com/licecap/

**Comment by danbates2** [comment] 2019-02-12 15:08
thanks.
my build is PR-beta1.9-BUILD-99

**Comment by facchinm** [comment] 2019-02-12 15:17
Latest is BUILD-102, so if you can redownload it and give it a try it would be awesome!

**Comment by danbates2** [comment] 2019-02-12 16:30
Still the same problem!
![1](https://user-images.githubusercontent.com/5250782/52651086-72ccf780-2ee3-11e9-8ee6-8f2304894401.jpeg)
![2](https://user-images.githubusercontent.com/5250782/52651087-73658e00-2ee3-11e9-9f65-d809da36b53e.jpeg)
![3](https://user-images.githubusercontent.com/5250782/52651088-73658e00-2ee3-11e9-8172-7f63b0a82d2e.jpg)


I close the monitor and the upload works.

**Comment by facchinm** [comment] 2019-02-21 15:56
@gvarisco could you try to reproduce this issue with any board using latest beta?

**Comment by danbates2** [comment] 2019-02-21 17:00
I've downloaded the latest again, and the issue is still present.

**Comment by akash73** [comment] 2019-02-21 18:56
Tested with 10.12.6 and latest IDE beta and correctly uploads with serial monitor open.

**Comment by per1234** [comment] 2022-12-01 09:45
Closing as "wontfix" because the Arduino IDE 1.9.x effort has been abandoned so that the resources can be put to Arduino IDE 2.x instead.

**Closed** 2022-12-01 09:44 UTC
Labels: Type: Bug, Component: Uploading, Component: IDE Serial monitor, IDE 1.9.x Beta
