### ISSUE TITLE
Incomplete documentation of auto-reset disabling capacitor in Arduino as ISP tutorial

### ISSUE THREAD

**Issue by dvarrel** [arduino/Arduino#8368] opened 2019-01-06 16:29 UTC
Hi,
thanks for Arduino as ISP and Arduino Bootloaders Tutorial

for some arduino nano (old bootloader), it's necessary to put an 1µF capacitor between RESET and Ground to burn new Bootloader.

best regards

**Comment by per1234** [comment] 2019-01-07 01:45
Are you referring to this tutorial?
https://www.arduino.cc/en/tutorial/arduinoISP

This may be a duplicate of https://github.com/arduino/Arduino/issues/8032. However, I have wondered about how that tutorial shows the capacitor used on the Mega, but not on the Uno used as Arduino as ISP. Is there something about the Mega that makes the capacitor more likely to be needed? Using the stk500v1 protocol, I have never needed the capacitor on any board I've used for Arduino as ISP.

Perhaps it would make more sense to change the tutorial to show the Mega without capacitor, but then add a note that if you're experiencing such and such error, try using a capacitor. It would be safest to always use a capacitor (since it does no harm). However, I think it's best for the tutorial to recommend it only when absolutely necessary because it increases the complexity of a process the average Arduino user finds already extremely difficult. Many Arduino users don't happen to have a suitable capacitor on hand, though they may very well have a spare Arduino board and jumper wires.

**Comment by dvarrel** [comment] 2019-01-07 05:56
hello,
yes you're right, no capacitor on mega and a note will be sufficient and
will make more sense
I didn't see the capacitor on the mega board, because i was using a uno !!!

thanks a lot

**Comment by mavrivan** [comment] 2019-01-22 16:55
Hi all,
I think my question is a bit related to the documentation about the tutorial, Arduino as ISP and Arduino Bootloaders.
My problem is that I want to install the Arduino Sun Tracking / Heliostat Program: "https://www.cerebralmeltdown.com/arduino-sun-tracking-heliostat-program-download-page", and there is a note that: "... some of the older Arduino Unos that keeps them from uploading programs over 30kb".
That problem can be fixed, I mean using a specialized bootloader sketch for example WestfW's OptiLoader: "https://github.com/Optiboot/optiboot/wiki/InstallingOnChips"

1. Set up an existing Arduino with an Arduino to ISP connector and load the optiLoader sketch using the standard Arduino IDE.
2. For each target board, connect the ISP connector and hit the reset button on the optiLoader Arduino, or use the "G" command in the Serial Monitor. Programming the bootloader takes about 5 seconds, and reports status and information to the Arduino serial port.

Ok, what i do not understand is the phrase "connect the ISP connector". Is this the same connectons described in "https://www.arduino.cc/en/Tutorial/ArduinoISP" for the case Programmer UNO -> Target UNO ?

**Comment by per1234** [comment] 2019-01-22 23:17
@mavrivan that is off topic for this issue, and even this repository.

Support questions like this should be made to the [Arduino Forum](http://forum.arduino.cc/), after reading the ["How to use this forum" guide](http://forum.arduino.cc/index.php?topic=148850).

If you want to suggest improvements to the documentation of the Optiboot repository, they should be submitted to that repository.

**Closed** 2020-12-03 09:01 UTC
Labels: Component: Documentation, feature request
