### ISSUE TITLE
Access denied when trying to download from official site

### ISSUE THREAD

**Issue by beshur** [arduino/Arduino#2722] opened 2015-03-01 22:24 UTC
Can't download compiled one from the official web-site: get an error

![Alt text](https://monosnap.com/file/cWIW26AcaBRBTAM99NmbtxiEEV5quI.png)

**Comment by mastrolinux** [comment] 2015-03-02 09:13
duplicate of: https://github.com/arduino/Arduino/issues/2717

**Closed by mastrolinux** 2015-03-02 09:13 UTC
