### ISSUE TITLE
Let Library manager delete libraries

### ISSUE THREAD

**Issue by AndKe** [arduino/Arduino#8269] opened 2018-12-06 09:28 UTC
Please make it equally easy to un-install libraries, not only update.

**Comment by facchinm** [comment] 2018-12-06 09:37
This was discussed in the past (~4 years ago) when introducing the Library Manager. 

The final outcome is that, unlike all other IDEs that allow "removing" a library from a project while leaving it in the filesystem, in Arduino everything in the sketchbook is a target for being compiled, so the button should really delete the library files (quite dangerous).

The board manager, instead, allows removing boards (apart from builtin AVR core) because they live in an "hidden" folder that the user is much less likely to modify.

**Comment by PaulStoffregen** [comment] 2018-12-06 10:38
While it would involve quite a bit of work, the library manager could download a fresh copy of the library and compare all the files.  If all are identical, then it's safe to delete.  If any have changed, maybe a message could be displayed asking the user to confirm they are willing to lose their edits.  Or maybe just refuse to delete, but print the full pathname and advise the user to manually delete their edited copy, losing all their work.

**Comment by matthijskooijman** [comment] 2019-09-19 12:14
I've changed the title to only mention libraries, since this is what the issue is about. Also, boards/cores can already be uninstalled with the current IDE version.

**Comment by per1234** [comment] 2020-03-16 10:42
I'm going to close this as a duplicate of https://github.com/arduino/Arduino/issues/2878, but I'll add a link back from there to make sure the good discussion in this thread won't be lost.

**Closed by per1234** 2020-03-16 10:42 UTC
Labels: Component: Board/Lib Manager, arduino-cli, feature request
