### ISSUE TITLE
"File > Print" feature in the IDE doesn't work properly

### ISSUE THREAD

**Issue by Fede85** [arduino/Arduino#1270] opened 2013-02-07 16:01 UTC
Trying to print a sketch (even into a file) will generate an output that depends on the line cursor position and if the code is long and need to be split into multiple pages, you loose some lines between the two pages.

Processing.org has the same issue and seems has not even been resolved.

**Comment by ffissore** [comment] 2015-05-28 12:46
I can't reproduce. I guess it got fixed by an update of the underlying JVM

**Closed by ffissore** 2015-05-28 12:46 UTC
Labels: Component: IDE, OS: Linux, OS: OSX, OS: Windows
