### ISSUE TITLE
The operator function has changed. ( ||  , &&  )

### ISSUE THREAD

**Issue by bkjoo1** [arduino/Arduino#3126] opened 2015-05-13 03:15 UTC
1.61   ,  1.6.4  version

if( (Mb.R[18] < Mb.R[MODBUS_FIRE_TEMPERATURE_REGISTER])  &&  (fire_check_flag == 1 ) )

The operator function has changed.

**Comment by bkjoo1** [comment] 2015-05-13 03:24
||  =>  &&
&& => ||
The operator function has changed.

**Comment by Chris--A** [comment] 2015-05-13 03:40
Can you post an example sketch highlighting the problem you are seeing. The `&&` and `||` operators are still the same (language specifications, nothing to do with IDE).

**Comment by ffissore** [comment] 2015-05-14 12:10
Such a inversion is likely to be caused by bad source code rather than having inverted operators. Closing as invalid

**Closed by ffissore** 2015-05-14 12:10 UTC
Labels: Waiting for feedback
