### ISSUE TITLE
Terminal escape code support in Serial Monitor

### ISSUE THREAD

**Issue by online-data-archive** [arduino/Arduino#9102] opened 2019-07-27 17:34 UTC
The Serial Monitor as it stands just display Serial Data and accepts data via a command line.

Can the Serial Monitor have the ability to Respond to Terminal Escape codes
Ie Font Change Cursor position, Draw lines, change font colour.

I realise that a external Terminal could be run but once the External Serial Terminal has taken
control of the port, the uploading and download of code cannot be accomplished,
Whereas the Serial Monitor looks to have controls to Disconnect automatically while code
is uploaded.

Component: Serial Monitor

**Comment by Hiddenvision** [comment] 2019-08-07 16:20
It would be nice to have a Hex/Dec/Char toggle also

**Comment by per1234** [comment] 2020-10-06 00:47
Closing as duplicate of https://github.com/arduino/Arduino/issues/346 and https://github.com/arduino/Arduino/issues/3654.

**Closed by per1234** 2020-10-06 00:47 UTC
Labels: Component: IDE Serial monitor, feature request
