### ISSUE TITLE
new feat.: seperate Find (^f) and replace (^h) functions, + search only whole words !

### ISSUE THREAD

**Issue by shiftleftplusone** [arduino/Arduino#5574] opened 2016-11-07 10:43 UTC
hello,
this is a feature request (curr.: 1.6.12),
there are still some features and functionalities missing with respect to search and replace functions:

1.) seperate **_Find (^f)_** and **_Replace (^h)_** functions would be needed 
(no "replace" string field and no replace btn  when just "find" had to be used)

2,) an additional option (check box) for **_"search only for whole words"_** is needed

3.) an additional **_"step back/undo last change"_** for the Replace function would be appreciated, too

**Comment by cousteaulecommandant** [comment] 2016-11-19 15:18
Or at least add the possibility to use a different editor (make Arduino IDE detect when the .ino file has been changed externally and update it; many IDEs do this).  I was going to suggest using Geany or another editor with this feature, but that's not quite convenient if you have to close and reopen the project every time you edit it externally.

**Comment by matthijskooijman** [comment] 2016-11-19 16:25
> Or at least add the possibility to use a different editor 

This is possible by setting the "use external editor" preference, which disables edits in the IDE and reloads the files whenever you verify or compile.

**Comment by shiftleftplusone** [comment] 2016-11-20 11:44
no, my request was just about the original Arduino IDE as  new "find" and "search/replace" feature requests. 
Please keep on-topic, thank you.

**Comment by per1234** [comment] 2017-07-06 16:48
Closing as duplicate of https://github.com/arduino/Arduino/issues/3727.

**Closed by per1234** 2017-07-06 16:48 UTC
Labels: Type: Duplicate
