### ISSUE TITLE
feature request: upload without compile

### ISSUE THREAD

**Issue by lpdunwell** [arduino/Arduino#8149] opened 2018-10-31 06:52 UTC
let's say upload failed.
clicking upload again with code unchanged should upload without compiling

**Comment by per1234** [comment] 2018-10-31 07:38
Closing as duplicate of https://github.com/arduino/Arduino/issues/6625, https://github.com/arduino/Arduino/issues/2335

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-10-31 07:38 UTC
Labels: Type: Duplicate
