### ISSUE TITLE
Delete file bug

### ISSUE THREAD

**Issue by lucailvec** [arduino/Arduino#6591] opened 2017-08-08 06:11 UTC
There is a bug when try to attemp to delete an added file (such as a .cpp or .h) to a .ino .

The current delete of a file require that the file must be saved, if a new file named $FILENAME is created and it's not saved, the ide show me the error "impossible to find $FILENAME".

Version 1.8.3, UBUNTU 16.04

**Comment by per1234** [comment] 2017-08-08 07:14
Closing as duplicate of https://github.com/arduino/Arduino/issues/6453

Bug reports and feature requests are welcome but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2017-08-08 07:14 UTC
