### ISSUE TITLE
Error on startup of Arduino IDE

### ISSUE THREAD

**Issue by nerdthatnoonelikes** [arduino/Arduino#10637] opened 2020-08-13 19:10 UTC
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
Hello, i run Arch Linux and i installed Arduino IDE from the aur, after launching it i receive this error

java.lang.NullPointerException
        at processing.app.Base.rebuildProgrammerMenu(Base.java:1705)
        at processing.app.Base.<init>(Base.java:286)
        at processing.app.Base.main(Base.java:150)

**Comment by per1234** [comment] 2020-08-13 22:50
I'm going to close this as a duplicate of https://github.com/arduino/Arduino/issues/10580

I believe the solution is explained here: https://github.com/arduino/Arduino/issues/10332#issuecomment-672098408

If that doesn't solve the error, please comment here and I'll reopen.

**Closed by per1234** 2020-08-13 22:50 UTC
