### ISSUE TITLE
bad cpu type in executable

### ISSUE THREAD

**Issue by sh1va73** [arduino/Arduino#9578] opened 2020-01-01 13:16 UTC
On Mac Catalina I get this error: bad cpu type in executable. I am using version 1.8.10
How to proceed?

**Comment by per1234** [comment] 2020-01-01 13:21
Closing as duplicate of https://github.com/arduino/Arduino/issues/8974

**Closed by per1234** 2020-01-01 13:21 UTC
Labels: 32bit Deprecation, OS: OSX, Type: Bug, Type: Duplicate

**Comment by sh1va73** [comment] 2020-01-01 13:23
I know this question has been asked before but the solutions is not clear to me. What is the solutions to this?

**Comment by per1234** [comment] 2020-01-01 13:26
@sh1va73 this isn't an appropriate place to request assistance. This is a place to report bugs and submit feature requests. The place to request assistance is the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post the full error output, using code tags (`</>` button on the toolbar).
