### ISSUE TITLE
Serial document links are broken!

### ISSUE THREAD

**Issue by qwerty13** [arduino/Arduino#10437] opened 2020-06-28 11:24 UTC
simple, click on "function" sections of this links:
https://www.arduino.cc/reference/en/language/functions/communication/serial

they navigate to (for example) this link:
https://www.arduino.cc/reference/en/language/functions/serial/print
but it's broken.

if you click on "print" link in this page:
https://www.arduino.cc/reference/en/language/functions/communication/serial/peek
it navigate to this link:
https://www.arduino.cc/reference/en/language/functions/communication/print
it's broken too.

the right link is this:
https://www.arduino.cc/reference/en/language/functions/communication/serial/print
(communication and serial missing in links)

**Comment by per1234** [comment] 2020-06-28 12:09
Closing as duplicate of https://github.com/arduino/reference-en/issues/729

Please see https://github.com/arduino/reference-en/issues/729#issuecomment-619938197 for an explanation of the cause of the issue and a workaround you can use to fix the links.

**Closed by per1234** 2020-06-28 12:09 UTC
