### ISSUE TITLE
ShieldPinUsage page inaccuracies and missing info

### ISSUE THREAD

**Issue by spacelego** [arduino/Arduino#6810] opened 2017-10-10 03:36 UTC
https://playground.arduino.cc/Main/ShieldPinUsage

Does not correctly state the pin usage for the Ethernet shield...
Pin 4 (SD card) / Pin 7 (handshake)

Ethernet shield 2 (not listed, in addition)...
Pin 4 (SD card) / Pin 7 (handshake)

Does not correctly state the pin usage for the WiFi shield (discontinued)...
Pin 4 (SD card) / Pin 7 (handshake)

WiFi shield 101 (not listed, in addition)...
Pin5 reset / Pin 7 (handshake)

There also needs to be documentation for pins you should NOT use on the UnoWiFi board...
Pin A4 and A5
Pin D0 and D1
Pin D13 (led? reset?)
and really unsure about PinD12, 11, 10 that was used by other WiFi shields, but may not be needed on this board.
Also, https://store.arduino.cc/usa/arduino-uno-wifi is missing the documentation tab, which I think should link to: https://www.arduino.cc/en/Guide/ArduinoUnoWiFi

**Comment by per1234** [comment] 2017-10-10 03:51
As stated in the [Contributing Guidelines](https://github.com/arduino/Arduino/blob/master/CONTRIBUTING.md), the Arduino Playground is a publicly editable wiki. You are welcome to make improvements to any Playground page yourself. If you want to discuss potential work on the Playground please do so on the [Arduino Forum](https://github.com/arduino/Arduino/blob/master/CONTRIBUTING.md). Issues with the Playground content should not be reported here.

Regarding the completely unrelated Uno WiFi issue, that appears to be a duplicate of https://github.com/arduino-libraries/UnoWiFi-Developer-Edition-Lib/issues/13.

**Closed by per1234** 2017-10-10 03:51 UTC
