### ISSUE TITLE
Watchdog problem 8Mhz bootloader

### ISSUE THREAD

**Issue by PRosenb** [arduino/Arduino#5285] opened 2016-08-24 10:58 UTC
I burned the 8Mhz bootloader to the ATmega328 (on a breadboard) with this sketch:
https://github.com/nickgammon/arduino_sketches/tree/master/Atmega_Board_Programmer

With that bootloader I experience problems with the watchdog reset. Instead of doing a reset, it gets stuck with a fast flashing LED (output 13).

I read about a bug in the standard Arduino Uno bootloader that caused such problem in the past.

May this bug not be fixed in the following bootloader?
https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/bootloaders/atmega/ATmegaBOOT_168_atmega328_pro_8MHz.hex

**Comment by matthijskooijman** [comment] 2016-08-24 13:17
I think this is essentially #4492, and indeed the bootloader you reference probably has this bug. I'm not sure what the update policy for bootloader is. The best way forward is probably to switch to optiboot, though that changes the bootloader size in a hard to detect way. @cmaglie, any comments?

**Comment by PRosenb** [comment] 2016-12-20 07:22
@matthijskooijman Is there any progress on the bootloader bug? It still blocks me from using it with 8MHz reliably.
Could you build the Arduino bootloader with the bug fixed or can I download it somewhere?
Thanks for some help.

**Comment by matthijskooijman** [comment] 2016-12-20 11:28
I'm not really the one to ask, so I'll try highlighting @cmaglie and @facchinm again.

**Comment by facchinm** [comment] 2016-12-20 11:33
Switching to optiboot (mainline) for new projects is the way to go. The policy is to release an updated bootloader as soon as it gets flashed on any production board (or if a board has a native way to update it - like the Zero).
Older bootloaders are there for reference/research and are probably FULL of bugs :smile:

**Comment by per1234** [comment] 2017-07-05 04:05
Closing as duplicate of https://github.com/arduino/Arduino/issues/4492.

**Closed by per1234** 2017-07-05 04:05 UTC
Labels: Type: Duplicate
