### ISSUE TITLE
Latest release of Arduino 1.8.12 crashes on search.

### ISSUE THREAD

**Issue by fiegener** [arduino/Arduino#9882] opened 2020-03-16 19:34 UTC
Teh latest release of Arduino for Mac OS Catalina crashes every time I do a search. Every time.

**Comment by facchinm** [comment] 2020-03-17 08:05
CLosing as duplicate of https://github.com/arduino/Arduino/issues/9828

**Closed by facchinm** 2020-03-17 08:05 UTC
