### ISSUE TITLE
Error on nano board page - Tech Specs Tab

### ISSUE THREAD

**Issue by TkonekT** [arduino/Arduino#7201] opened 2018-02-09 11:03 UTC
Error on "Tech Specs" Tab -> https://store.arduino.cc/arduino-nano

There is written : "Analog I/O pins" instead "Analog In Pins".
Sure, this pin can be DIGITAL I/O , there has never been a DAC ...

**Comment by kengdahl** [comment] 2018-02-13 10:46
This is not an error. There is 8 I/O pins on the nano. I/O stands for *"in/out"*

**Comment by TkonekT** [comment] 2018-02-13 10:49
I never see DAC on nano, as you want ...

**Comment by kengdahl** [comment] 2018-02-13 11:12
You are correct. I'm sorry.

**Comment by kengdahl** [comment] 2018-02-13 11:22
It's fixed now.

**Comment by per1234** [comment] 2018-02-14 02:09
@kengdahl the problem is solved for the "Europe/Africa" version of the product page but it remains for the "America/Oceania/Asia" page.

**Comment by kengdahl** [comment] 2018-02-14 10:09
@per1234 Should be fixed now :)
We have a sync between the pages but sometimes it just does not want to work.

**Closed by kengdahl** 2018-02-14 10:09 UTC
Labels: Component: Documentation
