### ISSUE TITLE
Comparison method BUG #9537 - not fixed.

### ISSUE THREAD

**Issue by alanmalk** [arduino/Arduino#9962] opened 2020-03-28 22:40 UTC
Using a Mac Mini, Mojave 10.14.6.  My first use of IDE 1.8.12
![Clipboard01](https://user-images.githubusercontent.com/8572152/77835815-c2817900-710d-11ea-8b19-a9c918e27fde.png)
```
Comparison method violates its general contract!
```

**Comment by cmaglie** [comment] 2020-04-01 11:35
Could you provide a copy of your SKETCHBOOK/libraries folder?

**Comment by alanmalk** [comment] 2020-04-01 21:19
This is part one of two. (Had to split the library folder in two to meet mailing size requirements)--Alan


    On Wednesday, April 1, 2020, 5:35:57 AM MDT, Cristian Maglie <notifications@github.com> wrote:  
 
 


Could you provide a copy of your SKETCHBOOK/libraries folder?

**Comment by alanmalk** [comment] 2020-04-01 21:21
Can you provide a mechanism to allow me to accomplish this with about 7Mb compressed?Getting this message too many times: "552: 5.3.4 Error: message file too big"
--Alan

    On Wednesday, April 1, 2020, 5:35:57 AM MDT, Cristian Maglie <notifications@github.com> wrote:  
 
 


Could you provide a copy of your SKETCHBOOK/libraries folder?

**Comment by per1234** [comment] 2020-04-02 00:15
The maximum attachment size allowed by GitHub is 10 MB. Could you put your file on a file hosting service like Dropbox and post a link to it here?

FYI: You can't attach files to a GitHub issue via an attachment to an email reply. GitHub just ignores the email attachment. You need to open the issue in your browser:
https://github.com/arduino/Arduino/issues/9962
and add a reply with your attachment there.

**Comment by alanmalk** [comment] 2020-04-02 02:17
[libraries copy.zip](https://github.com/arduino/Arduino/files/4418548/libraries.copy.zip)

Full library folder attached here as requested.

**Comment by alanmalk** [comment] 2020-04-02 02:19
Full library folder was added to #9962.--Alan

    On Wednesday, April 1, 2020, 5:35:57 AM MDT, Cristian Maglie <notifications@github.com> wrote:  
 
 


Could you provide a copy of your SKETCHBOOK/libraries folder?

**Comment by alanmalk** [comment] 2020-04-02 02:21
Library folder - compressed - is 7Mb.  I seem to have been able to upload it successfully.
--Alan


    On Wednesday, April 1, 2020, 6:15:33 PM MDT, per1234 <notifications@github.com> wrote:  
 
 


The maximum attachment size allowed by GitHub is 10 MB. Could you put your file on a file hosting service like Dropbox and post a link to it here?

FYI: You can't attach files to a GitHub issue via an attachment to an email reply. GitHub just ignores the email attachment. You need to open the issue in your browser:
#9962
and add a reply with your attachment there.

**Comment by cmaglie** [comment] 2020-05-13 11:09
@alanmalk thanks for sharing your sketchbook/libraries folder and sorry for the delay.

Unfortunately I'm unable to reproduce the issue, I also tried to unpack your zip on my MacOSX VM sketchbook folder to see if it's something depending on the OS but no errors also there.
I have no clue what the possible issue could be, the comparator now looks correct to me.

Are you still getting the error? I'd like to do more tests if you are available.

**Comment by alanmalk** [comment] 2020-05-13 13:16
Hello Cristian,At this point the error has fallen off my radar.  I doubt that I could reproduce it, and 
actually have no need.
Thank you for investigating but if you are willing to drop the investigation, I would alsobe willing to do the same.
Regards,Alan


    On Wednesday, May 13, 2020, 5:09:55 AM MDT, Cristian Maglie <notifications@github.com> wrote:  
 
 


@alanmalk thanks for sharing your sketchbook/libraries folder and sorry for the delay.

Unfortunately I'm unable to reproduce the issue, I also tried to unpack your zip on my MacOSX VM sketchbook folder to see if it's something depending on the OS but no errors also there.
I have no clue what the possible issue could be, the comparator now looks correct to me.

Are you still getting the error? I'd like to do more tests if you are available.

**Comment by cmaglie** [comment] 2020-05-15 09:32
>I doubt that I could reproduce it, and actually have no need.

Yes, my fault, I should have acted more promptly...
Anyway, without a way to reproduce it we are basically stuck, so let's close it for now.

**Closed by cmaglie** 2020-05-15 09:32 UTC
Labels: Component: Board/Lib Manager, Type: Bug
