### ISSUE TITLE
Enhancement request for theArduino  IDE

### ISSUE THREAD

**Issue by PickyBiker** [arduino/Arduino#9812] opened 2020-02-27 14:20 UTC
The bottom left of the Arduino screen shows the current cursor line number, but it does not show the current cursor column number.  Adding the column number would be trivial and useful for lining up things like comments and for quickly finding an error location on the line.

**Comment by per1234** [comment] 2020-02-27 19:34
Closing as duplicate of https://github.com/arduino/Arduino/issues/4403

**Closed by per1234** 2020-02-27 19:34 UTC
