### ISSUE TITLE
Add sketch path to the compile include path

### ISSUE THREAD

**Issue by ricklon** [arduino/Arduino#3635] opened 2015-08-07 03:17 UTC
When writing large complicated programs such as ones that use graphics, often it is need to have a header file (i.e. myconfig.h) that gets included from libraries. This file contains options such as which graphics card to use.  In this case the board specific network config is loaded in the users configuration folder.

Sketch
MyHttpServer.ino
```
#include HttpServer.h
```
HttpServer.h
```
#include HttpServerUserConfig.h
```
File in my sketch folder:
HttpServerUserConfig.h 

It is a worthy update. Plus a pretty small change:
```
    includeFolders.add(sketch.getFolder());

```

**Comment by ffissore** [comment] 2015-10-02 09:52
Duplicate of #2547

**Closed by ffissore** 2015-10-02 09:52 UTC
Labels: Component: Compilation, Type: Duplicate, Type: Improvement
