### ISSUE TITLE
Wrong boards.txt Parameters

### ISSUE THREAD

**Issue by CombiesGit** [arduino/Arduino#7482] opened 2018-04-18 12:54 UTC
The new nano should have the UNO Bootloader parameters.

-  Bootloader Size
-  Fuses
- upload maximum size

**Comment by per1234** [comment] 2018-04-18 12:57
Duplicate of https://github.com/arduino/ArduinoCore-avr/issues/10

**Closed by per1234** 2018-04-18 12:57 UTC
