### ISSUE TITLE
[Suggestion] Add a header defining which board and additional compile settings, the sketch should compile with

### ISSUE THREAD

**Issue by timkoers** [arduino/Arduino#7339] opened 2018-03-18 11:29 UTC
When dealing with loads of Arduino Sketches, you might get tired of switching the Board from one to another.
A header that auto-selects various build settings would make life a lot easier in this case.

To given an example of such a header
```
/* Arduino board definition header
*
* @arduino.board=Node32s
* @arduino.flashfreq=80MHz
*/
```
I hope others find this an interesting solution too!

**Comment by per1234** [comment] 2018-03-18 11:31
Closing as duplicate of #1481, and many others, including most recently #7324

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-03-18 11:31 UTC

**Comment by timkoers** [comment] 2018-03-20 05:26
Please reopen #1481 and add the label in progress to it.

Sent from Nine<http://www.9folders.com/>
________________________________
Van: per1234 <notifications@github.com>
verzonden: zondag 18 maart 2018 12:31 p.m.
Aan: arduino/Arduino
Cc: timkoers; Author
Onderwerp: Re: [arduino/Arduino] [Suggestion] Add a header defining which board and additional compile settings, the sketch should compile with (#7339)


Closing as duplicate of #1481<https://github.com/arduino/Arduino/issues/1481>, and many others, including most recently #7324<https://github.com/arduino/Arduino/issues/7324>

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.
