### ISSUE TITLE
Support in-sketch library config

### ISSUE THREAD

**Issue by NdK73** [arduino/Arduino#6952] opened 2017-11-20 20:43 UTC
If IDE included -I/path/to/sketch while compiling libraries it would be possible to have sketch-dependant configuration files.
For example, TFT_eSPI requires user to edit User_config.h to setup the display type and features needed. That means having to leave the IDE, modify the file, return to IDE, upload... And becomes a mess if user needs to support different displays in different projects.
If IDE included an extra -I/path/to/sketch before the others, it would be enough to have a new tab for "User_setup.h" to reconfigure the dir. If the user does not have that tab, default in-lib file gets used.

**Comment by per1234** [comment] 2017-11-20 23:13
This has already been requested quite a few different ways in the past and unfortunately it is official Arduino policy to reject the idea.

So I'm closing this as a duplicate of https://github.com/arduino/Arduino/issues/2547. You can find many other related proposals by following the web of other issues/PRs that are linked from there. If you want to show your support for one of the original proposals you can do so by giving it a "thumbs up", which is available by clicking on the smiley face icon on the top right corner of the comment.

**Closed by per1234** 2017-11-20 23:13 UTC
