### ISSUE TITLE
Compile fails after removing a header file

### ISSUE THREAD

**Issue by czghzc** [arduino/Arduino#9839] opened 2020-03-06 03:14 UTC
Compile fails after removing a header file.
![arduinoTest](https://user-images.githubusercontent.com/23645596/76046693-8b4efa80-5f9b-11ea-969a-9da7058aebc7.gif)

**Comment by per1234** [comment] 2020-03-06 03:18
Closing as duplicate of https://github.com/arduino/Arduino/issues/9505

**Closed by per1234** 2020-03-06 03:18 UTC
