### ISSUE TITLE
 unable to find a register to spill in class 'POINTER_REGS'

### ISSUE THREAD

**Issue by pmbroth** [arduino/Arduino#5717] opened 2016-12-13 18:03 UTC
Arduino: 1.6.12 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

sketch\temperature.cpp: In function 'Temperature::manage_heater() [clone .part.4]':

temperature.cpp:797: error: unable to find a register to spill in class 'POINTER_REGS'

 }

 ^

temperature.cpp:797: error: this is the insn:

(insn 100 99 103 3 (set (reg:SF 109 [ D.2252 ])

        (mem:SF (post_inc:HI (reg:HI 169 [ ivtmp.109 ])) [7 MEM[base: _144, offset: 0B]+0 S4 A8])) sketch\temperature.cpp:684 100 {*movsf}

     (expr_list:REG_INC (reg:HI 169 [ ivtmp.109 ])

        (nil)))

sketch\temperature.cpp:797: confused by earlier errors, bailing out

lto-wrapper: C:\Users\PMBROTH\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.3-arduino2/bin/avr-gcc returned 1 exit status

c:/users/pmbroth/appdata/local/arduino15/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.3-arduino2/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld.exe: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
unable to find a register to spill in class 'POINTER_REGS'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by facchinm** [comment] 2016-12-14 08:34
Duplicate of https://github.com/arduino/Arduino/issues/3972

**Closed by facchinm** 2016-12-14 08:34 UTC
