### ISSUE TITLE
Allow Serial Write in Serial Plotter

### ISSUE THREAD

**Issue by mholin1** [arduino/Arduino#5768] opened 2016-12-27 14:29 UTC
I use the Serial Monitor to update a variable in the program while the program is running and monitor the result on some other variable I am reading.   Would be very useful to be able to do the same thing in the Serial Plotter.  Allow serial writes so the effect can be seen in real time.

**Comment by per1234** [comment] 2017-07-06 13:08
Closing as duplicate of https://github.com/arduino/Arduino/issues/4090.

**Closed by per1234** 2017-07-06 13:08 UTC
Labels: Type: Duplicate
