### ISSUE TITLE
Simple enhancement request | Displaying column number along with row number

### ISSUE THREAD

**Issue by nehchal** [arduino/Arduino#4855] opened 2016-04-12 20:07 UTC
As of version 1.6.8, Arduino IDE shows row number in bottom left corner. I would request to add functionality to show column number also. This feature will be very useful for two reasons.
1. To limit the column width of comments and code (say length 80 or 100). If column number is shown, one can press enter when 80th column is reached.
2. Placing the comments on the same column, so that all the comments are aligned.

**Comment by lmihalkovic** [comment] 2016-04-12 20:37
Suggested in #4403

**Comment by per1234** [comment] 2017-07-04 19:56
Closing as duplicate of https://github.com/arduino/Arduino/issues/4403.

**Closed by per1234** 2017-07-04 19:56 UTC
Labels: Component: IDE, Type: Duplicate, Type: Improvement
