### ISSUE TITLE
Selected OTA port gets lost and then the esptool is ran against an IP

### ISSUE THREAD

**Issue by JorinL** [arduino/Arduino#8499] opened 2019-02-05 13:32 UTC
I experience the following problem since version 1.8.8 for windows.
I start the IDE and selecet an OTA Port, then I click on upload. It starts compiling and in the meantime the OTA device (why ever) gets lost. The ide now takes esptool and changes from com1 to an ip-address.
So it really switches from espota.py to the esptool.exe

As far I can say - at start all is nice and discovered and then something happens and kills all ota :-D

To update my devices in that situation I've build me a batchfile where I just enter the ip and the path to binary - works in 99% of the time.
So there should be no problem with my OTA devices or network.

![grafik](https://user-images.githubusercontent.com/33031729/52276568-d6d74500-2952-11e9-8e37-02f31b86c44b.png)

**Comment by JorinL** [comment] 2019-02-05 13:38
Probably something to do with #5588

**Comment by per1234** [comment] 2019-02-05 22:43
It sounds like a duplicate of https://github.com/arduino/Arduino/issues/8408

Please try using the Arduino IDE Beta build:
https://www.arduino.cc/en/Main/Software#beta
and let us know whether that solves the problem.

**Comment by JorinL** [comment] 2019-02-06 01:52
Looks good so far - I only receive also the "menu duplication" like in #8408 

![grafik](https://user-images.githubusercontent.com/33031729/52316091-3b79ba80-29ba-11e9-8aee-b3774391be3b.png)

**Comment by facchinm** [comment] 2019-02-07 08:58
@JorinL board menu duplication is intended (one is the internal java discoverer, the other list is the pluggable one from #8038). If the list diverge, we have a bug :stuck_out_tongue: 
I'm glad 1.9.0 fixes the issue, this will greatly speedup merging the features back in master

**Comment by JorinL** [comment] 2019-02-07 12:23
Okay - I wondered about the differences "Network Port" - "Network Ports" it was no real duplicate but strange without an idea about it.

Eventually it could be named "Java Network Ports" "Pluggable Discovered Network Ports" to make it clearer for everyone else :-)

I close this one here - thanks for the fast help!

**Comment by per1234** [comment] 2019-02-07 13:00
I'll go ahead and close this as a duplicate of https://github.com/arduino/Arduino/issues/8408

We can continue any further discussion over there, if needed.

**Closed by per1234** 2019-02-07 13:00 UTC
Labels: OS: Windows, Type: Duplicate

**Comment by JorinL** [comment] 2019-02-20 23:44
> 
> 
> @JorinL board menu duplication is intended (one is the internal java discoverer, the other list is the pluggable one from #8038). If the list diverge, we have a bug 😛
> I'm glad 1.9.0 fixes the issue, this will greatly speedup merging the features back in master

So ehh like this diverge of the list?

![grafik](https://user-images.githubusercontent.com/33031729/53132970-d0abb000-3571-11e9-87c2-7a5ef57ebd0e.png)

**Comment by facchinm** [comment] 2019-02-21 15:30
Uuuuuh yes :slightly_smiling_face:  
The one with only one entry is the new pluggable discoverer, while the other one is the bundled java one. Which one is correct?

**Comment by JorinL** [comment] 2019-02-21 16:03
List "Network ports" is correct - the list with only one entry is much too less.
