### ISSUE TITLE
Arduino mega freezes if send "!!!" by serial

### ISSUE THREAD

**Issue by daiolix** [arduino/Arduino#6314] opened 2017-05-23 08:37 UTC
While debugging my progect have found that arduino mega 2560 freezes and holding serial port if i try to send "!!!" somewhere in code. Only if unplug and plug the board i can continue. Progect didn't download, board is empty.
I don't know is it bug, or "!!!" is fobbiden.
Have tested with code below, tried different speeds. Same with Serial.write
Now i can't test it with uno.

void setup() {
  Serial.begin(9600);
  Serial.print("!!!");
 }

void loop() { 
}

**Comment by PaulStoffregen** [comment] 2017-05-23 08:39
Are you using a genuine Arduino Mega?

This problem was fixed many years ago.

**Comment by matthijskooijman** [comment] 2017-05-23 09:05
This is a duplicate of #459. To fix it, you'll have to update the bootloader in the mega. The version shipped with the Arduino IDE should have the fix, so you can use the "Burn Bootloader" option of the IDE. You will need an ISP programmer (or another arduino using the ArduinoISP sketch), Google probably has pointers on how to set this up.

**Closed by matthijskooijman** 2017-05-23 09:05 UTC
