### ISSUE TITLE
ABS documentation wrong

### ISSUE THREAD

**Issue by warpster** [arduino/Arduino#6214] opened 2017-04-25 14:32 UTC
The documentation says that ABS returns

x: if x is greater than or equal to 0. 
or
-x: if x is less than 0.   <-----this is wrong I believe, should be x: if x is less than 0.  (no minus)

That is unless ABS works different in Arduino than any other language.

**Comment by per1234** [comment] 2017-04-25 21:45
Duplicate of https://github.com/arduino/Arduino/issues/3338

**Comment by facchinm** [comment] 2017-04-26 07:41
Closing as duplicate

**Closed by facchinm** 2017-04-26 07:41 UTC
