### ISSUE TITLE
Ctrl-space

### ISSUE THREAD

**Issue by pfergiu** [arduino/Arduino#6349] opened 2017-06-05 12:46 UTC
This shortcut in IDE allows you to access methods in a class or functions in a library. When you write the name of the class and use period to invoke the methods, IDE can show the options that you have and the arguments of that methods.

**Comment by pfergiu** [comment] 2017-06-05 12:48
I think this gonna be very useful for beginners who wants to learn functionality. Besides this, with this help you can program faster and easier, because you have an assistant helping you all the time.

**Comment by cmaglie** [comment] 2017-06-05 12:50
Duplicate of #849

**Closed by cmaglie** 2017-06-05 12:50 UTC

**Comment by pfergiu** [comment] 2017-06-05 12:52
Sorry. Thanks!
