### ISSUE TITLE
Highlighting code block while editing 

### ISSUE THREAD

**Issue by JulyJim** [arduino/Arduino#5446] opened 2016-10-04 11:43 UTC
There used to be a nice feature when you could select  a bracketed code block and process it - delete, copy, comment et. 
After I inquired in this forum about where did it go , I have been told that it is not available in "new" editor. 
Case closed. 

Could someone please tell me how to identify this "new" editor in source code?
Thanks for your time.

**Comment by TTVert** [comment] 2016-12-04 19:11
I would love to know if we can reinstate this as well.  I've played w/ some of the xml/txt files and haven't had luck yet.

**Comment by per1234** [comment] 2017-06-04 22:28
Duplicate of https://github.com/arduino/Arduino/issues/3387

**Closed** 2017-06-05 07:56 UTC
