### ISSUE TITLE
Add "overflow()" to HardwareSerial

### ISSUE THREAD

**Issue by cider101** [arduino/Arduino#1911] opened 2014-03-06 16:00 UTC
Hi
it would be nice, to have an overflow handler in the HardwareSerial class. This would be handy if you have code (i.e. rendering a display) where you can not fetch the data and the serial buffer would overflow otherwise...
This could be simply achieved by 

//HardwareSerial.cpp line 92 Arduino 1.5.4

bool handle_serial_overflow() attribute((weak));
bool handle_serial_overflow(){ return false}

inline void store_char(unsigned char c, ring_buffer *buffer)
{
int i = (unsigned int)(buffer->head + 1) % SERIAL_BUFFER_SIZE;

if (i != buffer->tail) {
buffer->buffer[buffer->head] = c;
buffer->head = i;
}

//******************** overflow handling *******************************
else if( handle_serial_overflow()) {
store_char(c, buffer);
}
//************************************************************

The code snippet above is just some example code without the claim for completeness but rather to sketch the idea...One would have to provide different overflow methods for different Serials (or pass the buffer or even a reference to the serial along)

**Comment by cmaglie** [comment] 2015-08-31 14:42
Duplicate of #1898

**Closed by cmaglie** 2015-08-31 14:42 UTC
Labels: Component: Core, Type: Duplicate
