### ISSUE TITLE
[Windows] Arduino IDE leaves a lot of files in temp directory

### ISSUE THREAD

**Issue by tueddy** [arduino/Arduino#2724] opened 2015-03-02 16:08 UTC
After closing IDE there are a lot of files left in Windows temp folder (%TMP% folder), see screenshot
![tempfiles](https://cloud.githubusercontent.com/assets/11274319/6444537/77c945f6-c0fe-11e4-8573-52fa6bb77bbc.PNG)

**Comment by GEORGESLAVRA** [comment] 2015-03-05 18:18
You hit the problem of disk space hogging on the nose. Just ran out of space on my "C" drive..

**Comment by matthijskooijman** [comment] 2015-04-13 12:17
I'm closing this as a duplicate of #2971, which has a bit more details and analysis already.

**Closed by matthijskooijman** 2015-04-13 12:17 UTC
