### ISSUE TITLE
Editor Column number

### ISSUE THREAD

**Issue by JimDrewGH** [arduino/Arduino#7049] opened 2017-12-24 17:32 UTC
Can someone please add the column number next to the line number in the bottom of the display?  Preferably as line : column.

Please, please, please!  Did I mention please?  Some of us don't like to use an external editor for simplicity.

Thanks guys, and have a Merry Christmas!

**Comment by per1234** [comment] 2017-12-24 18:04
Closing as duplicate of 
https://github.com/arduino/Arduino/issues/4403
We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2017-12-24 18:04 UTC
