### ISSUE TITLE
"Burn Bootloader" doesn't display verbose results asynchronously

### ISSUE THREAD

**Issue by WestfW** [arduino/Arduino#1253] opened 2013-01-29 02:21 UTC
If you have verbose mode for uploads configured in the arduino preferences, and use a "burn bootloader" command, the results window does not display the avrdude output as it happens.  Instead, the whole command has to complete, and THEN the results window is updated with the entire text from the command.  (or as much as was buffered; I didn't check to see if it was ALL there.)

**Comment by per1234** [comment] 2017-07-02 21:08
I can't reproduce this with Arduino IDE 1.8.3 so I'm going to close this issue.

@WestfW if you're still experiencing this with the latest IDE version please comment and I'll re-open the issue.

**Closed by per1234** 2017-07-02 21:08 UTC
