### ISSUE TITLE
Application Cracks 

### ISSUE THREAD

**Issue by VASAPOL** [arduino/Arduino#10149] opened 2020-05-05 14:12 UTC
I use serial Plotter and I move to second screen and application cracks

macOS 10.15.4

**Comment by per1234** [comment] 2020-05-05 14:46
Closing as duplicate of #9764.

The workaround is to use Arduino IDE 1.8.10. You can download it here:
https://www.arduino.cc/en/Main/OldSoftwareReleases#1.5.x

**Closed by per1234** 2020-05-05 14:46 UTC
