### ISSUE TITLE
Wrong example code for salve sender

### ISSUE THREAD

**Issue by grantcroft** [arduino/Arduino#9986] opened 2020-04-03 00:37 UTC
Hi, 

I noticed wrong slave code is displayed for the master reader/slave sender document at: https://www.arduino.cc/en/Tutorial/MasterReader 

The slave receiver is displayed instead of the slave sender.

**Comment by per1234** [comment] 2020-04-03 01:25
Closing as duplicate of https://github.com/arduino/Arduino/issues/9740

**Closed by per1234** 2020-04-03 01:25 UTC
