### ISSUE TITLE
Board Manager Json not reachable (HTTP error code 416)

### ISSUE THREAD

**Issue by Randcook** [arduino/Arduino#7559] opened 2018-05-03 14:18 UTC
Mac 10.13.4 High Sierra
IDE 1.8.5
Java 8 171

Running Boards Manager

```
Error downloading http://downloads.arduino.cc/packages/package_index.json

 Error downloading http://downloads.arduino.cc/packages/package_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$0(ContributionManagerUI.java:151)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:131)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:334)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:309)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:287)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$0(ContributionManagerUI.java:147)
	... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 416
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:194)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:129)
	... 5 more
```

**Comment by facchinm** [comment] 2018-05-03 15:46
Hi @Randcook ,
did it use to work before? It may have been a temporarily network problem, now the index is reachable (from Italy)

**Comment by Randcook** [comment] 2018-05-03 15:51
Hi
WAs OK, This message from same Mac!

**Comment by facchinm** [comment] 2018-05-03 16:43
Are you still receiving it now?

**Comment by per1234** [comment] 2018-05-04 07:54
Issue was reported on the forum to have been resolved:
http://forum.arduino.cc/index.php?topic=545018.msg3717595#msg3717595

This may have been a duplicate of https://github.com/arduino/Arduino/issues/6628

**Comment by facchinm** [comment] 2018-05-04 07:56
Ok, closing as solved, please reopen if needed.
1.8.6 should solve the issue forever since e35c67b has been merged

**Closed by facchinm** 2018-05-04 07:56 UTC
Labels: Component: Board/Lib Manager, Waiting for feedback
