### ISSUE TITLE
Uploading (CTRL+U) restarts Serial Monitor on compile error

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3527] opened 2015-07-14 22:40 UTC
If you want to upload a program and the compiling fails it will reset the Serial Monitor. I think it should only do it with a proper uploading so you can control the program flow better. Depending on what you are using the Arduino this can cause unexpected problems (restart of the old, buggy program).

**Comment by facchinm** [comment] 2015-07-15 07:26
Hi Nico, I think you are right; the issue will be tackled by @ffissore as soon as he is back

**Comment by ffissore** [comment] 2015-08-03 07:05
What do you mean with "resetting". AFAIK, its contents are not cleared

**Comment by matthijskooijman** [comment] 2015-08-03 07:43
I suspect it means closing/disableing and re-enabling/re-opening, which would cause the board to reset?

**Comment by NicoHood** [comment] 2015-08-03 18:08
restart the Arduino (while Serial monitor is still opened)

**Comment by ffissore** [comment] 2015-09-09 08:08
If I got this right, you're saying that you don't want serial monitor to suspend when you have it open and you try to upload a sketch that doesn't compile. Because of the way this behaviour is coded, it's quite hard to fix at the moment. I'll leave this open as an improvement suggestion. Thanks!

**Comment by NicoHood** [comment] 2015-09-09 13:48
Yes. It should just reset when it really tries to upload. Meaning the reset should occur after a compilation, not before.

**Comment by per1234** [comment] 2021-04-07 05:30
Closing as duplicate of https://github.com/arduino/Arduino/issues/8146. Even though this one came first, the other has a little bit more discussion.

**Closed by per1234** 2021-04-07 05:30 UTC
Labels: Component: IDE, feature request
