### ISSUE TITLE
Relax the serial port name regex

### ISSUE THREAD

**Issue by vatral** [arduino/Arduino#8197] opened 2018-11-14 22:28 UTC
Linux has the very nice ability to use udev rules in order to give permanent names to devices. Unfortunately, the Arduino IDE is too strict in its checking. Here's what I'm doing for trying to give a permanent name to my 3D printer:

    SUBSYSTEMS=="usb", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="204b",ENV{ID_MAKER_TOOL}="1", SYMLINK += "3dprinter_%s{serial}", ENV{PRINTER_SERIAL}="%s{serial}"
    SUBSYSTEMS=="tty", ENV{ID_MAKER_TOOL}=="1", SYMLINK += "ttyACM%E{PRINTER_SERIAL}"
    SUBSYSTEMS=="tty", ENV{ID_MAKER_TOOL}=="1",ENV{PRINTER_SERIAL}=="55330333730351405042", SYMLINK += "ttyACM_sirius"
    ENV{ID_MAKER_TOOL}=="?*", TAG+="uaccess"

This produces this result:
    
    crw-rw----. 1 root dialout 166, 0 Nov 14 19:02 /dev/ttyACM0
    crw-rw----. 1 root dialout 166, 1 Nov 14 23:20 /dev/ttyACM1
    lrwxrwxrwx. 1 root root         7 Nov 14 23:11 /dev/ttyACM55330333730351405042 -> ttyACM1
    lrwxrwxrwx. 1 root root         7 Nov 14 23:11 /dev/ttyACM_sirius -> ttyACM1

This approach works fine with programs that accept arbitrary names like pronterface. 

The "ttyACM55330333730351405042" one was an attempt at a generic rule that would fit any device I might plug in and which would pass a "ttyACM\d+" check. Unfortunately it seems the IDE puts the limit at 3 numerical digits, so this doesn't work.

"ttyACM_sirius" is a no go either, which is a pity.

So I looked in the source to try to make it accept my names. src/processing/app/SerialPortList.java seems like the file to touch, but changes to it don't appear to have any effect, so there must be some other place that's enumerating serial ports.

So, what should I change, and would this change be wanted?

**Comment by facchinm** [comment] 2018-11-15 08:51
Hi @vatral ,
the problem is indeed related with `libListSerials` (the native library we use to enumerate and display serial ports). The library does not support symlinks, only real devices.
The java sources only contain an entry point [here](https://github.com/arduino/Arduino/blob/ee1967cd530ceb9a1d638875e385157e90d532e8/arduino-core/src/processing/app/Platform.java#L179), while to modify this behaviour you'd need to hack https://github.com/arduino/listSerialPortsC project, recompile it and then copy the `.so` in the IDE `lib` folder.
There's an ongoing effort to add pluggable discoverers [here](https://github.com/arduino/Arduino/issues/7942) , which would solve also your problem.
If you don't mind, I'd close this issue so we can continue discussing about this there.

**Closed by facchinm** 2018-11-15 08:51 UTC
Labels: OS: Linux, libListSerial
