### ISSUE TITLE
Arduino crashes after removing boards from /hardware

### ISSUE THREAD

**Issue by mrguen** [arduino/Arduino#11388] opened 2021-03-29 07:46 UTC
Hello,

The Arduino IDE (1.8.13)  aborts launching after I  defined some boards variants in the /hardware folder and removed them.

Here is what I did

Added new variants in the /hardware folder
The variant was listed but an error showed at compilation "Error resolving FQBN: getting"
So I removed the files in /hardware
Then the Arduino IDE does not launch

It seems Arduino still has a reference to these boards but pointing to nothing. The debug shows

"
...
TRACE StatusLogger Using default SystemClock for timestamps.
DEBUG StatusLogger org.apache.logging.log4j.core.util.SystemClock does not support precise timestamps.
TRACE StatusLogger Using DummyNanoClock for nanosecond timestamps.
DEBUG StatusLogger Reconfiguration complete for context[name=1e6f5c3] at URI jar:file:/C:/Program%20Files%20(x86)/Arduino/lib/pde.jar!/log4j2.xml (org.apache.logging.log4j.core.LoggerContext@f2bbc1) with optional ClassLoader: null
DEBUG StatusLogger Shutdown hook enabled. Registering a new one.
DEBUG StatusLogger LoggerContext[name=1e6f5c3, org.apache.logging.log4j.core.LoggerContext@f2bbc1] started OK.
Preparing boards...
java.lang.NullPointerException
        at processing.app.Base.rebuildProgrammerMenu(Base.java:1705)
        at processing.app.Base.<init>(Base.java:286)
        at processing.app.Base.main(Base.java:150)
"

How can I fix this?

**Comment by per1234** [comment] 2021-03-29 08:07
Hi @mrguen. When you say this:

>So I removed the files in /hardware

Are you referring to the `hardware` subfolder of the Arduino IDE installation folder?

**Comment by matthijskooijman** [comment] 2021-03-29 08:19
Can you try the "Hourly build" to see if the issue also exists there? I saw this same (or similar) issue and fixed it in git master with #10922, but that's not part of the 1.8.13 release yet.

**Comment by mrguen** [comment] 2021-03-29 08:27
@per1234 : I mean the personal /hardware folder, not in the installation path.

**Comment by mrguen** [comment] 2021-03-29 08:33
@matthijskooijman 

yes, it fixed the problem.

**Comment by matthijskooijman** [comment] 2021-03-29 08:48
Thanks for checking, then I'm going to close this as fixed.

**Closed by matthijskooijman** 2021-03-29 08:48 UTC
Labels: Component: IDE, Type: Bug, Waiting for feedback

**Comment by mrguen** [comment] 2021-03-30 08:51
@matthijskooijman 

I have a similar issue now.

I could upload sketches to Atmega1284p board using the MighyCore, but now when trying to upload the same sketch for an Atmega644pa, I get the error 
"Error resolving FQBN: getting
Error compiling for board ATmega644."

**Comment by matthijskooijman** [comment] 2021-03-30 19:36
Hm, I'm not sure I understand. If you removed stuff from hardware and that is now no longer available, that sounds like expected b behavior. But that's probably not what you mean.

Maybe your could create a new issue and describe in a bit more detail what happens, including full (verbose) compilation output?

**Comment by mrguen** [comment] 2021-03-31 10:35
@matthijskooijman  The first issue was solved in the hourly build.

I can't give you more details on the second issue. I reinstalled the regular 1.8.13 version and did not investigate further on the first issue (that does not happen after a fresh install, i.e. with an empty personal / hardware folder) and apparently don't have problem with the second one.

**Comment by cmaglie** [comment] 2021-05-15 16:18
This looks like a duplicate of #10580 and should be fixed in the latest release 1.8.15.
