### ISSUE TITLE
Selected board/port displays white on white

### ISSUE THREAD

**Issue by LightningStalker** [arduino/Arduino#6702] opened 2017-09-06 10:19 UTC
Not a major issue, but slightly annoying, as it is a bit difficult to tell what board and port is selected since it is completely unreadable.  Occurs in Linux, running Linux Mint 18.4 Xenial, cinnamon desktop, the same behavior occurs in latest hourly build

**Comment by facchinm** [comment] 2017-09-06 11:21
Hi @LightningStalker ,
could you provide a screenshot? I'm unable to reproduce in my current environment. Thanks!

**Comment by PaulStoffregen** [comment] 2017-09-06 11:22
Colors are correct when I run it on Ubuntu 14.04 (64 bit) and Raspbian "jessie".

**Comment by LightningStalker** [comment] 2017-09-06 16:18
Here is a screenshot:

![Image](https://github.com/user-attachments/assets/ec81b29f-98b6-41d9-a589-417fcdcd19b6)

**Comment by facchinm** [comment] 2017-09-08 16:03
It looks more "white on orange" than white on white. I think it's due to the gtk color theme chosen by your distro; I'd close it as "wontsolve"

**Closed by facchinm** 2017-09-08 16:03 UTC
Labels: Component: IDE user interface, OS: Linux, Waiting for feedback

**Comment by PaulStoffregen** [comment] 2017-09-08 16:06
Agreed, this is almost certainly a Mint issue.

However, one possible workaround for @LightningStalker might involve editing the arduino start script.  Deleting "-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel" might cause the JRE to revert to some Java default rendering that looks wrong for Mint, but probably doesn't suffer from low contrast color choices.

**Comment by LightningStalker** [comment] 2017-09-08 18:21
@facchinm I thought it was the theme too, but changing themes does not solve the issue.  And what do you mean "white on orange"?  Are you looking where the board is selected next to the little dot?  It definitely looks like white on white to my eyes.

@PaulStoffregen Removing that from the script does make it visible, however the text in the menus becomes really small and difficult to read.
[https://imgur.com/a/sEEYW](http://i.imgur.com/zy8NByu.jpg)

**Comment by per1234** [comment] 2017-09-08 21:02
I believe this is the issue @LightningStalker is reporting:
![5efptxm](https://user-images.githubusercontent.com/8572152/30231134-4be50e4a-949e-11e7-8fb3-28cbbde7a19d.jpg)
The text "Arduino/Genuino Micro" should be displayed in the blank white space I have circled in red.

**Comment by LightningStalker** [comment] 2017-09-08 21:23
Yep that's it. ☺

**Comment by facchinm** [comment] 2017-09-11 08:04
Oh, I see, sorry but I was looking at the highlighted "Leonardo ETH", my bad. 

I had a small review of the code we use to setup the GTK look and feel and we don't explicitly set the "selected item" color, so it's a theme issue indeed (or some setting even more buried in system GTK settings).

I also found an old issue about the same problem on an ancient Mint https://github.com/arduino/Arduino/issues/1540 , they could be doing something nasty with the gtk theme at a distribution level

**Comment by PaulStoffregen** [comment] 2017-09-11 10:34
Just for reference, it looks fine on Ubuntu.

![sc](https://user-images.githubusercontent.com/965463/30270636-1c676c2a-96a2-11e7-8937-ab33e60c19d6.png)
