### ISSUE TITLE
Custom hardware presets

### ISSUE THREAD

**Issue by marecl** [arduino/Arduino#7337] opened 2018-03-17 14:03 UTC
I have encountered one of the biggest problems: developing code on two different boards at the same time. Every time I change board I must set everything up again so I've got an idea:  
1. Every window with code can have independent board settings and Serial Monitor (SM wouldn't be critical but would be nice)  
2. Save current device settings (like baudrate, COM port, clock frequency)

Or (somebody posted this before) add preprocessor command so device can be identified and  configured "on the go" in the sketch.

**Comment by per1234** [comment] 2018-03-17 14:26
>Every window with code can have independent board settings and Serial Monitor (SM wouldn't be critical but would be nice)

At least on Windows and Linux, this is already possible. If you start two instances of the Arduino IDE (by starting the application twice), you can have a different board and port setting on each instance. This is different from the behavior of multiple open windows of the same IDE instance (which are generated from **File > Open**, **File > New**, **File > Examples**, and **File > Sketchbook**), where a Tools menu change on one IDE window affects all other windows.

I'd assume you can do the same on macOS but I can't check that. If someone discovers that is not possible on Mac then I think it would be reasonable to reopen this feature request.

>Save current device settings (like baudrate, COM port, clock frequency)

Closing as duplicate of https://github.com/arduino/Arduino/issues/1481, and many others, including most recently https://github.com/arduino/Arduino/issues/7324

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-03-17 14:26 UTC
Labels: Type: Duplicate
