### ISSUE TITLE
program again after unplugged

### ISSUE THREAD

**Issue by camohe90** [arduino/Arduino#4900] opened 2016-04-26 20:43 UTC
In the latest version 1.6.8 each time that i unplugged the arduino from the USB port and I plug again i need to program again.

**Comment by Paul-Ver** [comment] 2016-05-03 12:33
Had/have the same issue. I think it's because the way Arduino works in general (resets when you open a serial connection).

When I upload a program. It'll start running (in which I use hardware serial).
But when I reconnect the Arduino, it'll not run on default, it will only run when I open the Serial Monitor.

**Comment by facchinm** [comment] 2016-05-03 12:48
@camohe90 , could you expand your issue? Like adding the board you are using, operating system, sketch you are trying to run, if it works on 1.6.7, if it work in nighlty

@Paul-Ver , I don't believe the problem is related with `!Serial()`, otherwise it shouldn't work after programming it (unless you open the serial monitor)

**Comment by camohe90** [comment] 2016-05-03 12:57
@facchinm i was using an arduino uno, the operating system is windows 10. I try with different sketch. And  the only way to solve the problem is uninstall 1.6.8 and install again the 1.6.7 and everything worka perfect again

**Comment by facchinm** [comment] 2016-05-03 13:05
@camohe90 greta, thanks for the info. Probably you are encountering a side effect of https://github.com/arduino/Arduino/issues/4700 which we already fixed in mainline.
Could you test the nightly version of the IDE and report if it works? Thanks

**Comment by agdl** [comment] 2016-07-25 16:02
I'm closing this for lack of feedback. Please reopen it if needed.

**Closed by agdl** 2016-07-25 16:02 UTC
Labels: Waiting for feedback
