### ISSUE TITLE
Tie together the port, board and sketch.

### ISSUE THREAD

**Issue by bgma** [arduino/Arduino#3459] opened 2015-07-04 10:30 UTC
Hello,
I wish that in a sketch be able to specify
##Board = "Arduino Uno"
##Port = "COM13"
or in any other way tie together the port, board and sketch.
/Sincerely BG

**Comment by matthijskooijman** [comment] 2015-07-05 09:22
Thanks for the suggestion. However, this was already reported in #3228, so I'm closing this issue as a duplicate.

**Closed by matthijskooijman** 2015-07-05 09:22 UTC

**Comment by per1234** [comment] 2017-03-21 01:20
Duplicate of #1481
