### ISSUE TITLE
Scrolling in menus makes X crash on Ubuntu 15.04 (Arduino 1.6.5)

### ISSUE THREAD

**Issue by thomasgauthier** [arduino/Arduino#3306] opened 2015-06-08 17:12 UTC
Anytime I try to scroll in a long menu like Sketchbook or Examples, X crashes and Ubuntu prompts me with login.

**Comment by ffissore** [comment] 2015-06-08 19:17
Duplicate of #3174

**Closed** 2015-06-09 08:49 UTC
Labels: Type: Duplicate

**Comment by ffissore** [comment] 2015-06-10 07:39
Linux version will bundle the JVM, thus solving this issue
