### ISSUE TITLE
I2C/Wire library: Make Wire library non-blocking

### ISSUE THREAD

**Issue by ghost** [arduino/Arduino#1476] opened 2013-06-20 23:07 UTC
The Wire library has while loops that could go on forever. Although this will not happen in a normal situation, if it happens, the blocking stops the Arduino from working and that could be a safety issue.

Arduino version 1.0.5

A simple loop as timeout could solve this, as suggested here, http://diydrones.com/forum/topics/i2c-wiring-library-lockup
A non-blocking version was also made in 2011 by gknight4, http://forum.arduino.cc/index.php/topic,70705.0.html

**Comment by marekhalmo** [comment] 2016-05-21 13:18
Agree, this is crucial. If you have 20 sensors plugged in to arduino and one goes damaged/unplugged, everything freezes!
Please fix this :(

**Comment by imval** [comment] 2016-06-03 10:05
Issue is opened since almost 3 years :/ Is there anyone that can do something about this bug ? I have big issues with this, I'll probably use a timeout in the loop.

**Comment by marekhalmo** [comment] 2016-06-16 06:52
This just sucks :(

**Comment by juanmalunatic** [comment] 2016-09-21 16:36
Agreed, the proposed solutions should work fine and this is a much needed bug-fix.

**Comment by mdanetzky** [comment] 2017-01-20 13:49
https://github.com/SodaqMoja/Wire

Best replacement library I could find. Non-blocking and no code adjustments needed.

**Comment by dorinclisu** [comment] 2017-08-17 17:45
Is this implemented in Arduino 1.6.10? Because I still have the issue, but I can't use the latest IDE due to other compatibility problems.

**Comment by VladimirAkopyan** [comment] 2018-05-24 14:04
This is ridiculous - are we ever going to fix this?

**Comment by IanSC** [comment] 2019-06-19 18:03
try this dropin replacement:
[(https://github.com/IanSC/Arduino-Wire.h)]

**Comment by cimba007** [comment] 2019-08-17 20:58
@IanSC: What is the best way to replace the default wire library? Do you have and experience on this?

**Comment by matthijskooijman** [comment] 2019-09-06 07:35
I'm closing this issue, in favor of https://github.com/arduino/ArduinoCore-avr/issues/42 (which is in the, now, correct repository).

**Closed by matthijskooijman** 2019-09-06 07:35 UTC
Labels: Component: Core, Library: Wire, Type: Bug

**Comment by ermtl** [comment] 2020-03-27 01:15
It's been 9 FUCKING YEARS since that bug was first discussed (2011), countless people pulled their hair trying to understand why their Arduino was freezing, why would it work normally, then suddenly stop, a dozen of times, it's been raised in here, dozens of times people had been told to get lost, use something else, etc ...
https://github.com/arduino/Arduino/issues/7328
https://github.com/arduino/Arduino/issues/2418
https://github.com/arduino/Arduino/pull/1842
https://github.com/arduino/Arduino/issues/5249
https://github.com/arduino/ArduinoCore-avr/issues/42
Google shows pages after pages of people getting started and who get discouraged by this elusive bug they don't understand. This runs totally contrary of what arduino is supposed to stand for.

If the fix was difficult, if it compromised compatibility or added other problem, it would be understandable, but it's not the case, all that shit is caused by those 2 damn lines of code that obviously can create an infinite loop if for some reason the read operation does not complete :

  // wait for read operation to complete
  while(TWI_MRX == twi_state){
    continue;
  }

Yes, I know, this state is not supposed to happen according to the I2C protocol, but guess what ? electrical glitches didn't get the memo.

Countless people, after losing hours or days kind of solved the issue either by making a modified version for themselves, or switching to another library, so there are several implementations of a timeout that are simple and would easily solve the issue.

But arduino developpers stubbornly refuse to fix it !

You think I'm rude ? After 9 years of giving the finger on this issue to the whole community for absolutely no reason, I couldn't care less.

How long before you close it again ?
Just be honest, and put a "fuck you all, WONTFIX" label on it ...

**Comment by mattborja** [comment] 2022-04-13 06:06
Yeah, still a problem in 2022 in Arduino 1.8.19. My `Wire.endTransmission()` still hangs if my IC is disconnected.

Waiting for a reply on https://github.com/rambo/I2C/issues/12 before switching to that.

**Comment by cmaglie** [comment] 2022-04-13 08:31
Quoting @matthijskooijman [answer](https://github.com/arduino/ArduinoCore-avr/issues/42#issuecomment-1097670356) for future reference:

> @mattborja, this timeout feature has actually been implemented (two years ago) in https://github.com/arduino/ArduinoCore-avr/pull/107, but it is not enabled by default. Did you try turning it on using https://www.arduino.cc/reference/en/language/functions/communication/wire/setwiretimeout/ ?
>
> Since we seem to have forgotten closing this issue, I'll do that now. For future reference, https://github.com/arduino/ArduinoCore-avr/pull/107 implemented the feature, https://github.com/arduino/ArduinoCore-avr/pull/362 is still pending to add feature detection macros like WIRE_HAS_TIMEOUT, and https://github.com/arduino/ArduinoCore-avr/pull/363 is a draft to enable timeouts by default in the future.
