### ISSUE TITLE
Extend menu bar of the IDE for Ultra-Wide Monitors

### ISSUE THREAD

**Issue by TheBetaFruit** [arduino/Arduino#6424] opened 2017-06-24 20:55 UTC
When using a 21:9 Ultra-Wide Monitor (e.g. the popular LG 34UM95, resolution = 3440x1440px), the upper turquise menu bar of the Arduino IDE is too short in full-screen mode and therefore centered with two ugly grey areas besides it.

It would be nice to fix this by making sure the menu bar stays left-aligned while expanding the turquise area to the right, fitting any screen width.

**Comment by facchinm** [comment] 2017-06-26 07:58
Hi @TheBetaFruit ,
I'm closing the issue as duplicate of https://github.com/arduino/Arduino/issues/5341, I'm moving your comment there too, thanks!

**Closed by facchinm** 2017-06-26 07:58 UTC
