### ISSUE TITLE
abort compile

### ISSUE THREAD

**Issue by lpdunwell** [arduino/Arduino#8147] opened 2018-10-31 06:15 UTC
when clicking upload or verify, there's no way of aborting the process.
combine this with the "reset target, then compile" behaviour of the upload button for maximum annoyance. there should be a possibility of completely aborting the process.
also, this would be a great place to make sure the avrdude process gets closed on timeout etc, which is not always the case. (i find myself opening windows task manager to manually end avrdude regularly)

**Comment by per1234** [comment] 2018-10-31 07:43
Closing as duplicate of https://github.com/arduino/Arduino/issues/5928

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-10-31 07:43 UTC
Labels: Type: Duplicate
