### ISSUE TITLE
arduino --install-boards "arduino:avr:1.6.2"

### ISSUE THREAD

**Issue by czgtest** [arduino/Arduino#8040] opened 2018-09-29 08:48 UTC
OS : windows10
Arduino : 1.8.7

go to C:\Program Files (x86)\Arduino and run command : arduino --install-boards "arduino:avr:1.6.2"

then I can't find board package in  ..\Arduino15\packages folder

but in Arduino 1.8.6, this command work well.

Is there any change?

**Comment by per1234** [comment] 2018-09-29 08:53
It sounds the same as https://github.com/arduino/Arduino/issues/8034

Do you get the "Selected board is not available" error?

**Comment by czgtest** [comment] 2018-09-30 00:44
I can't see any error print out in command line

**Comment by matthijskooijman** [comment] 2018-09-30 00:46
You might need to run arduino_debug.exe instead of arduino.exe to see commandline (error) output.

**Comment by facchinm** [comment] 2018-10-05 16:02
Closing as duplicate of #8034

**Closed by facchinm** 2018-10-05 16:02 UTC
Labels: Component: CLI, Waiting for feedback

**Comment by lsaidman** [comment] 2019-01-03 19:51
Does 1.8.8 fix this?
