### ISSUE TITLE
Library related, static library won't work, precompiled=true will ignore compilation of cpp file, Version 1.8.12

### ISSUE THREAD

**Issue by xukangmin** [arduino/Arduino#10164] opened 2020-05-07 14:25 UTC
Hello,

precompiled static library (.a files) works fine on Version 1.8.9.

When I switch to 1.8.12, the same configuration won't work.

Basically, when I compile in 1.8.12, it will skip compiling library cpp file which resulting linking issue if I set precompiled=true.

If I remove precompiled=true, it won't add the search path for the static files and miss ldfalgs tag.

Here is the library.properties

name=TinyTouch
version=0.1
author=Kangmin
maintainer=kangmin <xukangmin@gmail.com>
sentence=Enables Touch Interface
paragraph=1
category=Sensors
url=https://docs.tinycore.dev/en/latest/usage.html#touch
architectures=avr
precompiled=true
ldflags=-lqtm_acq_runtime -lqtm_binding_layer -lqtm_touch_key

I attach the library for your reference.

[TinyTouch.zip](https://github.com/arduino/Arduino/files/4593512/TinyTouch.zip)

**Comment by facchinm** [comment] 2020-05-07 14:39
Closing as duplicate of https://github.com/arduino/arduino-builder/issues/353 ; a fix is ongoing here https://github.com/arduino/arduino-cli/pull/611 and will be merged / integrated in hourly IDE soon

**Closed by facchinm** 2020-05-07 14:39 UTC
