### ISSUE TITLE
Close tab

### ISSUE THREAD

**Issue by fivitti** [arduino/Arduino#5067] opened 2016-06-23 19:10 UTC
Hello!
I cannot close any tab without delete them. I don't have 'x' button on tab. Shortcut Ctrl+W close the ArduinoIDE window.
Version 1.6.9.

**Comment by matthijskooijman** [comment] 2016-06-23 21:55
This is intentional, all files in the sketch are always shown in tabs.

**Comment by q2dg** [comment] 2016-06-24 14:16
Well, weĺl have no luck, @fivitti ...see https://github.com/arduino/Arduino/issues/2883

**Comment by per1234** [comment] 2017-07-03 07:51
Closing as duplicate of https://github.com/arduino/Arduino/issues/2883

**Closed by per1234** 2017-07-03 07:51 UTC
Labels: Type: Duplicate
