### ISSUE TITLE
Autoclose Serial Monitor/Serial Plotter when opening the other one

### ISSUE THREAD

**Issue by agdl** [arduino/Arduino#5626] opened 2016-11-23 16:39 UTC
Now if the serial monitor is open and you want to open the plotter (or viceversa) you can't do it simply clicking on the desired extension, but you have to close the opened one first. Would be very nice to autoclose the open one.

And upload with plotter open is not possible. You get: board can't be found

**Comment by cousteaulecommandant** [comment] 2016-11-29 11:22
Being able to use both monitor and plotter simultaneously would be too complicated to code, right?  If not, it would be nice.  (I guess you can't just have 2 threads accessing the same serial port; there should be some sort of centralized program that reads the serial port and sends data to both windows for this.)

**Comment by madsdyd** [comment] 2020-04-07 12:21
@per1234 I would think this should be closed as a duplicate of #4090

**Comment by per1234** [comment] 2022-11-18 13:45
Obviated by addition of support for using Serial Monitor and Serial Plotter simultaneously in Arduino IDE 2.x

**Closed by per1234** 2022-11-18 13:45 UTC
Labels: feature request, Component: IDE Serial monitor, SerialPlotter
