### ISSUE TITLE
Button to cancel in-progress upload. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#585] opened 2012-11-15 18:40 UTC
This is [Issue 585](http://code.google.com/p/arduino/issues/detail?id=585) moved from a Google Code project.
Added by 2011-08-17T18:23:35.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-IDE, Milestone-Post-1.0, OpSys-All

### Original description

**What change would like to see?**

A cancel (or stop) button in the editor status bar (next to the new progress bar) during a compile or upload, that would allow you to interrupt the process (i.e. kill avrdude).

**Why?**

Sometimes failed uploads take a long time to error out (avrdude will keep retrying, but you might realize you have the wrong board or serial port selected).  It's annoying to have to wait for it to happen on its own.

**Comment by Testato** [comment] 2015-08-09 19:27
+1

**Comment by facchinm** [comment] 2015-08-10 07:45
Closing as duplicate of #3568 because the latest is gaining much more attention

**Closed by facchinm** 2015-08-10 07:45 UTC
Labels: Component: Compilation, Component: Uploading
