### ISSUE TITLE
Please add uMT library

### ISSUE THREAD

**Issue by GO01260** [arduino/Arduino#6312] opened 2017-05-22 12:41 UTC
uMT - a preemptive, real-time multitasker for the ARDUINO AVR/SAM boards

https://github.com/GO01260/uMT.git

**Comment by matthijskooijman** [comment] 2017-05-22 14:25
This is a duplicate of #6300. According to that, the library was added and awaiting a proper tag by @GO01260. Looking at the new tag now, it looks ok, so I expect the library will be added automatically. If it doesn't appear within a few hours, best leave a comment on #6300.

**Closed by matthijskooijman** 2017-05-22 14:25 UTC
Labels: Component: Board/Lib Manager

**Comment by GO01260** [comment] 2017-05-22 16:17
Thanks.
This is my first publication so I made a large series of mistakes... Sorry.

Any doc I can read which explains how to manage releases and how to create new versions of GitHub library?

I spent some time reading here and there but I did not get the concepts... (my fault).

Regards

**Comment by cmaglie** [comment] 2017-05-24 14:30
To create a new release you must change the version in the library.properties file, commit the change and make a new tag (just remember to create the new tag **after** having committed and pushed the changes to library.properties). Once done the new release will be published within an hour.

To remove a release you must remove the corresponding tag. The release will be actually removed from the index within a week (because our indexer runs a clean up job every week).
