### ISSUE TITLE
ATMega2560 compilation bug

### ISSUE THREAD

**Issue by OlivierCROISET** [arduino/Arduino#8544] opened 2019-02-15 17:08 UTC
See below the error message.
The error message appears as I compile a software using a ATMega2560 and an ISD1700 ( https://github.com/Velleman/KA02/tree/master/ISD1700 ), very often but not always. My software is about 32 ko.

**Compiler error message  :**
. . . . . 
Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Users\papa\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\5.4.0-atmel3.6.1-arduino2/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/users/papa/appdata/local/arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by per1234** [comment] 2019-02-16 00:09
Closing as duplicate of https://github.com/arduino/Arduino/issues/7949

**Closed by per1234** 2019-02-16 00:09 UTC
Labels: Architecture: AVR, Component: Compilation, Type: Duplicate
