### ISSUE TITLE
Windows 10 lan ports disappear after a minute on new laptop. Is fine with wired desktop and XP SP2

### ISSUE THREAD

**Issue by jcflyer** [arduino/Arduino#8409] opened 2019-01-20 11:39 UTC
I have used Arduino IDE 1.6.11 on a wired desktop running XP SP2 to wirelessly program 4 Nodemcu devices without any problem for over a year.
I got a new laptop with Windows 10 and installed 1.6.11 and all the network ports show up and work immediately but then disappear and the port is greyed out in a minute or so.
I can only upload once or twice before the port is gone.
If I restart the laptop the ports show up and work again for a short time. Nothing I have tried has worked so far including allowing port 8266 or turning off the firewall.
Also compiling is very slow now.

**Comment by per1234** [comment] 2019-01-20 12:45
Closing as duplicate of https://github.com/arduino/Arduino/issues/8408

**Closed by per1234** 2019-01-20 12:45 UTC
