### ISSUE TITLE
Arduino IDE as a toolchain in VS Code Arduino extension broken.

### ISSUE THREAD

**Issue by Seefer** [arduino/Arduino#10870] opened 2020-10-20 12:06 UTC
Visual studio Code Arduino extension relies on Arduino IDE installation but it appears version problems possibly involving Arduino IDEs use of native node modules is causing issues as explained on VS Code's Arduino extension Github issues tracker:

https://github.com/microsoft/vscode-arduino/issues/918

Is this something that can be remedied in future Arduino IDE releases because integration of the Arduino toolchain with other IDEs should be an important goal.

**Comment by matthijskooijman** [comment] 2020-10-20 12:36
I had a quick look at the linked issue, but it's not quite clear to me what the issue is and whether this issue is in the IDE or in the vscode extension (I'm inclined to think it's in vscode). Regardless, this issue does not currently have anything really actionable, other than someone investing time to figure out how this vscode extension works and what the actual problem is.

It would seem more logical for the vscode-arduino developers to figure out what the problem is, and if they figure out changes are needed on the IDE side, report back here to discuss them.

In the meantime, I'm inclined to close this issue here, or does it still serve a purpose here?

**Closed** 2021-03-29 10:16 UTC
Labels: Component: IDE, Component: IDE Serial monitor, Type: Bug
